import {useCallback,useEffect,useRef,useState,type ReactNode} from 'react'
import {useHost,unwrap,ModuleSurface,type GitHubBoardSnapshot,type PullRequestCard,type PRStage,type CodeAgent,type CodeTaskCard,type PRRun} from '@zq/module-api'
import {Button,Input,Textarea,SelectField,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,TooltipButton,Checkbox,Collapsible,CollapsibleTrigger,CollapsibleContent} from '@zq/ui'
import {GitPullRequest,ArrowClockwise,DotsThree,ArrowSquareOut,Robot,FolderSimple,Plus,Kanban,CheckCircle,Clock,WarningCircle,Stop,Circle,CaretRight,CaretDown} from '@phosphor-icons/react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import './code-tasks.css'
import {useCodeTaskArrivals,CodeTaskArrival} from './useCodeTaskArrivals'
import {CodeReviewActions,type ReviewAction} from './CodeReviewActions'
const stages:PRStage[]=['Backlog','Needs review','Agent reviewing','Needs your input','Ready to merge']
const statusLabel:Record<PRStage,string>={'Backlog':'Backlog','Needs review':'To do','Agent reviewing':'In progress','Needs your input':'Human Review','Ready to merge':'Done'}
const statusOptions=stages.map(value=>({value,label:statusLabel[value]}))
type BoardCard=PullRequestCard&{source?:'task'|'issue';labels?:string[];assignees?:string[];stateReason?:string;description?:string;category?:string}
const empty:GitHubBoardSnapshot={tasks:[],repositories:[],cards:[],login:'',projects:[],profiles:[]}
const isActive=(state:string)=>['starting','running','needs_input','uncertain'].includes(state)
const runLabel:Record<string,string>={starting:'Starting review',running:'Agent reviewing',needs_input:'Agent needs input',complete:'Report ready',failed:'Review stopped',uncertain:'Check linked session'}
type Action={label:string;run:()=>void;disabled?:boolean}
export function PRContext({actions,children}:{actions:Action[];children:ReactNode}){return <ContextMenu><ContextMenuTrigger asChild>{children}</ContextMenuTrigger><ContextMenuContent>{actions.map(a=><ContextMenuItem key={a.label} disabled={a.disabled} onSelect={a.run}>{a.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>}
function More({actions,label}:{actions:Action[];label:string}){return <DropdownMenu><DropdownMenuTrigger asChild><TooltipButton className="pr-more" aria-label={label}><DotsThree size={19}/></TooltipButton></DropdownMenuTrigger><DropdownMenuContent align="end">{actions.map(a=><DropdownMenuItem key={a.label} disabled={a.disabled} onSelect={a.run}>{a.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>}
export function CodeTasks({active,pickerSignal,refreshSignal}:{active:boolean;pickerSignal:number;refreshSignal:number}){
 const host=useHost(),bridge=host.services.github
 const [data,setData]=useState(empty),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[refreshing,setRefreshing]=useState(false)
 const [scope,setScope]=useState('All tracked'),[repo,setRepo]=useState(''),[query,setQuery]=useState(''),[picker,setPicker]=useState(false),[selected,setSelected]=useState(''),[assigning,setAssigning]=useState(''),[pending,setPending]=useState(''),[end,setEnd]=useState(''),[ending,setEnding]=useState<{id:string;run:PRRun}|null>(null),[stopping,setStopping]=useState(false),[syncDetails,setSyncDetails]=useState(false)
 const [closingIssue,setClosingIssue]=useState<BoardCard|null>(null),[closeReason,setCloseReason]=useState<'completed'|'not_planned'>('completed'),[closing,setClosing]=useState(false),[closeError,setCloseError]=useState('')
 const requestClose=(c:BoardCard)=>{setClosingIssue(c);setCloseReason('completed');setCloseError('')}
 const [reviewAction,setReviewAction]=useState<ReviewAction|null>(null)
 const [category,setCategory]=useState('All tasks'),[editing,setEditing]=useState<Partial<CodeTaskCard>|null>(null),[deleting,setDeleting]=useState(''),[expandedEnded,setExpandedEnded]=useState<Set<string>>(()=>new Set())
 const cards:BoardCard[]=[...data.cards,...(data.issues||[]),...(data.tasks||[]).map(t=>({...t,repo:'',number:0,url:'',author:'',draft:false,review:'',requested:false}))]
 const categories=['All tasks','General','Open PRs','Issues',...new Set((data.tasks||[]).map(t=>t.category).filter(c=>c!=='General'))]
 const newTask=()=>setEditing({title:'',description:'',category:['All tasks','Open PRs','Issues'].includes(category)?'General':category,stage:'Needs review'})
 const [drag,setDrag]=useState<PRStage|null>(null),running=useRef(false),alive=useRef(true)
 useEffect(()=>{alive.current=true;return()=>{alive.current=false}},[])
 async function perform(fn:()=>Promise<unknown>){setError('');try{await fn()}catch(e){setError((e as Error).message)}}
 const copy=(text:string)=>void perform(async()=>{await unwrap(host.services.clipboard.writeText(text));host.notify('Copied')})
 const open=(c:PullRequestCard)=>void perform(()=>bridge.invoke('open',{id:c.id}))
 const linked=(id?:string)=>{if(!id)return;setSelected('');if(!host.commands.run('code.open',{id}))setError('Update the Code module to open linked review sessions.')}
 const move=(c:PullRequestCard,stage:PRStage)=>void perform(async()=>accept(await bridge.invoke('move',{id:c.id,stage})))
 const canEnd=(r?:PRRun)=>!!r?.sessionId&&!r.sessionUnavailable&&!!r.sessionState&&!['stopped','busy','starting','approval','switching'].includes(r.sessionState)
 const sessionActions=(c:BoardCard,r?:PRRun):Action[]=>[{label:'Open agent',run:()=>linked(r?.sessionId),disabled:!r?.sessionId},{label:'End session…',run:()=>r&&setEnding({id:c.id,run:r}),disabled:!canEnd(r)}]
 const reviewActions=(c:BoardCard):Action[]=>{
  const r=c.runs.at(-1),completed=r?.state==='complete'&&!!r.report,open=c.state==='OPEN'
  const choose=(kind:ReviewAction['kind'])=>setReviewAction({kind,id:c.id,title:c.title,repo:c.repo,number:c.number,runId:r?.id||'',agent:r?.agent})
  const available=completed&&open&&!!r?.sessionId&&!r.sessionUnavailable&&['ready','stopped'].includes(r.sessionState||'')&&r.sessionMode!=='terminal'
  return [...(completed&&open?[{label:'Request changes…',run:()=>choose('changes'),disabled:!available},...(c.source==='issue'?[{label:'Implement fix…',run:()=>choose('implement'),disabled:!available}]:[]),...(!c.source?[{label:'Merge…',run:()=>choose('merge'),disabled:c.head!==r.head||!!c.stale}]:[])]:[]),...(['issue','task'].includes(c.source||'')?[{label:'Link PR…',run:()=>choose('link')}]:[])]
 }
 const endedKey=(c:BoardCard)=>{const r=c.runs.at(-1);return `${c.id}:${r?.id}:${r?.endedAt||''}`}
 const isEnded=(c:BoardCard)=>c.runs.at(-1)?.sessionState==='stopped'
 const isCompact=(c:BoardCard)=>isEnded(c)&&!expandedEnded.has(endedKey(c))
 const expandCard=(c:BoardCard,open:boolean)=>setExpandedEnded(old=>{const next=new Set(old);if(open)next.add(endedKey(c));else next.delete(endedKey(c));return next})
 function actions(c:BoardCard):Action[]{const run=c.runs.at(-1),task=c.source==='task';return [...(isEnded(c)?[{label:isCompact(c)?'Expand card':'Collapse card',run:()=>expandCard(c,isCompact(c))}]:[]),{label:task?'View task and reports':c.source==='issue'?'View issue and reports':'View PR and reports',run:()=>setSelected(c.id)},...(task?[{label:'Edit task…',run:()=>setEditing(data.tasks.find(t=>t.id===c.id)!),disabled:c.runs.some(r=>isActive(r.state))},{label:'Delete task…',run:()=>setDeleting(c.id),disabled:c.runs.some(r=>isActive(r.state))}]:[{label:'Open on GitHub',run:()=>open(c)}]),...(c.source==='issue'&&c.state==='OPEN'?[{label:'Close issue on GitHub…',run:()=>requestClose(c)}]:[]),{label:task?'Assign agent…':c.source==='issue'?'Investigate issue…':'Assign agent to review…',run:()=>{setSelected(c.id);setAssigning(c.id)},disabled:c.state!=='OPEN'||!!c.stale||c.runs.some(r=>isActive(r.state))},...reviewActions(c),...sessionActions(c,run),{label:task?'Copy task':c.source==='issue'?'Copy issue link':'Copy PR link',run:()=>copy(task?c.title+'\n'+c.description:c.url)},...stages.map(stage=>({label:`Move to ${statusLabel[stage]}`,run:()=>move(c,stage),disabled:stage===c.stage||c.state!=='OPEN'}))]}
 const selectedRepos=new Set(data.repositories.map(r=>r.name.toLowerCase()))
 const inCategory=(c:BoardCard,name:string)=>(c.source==='task'||selectedRepos.has(c.repo.toLowerCase()))&&(name==='All tasks'||name==='Open PRs'&&!c.source||name==='Issues'&&c.source==='issue'||c.source==='task'&&c.category===name)
 const githubCategory=category==='Open PRs'||category==='Issues',issueCategory=category==='Issues'
 const visible=cards.filter(c=>inCategory(c,category)&&(!githubCategory||!repo||c.repo===repo)&&(!githubCategory||scope==='All tracked'||scope==='All open'&&c.state==='OPEN'||scope==='Closed / merged'&&c.state!=='OPEN'||scope==='Mine'&&c.author.toLowerCase()===data.login.toLowerCase()||scope==='Review requested'&&c.requested||scope==='Assigned to me'&&c.assignees?.some(a=>a.toLowerCase()===data.login.toLowerCase()))&&`${c.category||''} ${c.repo} ${c.number} ${c.title} ${c.author} ${(c.labels||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()))
 const {arrivals,observe,begin,finish}=useCodeTaskArrivals(data,visible.map(c=>c.id),JSON.stringify([category,repo,scope,query]),active)
 const accept=useCallback((next:GitHubBoardSnapshot,ticket?:number)=>{if(alive.current){observe(next,ticket);setData(old=>JSON.stringify(old)===JSON.stringify(next)?old:next);setLoaded(true)}},[observe])
 const refresh=useCallback(async(automatic=false)=>{if(running.current)return;running.current=true;setRefreshing(true);setError('');const ticket=automatic?begin():undefined;try{accept(await bridge.invoke('refresh',{automatic}),ticket)}catch(e){if(alive.current)setError((e as Error).message)}finally{running.current=false;if(alive.current)setRefreshing(false)}},[bridge,accept,begin])
 useEffect(()=>{if(!active)return;let stopped=false;void bridge.invoke('snapshot',undefined).then(next=>{if(!stopped){accept(next);void refresh(true)}}).catch(e=>{if(!stopped){setError(e.message);setLoaded(true)}});const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh(true)},60000);return()=>{stopped=true;clearInterval(timer)}},[active,bridge,accept,refresh])
 useEffect(()=>{if(!active||!cards.some(c=>c.runs.some(r=>isActive(r.state))))return;let stopped=false;const timer=setInterval(()=>{if(document.visibilityState==='visible'){const ticket=begin();void bridge.invoke('snapshot',undefined).then(next=>{if(!stopped)accept(next,ticket)}).catch(()=>{})}},3000);return()=>{stopped=true;clearInterval(timer)}},[active,bridge,accept,begin,data.cards,data.issues,data.tasks])
 useEffect(()=>{if(pickerSignal)setPicker(true)},[pickerSignal])
 useEffect(()=>{if(refreshSignal)void refresh()},[refreshSignal,refresh])
 const detail=cards.find(c=>c.id===selected),latest=detail?.runs.at(-1)
 const checked=data.repositories.flatMap(r=>[r.checkedAt||0,r.issuesCheckedAt||0]).filter(Boolean),lastChecked=checked.length?Math.min(...checked):0
 const syncRepos=data.repositories.filter(r=>!githubCategory||!repo||r.name===repo)
 const disabledIssues=category==='Open PRs'?[]:syncRepos.filter(r=>r.issuesDisabled)
 const warnings=syncRepos.flatMap(r=>[{name:r.name,kind:'PRs',error:r.error,truncated:r.truncated},{name:r.name,kind:'issues',error:r.issuesError,truncated:r.issuesTruncated}]).filter(r=>(r.error||r.truncated)&&(category!=='Open PRs'||r.kind==='PRs')&&(category!=='Issues'||r.kind==='issues'))
 const paused=!!data.retryAt&&data.retryAt>Date.now()
 const pauseText=paused?`GitHub sync paused until ${new Date(data.retryAt!).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}. Cached tasks remain available.`:''
 const syncSummary=[pauseText,warnings.length?`${warnings.length} sync notice${warnings.length===1?'':'s'}`:'',disabledIssues.length?`Issues disabled in ${disabledIssues.length} repositor${disabledIssues.length===1?'y':'ies'}`:''].filter(Boolean).join(' · ')
 function tile(c:BoardCard){
  const r=c.runs.at(-1),ended=isEnded(c),compact=isCompact(c),task=c.source==='task'
  const categoryIcon=c.source==='issue'?<Circle size={12}/>:!task?<GitPullRequest size={12}/>:null
  const completion=c.state==='MERGED'?'Merged':c.state==='CLOSED'?'Closed':r?.state==='failed'?'Review stopped':statusLabel[c.stage]
  const cached=!!(c.stale||data.repositories.find(repo=>repo.name===c.repo)?.[c.source==='issue'?'issuesError':'error'])
  return <PRContext key={c.id} actions={actions(c)}><Collapsible open={!compact} onOpenChange={open=>expandCard(c,open)} asChild>
   <article className={`pr-card${compact?' pr-card-compact':''}`} data-card-id={c.id} data-stage={stages.indexOf(c.stage)} draggable={c.state==='OPEN'} onDragStart={e=>{e.dataTransfer.setData('application/x-zq-pr',c.id);e.dataTransfer.effectAllowed='move'}}>
    {arrivals[c.id]&&<CodeTaskArrival key={arrivals[c.id]} id={c.id} runId={arrivals[c.id]} finish={finish}/>}
    <div className="pr-card-meta">
     {compact?<span className="pr-compact-source">{categoryIcon}<span>{task?c.category:`${c.repo} #${c.number}`}</span></span>:<span className={`pr-category ${task?'pr-category-task':c.source==='issue'?'pr-category-issue':'pr-category-pull'}`}>{categoryIcon}<span>{task?c.category:c.source==='issue'?'Issues':'Open PRs'}</span></span>}
     {ended&&<CollapsibleTrigger className="pr-more pr-card-toggle" aria-label={`${compact?'Expand':'Collapse'} card: ${c.title}`} tooltip={compact?'Expand card':'Collapse card'}>{compact?<CaretRight size={14}/>:<CaretDown size={14}/>}</CollapsibleTrigger>}
     <More actions={actions(c)} label={task?`Actions for ${c.title}`:`Actions for ${c.source==='issue'?'issue':'PR'} #${c.number}`}/>
    </div>
    <button className="pr-card-open" onClick={()=>setSelected(c.id)} aria-label={`View ${task?'task':c.source==='issue'?'issue':'PR'} and reports: ${c.title}`}>
     {!compact&&!task&&<span className="pr-card-repo">{c.repo} #{c.number}</span>}
     <span className="pr-card-title">{c.title}</span>
     {compact&&<span className={`pr-compact-status${r?.state==='failed'?' pr-compact-failed':''}`}>{completion} · Session ended{cached?' · Cached':''}</span>}
    </button>
    <CollapsibleContent className="pr-card-details">
     <div className="pr-card-facts">
      <span className="pr-card-byline">{task?'Task':c.author}{c.draft?' · Draft':''}{c.state!=='OPEN'?` · ${c.state==='CLOSED'&&c.stateReason==='NOT_PLANNED'?'closed · Not planned':c.state.toLowerCase()}`:''}</span>
      {c.checks&&c.checks!=='none'&&<span className={`pr-checks pr-checks-${c.checks}`}>{c.checks==='passing'?<CheckCircle size={14}/>:c.checks==='failing'?<WarningCircle size={14}/>:<Clock size={14}/>}Checks {c.checks}{c.review==='APPROVED'?' · Approved':c.review==='CHANGES_REQUESTED'?' · Changes requested':''}</span>}
      {r&&<span className={`pr-run pr-run-${r.state}`}><Robot size={13}/>{r.action==='implement'&&r.state==='running'?'Implementing fix':r.action==='changes'&&r.state==='running'?'Updating work':c.source==='issue'&&r.state==='running'?'Investigating issue':task&&r.state==='running'?'Agent working':runLabel[r.state]}</span>}
      {cached&&<span className="pr-stale">Cached · refresh needed</span>}
     </div>
     {c.stage==='Needs your input'&&r?.state==='complete'&&<div className="pr-card-review-actions">{reviewActions(c).filter(a=>a.label!=='Link PR…').map(a=><Button key={a.label} variant="outline" size="sm" disabled={a.disabled} onClick={a.run}>{a.label}</Button>)}</div>}
     {r?.sessionId&&<div className="pr-card-actions"><Button variant="outline" size="sm" onClick={()=>linked(r.sessionId)}><Robot size={14}/>Open agent</Button>{canEnd(r)&&<Button variant="ghost" size="sm" onClick={()=>setEnding({id:c.id,run:r})}><Stop size={14}/>End session</Button>}{ended&&<span className="pr-muted pr-session-ended">Session ended · history saved</span>}</div>}
    </CollapsibleContent>
   </article>
  </Collapsible></PRContext>
 }
 return <ModuleSurface><div className="pr-view" hidden={!active}>
  <header className="pr-header"><div><h1><Kanban size={20}/>Tasks</h1><span className="pr-muted">Code · {data.login?`@${data.login} · `:''}{refreshing?'Refreshing…':lastChecked?`Updated ${new Date(lastChecked).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:'Your coding work'}</span></div><div className="pr-actions"><TooltipButton className="pr-more" aria-label="Refresh GitHub" disabled={paused||refreshing||!data.repositories.length} onClick={()=>void refresh()}><ArrowClockwise size={18}/></TooltipButton><Button variant="outline" onClick={()=>setPicker(true)}>Choose repositories</Button><Button onClick={newTask}><Plus size={15}/>New task</Button></div></header>
  <nav className="code-task-categories" aria-label="Code task categories">{categories.map(name=><PRContext key={name} actions={[{label:'Show '+name,run:()=>{setCategory(name);setScope('All tracked')}},...(['Open PRs','Issues'].includes(name)?[{label:'Choose repositories…',run:()=>setPicker(true)},{label:'Refresh GitHub',run:()=>void refresh()}]:[{label:'New task in '+name,run:()=>{setCategory(name);setEditing({title:'',description:'',category:name==='All tasks'?'General':name,stage:'Needs review'})}}])]}><button aria-pressed={category===name} onClick={()=>{setCategory(name);setScope('All tracked')}}>{name}<span>{cards.filter(c=>inCategory(c,name)).length}</span></button></PRContext>)}</nav>
  {error&&<p className="pr-error" role="alert">{error}</p>}
  {syncSummary&&<div className="pr-sync-summary"><span role="status">{warnings.length>0&&<WarningCircle size={15}/>}<span>{syncSummary}</span></span><Button variant="ghost" size="sm" onClick={()=>setSyncDetails(true)}>Details</Button></div>}
  <Dialog open={syncDetails&&active} onOpenChange={setSyncDetails}><DialogContent className="pr-dialog pr-sync-dialog"><DialogTitle>Repository sync details</DialogTitle><DialogDescription>Available tasks stay on the board. Repositories with Issues disabled can still track pull requests.</DialogDescription><div className="pr-sync-list">{paused&&<p>{pauseText} GitHub actions can be retried after this time. Closing an issue is never retried automatically.</p>}{warnings.map(r=><PRContext key={r.name+r.kind} actions={[{label:'Copy repository name',run:()=>copy(r.name)}]}><div className="pr-warning"><strong>{r.name} · {r.kind}</strong><p>{r.error||`Showing the first 200 open ${r.kind}. Missing cards are kept until their state can be verified.`}</p></div></PRContext>)}{disabledIssues.map(r=><PRContext key={r.name} actions={[{label:'Copy repository name',run:()=>copy(r.name)}]}><div className="pr-sync-disabled"><strong>{r.name}</strong><p>Issues disabled on GitHub</p></div></PRContext>)}{!syncSummary&&<p>All selected repositories are up to date.</p>}</div><div className="dialog-actions"><Button variant="ghost" onClick={()=>setSyncDetails(false)}>Close</Button>{warnings.length>0&&<Button disabled={paused||refreshing} onClick={()=>void refresh()}>{refreshing?'Refreshing…':'Retry sync'}</Button>}</div></DialogContent></Dialog>
  {!loaded?<div className="pr-empty" role="status">Loading Code tasks…</div>:githubCategory&&!data.repositories.length?<div className="pr-empty"><GitPullRequest size={32}/><h2>{issueCategory?'Add issues to your task board':'Add PRs to your task board'}</h2><p>Choose repositories to follow. Assign an agent and keep its report with the task.</p><Button onClick={()=>setPicker(true)}>Choose repositories</Button></div>:<>
   <div className="pr-toolbar">{githubCategory&&<><SelectField label={issueCategory?'Issue view':'PR view'} value={scope} onValueChange={setScope} options={['All tracked','All open','Mine',issueCategory?'Assigned to me':'Review requested',{value:'Closed / merged',label:issueCategory?'Closed':'Closed / merged'}]}/><SelectField label={issueCategory?'Issue repository':'PR repository'} value={repo} onValueChange={setRepo} options={[{value:'',label:'All repositories'},...data.repositories.map(r=>r.name)]}/></>}<Input aria-label="Search Code tasks" placeholder="Find a task…" value={query} onChange={e=>setQuery(e.target.value)}/><span className="pr-muted">{visible.length} item{visible.length===1?'':'s'}</span></div>
   <div className="pr-board">{stages.map(stage=><section key={stage} aria-label={statusLabel[stage]} className={`pr-column ${drag===stage?'pr-drop':''}`} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-zq-pr')){e.preventDefault();setDrag(stage)}}} onDragLeave={()=>setDrag(null)} onDrop={e=>{e.preventDefault();setDrag(null);const c=cards.find(c=>c.id===e.dataTransfer.getData('application/x-zq-pr'));if(c&&c.state==='OPEN')move(c,stage)}}><header><span className={`pr-dot pr-dot-${stages.indexOf(stage)}`}/><h2>{statusLabel[stage]}</h2><span className="pr-muted">{visible.filter(c=>c.stage===stage).length}</span></header><div className="pr-stack">{visible.filter(c=>c.stage===stage).map(tile)}{!visible.some(c=>c.stage===stage)&&<p className="pr-column-empty">No tasks here</p>}</div></section>)}</div>
   <footer className="pr-footer">Merged PRs and closed issues move to Done after refresh. Moving a card yourself does not change GitHub.</footer>
  </>}
  <RepoPicker open={picker&&active} onClose={()=>setPicker(false)} data={data} save={async names=>{accept(await bridge.invoke('configure',{repositories:names}));setRepo('');setPicker(false);void refresh()}} copy={copy}/>
  <Dialog open={!!detail&&active} onOpenChange={o=>{if(!o){setSelected('');setAssigning('')}}}><DialogContent className="pr-dialog pr-detail"><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>{detail?.source==='task'?`Code task · ${detail.category}`:`${detail?.repo} #${detail?.number} · ${detail?.author} · ${detail?.state.toLowerCase()}`}</DialogDescription>{detail&&<>
   <div className="pr-actions">{detail.source!=='task'&&<Button variant="outline" onClick={()=>open(detail)}><ArrowSquareOut size={15}/>Open on GitHub</Button>}{detail.source==='issue'&&detail.state==='OPEN'&&<Button variant="outline" onClick={()=>requestClose(detail)}>Close issue on GitHub…</Button>}<SelectField label="Task workflow column" value={detail.stage} onValueChange={s=>move(detail,s as PRStage)} options={statusOptions} disabled={detail.state!=='OPEN'}/><More actions={actions(detail)} label="Task actions"/></div>
   <div className="pr-actions">{reviewActions(detail).map(a=><Button key={a.label} variant="outline" disabled={a.disabled} onClick={a.run}>{a.label}</Button>)}</div>
   {((detail.linkedPRIds?.length||0)>0||cards.some(c=>c.linkedPRIds?.includes(detail.id)))&&<section className="pr-linked-work"><h3>Linked work</h3>{[...(detail.linkedPRIds||[]).map(id=>cards.find(c=>c.id===id)).filter((c):c is BoardCard=>!!c),...cards.filter(c=>c.linkedPRIds?.includes(detail.id))].map(c=><PRContext key={c.id} actions={[{label:'Open linked card',run:()=>setSelected(c.id)},{label:'Remove link',run:()=>void perform(async()=>accept(await bridge.invoke('unlinkPR',{id:detail.linkedPRIds?.includes(c.id)?detail.id:c.id,prId:detail.linkedPRIds?.includes(c.id)?c.id:detail.id})))}]}><button onClick={()=>setSelected(c.id)}><span>{c.source==='task'?'Task':`${c.repo} #${c.number}`} · {c.state==='OPEN'?statusLabel[c.stage]:c.state.toLowerCase()}</span><strong>{c.title}</strong></button></PRContext>)}</section>}
   {detail.description&&<p className="code-task-description">{detail.description}</p>}
   {error&&<p className="pr-error" role="alert">{error}</p>}
   {detail.stale&&<p className="pr-warning">This PR’s current state could not be verified. Refresh before assigning a review.</p>}
   {latest&&<div className="pr-review-summary"><strong>{latest.sessionState==='stopped'?'Session ended · report saved':runLabel[latest.state]}</strong><span>{latest.agent} · {data.profiles.find(p=>p.id===latest.profileId)?.name||'Native account'} · {new Date(latest.startedAt).toLocaleString()}</span>{latest.error&&<p className="pr-error">{latest.error}</p>}{latest.head!==detail.head&&<p className="pr-warning">This item changed after the agent started. The report refers to an earlier version.</p>}<div className="pr-actions"><Button disabled={!latest.sessionId} onClick={()=>linked(latest.sessionId)}><Robot size={15}/>Open agent</Button>{canEnd(latest)&&<Button variant="outline" onClick={()=>setEnding({id:detail.id,run:latest})}><Stop size={15}/>End session</Button>}{isActive(latest.state)&&<Button variant="ghost" onClick={()=>setEnd(detail.id)}>End tracking…</Button>}</div>{latest.sessionId&&<p className="pr-muted">{latest.sessionState==='stopped'?'Your report and native conversation are saved. Open the agent to resume when needed.':detail.source==='issue'?'Review the findings, request changes, or implement the suggested fix in the same agent conversation.':detail.state!=='OPEN'?'The GitHub work is closed. End the agent session when you are finished; its report and conversation stay saved.':detail.source==='task'?'Continue this conversation to give the agent its next instructions.':'Request changes in the same conversation, or merge the reviewed commit with confirmation.'}</p>}</div>}
   {assigning===detail.id?<Assignment issue={detail.source==='issue'} task={detail.source==='task'} data={data} pending={pending===detail.id} submit={async(agent,profileId,projectId)=>{setPending(detail.id);setError('');try{accept(await bridge.invoke('assign',{id:detail.id,agent,profileId,projectId}));setAssigning('')}catch(e){setError((e as Error).message)}finally{setPending('')}}} cancel={()=>setAssigning('')}/>:<Button className="pr-assign-button" variant="outline" disabled={detail.state!=='OPEN'||!!detail.stale||detail.runs.some(r=>isActive(r.state))} onClick={()=>setAssigning(detail.id)}><Robot size={16}/>{detail.source==='task'?'Assign agent':detail.source==='issue'?'Investigate issue':detail.runs.length?'Assign another review':'Assign agent to review'}</Button>}
   {data.contextError&&<p className="pr-warning">{data.contextError}</p>}
   {detail.runs.length>0?<div className="pr-reports">{[...detail.runs].reverse().map((r,i)=><PRContext key={r.id} actions={[{label:'Copy report',run:()=>copy(r.report),disabled:!r.report},...sessionActions(detail,r)]}><section className="pr-report"><header><h3>{i===0?'Latest report':`Review ${detail.runs.length-i}`}</h3><span className="pr-muted">{r.action==='implement'?'Implementation':r.action==='changes'?'Requested changes':r.agent} · {runLabel[r.state]}</span><More label={`Report actions ${detail.runs.length-i}`} actions={[{label:'Copy report',run:()=>copy(r.report),disabled:!r.report},...sessionActions(detail,r)]}/></header>{r.instructions&&<p className="pr-followup-instructions"><strong>Your instructions</strong>{r.instructions}</p>}{r.reportTruncated&&<p className="pr-warning">Showing the latest part of this report. Open the linked Code session for the full response.</p>}{r.report?<ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({children})=><span>{children}</span>,img:({alt})=><span>{alt}</span>}}>{r.report}</ReactMarkdown>:<p className="pr-muted">{isActive(r.state)?'The report will appear here as the agent responds.':'No report was captured. Open the linked session for details.'}</p>}</section></PRContext>)}</div>:<p className="pr-muted">Agent reports stay on this task. The full conversation stays in its native Claude, Codex, or Kimi history.</p>}
  </>}</DialogContent></Dialog>
  <CodeReviewActions action={reviewAction} active={active} data={data} accept={accept} close={()=>setReviewAction(null)}/>
  <Dialog open={!!closingIssue&&active} onOpenChange={o=>{if(!o&&!closing)setClosingIssue(null)}}><DialogContent className="pr-dialog"><DialogTitle>Close issue on GitHub?</DialogTitle><DialogDescription>This closes the issue on GitHub and moves its card to Done. Saved reports and agent history stay on the card.</DialogDescription><div><p className="pr-muted">{closingIssue?.repo} #{closingIssue?.number}</p><strong>{closingIssue?.title}</strong></div><label>Reason<SelectField label="Issue closing reason" value={closeReason} onValueChange={v=>setCloseReason(v as 'completed'|'not_planned')} disabled={closing} options={[{value:'completed',label:'Completed'},{value:'not_planned',label:'Not planned'}]}/></label><p className="pr-muted">{closeReason==='completed'?'The issue has been resolved.':'The issue will not be worked on.'}{closingIssue?.runs.some(r=>isActive(r.state))?' Its agent session will remain open.':''}</p>{closeError&&<p className="pr-error" role="alert">{closeError}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={closing} onClick={()=>{if(closingIssue)open(closingIssue)}}>Open on GitHub</Button><Button variant="ghost" disabled={closing} onClick={()=>setClosingIssue(null)}>Cancel</Button><Button disabled={closing} onClick={()=>void (async()=>{if(!closingIssue||closing)return;setClosing(true);setCloseError('');try{accept(await bridge.invoke('closeIssue',{id:closingIssue.id,reason:closeReason}));setClosingIssue(null);host.notify('Issue closed on GitHub')}catch(e){setCloseError((e as Error).message);void bridge.invoke('snapshot',undefined).then(accept).catch(()=>{})}finally{setClosing(false)}})()}>{closing?'Closing…':'Close issue'}</Button></div></DialogContent></Dialog>
  <Dialog open={!!ending&&active} onOpenChange={o=>{if(!o&&!stopping)setEnding(null)}}><DialogContent className="pr-dialog"><DialogTitle>End agent session?</DialogTitle><DialogDescription>This stops the agent and closes its tab. The task, report and native conversation stay saved. You can open the agent again later.</DialogDescription>{error&&<p className="pr-error" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={stopping} onClick={()=>setEnding(null)}>Cancel</Button><Button disabled={stopping} onClick={()=>void perform(async()=>{if(!ending||stopping)return;setStopping(true);try{accept(await bridge.invoke('endSession',{id:ending.id,runId:ending.run.id}));host.commands.run('code.dismissSession',{id:ending.run.sessionId!});setEnding(null)}finally{setStopping(false)}})}>{stopping?'Ending…':'End session'}</Button></div></DialogContent></Dialog>
  <Dialog open={!!end&&active} onOpenChange={o=>{if(!o)setEnd('')}}><DialogContent className="pr-dialog"><DialogTitle>End review tracking?</DialogTitle><DialogDescription>This keeps the report and native conversation. It does not stop the agent. Check the linked Code session first; a busy session must be stopped there before tracking can end.</DialogDescription>{error&&<p className="pr-error" role="alert">{error}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={()=>setEnd('')}>Cancel</Button><Button onClick={()=>void perform(async()=>{accept(await bridge.invoke('endTracking',{id:end}));setEnd('')})}>End tracking</Button></div></DialogContent></Dialog>
  <TaskEditor task={editing} open={!!editing&&active} close={()=>setEditing(null)} save={async input=>{accept(await bridge.invoke('saveTask',input));setEditing(null)}}/>
  <Dialog open={!!deleting&&active} onOpenChange={o=>{if(!o)setDeleting('')}}><DialogContent className="pr-dialog"><DialogTitle>Delete Code task?</DialogTitle><DialogDescription>The task and its saved reports will be removed from this board. Native agent conversations remain in Code.</DialogDescription>{error&&<p role="alert" className="pr-error">{error}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={()=>setDeleting('')}>Cancel</Button><Button onClick={()=>void perform(async()=>{accept(await bridge.invoke('deleteTask',{id:deleting}));if(selected===deleting)setSelected('');setDeleting('')})}>Delete task</Button></div></DialogContent></Dialog>
 </div></ModuleSurface>
}
function Assignment({data,pending,submit,cancel,task,issue}:{issue:boolean;task:boolean;data:GitHubBoardSnapshot;pending:boolean;submit:(a:CodeAgent,p:string,c:string)=>Promise<void>;cancel:()=>void}){
 const [agent,setAgent]=useState<CodeAgent>('claude'),[profile,setProfile]=useState(''),[project,setProject]=useState(data.projects[0]?.id||'')
 const profiles=data.profiles.filter(p=>(p.adapter||'claude')===agent),selected=profiles.find(p=>p.id===profile)?.id||profiles[0]?.id||''
 return <form className="pr-assignment" onSubmit={e=>{e.preventDefault();if(!pending)void submit(agent,agent==='kimi'?'':selected,project)}}><h3>{task?'Assign this task':issue?'Investigate this issue':'Assign a review'}</h3><div className="pr-form-row"><label>Agent<SelectField label="Review agent" value={agent} onValueChange={a=>{setAgent(a as CodeAgent);setProfile('')}} options={[{value:'claude',label:'Claude'},{value:'codex',label:'Codex'},{value:'kimi',label:'Kimi'}]} disabled={pending}/></label>{agent!=='kimi'&&<label>Account<SelectField label="Review account" value={selected} onValueChange={setProfile} options={profiles.length?profiles.map(p=>({value:p.id,label:p.name})):[{value:'',label:'No account profiles'}]} disabled={pending}/></label>}<label>Local project<SelectField label="Review project" value={project} onValueChange={setProject} options={data.projects.length?data.projects.map(p=>({value:p.id,label:p.name})):[{value:'',label:'Add a project in Code'}]} disabled={pending}/></label></div><p className="pr-muted">{issue?'The agent reads the issue, attempts a safe reproduction and proposes a fix. You review the report before it implements changes.':task?'Starts a new native conversation in this project with the task instructions.':'Starts a new native conversation in this folder to inspect the PR and report back without changing files or GitHub.'}</p>{!data.projects.length&&<p className="pr-warning">Add a local project in Code first. Remote agent reviews are not supported here yet.</p>}<div className="pr-actions"><Button type="button" variant="ghost" disabled={pending} onClick={cancel}>Cancel</Button><Button type="submit" disabled={pending||!project||agent!=='kimi'&&!selected}>{pending?'Starting…':task?'Start agent':issue?'Start investigation':'Start review'}</Button></div></form>
}
function RepoPicker({open,onClose,data,save,copy}:{open:boolean;onClose:()=>void;data:GitHubBoardSnapshot;save:(names:string[])=>Promise<void>;copy:(s:string)=>void}){
 const bridge=useHost().services.github
 const [names,setNames]=useState<string[]>([]),[chosen,setChosen]=useState<string[]>([]),[query,setQuery]=useState(''),[manual,setManual]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[truncated,setTruncated]=useState(false)
 useEffect(()=>{if(!open)return;setChosen(data.repositories.map(r=>r.name));setQuery('');setManual('');setError('');setLoading(true);let stopped=false;void bridge.invoke('discover',undefined).then(r=>{if(!stopped){setNames(r.repositories);setTruncated(r.truncated)}}).catch(e=>{if(!stopped)setError(e.message)}).finally(()=>{if(!stopped)setLoading(false)});return()=>{stopped=true}},[open,bridge])
 const rows=[...new Map([...chosen,...names].map(n=>[n.toLowerCase(),n])).values()].filter(n=>n.toLowerCase().includes(query.toLowerCase()))
 const selectedNames=new Set(chosen.map(n=>n.toLowerCase())),matchingSelected=rows.filter(n=>selectedNames.has(n.toLowerCase()))
 function selectResults(){setChosen(old=>[...new Map([...old,...rows].map(n=>[n.toLowerCase(),n])).values()])}
 function clearResults(){const matching=new Set(rows.map(n=>n.toLowerCase()));setChosen(old=>old.filter(n=>!matching.has(n.toLowerCase())))}
 function toggle(name:string){setChosen(old=>old.some(n=>n.toLowerCase()===name.toLowerCase())?old.filter(n=>n.toLowerCase()!==name.toLowerCase()):[...old,name])}
 function add(){const name=manual.trim();if(!/^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/.test(name)){setError('Enter a repository as owner/name.');return}setChosen(old=>old.some(n=>n.toLowerCase()===name.toLowerCase())?old:[...old,name]);setManual('');setError('')}
 return <Dialog open={open} onOpenChange={o=>{if(!o&&!saving)onClose()}}><DialogContent className="pr-dialog pr-repo-picker"><DialogTitle>Choose repositories</DialogTitle><DialogDescription>Uses your GitHub CLI account. Select the repositories to follow. Removing one hides its cards and keeps saved reports.</DialogDescription><Input aria-label="Search repositories" placeholder="Find a repository…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="pr-picker-meta"><span>{chosen.length} selected</span><div className="pr-actions"><Button variant="ghost" size="sm" disabled={loading||saving||!rows.length||matchingSelected.length===rows.length} onClick={selectResults}>{query?'Select results':'Select all'}</Button><Button variant="ghost" size="sm" disabled={saving||!matchingSelected.length} onClick={clearResults}>{query?'Clear results':'Clear selection'}</Button></div></div>{error&&<p className="pr-error" role="alert">{error}</p>}<div className="pr-repo-list">{rows.map(name=>{const checked=chosen.some(n=>n.toLowerCase()===name.toLowerCase());return <PRContext key={name} actions={[{label:checked?'Remove from selection':'Select repository',run:()=>toggle(name),disabled:saving},{label:'Copy repository name',run:()=>copy(name)}]}><label className="pr-repo-row"><Checkbox checked={checked} disabled={saving} onCheckedChange={()=>toggle(name)}/><FolderSimple size={17}/><span>{name}</span></label></PRContext>})}{loading&&<p role="status">Loading repositories…</p>}{!loading&&!rows.length&&<p className="pr-muted">No matching repositories. You can add one by name below.</p>}</div>{truncated&&<p className="pr-muted">Showing up to 500 recently active repositories. Add others by name.</p>}<form className="pr-manual" onSubmit={e=>{e.preventDefault();add()}}><Input aria-label="Repository owner/name" placeholder="owner/repository" value={manual} onChange={e=>setManual(e.target.value)} disabled={saving}/><Button type="submit" variant="outline" disabled={!manual.trim()||saving}>Add</Button></form><div className="dialog-actions"><Button variant="ghost" disabled={saving} onClick={onClose}>Cancel</Button><Button disabled={saving} onClick={async()=>{setSaving(true);setError('');try{await save(chosen)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}}>{saving?'Saving…':'Save selection'}</Button></div></DialogContent></Dialog>
}

function TaskEditor({task,open,close,save}:{task:Partial<CodeTaskCard>|null;open:boolean;close:()=>void;save:(input:{id?:string;title:string;description:string;category:string;stage:PRStage})=>Promise<void>}){
 const [draft,setDraft]=useState({title:'',description:'',category:'General',stage:'Needs review' as PRStage}),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{if(task){setDraft({title:task.title||'',description:task.description||'',category:task.category||'General',stage:task.stage||'Needs review'});setError('')}},[task])
 return <Dialog open={open} onOpenChange={o=>{if(!o&&!busy)close()}}><DialogContent className="pr-dialog"><DialogTitle>{task?.id?'Edit Code task':'New Code task'}</DialogTitle><DialogDescription>Organize your coding work. Open PRs and Issues are GitHub categories on this same board.</DialogDescription><form className="code-task-editor" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await save({...draft,...(task?.id?{id:task.id}:{})})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Title<Input aria-label="Code task title" required maxLength={500} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label>Instructions<Textarea aria-label="Code task instructions" maxLength={12000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="pr-form-row"><label>Category<Input aria-label="Code task category" required maxLength={80} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}/></label><label>Status<SelectField label="Code task status" value={draft.stage} onValueChange={stage=>setDraft({...draft,stage:stage as PRStage})} options={statusOptions}/></label></div>{error&&<p role="alert" className="pr-error">{error}</p>}<div className="dialog-actions"><Button type="button" variant="ghost" disabled={busy} onClick={close}>Cancel</Button><Button type="submit" disabled={busy||!draft.title.trim()||!draft.category.trim()}>{busy?'Saving…':'Save task'}</Button></div></form></DialogContent></Dialog>
}
