import {useEffect,useRef,useState} from 'react'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {Button,Textarea,TooltipButton,Input} from '@zq/ui'
import {ArrowUp,Stop,Check,CaretDown} from '@phosphor-icons/react'
import {useHost,type CodeSession,type CodeEvent} from '@zq/module-api'
import {mergeEvents,canWrite,stateLabel} from './session-model'

function Permission({event,session,onError}:{event:CodeEvent;session:CodeSession;onError:(message:string)=>void}){
 const bridge=useHost().services.code,[busy,setBusy]=useState(false),[answers,setAnswers]=useState<Record<string,string>>({})
 const questions=Array.isArray(event.input?.questions)?event.input.questions as {question?:string;header?:string;options?:{label:string;description?:string}[];multiSelect?:boolean}[]:[]
 async function respond(allow:boolean){if(!event.requestId)return;setBusy(true);try{await bridge.invoke('respondPermission',{id:session.id,requestId:event.requestId,allow,...(questions.length?{answers}:{})})}catch(error){onError(String(error instanceof Error?error.message:error))}finally{setBusy(false)}}
 if(event.resolved)return <details className="code-resolved"><summary><Check size={14}/>Answered <CaretDown size={12}/></summary><p>{event.text}</p></details>
 return <section className="code-permission" aria-label={questions.length?'Claude needs your input':'Tool permission'}><strong>{questions.length?'Claude needs your input':event.toolName||'Permission requested'}</strong><p>{event.text}</p>{questions.length?questions.map((question,index)=>{const key=question.question||question.header||String(index);return <fieldset key={key}><legend>{question.question}</legend>{question.options?.map(option=><label key={option.label}><input type={question.multiSelect?'checkbox':'radio'} name={key} checked={(answers[key]||'').split(', ').includes(option.label)} onChange={e=>setAnswers(old=>({...old,[key]:question.multiSelect?(e.target.checked?[...(old[key]||'').split(', ').filter(Boolean),option.label]:(old[key]||'').split(', ').filter(value=>value!==option.label)).join(', '):option.label}))}/><span>{option.label}{option.description&&<small>{option.description}</small>}</span></label>)}<Input aria-label={`Answer: ${key}`} placeholder="Or enter an answer" value={answers[key]||''} onChange={e=>setAnswers(old=>({...old,[key]:e.target.value}))}/></fieldset>}):event.input&&<details><summary>Review action</summary><pre>{JSON.stringify(event.input,null,2)}</pre></details>}<div className="code-actions"><Button variant="ghost" disabled={busy||!canWrite(session)} onClick={()=>void respond(false)}>Decline</Button><Button disabled={busy||!canWrite(session)||(questions.length>0&&questions.some(q=>!answers[q.question||q.header||'']))} onClick={()=>void respond(true)}>{questions.length?'Submit answer':'Allow once'}</Button></div></section>
}
export function CodeChat({session,onError}:{session:CodeSession;onError:(message:string)=>void}){
 const host=useHost(),bridge=host.services.code,[events,setEvents]=useState<CodeEvent[]>([]),[draft,setDraft]=useState(()=>localStorage.getItem(`zq.code.draft.${session.id}`)||''),[sending,setSending]=useState(false),[truncated,setTruncated]=useState(false),bottom=useRef<HTMLDivElement>(null),scroller=useRef<HTMLDivElement>(null),follow=useRef(true)
 const errors=useRef(onError);errors.current=onError
 useEffect(()=>{let disposed=false,after=0,timer:ReturnType<typeof setTimeout>;setEvents([]);setTruncated(false);follow.current=true
  const poll=async()=>{try{const page=await bridge.invoke('events',{id:session.id,after});if(disposed)return;after=page.seq;setEvents(old=>mergeEvents(old,page.events,page.truncated));if(page.truncated)setTruncated(true)}catch(error){if(!disposed)errors.current(error instanceof Error?error.message:String(error))}finally{if(!disposed)timer=setTimeout(poll,600)}}
  void poll();return()=>{disposed=true;clearTimeout(timer)}
 },[bridge,session.id])
 useEffect(()=>{if(follow.current)bottom.current?.scrollIntoView({block:'end'})},[events,session.state])
 useEffect(()=>{if(draft.trim())localStorage.setItem(`zq.code.draft.${session.id}`,draft);else localStorage.removeItem(`zq.code.draft.${session.id}`)},[session.id,draft])
 async function send(){if(!draft.trim()||sending||session.state!=='ready')return;const text=draft;setSending(true);try{await bridge.invoke('sendMessage',{id:session.id,text});setDraft('');localStorage.removeItem(`zq.code.draft.${session.id}`);follow.current=true}catch(error){onError(error instanceof Error?error.message:String(error))}finally{setSending(false)}}
 return <div className="code-chat"><div className="code-transcript" ref={scroller} onScroll={()=>{const el=scroller.current;if(el)follow.current=el.scrollHeight-el.scrollTop-el.clientHeight<100}}>{truncated&&<p className="code-muted">Earlier activity is outside the display history. Claude’s native conversation is retained.</p>}{!events.length&&<div className="code-chat-empty"><h2>What are we building?</h2><p>Claude works in this project using your selected profile.</p></div>}{events.map(event=><div className={`code-event code-event-${event.kind}`} key={event.seq}>{event.kind==='permission'||event.kind==='question'?<Permission event={event} session={session} onError={onError}/>:event.kind==='tool'?<details><summary>{event.toolName||'Tool activity'}</summary><p>{event.text}</p>{event.input&&<pre>{JSON.stringify(event.input,null,2)}</pre>}</details>:event.kind==='assistant'?<ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=><a href={href} onClick={e=>{e.preventDefault();if(href)void bridge.invoke('openExternal',{url:href}).catch(error=>onError(error.message))}}>{children}</a>}}>{event.text}</ReactMarkdown>:<p>{event.text}</p>}</div>)}{['starting','busy','switching'].includes(session.state)&&<div className="code-working" role="status"><span/>{stateLabel(session)}…</div>}<div ref={bottom}/></div><form className="code-composer" onSubmit={e=>{e.preventDefault();void send()}}><Textarea aria-label="Message Claude" placeholder={session.state==='approval'?'Answer Claude’s question above…':'Ask Claude to work in this project…'} value={draft} disabled={!canWrite(session)} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void send()}}}/><div><span>Enter to send · Shift Enter for a new line</span>{session.state==='busy'?<TooltipButton type="button" aria-label="Interrupt Claude" onClick={()=>void bridge.invoke('interruptSession',{id:session.id}).catch(error=>onError(error.message))}><Stop size={18}/></TooltipButton>:<TooltipButton type="submit" aria-label="Send message" disabled={sending||!draft.trim()||session.state!=='ready'}><ArrowUp size={19}/></TooltipButton>}</div></form></div>
}
