import type { Result } from './desktop'
export type ProviderKind='ollama'|'vllm'|'openai'|'anthropic'|'google'|'xai'|'perplexity'|'openrouter'|'groq'|'bedrock'
export type ModelChoice={connectionId:string;model:string}
export type Connection={id:string;name:string;provider:ProviderKind;baseUrl:string;hasApiKey?:boolean;updatedAt?:number;enabledModels:string[];favoriteModels:string[];modelLabels?:Record<string,string>}
export type ConnectionInput={id?:string;name:string;provider:ProviderKind;baseUrl:string;apiKey?:string;removeApiKey?:boolean;enabledModels?:string[]}
export type Attachment={resourcePath?:string;id:string;name:string;kind:'text'|'image'|'pdf';size:number;mime:string;preview:string;pages?:number;width?:number;height?:number}
export type AttachmentPreview=Attachment&{text?:string;image?:string}
export type AttachmentResult={items:Attachment[];errors:{name:string;message:string}[]}
export type AttachmentBridge={pick:()=>Promise<Result<AttachmentResult>>;import:(files:{name:string;bytes:Uint8Array}[])=>Promise<Result<AttachmentResult>>;discard:(id:string)=>Promise<Result<null>>;preview:(id:string)=>Promise<Result<AttachmentPreview>>}
export type ChatSkill={source?:SkillSource;package?:SkillPackage;id:string;name:string;description:string;instructions:string;files:Attachment[];createdAt:number;updatedAt:number}
export type ChatProject={connectorIds?:string[];skillIds?:string[];pinned?:boolean;defaultModel?:ModelChoice|null;defaultTools?:ChatToolKind[];icon?:string;color?:string;id:string;name:string;instructions:string;files:Attachment[]}
export type ChatToolKind='web_search'|'x_search'|'code_execution'
export type ChatToolOption={kind:ChatToolKind;label:string;description:string}
export type ChatToolActivity={id:string;kind:ChatToolKind|'create_document'|'mcp';status:'running'|'complete'|'error'|'stopped'|'interrupted';detail?:string}
export type GeneratedFile={id:string;name:string;mime:string;size:number}
export type GeneratedFileTarget={conversationId:string;messageId:string;fileId:string}
export type ChatSource={id:string;url:string;title:string}
export type ChatInteraction={id:string;kind:'clarification'|'approval';question:string;options?:string[];tool?:string;detail?:string;onceOnly?:boolean;approvalAction?:'send_email'|'create_event'|'reschedule_event'|'cancel_event'|'upload_file';status:'waiting'|'answered'|'denied'|'cancelled';answer?:string;createdAt:number}
export type QueuedMessage={connectorIds?:string[];id:string;text:string;createdAt:number;connectionId:string;model:string;attachments:Attachment[];context:{id:string;title:string;body:string}[];skillContext?:ChatSkill[];tools:ChatToolKind[]}
export type ChatQueueState={items:QueuedMessage[];paused:boolean;error:string}
export type ChatSkillUsage={id:string;name:string;description:string;source:'automatic'|'selected';referenceNames:string[];hasResources:boolean}
export type ChatMessage={connectorIds?:string[];skillUsage?:ChatSkillUsage[];interactions?:ChatInteraction[];skillContext?:ChatSkill[];artifactContext?:import('./artifact-types').ArtifactTarget;sources?:ChatSource[];reportedModel?:string;usage?:{inputTokens?:number;outputTokens?:number;cachedInputTokens?:number;reasoningTokens?:number};activeVersionId?:string;versions?:{id:string;content:string;createdAt:number;model?:string}[];connectionId?:string;connectionName?:string;model?:string;provider?:ProviderKind;finishedAt?:number;id:string;role:'user'|'assistant';content:string;thinking:string;tools?:ChatToolKind[];toolActivity?:ChatToolActivity[];generatedFiles?:GeneratedFile[];status:'complete'|'streaming'|'stopped'|'error'|'interrupted';createdAt:number;attachments?:Attachment[];projectContext?:ChatProject;context:{id:string;title:string;body:string}[];error:string}
export type Conversation={connectorIds?:string[]|null;queue?:ChatQueueState;approvalMode?:'auto'|'ask';skillIds?:string[]|null;pinned?:boolean;archivedAt?:number|null;deletedAt?:number|null;projectId?:string|null;id:string;title:string;connectionId:string|null;model:string;createdAt:number;updatedAt:number;messages:ChatMessage[]}
export type ChatDraft={research?:import('./research-types').ResearchDraft;connectorIds?:string[]|null;skillIds?:string[]|null;text:string;noteIds:string[];tools:ChatToolKind[];attachments:Attachment[]}
export type ChatViewState={selected:string;projectId:string|null;projectHome:boolean;positions:Record<string,number>}
export type ChatSnapshot={skills?:ChatSkill[];drafts?:Record<string,ChatDraft>;chatView?:ChatViewState;defaultModel:ModelChoice|null;projects:ChatProject[];connections:Connection[];conversations:Conversation[];revision:number;error:string}
export type SkillSource={catalogId:string;revision:string;contentHash:string}
export type SkillUpdatePreview={id:string;expectedHash:string;candidate:SkillImport;modified:boolean}
export type SkillCatalogEntry={revision?:string;checkedAt?:number;checkError?:string;id:string;name:string;description:string;category:string;source:string;url:string;requirements:string}
export type SkillPackage={frontmatter:string;resources:{path:string;digest:string;size:number}[]}
export type SkillImport={source?:SkillSource;package?:{frontmatter:string;resources:{path:string;data:string;size:number}[]};name:string;description:string;instructions:string;files:{resourcePath?:string;name:string;kind:'text'|'pdf';mime:string;size:number;text:string;pages?:number}[];warnings:string[]}
export type ChatBridge={
 setConversationConnectors:(input:{conversationId:string;connectorIds:string[]|null})=>Promise<Result<ChatSnapshot>>;
 enqueueMessage:(input:Parameters<ChatBridge['send']>[0])=>Promise<Result<ChatSnapshot>>;
 updateQueuedMessage:(input:{conversationId:string;id:string;text?:string;move?:'up'|'down';remove?:boolean})=>Promise<Result<ChatSnapshot>>;
 setQueuePaused:(input:{conversationId:string;paused:boolean})=>Promise<Result<ChatSnapshot>>;
 respondToInteraction:(input:{conversationId:string;id:string;answer?:string;decision?:'once'|'chat'|'deny'})=>Promise<Result<ChatSnapshot>>;
 setApprovalMode:(input:{conversationId:string;mode:'auto'|'ask'})=>Promise<Result<ChatSnapshot>>;
 checkSkillUpdates:()=>Promise<Result<SkillCatalogEntry[]>>;
 previewSkillUpdate:(id:string)=>Promise<Result<SkillUpdatePreview>>;
 updateCatalogSkill:(input:{id:string;expectedHash:string;candidate:SkillImport})=>Promise<Result<ChatSkill>>;
 browseSkills:(input?:{query?:string})=>Promise<Result<SkillCatalogEntry[]>>;
 previewCatalogSkill:(id:string)=>Promise<Result<SkillImport>>;
 pickSkillImport:(options?:{directory?:boolean})=>Promise<Result<SkillImport|null>>;
 previewSkillResource:(input:{id:string;path:string})=>Promise<Result<{name:string;text?:string;size:number}>>;
 saveSkillResource:(input:{id:string;path:string})=>Promise<Result<boolean>>;
 importSkill:(input:SkillImport)=>Promise<Result<ChatSkill>>;
 saveSkill:(input:{id?:string;name?:string;description?:string;instructions?:string})=>Promise<Result<ChatSkill>>;
 duplicateSkill:(id:string)=>Promise<Result<ChatSkill>>;
 deleteSkill:(id:string)=>Promise<Result<null>>;
 addSkillFiles:(input:{id:string;attachmentIds:string[]})=>Promise<Result<null>>;
 removeSkillFile:(input:{id:string;attachmentId:string})=>Promise<Result<null>>;
 exportSkill:(id:string)=>Promise<Result<boolean>>;
 searchProjectFiles:(input:{id:string;query:string})=>Promise<Result<{id:string;snippet:string}[]>>;
 searchConversations:(input:{query:string;scope:'active'|'archived'|'trash'})=>Promise<Result<{conversationId:string;messageId?:string;versionId?:string;snippet:string}[]>>;
 inspectContext:(input:{skillIds?:string[]|null;conversationId?:string;projectId?:string|null;text:string;noteIds:string[];attachmentIds:string[];tools:ChatToolKind[]})=>Promise<Result<{referenceBytes:number;conversationBytes:number;error:string}>>;
 reviseMessage:(input:{conversationId:string;messageId:string;text?:string;connectionId?:string;model?:string})=>Promise<Result<ChatSnapshot>>;
 branchConversation:(input:{conversationId:string;messageId:string})=>Promise<Result<Conversation>>;
 selectMessageVersion:(input:{conversationId:string;messageId:string;versionId:string})=>Promise<Result<Conversation>>;
 updateConversation:(input:{id:string;pinned?:boolean;archived?:boolean;deleted?:boolean})=>Promise<Result<Conversation>>;
 updateProject:(input:{connectorIds?:string[];skillIds?:string[];id:string;pinned?:boolean;defaultModel?:ModelChoice|null;defaultTools?:ChatToolKind[]})=>Promise<Result<ChatProject>>;
 saveDraft:(input:{research?:import('./research-types').ResearchDraft;connectorIds?:string[]|null;skillIds?:string[]|null;id:string;text:string;noteIds:string[];tools:ChatToolKind[];attachmentIds:string[]})=>Promise<Result<null>>;
 saveChatView:(input:ChatViewState)=>Promise<Result<null>>;
 exportConversation:(id:string)=>Promise<Result<boolean>>;
 saveTextFile:(input:{name:string;text:string})=>Promise<Result<boolean>>;
 previewGeneratedFile:(input:GeneratedFileTarget)=>Promise<Result<GeneratedFile&{text?:string;image?:string}>>;
 reuseGeneratedFile:(input:GeneratedFileTarget)=>Promise<Result<Attachment>>;
 generatedFileToProject:(input:GeneratedFileTarget&{projectId:string})=>Promise<Result<null>>;
 load:()=>Promise<Result<ChatSnapshot>>;
 toolOptions:(input:{connectionId:string;model:string})=>Promise<Result<ChatToolOption[]>>;
 saveGeneratedFile:(input:GeneratedFileTarget)=>Promise<Result<boolean>>;
 sourceIcon?:(url:string)=>Promise<Result<string|null>>;
 openLink:(url:string)=>Promise<Result<null>>;
 subscribe:(callback:(snapshot:ChatSnapshot)=>void)=>()=>void;
 saveConnection:(input:ConnectionInput)=>Promise<Result<Connection>>;
 saveModelPreferences:(input:{connectionId:string;enabledModels?:string[];favoriteModels?:string[];defaultModel?:string|null;modelLabel?:{model:string;label:string|null}})=>Promise<Result<ChatSnapshot>>;
 deleteConnection:(id:string)=>Promise<Result<null>>;
 createConversation:(input?:{draftFrom?:string;connectionId?:string|null;model?:string;projectId?:string|null})=>Promise<Result<Conversation>>;
 renameConversation:(input:{id:string;title:string})=>Promise<Result<Conversation>>;
 deleteConversation:(id:string)=>Promise<Result<null>>;
 configureConversation:(input:{id:string;connectionId:string;model:string})=>Promise<Result<Conversation>>;
 saveProject:(input:{id?:string;name?:string;instructions?:string;icon?:string;color?:string})=>Promise<Result<ChatProject>>;
 deleteProject:(id:string)=>Promise<Result<null>>;
 moveConversation:(input:{id:string;projectId:string|null})=>Promise<Result<Conversation>>;
 addProjectFiles:(input:{id:string;attachmentIds:string[]})=>Promise<Result<null>>;
 removeProjectFile:(input:{id:string;attachmentId:string})=>Promise<Result<null>>;
 models:(id:string)=>Promise<Result<string[]>>;
 testConnection:(input:string|ConnectionInput)=>Promise<Result<string[]>>;
 send:(input:{connectorIds?:string[]|null;skillIds?:string[]|null;artifactContext?:import('./artifact-types').ArtifactTarget;conversationId:string;text:string;noteIds:string[];attachmentIds?:string[];tools?:ChatToolKind[]})=>Promise<Result<ChatSnapshot>>;
 stop:(id:string)=>Promise<Result<ChatSnapshot>>;
}
