'use strict';
const fs=require('node:fs'),path=require('node:path');
const {randomUUID,createHash}=require('node:crypto');
const {validTypography,checkTypography}=require('./artifact-typography.cjs');
const FORMATS=['pdf','docx','xlsx','pptx'];
const FILE_MAX=10*1024*1024,INDEX_MAX=8*1024*1024,TOTAL_MAX=256*1024*1024;
const text=(v,max)=>typeof v==='string'&&Buffer.byteLength(v)<=max&&!v.includes('\0')&&Buffer.from(v).toString('utf8')===v;
const id=v=>typeof v==='string'&&/^[a-f0-9-]{36}$/.test(v);
const name=v=>text(v,256)&&v.trim()&&!/[\\/\x00-\x1f\x7f]/.test(v)&&!/^\.+$/.test(v);
const stamp=v=>Number.isFinite(v)&&v>=0;
function sourceValid(s){return s===undefined||s&&typeof s==='object'&&!Array.isArray(s)&&Object.keys(s).every(k=>['conversationId','messageId','versionId','conversationTitle','projectId','projectName','generatedFileId'].includes(k))&&Object.values(s).every(v=>text(v,1024))}
function checkDir(p){const s=fs.lstatSync(p);if(!s.isDirectory()||s.isSymbolicLink())throw Error('Artifact storage must be a regular directory.');}
function dir(p){fs.mkdirSync(p,{recursive:true,mode:0o700});checkDir(p)}
function read(p,limit){const fd=fs.openSync(p,fs.constants.O_RDONLY|fs.constants.O_NOFOLLOW|fs.constants.O_NONBLOCK);try{const stat=fs.fstatSync(fd);if(!stat.isFile()||stat.size>limit)throw Error('Artifact file is invalid or exceeds its size limit.');const b=Buffer.alloc(stat.size+1);let offset=0;while(offset<b.length){const n=fs.readSync(fd,b,offset,b.length-offset,null);if(!n)break;offset+=n}if(offset>stat.size)throw Error('Artifact file changed while reading.');return b.subarray(0,offset)}finally{fs.closeSync(fd)}}
function valid(items){return Array.isArray(items)&&items.length<=500&&new Set(items.map(a=>a.id)).size===items.length&&items.every(a=>id(a.id)&&name(a.name)&&text(a.format,32)&&stamp(a.createdAt)&&stamp(a.updatedAt)&&(a.deletedAt===null||stamp(a.deletedAt))&&Array.isArray(a.versions)&&a.versions.length>0&&a.versions.length<=50&&new Set(a.versions.map(v=>v.id)).size===a.versions.length&&a.versions.every((v,i)=>id(v.id)&&v.number===i+1&&name(v.name)&&text(v.mime,128)&&/^[\w.+-]+\/[\w.+-]+$/.test(v.mime)&&Number.isSafeInteger(v.size)&&v.size>=0&&v.size<=FILE_MAX&&stamp(v.createdAt)&&/^[a-f0-9]{64}$/.test(v.hash)&&sourceValid(v.source)&&(v.publicationKey===undefined||text(v.publicationKey,256))&&validTypography(v.typography)&&(v.content===undefined||text(v.content,100000))&&(v.previewText===undefined||text(v.previewText,200000))))}
const visibleVersion=({hash,content,previewText,publicationKey,...v})=>v;
const visible=a=>({...a,versions:a.versions.map(visibleVersion)});
class ArtifactService{
 constructor({directory,render,onChange=()=>{}}){this.directory=path.join(directory,'artifacts');this.files=path.join(this.directory,'files');this.index=path.join(this.directory,'index.json');this.render=render??(input=>require('./artifact-renderer.cjs').renderArtifact(input));this.onChange=onChange;dir(this.directory);dir(this.files);this.items=[];this.indexHash=null;try{const raw=read(this.index,INDEX_MAX);const data=JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(raw));this.indexHash=createHash('sha256').update(raw).digest('hex');if(data.version!==1||!valid(data.items))throw Error('Invalid artifact index.');this.items=data.items}catch(e){if(e.code!=='ENOENT')throw Error('Artifact library could not be read. Its original files have been preserved. '+e.message)}}
 list(){return structuredClone(this.items.map(visible))}
 artifact(artifactId,items=this.items){const a=items.find(a=>a.id===artifactId);if(!a)throw Error('Artifact not found.');return a}
 version({artifactId,versionId}){const a=this.artifact(artifactId),v=a.versions.find(v=>v.id===versionId);if(!v)throw Error('Artifact version not found.');const {hash,previewText,publicationKey,...result}=v;return structuredClone({...result,format:a.format,artifactName:a.name})}
 file(target){checkDir(this.directory);checkDir(this.files);const a=this.artifact(target.artifactId),v=a.versions.find(v=>v.id===target.versionId);if(!v||!id(v.id))throw Error('Artifact version not found.');const buffer=read(path.join(this.files,v.id+'.bin'),FILE_MAX);if(buffer.length!==v.size||createHash('sha256').update(buffer).digest('hex')!==v.hash)throw Error('This artifact file is damaged. Its stored version has been preserved.');return {...visibleVersion(v),data:buffer.toString('base64')}}
 persist(items){if(!valid(items))throw Error('Invalid artifact library update.');if(items.reduce((total,a)=>total+a.versions.reduce((n,v)=>n+v.size,0),0)>TOTAL_MAX)throw Error('Artifact library reached its 256 MB limit.');const data=JSON.stringify({version:1,items});if(Buffer.byteLength(data)>INDEX_MAX)throw Error('Artifact library metadata is full.');dir(this.directory);try{const raw=read(this.index,INDEX_MAX);if(createHash('sha256').update(raw).digest('hex')!==this.indexHash)throw Error('Artifact library changed on disk. Reopen zQ before saving; the original has been preserved.')}catch(e){if(e.code!=='ENOENT')throw e;if(this.indexHash!==null)throw Error('Artifact index disappeared. Reopen zQ before saving.');}const temp=this.index+'.tmp-'+randomUUID();let fd;try{fd=fs.openSync(temp,'wx',0o600);fs.writeFileSync(fd,data);fs.fsyncSync(fd);fs.closeSync(fd);fd=undefined;fs.renameSync(temp,this.index);this.indexHash=createHash('sha256').update(data).digest('hex');try{const d=fs.openSync(this.directory,'r');try{fs.fsyncSync(d)}finally{fs.closeSync(d)}}catch(e){throw Object.assign(Error('Artifact was saved, but its disk flush failed. Keep zQ open and check available storage.'),{committed:true,cause:e})}}finally{if(fd!==undefined)fs.closeSync(fd);fs.rmSync(temp,{force:true})}}
 publish(){try{this.onChange(this.list())}catch{}}
 update({id:artifactId,name:nextName,deleted}){const items=structuredClone(this.items),a=this.artifact(artifactId,items);if(nextName!==undefined){if(!name(nextName))throw Error('Enter a name without path separators, up to 256 bytes.');a.name=nextName.trim()}if(deleted!==undefined){if(typeof deleted!=='boolean')throw Error('Invalid artifact status.');a.deletedAt=deleted?Date.now():null}a.updatedAt=Date.now();try{this.persist(items)}catch(e){if(e.committed){this.items=items;this.publish()}throw e}this.items=items;this.publish();return structuredClone(visible(a))}
 async create(input){const {artifactId,expectedLatestVersionId,format,title,content,source}=input??{};let typography=input?.typography;checkTypography(typography);if(!FORMATS.includes(format)||!name(title)||!text(content,100000)||!content.trim()||!sourceValid(source))throw Error('Choose a supported format, a valid title and up to 100 KB of content.');if(artifactId)this.checkRevision(artifactId,expectedLatestVersionId,format);if(artifactId)typography={...this.artifact(artifactId).versions.at(-1).typography,...typography};const file=await this.render({format,title,content,typography});if(artifactId)this.checkRevision(artifactId,expectedLatestVersionId,format);return this.commit(file,{artifactId,format,title,content,typography,source:source??(artifactId?this.artifact(artifactId).versions.at(-1).source:undefined)})}
 checkRevision(artifactId,expected,format){const a=this.artifact(artifactId);if(a.deletedAt)throw Error('Restore the artifact before creating a version.');if(a.format!==format)throw Error('A new version must use the same file format.');if(a.versions.at(-1).id!==expected)throw Error('This artifact changed. Reopen it before creating a new version.');if(a.versions.length>=50)throw Error('An artifact can hold up to 50 versions.')}
 importFile(file,source){if(!sourceValid(source))throw Error('Invalid artifact source.');if(source?.generatedFileId){const existing=this.items.find(a=>a.versions.some(v=>v.source?.generatedFileId===source.generatedFileId));if(existing)return structuredClone(visible(existing))}const extension=path.extname(file.name??'').slice(1).toLowerCase();return this.commit(file,{format:extension.slice(0,32)||'file',title:file.name,source})}
 commit(file,{artifactId,format,title,content,typography,source,publicationKey}){checkTypography(typography);if(!name(file.name)||!text(file.mime,128)||!/^[\w.+-]+\/[\w.+-]+$/.test(file.mime)||typeof file.data!=='string'||file.data.length>Math.ceil(FILE_MAX/3)*4)throw Error('Artifact output is invalid or exceeds 10 MB.');const buffer=Buffer.from(file.data,'base64');if(buffer.toString('base64')!==file.data||buffer.length>FILE_MAX)throw Error('Artifact output is invalid or exceeds 10 MB.');const items=structuredClone(this.items),now=Date.now(),a=artifactId?this.artifact(artifactId,items):{id:randomUUID(),name:title,format,createdAt:now,updatedAt:now,deletedAt:null,versions:[]};if(!artifactId)items.unshift(a);const v={id:randomUUID(),number:a.versions.length+1,name:file.name,mime:file.mime,size:buffer.length,createdAt:now,...(publicationKey?{publicationKey}:{}),hash:createHash('sha256').update(buffer).digest('hex'),...(content!==undefined?{content}:{}),...(typography!==undefined?{typography:structuredClone(typography)}:{}),...(text(file.previewText,200000)?{previewText:file.previewText}:{}),...(source?{source:structuredClone(source)}:{})};a.versions.push(v);a.updatedAt=now;dir(this.files);const dest=path.join(this.files,v.id+'.bin');let fd;try{fd=fs.openSync(dest,'wx',0o600);fs.writeFileSync(fd,buffer);fs.fsyncSync(fd);fs.closeSync(fd);fd=undefined;const folder=fs.openSync(this.files,'r');try{fs.fsyncSync(folder)}finally{fs.closeSync(folder)}this.persist(items)}catch(e){if(fd!==undefined)fs.closeSync(fd);if(e.committed){this.items=items;this.publish()}else fs.rmSync(dest,{force:true});throw e}this.items=items;this.publish();return structuredClone(visible(a))}
 async document(target){const file=this.file(target);if(this.artifact(target.artifactId).format==='research'){this.researchReport(target);return{name:file.name,mime:file.mime,data:file.data,format:'research'}}const {format}=await require('./artifact-document-validation.cjs').validateDocumentFile(file);return {name:file.name,mime:file.mime,data:file.data,format};}
 async preview(target){if(this.artifact(target.artifactId).format==='research')return{text:this.researchReport(target).markdown};const a=this.artifact(target.artifactId),v=a.versions.find(v=>v.id===target.versionId);if(!v)throw Error('Artifact version not found.');const file=this.file(target);if(v.previewText!==undefined)return {text:v.previewText};if(['docx','xlsx','pptx'].includes(a.format))return require('./artifact-renderer.cjs').previewArtifact(file);if(['image/png','image/jpeg','image/webp','image/gif'].includes(file.mime))return {image:`data:${file.mime};base64,${file.data}`};if(a.format==='pdf'||file.mime==='application/pdf'){const {AttachmentService}=require('./chat-attachments.cjs');const attachments=new AttachmentService();const result=await attachments.importFiles([{name:file.name,bytes:Buffer.from(file.data,'base64')}]);if(result.errors.length)throw Error(result.errors[0].message);try{return {text:(await attachments.preview(result.items[0].id)).text??''}}finally{for(const item of result.items)attachments.discard(item.id)}}if(file.mime.startsWith('text/')||['json','csv','md','txt','js','ts','py','html'].includes(a.format)){const b=Buffer.from(file.data,'base64');if(b.length>200000)throw Error('Text preview is limited to 200 KB. Download this file to view it.');const t=new TextDecoder('utf-8',{fatal:true}).decode(b);return {text:t}}return {text:'Preview is unavailable for this format. Download the file to open it in its application.'}}
}
Object.assign(ArtifactService.prototype,require('./research/report-artifacts.cjs').methods);
module.exports={ArtifactService};
