const { contextBridge, ipcRenderer } = require('electron');
const invoke = (name, ...args) => ipcRenderer.invoke(name, ...args);
contextBridge.exposeInMainWorld('zq', Object.freeze({
 platform:process.platform,
 preferences:{load:()=>invoke('preferences:load'),save:patch=>invoke('preferences:save',patch),testNotification:()=>invoke('preferences:testNotification'),subscribe:callback=>{const listener=(_,value)=>callback(value);ipcRenderer.on('preferences:changed',listener);return()=>ipcRenderer.removeListener('preferences:changed',listener)}},
 updates:{status:()=>invoke('updates:status'),check:()=>invoke('updates:check'),download:()=>invoke('updates:download'),install:()=>invoke('updates:install'),subscribe:callback=>{const listener=(_,state)=>callback(state);ipcRenderer.on('updates:changed',listener);return()=>ipcRenderer.removeListener('updates:changed',listener)}},
 research:{catalog:input=>invoke('research:catalog',input),availability:input=>invoke('research:availability',input),create:input=>invoke('research:create',input),list:()=>invoke('research:list'),get:id=>invoke('research:get',id),acceptPlan:input=>invoke('research:acceptPlan',input),stop:id=>invoke('research:stop',id),finish:id=>invoke('research:finish',id),resume:id=>invoke('research:resume',id),retryStorage:()=>invoke('research:retryStorage'),subscribe:callback=>{const listener=(_,change)=>callback(change);ipcRenderer.on('research:changed',listener);return()=>ipcRenderer.removeListener('research:changed',listener)}},
 github:{invoke:async(method,input)=>{const result=await invoke('github:invoke',method,input);if(!result.ok)throw Object.assign(new Error(result.error.message),{code:result.error.code});return result.value}},
 code:{invoke:async(method,input)=>{const result=await invoke('code:invoke',method,input);if(!result.ok)throw Object.assign(new Error(result.error.message),{code:result.error.code});return result.value},subscribe:callback=>{const listener=(_,state)=>callback(state);ipcRenderer.on('code:changed',listener);return()=>ipcRenderer.removeListener('code:changed',listener)},onTerminal:callback=>{const listener=(_,chunk)=>callback(chunk);ipcRenderer.on('code:terminal',listener);return()=>ipcRenderer.removeListener('code:terminal',listener)}},
 connectors:{catalog:()=>invoke('connectors:catalog'),list:()=>invoke('connectors:list'),save:input=>invoke('connectors:save',input),connect:id=>invoke('connectors:connect',id),disconnect:id=>invoke('connectors:disconnect',id),remove:id=>invoke('connectors:remove',id),setTools:input=>invoke('connectors:setTools',input),subscribe:callback=>{const listener=(_,rows)=>callback(rows);ipcRenderer.on('connectors:changed',listener);return()=>ipcRenderer.removeListener('connectors:changed',listener)}},
 clipboard:{writeText:text=>invoke('clipboard:writeText',text)},
 voice:{load:input=>invoke('voice:load',input),save:input=>invoke('voice:save',input),availability:input=>invoke('voice:availability',input),begin:input=>invoke('voice:begin',input),transcribe:input=>invoke('voice:transcribe',input),cancel:input=>invoke('voice:cancel',input)},
 modules:{runtime:()=>invoke('modules:runtime'),list:()=>invoke('modules:list'),install:()=>invoke('modules:install'),download:url=>invoke('modules:download',url),rollback:id=>invoke('modules:rollback',id),recover:(id,version)=>invoke('modules:recover',id,version)},
 attachments:{pick:()=>invoke('attachments:pick'),import:files=>invoke('attachments:import',files),discard:id=>invoke('attachments:discard',id),preview:id=>invoke('attachments:preview',id)},
 artifacts:{researchView:input=>invoke('artifacts:researchView',input),reviseResearch:input=>invoke('artifacts:reviseResearch',input),exportResearch:input=>invoke('artifacts:exportResearch',input),document:input=>invoke('artifacts:document',input),status:()=>invoke('artifacts:status'),list:()=>invoke('artifacts:list'),create:input=>invoke('artifacts:create',input),update:input=>invoke('artifacts:update',input),version:input=>invoke('artifacts:version',input),preview:input=>invoke('artifacts:preview',input),save:input=>invoke('artifacts:save',input),importGenerated:input=>invoke('artifacts:importGenerated',input),subscribe:callback=>{const listener=(_,items)=>callback(items);ipcRenderer.on('artifacts:changed',listener);return()=>ipcRenderer.removeListener('artifacts:changed',listener)}},
 chat: {
  setConversationConnectors:input=>invoke('chat:setConversationConnectors',input),
  enqueueMessage:input=>invoke('chat:enqueueMessage',input),
  updateQueuedMessage:input=>invoke('chat:updateQueuedMessage',input),
  setQueuePaused:input=>invoke('chat:setQueuePaused',input),
  respondToInteraction:input=>invoke('chat:respondToInteraction',input),
  setApprovalMode:input=>invoke('chat:setApprovalMode',input),
  checkSkillUpdates:()=>invoke('chat:checkSkillUpdates'),
  previewSkillUpdate:id=>invoke('chat:previewSkillUpdate',id),
  updateCatalogSkill:input=>invoke('chat:updateCatalogSkill',input),
  browseSkills:input=>invoke('chat:browseSkills',input),
  previewCatalogSkill:input=>invoke('chat:previewCatalogSkill',input),
  pickSkillImport:input=>invoke('chat:pickSkillImport',input),
  previewSkillResource:input=>invoke('chat:previewSkillResource',input),
  saveSkillResource:input=>invoke('chat:saveSkillResource',input),
  importSkill:input=>invoke('chat:importSkill',input),
  saveSkill:input=>invoke('chat:saveSkill',input),
  duplicateSkill:input=>invoke('chat:duplicateSkill',input),
  deleteSkill:input=>invoke('chat:deleteSkill',input),
  addSkillFiles:input=>invoke('chat:addSkillFiles',input),
  removeSkillFile:input=>invoke('chat:removeSkillFile',input),
  exportSkill:input=>invoke('chat:exportSkill',input),

  searchProjectFiles:input=>invoke('chat:searchProjectFiles',input),
  searchConversations:input=>invoke('chat:searchConversations',input),
  inspectContext:input=>invoke('chat:inspectContext',input),
  reviseMessage:input=>invoke('chat:reviseMessage',input),
  branchConversation:input=>invoke('chat:branchConversation',input),
  selectMessageVersion:input=>invoke('chat:selectMessageVersion',input),
  updateConversation:input=>invoke('chat:updateConversation',input),
  updateProject:input=>invoke('chat:updateProject',input),
  saveDraft:input=>invoke('chat:saveDraft',input),
  saveChatView:input=>invoke('chat:saveChatView',input),
  exportConversation:input=>invoke('chat:exportConversation',input),
  saveTextFile:input=>invoke('chat:saveTextFile',input),
  previewGeneratedFile:input=>invoke('chat:previewGeneratedFile',input),
  reuseGeneratedFile:input=>invoke('chat:reuseGeneratedFile',input),
  generatedFileToProject:input=>invoke('chat:generatedFileToProject',input),

  load:()=>invoke('chat:load'),
  toolOptions:input=>invoke('chat:toolOptions',input),
  saveGeneratedFile:input=>invoke('chat:saveGeneratedFile',input),
  sourceIcon:url=>invoke('chat:sourceIcon',url),
  openLink:url=>invoke('chat:openLink',url),
  deleteConnection:id=>invoke('chat:deleteConnection',id),
  saveConnection:input=>invoke('chat:saveConnection',input),
  saveModelPreferences:input=>invoke('chat:saveModelPreferences',input),
  createConversation:input=>invoke('chat:createConversation',input),
  configureConversation:input=>invoke('chat:configureConversation',input),
  renameConversation:input=>invoke('chat:renameConversation',input),
  deleteConversation:id=>invoke('chat:deleteConversation',id),
  saveProject:input=>invoke('chat:saveProject',input), deleteProject:id=>invoke('chat:deleteProject',id),
  moveConversation:input=>invoke('chat:moveConversation',input),
  addProjectFiles:input=>invoke('chat:addProjectFiles',input), removeProjectFile:input=>invoke('chat:removeProjectFile',input),
  models:id=>invoke('chat:models',id), testConnection:url=>invoke('chat:testConnection',url),
  send:input=>invoke('chat:send',input), stop:id=>invoke('chat:stop',id),
  subscribe:callback=>{const listener=(_,state)=>callback(state);ipcRenderer.on('chat:changed',listener);return()=>ipcRenderer.removeListener('chat:changed',listener)},
 },
 workspace: { load: () => invoke('workspace:load'), save: state => invoke('workspace:save', state), saveDraftCopy: input => invoke('workspace:saveDraftCopy', input) },
 files: {
  list: () => invoke('files:list'), open: () => invoke('files:open'),
  edit: (id, body) => invoke('files:edit', id, body), save: id => invoke('files:save', id),
  saveAs: id => invoke('files:save-as', id), reload: id => invoke('files:reload', id),
 },
 onCommand: callback => { const listener = (_, command) => callback(command); ipcRenderer.on('app:command', listener); ipcRenderer.send('app:commands-ready'); return () => ipcRenderer.removeListener('app:command', listener); },
 onCloseRequested: callback => { const listener = (_, id) => callback(id); ipcRenderer.on('window:close-request', listener); return () => ipcRenderer.removeListener('window:close-request', listener); },
 onCloseCancelled: callback => { const listener = (_, id) => callback(id); ipcRenderer.on('window:close-cancelled', listener); return () => ipcRenderer.removeListener('window:close-cancelled', listener); },
 finishClose: (id, error) => ipcRenderer.send('window:close-ready', id, error),
}));
