'use strict';
// Publisher endpoints and public client configuration. Never put credentials here.
const GOOGLE_SETUP = 'Uses the standard Google API with your personal account. Enable the corresponding API in your Google Cloud project and configure an OAuth web client. Add your account as a test user and register http://127.0.0.1:43187/oauth/callback, then enter the client ID and secret.';
const catalog = [
 {id:'scite',name:'Scite.AI',description:'Find research and explore evidence with Smart Citations.',category:'Research',url:'https://api.scite.ai/mcp',publisher:'Scite',documentationUrl:'https://scite.ai/mcp',accountLabel:'Scite account',setupNote:'Sign in to Scite in your browser. Available literature and tools depend on your account.',authType:'oauth',requiresSetup:false},
 {id:'arxiv',name:'arXiv',description:'Search papers and read abstracts, with links to the original papers and PDFs.',category:'Research',url:'https://export.arxiv.org/api/query',publisher:'arXiv',documentationUrl:'https://info.arxiv.org/help/api/user-manual.html',accountLabel:'No account needed',setupNote:'Uses the public arXiv API through a bundled MCP adapter. Searches include metadata and abstracts; full papers open from their source links.',authType:'oauth',requiresSetup:false,bundled:true},
 {id:'scholar-gateway',name:'Scholar Gateway',description:'Search Wiley research and find relevant passages with citations.',category:'Research',url:'https://connector.scholargateway.ai/mcp',publisher:'Wiley',documentationUrl:'https://docs.scholargateway.ai/',accountLabel:'Wiley CONNECT account',setupNote:'Sign in with Wiley CONNECT in your browser. Research access depends on your account or institutional subscription.',authType:'oauth',requiresSetup:false},
 {id:'gmail',name:'Gmail',description:'Search and read personal email, create drafts, and send reviewed emails.',category:'Productivity',url:'https://gmail.googleapis.com/gmail/v1',publisher:'Google',documentationUrl:'https://developers.google.com/workspace/gmail/api/quickstart/js',accountLabel:'Personal Google account',setupNote:'Uses the standard Gmail API. Enable Gmail API in your Google Cloud project and configure an OAuth web client. Add your account as a test user and register http://127.0.0.1:43187/oauth/callback, then enter the client ID and secret. No MCP preview enrollment is needed.',authType:'oauth',redirectPort:43187,redirectHost:'127.0.0.1',requiresSetup:true,bundled:true},
 ...[
    ['google-calendar','Google Calendar','Find, create, reschedule, and cancel calendar events with review.','https://www.googleapis.com/calendar/v3'],
  ['google-drive','Google Drive','Find and read files in your personal Drive.','https://www.googleapis.com/drive/v3'],
 ].map(([id,name,description,url])=>({id,name,description,url,category:'Productivity',publisher:'Google',documentationUrl:id==='google-calendar'?'https://developers.google.com/workspace/calendar/api/v3/reference':'https://developers.google.com/workspace/drive/api/reference/rest/v3',accountLabel:'Personal Google account',bundled:true,setupNote:GOOGLE_SETUP,authType:'oauth',redirectPort:43187,redirectHost:'127.0.0.1',requiresSetup:true})),
 {id:'microsoft365',name:'Microsoft 365',description:'Work with email, calendar, OneDrive, and Teams through Work IQ.',category:'Productivity',url:'https://workiq.svc.cloud.microsoft/mcp',publisher:'Microsoft',documentationUrl:'https://github.com/microsoft/work-iq/tree/main/plugins/workiq',accountLabel:'Work Microsoft account',setupNote:'Sign in with your work account. Work IQ availability, permissions, and administrator consent depend on your organization. Uses Microsoft’s published public MCP client configuration.',authType:'oauth',clientId:'ba081686-5d24-4bc6-a0d6-d034ecffed87',redirectPort:12798,redirectHost:'127.0.0.1',redirectPath:'/',requiresSetup:false},
 {id:'github',name:'GitHub',description:'Work with repositories, issues, and pull requests.',category:'Development',url:'https://api.githubcopilot.com/mcp/',publisher:'GitHub',documentationUrl:'https://github.com/github/github-mcp-server/blob/main/docs/host-integration.md',accountLabel:'GitHub account',setupNote:'Enter a GitHub personal access token with access to the repositories you choose. Organization approval may be required. Browser sign-in requires your own registered OAuth app.',authType:'bearer',requiresSetup:true},
];
function getCatalog(){ return structuredClone(catalog); }
function getCatalogEntry(id){ const entry=catalog.find(item=>item.id===id);return entry?structuredClone(entry):undefined; }
function isBundledArxiv(row){return row?.catalogId==='arxiv' && row.url===getCatalogEntry('arxiv').url;}
const LEGACY_GMAIL='https://gmailmcp.googleapis.com/mcp/v1',GMAIL_API='https://gmail.googleapis.com/gmail/v1';
function isBundledGmail(row){return row?.catalogId==='gmail'&&row.url===GMAIL_API}
const LEGACY_GOOGLE={gmail:LEGACY_GMAIL,'google-calendar':'https://calendarmcp.googleapis.com/mcp/v1','google-drive':'https://drivemcp.googleapis.com/mcp/v1'};
function isBundledGoogle(row){return !!LEGACY_GOOGLE[row?.catalogId]&&row.url===getCatalogEntry(row.catalogId).url}
module.exports={LEGACY_GOOGLE,isBundledGoogle,LEGACY_GMAIL,GMAIL_API,isBundledGmail,getCatalog,getCatalogEntry,isBundledArxiv};
