const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ChatService}=require('../electron/chat-service.cjs'),{ArtifactService}=require('../electron/artifact-service.cjs'),{WorkspaceStore}=require('../electron/storage.cjs');
const wait=async service=>{for(let i=0;i<200;i++){if(!service.runs.size)return;await new Promise(r=>setTimeout(r,5))}assert.fail('response did not finish')};
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-artifact-integration-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return directory}
test('provider sources and generated files persist across alternate replies and deleted source chats',async t=>{
 const directory=fixture(t),artifacts=new ArtifactService({directory});let round=0;
 const keys=new Map(),credentials={get:async id=>keys.get(id),set:async(id,key)=>keys.set(id,key),delete:async id=>keys.delete(id)};
 const providerFactory=()=>({streamChat:async a=>{round++;a.onTool({id:'search',kind:'web_search',status:'complete'});a.onSources([{id:'1',url:`https://example.com/${round}`,title:`Source ${round}`}]);a.onDelta({content:`Reply ${round} [1](https://example.com/${round})`});await a.onArtifact({name:'result.txt',mime:'text/plain',data:Buffer.from('file '+round).toString('base64')})}});
 const chat=new ChatService({directory,credentials,providerFactory,artifacts});t.after(()=>chat.shutdown());const c=await chat.saveConnection({provider:'openai',name:'Fixture',apiKey:'fixture-only'});const conversation=chat.createConversation({connectionId:c.id,model:'gpt-5.5'});
 await chat.sendMessage({conversationId:conversation.id,text:'Research',tools:['web_search','code_execution']});await wait(chat);const original=structuredClone(chat.conversation(conversation.id).messages[1]);assert.equal(artifacts.list().length,1);
 await chat.reviseMessage({conversationId:conversation.id,messageId:original.id});await wait(chat);assert.equal(artifacts.list().length,2);chat.selectMessageVersion({conversationId:conversation.id,messageId:original.id,versionId:original.versionId??original.id});assert.equal(chat.snapshot().conversations[0].messages[1].sources[0].title,'Source 1');
 chat.shutdown();const restored=new ChatService({directory,credentials,providerFactory,artifacts});assert.equal(restored.snapshot().conversations[0].messages[1].sources[0].url,'https://example.com/1');restored.deleteConversation(conversation.id);const a=artifacts.list()[0];assert.ok(artifacts.file({artifactId:a.id,versionId:a.versions[0].id}).data);restored.shutdown();
});
test('Notes and Tasks keep explicit version references after artifact revisions and deletion',async t=>{const directory=fixture(t),s=new ArtifactService({directory,render:async({title,format,content})=>({name:title+'.'+format,mime:'text/plain',data:Buffer.from(content).toString('base64')})}),a=await s.create({title:'Plan',format:'docx',content:'First'}),ref={artifactId:a.id,versionId:a.versions[0].id,name:a.name};const store=new WorkspaceStore(directory);store.save({notes:[{id:'n',title:'Note',body:'',project:'',pinned:false,updated:'now',artifacts:[ref]}],tasks:[{id:'t',title:'Task',description:'',project:'llm-img',status:'Inbox',priority:'Normal',artifacts:[ref]}],theme:'light',palette:'gunmetal'});await s.create({artifactId:a.id,expectedLatestVersionId:ref.versionId,title:'Plan',format:'docx',content:'Second'});s.update({id:a.id,deleted:true});const saved=store.load();assert.equal(saved.notes[0].artifacts[0].versionId,ref.versionId);assert.equal(saved.tasks[0].artifacts[0].versionId,ref.versionId);assert.equal(Buffer.from(s.file(ref).data,'base64').toString(),'First');saved.notes[0].artifacts[0].versionId='../../escape';assert.throws(()=>store.save(saved),/invalid/)});
