const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');
const {ArtifactService}=require('../electron/artifact-service.cjs');
const render=async({format,title,content})=>({name:title+'.'+format,mime:'text/plain',data:Buffer.from(content).toString('base64'),previewText:content});
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-artifacts-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return {directory,service:new ArtifactService({directory,render})}}
test('artifact versions and source provenance survive restart; stale revisions cannot overwrite',async t=>{const {directory,service:s}=fixture(t);const a=await s.create({format:'docx',title:'Plan',content:'Original',source:{conversationId:'c',messageId:'m',versionId:'mv',conversationTitle:'Source'}});const v1=a.versions[0].id;const b=await s.create({artifactId:a.id,expectedLatestVersionId:v1,format:'docx',title:'Plan',content:'Revised'});assert.equal(b.versions.length,2);await assert.rejects(s.create({artifactId:a.id,expectedLatestVersionId:v1,format:'docx',title:'Plan',content:'Stale'}),/changed/);const reopened=new ArtifactService({directory,render});assert.equal(reopened.file({artifactId:a.id,versionId:v1}).data,Buffer.from('Original').toString('base64'));assert.equal(reopened.version({artifactId:a.id,versionId:v1}).source.conversationId,'c');assert.equal(reopened.list()[0].versions.length,2);assert.ok(!('data' in reopened.list()[0].versions[0]));assert.ok(!('content' in reopened.list()[0].versions[0]));});
test('same named artifacts stay separate; generated import is idempotent and independent of chat',async t=>{const {service:s}=fixture(t);const a=await s.create({format:'pdf',title:'Same',content:'A'}),b=await s.create({format:'pdf',title:'Same',content:'B'});assert.notEqual(a.id,b.id);const input={name:'report.pdf',mime:'application/pdf',data:Buffer.from('%PDF-fixture').toString('base64')},source={conversationId:'c',messageId:'m',generatedFileId:'file1'};const imported=s.importFile(input,source);assert.equal(s.importFile(input,source).id,imported.id);assert.equal(s.list().length,3);s.update({id:imported.id,deleted:true});assert.equal(s.list().find(a=>a.id===imported.id).deletedAt>0,true);assert.equal(s.file({artifactId:imported.id,versionId:imported.versions[0].id}).data,input.data);s.update({id:imported.id,deleted:false,name:'Renamed'});assert.equal(s.list().find(a=>a.id===imported.id).name,'Renamed');});
test('invalid payloads and failed index write leave published versions unchanged',async t=>{const {service:s}=fixture(t);await assert.rejects(s.create({format:'exe',title:'Bad',content:'x'}));await assert.rejects(s.create({format:'pdf',title:'../bad',content:'x'}));const a=await s.create({format:'pdf',title:'Good',content:'x'});const save=s.persist;s.persist=()=>{throw Error('disk full')};await assert.rejects(s.create({artifactId:a.id,expectedLatestVersionId:a.versions[0].id,format:'pdf',title:'Good',content:'y'}),/disk full/);s.persist=save;assert.equal(s.list()[0].versions.length,1);assert.throws(()=>s.file({artifactId:a.id,versionId:'../../secret'}));});
test('corrupt metadata and symlinked bytes are rejected without replacing originals',async t=>{const {directory,service:s}=fixture(t);const a=await s.create({format:'pdf',title:'Good',content:'x'});const file=path.join(directory,'artifacts','files',a.versions[0].id+'.bin');fs.unlinkSync(file);const outside=path.join(directory,'private');fs.writeFileSync(outside,'private');fs.symlinkSync(outside,file);assert.throws(()=>s.file({artifactId:a.id,versionId:a.versions[0].id}));const index=path.join(directory,'artifacts','index.json');fs.writeFileSync(index,'broken');assert.throws(()=>new ArtifactService({directory,render}));assert.equal(fs.readFileSync(index,'utf8'),'broken');});
test('external metadata edits after startup are preserved',async t=>{const {directory,service:s}=fixture(t);const a=await s.create({format:'pdf',title:'Good',content:'x'});const index=path.join(directory,'artifacts','index.json');fs.writeFileSync(index,'external corruption');assert.throws(()=>s.update({id:a.id,name:'Changed'}),/changed on disk/);assert.equal(fs.readFileSync(index,'utf8'),'external corruption');});
test('post-rename fsync failure keeps the committed version bytes and reconciles memory',async t=>{const {directory,service:s}=fixture(t);const a=await s.create({format:'pdf',title:'Good',content:'x'}),original=fs.fsyncSync;let directoryCount=0;fs.fsyncSync=fd=>{if(fs.fstatSync(fd).isDirectory()&&++directoryCount===2)throw Error('directory flush failed');return original(fd)};try{await assert.rejects(s.create({artifactId:a.id,expectedLatestVersionId:a.versions[0].id,format:'pdf',title:'Good',content:'y'}),/was saved/)}finally{fs.fsyncSync=original}assert.equal(directoryCount,2);assert.equal(s.list()[0].versions.length,2);const reopened=new ArtifactService({directory,render}),v=reopened.list()[0].versions[1];assert.equal(Buffer.from(reopened.file({artifactId:a.id,versionId:v.id}).data,'base64').toString(),'y');});
test('replacing the version directory with a symlink cannot redirect reads',async t=>{const {directory,service:s}=fixture(t);const a=await s.create({format:'pdf',title:'Good',content:'x'});const files=path.join(directory,'artifacts','files'),moved=path.join(directory,'moved-files');fs.renameSync(files,moved);fs.symlinkSync(moved,files);assert.throws(()=>s.file({artifactId:a.id,versionId:a.versions[0].id}),/regular directory/)});
