// Run from the repository root: node apps/desktop/tests/citation-interactions.browser.cjs
// Uses isolated fixtures and a temporary local server; no workspace or provider writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require('playwright-core');
(async()=>{const {build}=await import('vite'),{default:react}=await import('@vitejs/plugin-react'),{default:tailwind}=await import('@tailwindcss/vite');const root=path.resolve('.local-data/artifact-revision-browser');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'index.html'),'<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>');fs.writeFileSync(path.join(root,'main.tsx'),"import '../../apps/desktop/tests/fixtures/artifact-revisions'");await build({root,configFile:false,logLevel:'error',plugins:[react(),tailwind()],resolve:{dedupe:['react','react-dom','radix-ui']}});const dist=path.join(root,'dist');const server=http.createServer((req,res)=>{const file=path.join(dist,new URL(req.url,'http://localhost').pathname);const target=file===dist+'/'?path.join(dist,'index.html'):file;if(!target.startsWith(dist)||!fs.existsSync(target)){res.writeHead(404).end();return}res.setHeader('Content-Type',/\.js$/.test(target)?'text/javascript':/\.css$/.test(target)?'text/css':'text/html');fs.createReadStream(target).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'chrome',headless:true});const {renderArtifact}=require('../electron/artifact-renderer.cjs');const original=await renderArtifact({format:'docx',title:'Plan',content:'# Overview\nOriginal content'}),revised=await renderArtifact({format:'docx',title:'Plan',content:'# Overview\nRevised content',typography:{headingSize:14}});const page=await browser.newPage({viewport:{width:1200,height:800}}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('UI error:',e.message)});await page.addInitScript(files=>window.documentFiles=files,{v1:original,v2:revised});await page.goto(`http://127.0.0.1:${server.address().port}`);const pane=page.getByRole('complementary',{name:'Artifact preview'});
await page.getByRole('button',{name:'Open original',exact:true}).click();await pane.waitFor();
await page.getByRole('textbox',{name:'Chat message',exact:true}).fill('Make the heading smaller');await page.getByRole('button',{name:'Send message',exact:true}).click();
await page.waitForFunction(()=>window.events.some(e=>e[0]==='send'));
assert.deepEqual(await page.evaluate(()=>window.events.find(e=>e[0]==='send')[1].artifactContext),{artifactId:'artifact',versionId:'v1'});
await page.waitForFunction(()=>!!window.finishRevision);await page.evaluate(()=>window.finishRevision());
await page.getByRole('combobox',{name:'Artifact version'}).filter({hasText:'Version 2'}).waitFor();await page.frameLocator('iframe[title="Plan.docx document"]').getByText('Revised content',{exact:true}).waitFor();await page.getByRole('status').filter({hasText:'Rendering document'}).waitFor({state:'detached'});await page.screenshot({path:'.local-data/artifact-revision-v2.png'});
await page.getByRole('combobox',{name:'Artifact version'}).click();await page.getByRole('option',{name:'Version 1',exact:true}).click();
await page.getByRole('combobox',{name:'Artifact version'}).filter({hasText:'Version 1'}).waitFor();
await page.frameLocator('iframe[title="Plan.docx document"]').getByText('Original content',{exact:true}).waitFor();await page.getByRole('status').filter({hasText:'Rendering document'}).waitFor({state:'detached'});await page.screenshot({path:'.local-data/artifact-revision-preview.png'});await page.locator('.generated-file-row').click({button:'right'});await page.getByRole('menuitem',{name:'Revise in chat…',exact:true}).click();await page.getByRole('combobox',{name:'Artifact version'}).filter({hasText:'Version 2'}).waitFor();
await page.getByRole('button',{name:'Switch chat',exact:true}).click();await pane.waitFor({state:'detached',timeout:2000});
await page.getByRole('button',{name:'Open original',exact:true}).click();await page.getByRole('button',{name:'New chat',exact:true}).click();await page.waitForFunction(()=>!!window.finishNewChat);await pane.waitFor({state:'detached',timeout:2000});await page.evaluate(()=>window.finishNewChat());
await page.getByRole('button',{name:'Library',exact:true}).click();const row=page.locator('[data-artifact-id="artifact"]');await row.click({button:'right'});await page.getByRole('menuitem',{name:'Revise in chat…',exact:true}).click();await pane.waitFor();await page.getByRole('textbox',{name:'Chat message',exact:true}).waitFor();
await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Chat message');
await page.evaluate(()=>window.removeSource());await page.getByRole('button',{name:'Library',exact:true}).click();await page.locator('[data-artifact-id="artifact"]').click({button:'right'});await page.getByRole('menuitem',{name:'Revise in chat…',exact:true}).click();await page.waitForFunction(()=>!!window.finishNewChat);await page.getByRole('button',{name:'Switch chat',exact:true}).click();await page.evaluate(()=>window.finishNewChat());await page.waitForTimeout(100);assert.equal(await page.getByLabel('Current chat').textContent(),'other');assert.equal(await pane.count(),0);
assert.deepEqual(errors,[]);console.log('PASS selected document sent, new version auto-previewed, old version selected, navigation closes pane, and right-click revision returns to composer.');}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
