// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/chat-approval-draft-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills-chat'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button=name=>page.getByRole('button',{name,exact:true}),message=page.getByRole('textbox',{name:'Chat message',exact:true}),mode=page.getByRole('menuitemcheckbox',{name:'Ask before tool actions',exact:true})
  await message.waitFor(); await page.evaluate(()=>{window.failApprovalMode=true;window.holdApprovalMode=true}); await button('Add attachments').click(); await mode.click(); await page.waitForFunction(()=>!!window.finishApprovalMode); assert.equal(await button('Send message').isDisabled(),true); assert.equal(await message.isDisabled(),true); assert.equal(await page.evaluate(()=>window.events.find(event=>event[0]==='mode')[1].conversationId),'chat-1'); await page.evaluate(()=>{window.holdApprovalMode=false;window.finishApprovalMode()}); await page.getByRole('alert').filter({hasText:'Could not save approval mode'}).waitFor(); assert.equal(await message.inputValue(),'Hydrated message'); assert.equal(await page.evaluate(()=>window.chatState.conversation.id),'chat-1'); assert.equal(await page.evaluate(()=>window.events.filter(event=>event[0]==='send').length),0)
  await page.evaluate(()=>window.failApprovalMode=false); await button('Add attachments').click(); await mode.click(); await page.waitForFunction(()=>window.chatState.conversation.approvalMode==='ask'); assert.equal(await page.evaluate(()=>window.events.filter(event=>event[0]==='create').length),1); assert.equal(await message.inputValue(),'Hydrated message'); await button('Send message').click(); await page.waitForFunction(()=>window.events.filter(event=>event[0]==='send').length===1); assert.equal(await page.evaluate(()=>window.events.find(event=>event[0]==='send')[1].text),'Hydrated message'); await page.evaluate(()=>window.chatState.create()); await page.waitForFunction(()=>window.chatState.conversation?.id==='chat-2'); await button('Open first chat').click(); await page.waitForFunction(()=>window.chatState.conversation?.id==='chat-1'); await page.evaluate(()=>{window.holdApprovalMode=true;delete window.finishApprovalMode}); await button('Add attachments').click(); await mode.click(); await page.waitForFunction(()=>!!window.finishApprovalMode); await page.evaluate(()=>window.chatState.select('chat-2')); await page.waitForFunction(()=>window.chatState.draftId==='chat-2'); await page.evaluate(()=>{window.holdApprovalMode=false;window.finishApprovalMode()}); await message.fill('Unrelated new draft'); await page.waitForFunction(()=>window.chatState.state.conversations.find(c=>c.id==='chat-1').approvalMode==='auto'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='mode').at(-1)[1].conversationId),'chat-1'); assert.equal(await message.inputValue(),'Unrelated new draft'); assert.equal(await page.evaluate(()=>window.chatState.draftId),'chat-2'); assert.deepEqual(errors,[]); console.log('PASS Ask before tool actions works before first send, creates/transfers draft once, locks sending during mode mutation, preserves draft on failure, retries on same conversation, and retains the original mode target while navigating without changing the other draft.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
