'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {selectedConnectors,connectorTools,createConnectorExecutor,validConnectorIds}=require('../electron/chat-connectors.cjs');
const {ChatService}=require('../electron/chat-service.cjs');
const tool={name:'search',description:'Search documents',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},enabled:true,readOnly:true};
function fixture(){const row={id:'remote-a',name:'Research',url:'https://mcp.example.test/mcp',status:'connected',revision:1,tools:[structuredClone(tool)]};let calls=[];const service={list:()=>[structuredClone(row)],callTool:async(id,name,args,options)=>{calls.push({id,name,args,options});return{content:[{type:'text',text:'Found one document'},{type:'resource_link',uri:'https://example.test/research',name:'Research source'}]}}};return{row,service,calls};}
const tick=()=>new Promise(resolve=>setImmediate(resolve));
async function until(fn){for(let i=0;i<200;i++){if(fn())return;await new Promise(resolve=>setTimeout(resolve,5))}throw Error('Expected chat state did not arrive')}
test('selection defaults to none, supports explicit overrides, and rejects removed connectors',()=>{const {service}=fixture();assert.deepEqual(selectedConnectors(service,undefined,null),[]);assert.deepEqual(selectedConnectors(service,null,{connectorIds:['remote-a']}),['remote-a']);assert.deepEqual(selectedConnectors(service,[],{connectorIds:['remote-a']}),[]);assert.throws(()=>selectedConnectors(service,['missing']),/removed/);assert.equal(validConnectorIds(['remote-a','remote-a']),false);assert.equal(validConnectorIds(null),false)});
test('tools are namespaced and only enabled tools are exposed; unsafe schemas are rejected',()=>{const {service,row}=fixture();const entries=connectorTools(service,['remote-a']);assert.match(entries[0].name,/^mcp_[a-f0-9]{32}$/);assert.equal(entries[0].definition.parameters.required[0],'query');row.tools[0].enabled=false;assert.throws(()=>connectorTools(service,['remote-a']),/Research.*no tools enabled/);row.tools[0].enabled=true;row.tools[0].inputSchema={$ref:'https://external.test/schema',type:'object'};assert.throws(()=>connectorTools(service,['remote-a']),/unsupported/)});
test('execution validates arguments and current scope before side effects; grants bind revision',async()=>{const {service,row,calls}=fixture();let grant,approvals=0;const messages={};const entries=connectorTools(service,['remote-a']);const exec=createConnectorExecutor({service,entries,conversationId:'chat',run:{controller:new AbortController()},check:()=>{},update:fn=>fn(messages),interactions:{approve:async(...args)=>{approvals++;grant=args[2];return true}}});assert.match((await exec.execute({name:entries[0].name,arguments:{}})).error,/schema/);assert.equal(calls.length,0);await exec.execute({name:entries[0].name,arguments:{query:'news'}});assert.equal(approvals,1);assert.match(grant,/^mcp:/);assert.equal(messages.toolActivity[0].status,'complete');assert.equal(messages.sources[0].url,'https://example.test/research');row.revision++;await assert.rejects(exec.execute({name:entries[0].name,arguments:{query:'again'}}),/changed/);assert.equal(calls.length,1)});
test('chat requires real approval even for claimed read-only MCP tools, then stores activity and citations',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'zq-chat-mcp-'));const {service,calls}=fixture();let offered;
 const provider={supportsLocalTools:async()=>true,async streamChat({localTools,onLocalTool,onDelta}){offered=localTools.find(t=>t.name.startsWith('mcp_'));assert.ok(offered);const result=await onLocalTool({name:offered.name,arguments:{query:'Montana'}});assert.equal(result.content[0].text,'Found one document');onDelta({content:'Here is the result.'})}};
 const host=new ChatService({directory:dir,provider,connectors:service});t.after(()=>{host.shutdown();fs.rmSync(dir,{recursive:true,force:true})});const connection=host.saveConnection({provider:'ollama',baseUrl:'http://localhost:11434',name:'Test'}),conversation=host.createConversation({connectionId:connection.id,model:'test'});host.setConversationConnectors({conversationId:conversation.id,connectorIds:['remote-a']});await host.sendMessage({conversationId:conversation.id,text:'Find research'});
 await until(()=>host.conversation(conversation.id).messages.at(-1)?.interactions?.length);assert.equal(calls.length,0);const card=host.conversation(conversation.id).messages.at(-1).interactions[0];assert.match(card.question,/Research/);host.respondToInteraction({conversationId:conversation.id,id:card.id,decision:'chat'});await until(()=>!host.runs.size);assert.equal(calls.length,1);let reply=host.conversation(conversation.id).messages.at(-1);assert.equal(reply.status,'complete');assert.equal(reply.toolActivity[0].kind,'mcp');assert.equal(reply.sources.length,1);
 await host.sendMessage({conversationId:conversation.id,text:'Again'});await until(()=>!host.runs.size);assert.equal(calls.length,2);assert.equal(host.conversation(conversation.id).messages.at(-1).interactions,undefined);
 const restored=new ChatService({directory:dir,provider,connectors:service});assert.deepEqual(restored.conversation(conversation.id).connectorIds,['remote-a']);assert.deepEqual(restored.conversation(conversation.id).messages[0].connectorIds,['remote-a']);restored.shutdown();
});
test('queued messages retain connector selection when project defaults change',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'zq-chat-mcp-'));const {service}=fixture();const host=new ChatService({directory:dir,connectors:service});t.after(()=>{host.shutdown();fs.rmSync(dir,{recursive:true,force:true})});const conn=host.saveConnection({provider:'ollama',baseUrl:'http://localhost:11434',name:'Test'}),project=host.saveProject({name:'Project'});host.updateProject({id:project.id,connectorIds:['remote-a']});const c=host.createConversation({connectionId:conn.id,model:'test',projectId:project.id});host.setQueuePaused({conversationId:c.id,paused:true});host.enqueueMessage({conversationId:c.id,text:'Later'});host.updateProject({id:project.id,connectorIds:[]});assert.deepEqual(host.conversation(c.id).queue.items[0].connectorIds,['remote-a']);});
test('denying connector approval prevents the network call and stops the run',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'zq-chat-mcp-'));const {service,calls}=fixture();const provider={supportsLocalTools:async()=>true,async streamChat({localTools,onLocalTool}){await onLocalTool({name:localTools.find(t=>t.name.startsWith('mcp_')).name,arguments:{query:'write'}})}};const host=new ChatService({directory:dir,provider,connectors:service});t.after(()=>{host.shutdown();fs.rmSync(dir,{recursive:true,force:true})});const conn=host.saveConnection({provider:'ollama',baseUrl:'http://localhost:11434',name:'Test'}),c=host.createConversation({connectionId:conn.id,model:'test'});await host.sendMessage({conversationId:c.id,text:'Use connector',connectorIds:['remote-a']});await until(()=>host.conversation(c.id).messages.at(-1)?.interactions?.length);const card=host.conversation(c.id).messages.at(-1).interactions[0];host.respondToInteraction({conversationId:c.id,id:card.id,decision:'deny'});await tick();assert.equal(calls.length,0);assert.equal(host.runs.size,0);assert.equal(host.conversation(c.id).messages.at(-1).status,'stopped')});
test('oversized results do not claim failure or repeat a possibly completed action',async()=>{
 const {service}=fixture();let calls=0;service.callTool=async()=>{calls++;return{content:[{type:'text',text:'a'.repeat(100001)}]}};
 const entries=connectorTools(service,['remote-a']),reply={};const exec=createConnectorExecutor({service,entries,conversationId:'chat',run:{controller:new AbortController()},check:()=>{},update:fn=>fn(reply),interactions:{approve:async()=>true}});
 const call={name:entries[0].name,arguments:{query:'create'}};assert.match((await exec.execute(call)).error,/may already be complete/);assert.match((await exec.execute(call)).error,/Do not repeat/);assert.equal(calls,1);
});

test('a selected connector with no enabled tools stops before model execution and preserves the draft',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'zq-chat-mcp-empty-'));const {service,row}=fixture();row.tools[0].enabled=false;let modelCalls=0;
 const provider={supportsLocalTools:async()=>true,async streamChat(){modelCalls++}};
 const host=new ChatService({directory:dir,provider,connectors:service});t.after(()=>{host.shutdown();fs.rmSync(dir,{recursive:true,force:true})});
 const connection=host.saveConnection({provider:'ollama',baseUrl:'http://localhost:11434',name:'Test'}),conversation=host.createConversation({connectionId:connection.id,model:'test'});
 host.saveDraft({id:conversation.id,text:'Find research',connectorIds:['remote-a']});
 await assert.rejects(host.sendMessage({conversationId:conversation.id,text:'Find research',connectorIds:['remote-a']}),/Research.*no tools enabled/);
 assert.equal(modelCalls,0);assert.equal(host.conversation(conversation.id).messages.length,0);assert.equal(host.state.drafts[conversation.id].text,'Find research');
});
