const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ChatService}=require('../electron/chat-service.cjs');
const {ChatStore}=require('../electron/chat-store.cjs');
const wait=async fn=>{for(let n=0;n<100;n++){if(fn())return;await new Promise(r=>setTimeout(r,5))}assert.fail('response did not settle')};
async function fixture(t,streamChat){
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-tools-')),keys=new Map();
 const credentials={get:async id=>keys.get(id),set:async(id,key)=>keys.set(id,key),delete:async id=>keys.delete(id)};
 const service=new ChatService({directory,credentials,providerFactory:()=>({streamChat})});
 t.after(()=>{service.shutdown();fs.rmSync(directory,{recursive:true,force:true})});
 const connection=await service.saveConnection({provider:'openai',name:'Fixture',apiKey:'fixture-only'});
 const chat=service.createConversation({connectionId:connection.id,model:'gpt-5.5'});
 return {service,directory,chat,last:()=>service.conversation(chat.id).messages.at(-1),send:tools=>service.sendMessage({conversationId:chat.id,text:'Research this',tools})};
}
test('selected tools and activity reach native execution and survive reload',async t=>{
 let request;const f=await fixture(t,async args=>{request=args;args.onTool({id:'search1',kind:'web_search',status:'running',detail:'Looking up sources'});args.onTool({id:'search1',kind:'web_search',status:'complete'});args.onDelta({content:'Found it.'})});
 await f.send(['web_search']);await wait(()=>f.last().status==='complete');
 assert.deepEqual(request.tools,['web_search']);assert.doesNotMatch(request.messages[0].content,/have no tools/);
 const saved=new ChatStore(f.directory).load().conversations[0].messages;
 assert.deepEqual(saved[0].tools,['web_search']);assert.equal(saved[1].toolActivity[0].status,'complete');
 assert.equal(saved[1].toolActivity[0].detail,'Looking up sources');
});
test('unsupported, repeated and malformed tools reject before history changes',async t=>{
 const f=await fixture(t,async()=>assert.fail('must not send'));
 for(const tools of [['shell'],['web_search','web_search'],{},[null]])await assert.rejects(f.send(tools),/tool/i);
 assert.equal(f.service.conversation(f.chat.id).messages.length,0);
 f.service.configureConversation({id:f.chat.id,connectionId:f.chat.connectionId,model:'gpt-3.5-turbo'});
 await assert.rejects(f.send(['web_search']),/tool/i);
});
test('stopping settles tool activity and ignores late callbacks and files',async t=>{
 let args,done;const f=await fixture(t,a=>{args=a;a.onTool({id:'s',kind:'web_search',status:'running'});return new Promise(r=>done=r)});
 await f.send(['web_search']);await wait(()=>!!args);f.service.stop(f.chat.id);
 args.onTool({id:'s',kind:'web_search',status:'complete'});await args.onArtifact({name:'late.txt',mime:'text/plain',data:Buffer.from('late').toString('base64')});done();
 assert.equal(f.last().toolActivity[0].status,'stopped');assert.equal(f.last().generatedFiles,undefined);
});
test('generated file bytes persist locally but are absent from public snapshots',async t=>{
 const data=Buffer.from('private generated bytes').toString('base64');
 const f=await fixture(t,async a=>{await a.onArtifact({name:'report.txt',mime:'text/plain',data});a.onDelta({content:'Created report.'})});
 await f.send(['code_execution']);await wait(()=>f.last().status==='complete');
 const file=f.last().generatedFiles[0];assert.equal(file.data,data);
 assert.equal(f.service.snapshot().conversations[0].messages.at(-1).generatedFiles[0].data,undefined);
 assert.equal(new ChatStore(f.directory).load().conversations[0].messages.at(-1).generatedFiles[0].data,data);
 assert.equal(f.service.renameConversation({id:f.chat.id,title:'Renamed'}).messages.at(-1).generatedFiles[0].data,undefined);
 assert.equal(f.service.configureConversation({id:f.chat.id,connectionId:f.chat.connectionId,model:'gpt-5.5'}).messages.at(-1).generatedFiles[0].data,undefined);
 assert.equal(f.service.moveConversation({id:f.chat.id,projectId:null}).messages.at(-1).generatedFiles[0].data,undefined);
 assert.deepEqual(f.service.generatedFile({conversationId:f.chat.id,messageId:f.last().id,fileId:file.id}),file);
});
test('a generated file is a successful response even without answer text',async t=>{
 const f=await fixture(t,async a=>{await a.onArtifact({name:'result.csv',mime:'text/csv',data:Buffer.from('a,b\n1,2').toString('base64')})});
 await f.send(['code_execution']);await wait(()=>f.last().status!=='streaming');assert.equal(f.last().status,'complete');
});
test('invalid tool output fails cleanly without poisoning saved history',async t=>{
 const f=await fixture(t,async a=>{a.onDelta({content:'Partial'});a.onTool({id:'bad',kind:'shell',status:'running'})});
 await f.send(['web_search']);await wait(()=>f.last().status==='error');
 assert.equal(f.last().content,'Partial');assert.doesNotThrow(()=>new ChatStore(f.directory).load());
});
test('unrequested and oversized generated files fail without storing bytes',async t=>{
 const f=await fixture(t,async a=>{await a.onArtifact({name:'big.bin',mime:'application/octet-stream',data:Buffer.alloc(4*1024*1024+1).toString('base64')})});
 await f.send(['code_execution']);await wait(()=>f.last().status==='error');assert.equal(f.last().generatedFiles,undefined);
 assert.doesNotThrow(()=>new ChatStore(f.directory).load());
});
test('recovery marks interrupted hosted activity and validates stored tool shape',async t=>{
 const f=await fixture(t,async()=>{}),state=new ChatStore(f.directory).load();
 const message={id:'unfinished',role:'assistant',content:'',thinking:'',status:'streaming',createdAt:1,context:[],error:'',toolActivity:[{id:'search',kind:'web_search',status:'running',detail:''}]};
 state.conversations[0].messages.push(message);new ChatStore(f.directory).save(state);
 const recovered=new ChatService({directory:f.directory});t.after(()=>recovered.shutdown());
 assert.equal(recovered.conversation(f.chat.id).messages.at(-1).toolActivity[0].status,'interrupted');
 message.toolActivity[0].status='made-up';assert.throws(()=>new ChatStore(f.directory).save(state),/Invalid/);
});
test('final citation replacement preserves thinking without duplicate streamed text',async t=>{
 const f=await fixture(t,async a=>{a.onDelta({content:'Answer',thinking:'Checked sources'});a.onReplace('Answer [1](https://example.com/)')});
 await f.send(['web_search']);await wait(()=>f.last().status==='complete');
 assert.equal(f.last().content,'Answer [1](https://example.com/)');assert.equal(f.last().thinking,'Checked sources');
});
test('source opening accepts web links and rejects credentials and executable schemes',()=>{
 const {externalURL}=require('../electron/chat-tools.cjs');
 assert.equal(externalURL('https://example.com/source?q=a%20b'),'https://example.com/source?q=a%20b');
 for(const link of ['file:///tmp/test','javascript:alert(1)','data:text/html,x','https://user:secret@example.com','https://example.com/\nheader',{},' https://example.com'])assert.throws(()=>externalURL(link));
});
test('real provider factory streams hosted search through ChatService and saves final citations',async t=>{
 const f=await fixture(t,async()=>assert.fail('override should be replaced')),requests=[];
 const {createProvider}=require('../../../packages/providers/index.cjs');
 f.service.connections.factory=(provider,options)=>createProvider(provider,{...options,fetchImpl:async(url,options)=>{
  requests.push({url,body:JSON.parse(options.body)});
  const frames=[
   {type:'response.output_item.added',output_index:0,item:{type:'web_search_call',id:'ws1',status:'in_progress'}},
   {type:'response.output_text.delta',output_index:1,item_id:'m1',content_index:0,delta:'Verified answer'},
   {type:'response.completed',response:{status:'completed',output:[{type:'web_search_call',id:'ws1',status:'completed'},{type:'message',id:'m1',content:[{type:'output_text',text:'Verified answer',annotations:[{type:'url_citation',end_index:15,url:'https://example.com/source'}]}]}]}},
  ];return {status:200,body:new ReadableStream({start(c){for(const frame of frames)c.enqueue(Buffer.from(`data: ${JSON.stringify(frame)}\n\n`));c.close()}})};
 }});
 await f.send(['web_search']);await wait(()=>f.last().status!=='streaming');
 assert.equal(f.last().status,'complete');assert.equal(requests[0].url,'https://api.openai.com/v1/responses');
 assert.deepEqual(requests[0].body.tools.filter(tool=>tool.type!=='function'),[{type:'web_search'}]);
 assert.deepEqual(requests[0].body.tools.filter(tool=>tool.type==='function').map(tool=>tool.name),['request_user_input']);
 assert.equal(f.last().content,'Verified answer [1](<https://example.com/source>)');assert.equal(f.last().toolActivity[0].status,'complete');
});
