// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/chat-flow-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/chat-flow'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.setDefaultTimeout(5000);page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button=name=>page.getByRole('button',{name,exact:true}),menu=name=>page.getByRole('menuitem',{name,exact:true}),message=page.getByRole('textbox',{name:'Chat message',exact:true})
  await message.waitFor(); await button('Queue message').waitFor(); assert.equal(await button('Stop response').isVisible(),true); const queue=page.getByRole('region',{name:'Message queue',exact:true}); await queue.waitFor(); assert.match(await queue.innerText(),/Guide.txt.*Project note.*Writing style/)
  await button('Add attachments').click(); assert.equal(await page.getByRole('menuitemcheckbox',{name:'Ask before tool actions',exact:true}).getAttribute('aria-disabled'),'true'); await page.keyboard.press('Escape')
  await page.evaluate(()=>window.failEnqueue=true); await message.press('Enter'); await page.getByRole('alert').filter({hasText:'Could not queue'}).waitFor(); assert.equal(await message.inputValue(),'Next request'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='send').length),0); await page.evaluate(()=>window.failEnqueue=false); await message.press('Enter'); await page.waitForFunction(()=>window.chatState.conversation.queue.items.length===3); assert.equal(await message.inputValue(),''); assert.deepEqual(await page.evaluate(()=>window.events.filter(e=>e[0]==='enqueue').at(-1)[1].skillIds),['skill'])
  await button('Actions for queued message 2').click(); assert.deepEqual(await page.getByRole('menuitem').allTextContents(),['Edit','Move up','Move down','Remove']); await menu('Move up').click(); assert.match(await button('Edit queued message 1').innerText(),/Third task/); await button('Edit queued message 1').click({button:'right'}); await menu('Move down').click(); assert.match(await button('Edit queued message 1').innerText(),/Second task/)
  await button('Edit queued message 1').click(); const editor=page.getByRole('dialog',{name:'Edit queued message',exact:true}); await editor.waitFor(); assert.equal(await page.evaluate(()=>window.chatState.conversation.queue.paused),true); await page.getByRole('textbox',{name:'Queued message text',exact:true}).fill('Edited second task'); await page.evaluate(()=>window.failQueueMutation=true); await button('Save queued message').click(); await editor.getByRole('alert').filter({hasText:'Could not update'}).waitFor(); assert.equal(await page.getByRole('textbox',{name:'Queued message text',exact:true}).inputValue(),'Edited second task'); await page.evaluate(()=>{window.failQueueMutation=false;window.holdQueueMutation=true}); await button('Save queued message').click(); await page.waitForFunction(()=>!!window.finishQueueMutation); await page.keyboard.press('Escape'); assert.equal(await editor.count(),1); assert.equal(await button('Cancel').isDisabled(),true); await page.evaluate(()=>{window.holdQueueMutation=false;window.finishQueueMutation()}); await editor.waitFor({state:'detached'}); await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Edit queued message 1'); assert.match(await button('Edit queued message 1').innerText(),/Edited second task/)
  await button('Resume queue').click(); await button('Pause queue').waitFor(); await button('Pause queue').click(); await button('Resume queue').waitFor(); await button('Actions for queued message 2').click(); await menu('Remove').click(); await page.waitForFunction(()=>window.chatState.conversation.queue.items.length===2)
  await page.evaluate(()=>{delete window.finishQueueMutation;window.holdQueueMutation=true}); await button('Actions for queued message 1').click(); await menu('Move down').click(); await page.waitForFunction(()=>!!window.finishQueueMutation); await button('Second chat').click(); await message.fill('Other chat draft'); await page.evaluate(()=>{window.holdQueueMutation=false;window.finishQueueMutation()}); await page.waitForFunction(()=>window.chatState.conversation.id==='two'); assert.equal(await queue.count(),0); assert.equal(await message.inputValue(),'Other chat draft'); assert.equal(await button('Send message').isVisible(),true); await button('First chat').click(); await queue.waitFor()
  await button('Stop response').click(); await button('Resume queue').waitFor(); assert.equal(await button('Stop response').count(),0); assert.equal(await button('Queue message').isVisible(),true); await message.fill('Queued while paused'); await message.press('Enter'); await page.waitForFunction(()=>window.chatState.conversation.queue.items.length===3); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='send').length),0)
  await button('Add attachments').click(); await page.getByRole('menuitemcheckbox',{name:'Ask before tool actions',exact:true}).click(); await page.waitForFunction(()=>window.chatState.conversation.approvalMode==='ask'); await page.keyboard.press('Escape')
  await page.evaluate(()=>window.addDecision('clarification')); const question=page.getByRole('region',{name:'Question for you',exact:true}); await question.waitFor(); await question.click({button:'right'}); await menu('Copy question').click(); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='copy').at(-1)[1]),await question.locator('.chat-interaction-question').innerText()); assert.equal(await button('Resume queue').isDisabled(),true); await button('Executives').click(); const answer=page.getByRole('textbox',{name:'Your answer',exact:true}); assert.equal(await answer.inputValue(),'Executives'); await answer.fill('Executives preparing the board review'); await page.evaluate(()=>window.failAnswer=true); await answer.press('Enter'); await question.getByRole('alert').filter({hasText:'Could not send your answer'}).waitFor(); assert.equal(await answer.inputValue(),'Executives preparing the board review')
  const beforeAnswerQueue=await page.evaluate(()=>window.events.filter(e=>e[0]==='enqueue').length); await message.fill('Follow-up after the answer'); await message.press('Enter'); await page.waitForFunction(count=>window.events.filter(e=>e[0]==='enqueue').length===count+1,beforeAnswerQueue); assert.equal(await answer.inputValue(),'Executives preparing the board review'); await page.evaluate(()=>{window.failAnswer=false;window.holdAnswer=true}); await button('Send answer').click(); await page.waitForFunction(()=>!!window.finishAnswer); assert.equal(await answer.isDisabled(),true); await page.evaluate(()=>{window.holdAnswer=false;window.finishAnswer()}); await question.getByText('Answered',{exact:true}).waitFor(); await question.getByRole('button',{name:'Question actions',exact:true}).click(); await menu('Copy answer').click(); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='copy').at(-1)[1]),'Executives preparing the board review'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='answer').at(-1)[1].answer),'Executives preparing the board review'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='enqueue').length),beforeAnswerQueue+1)
  for(const [label,decision] of [['Allow once','once'],['Allow for this chat','chat'],['Deny','deny']]){await page.evaluate(()=>window.addDecision('approval')); const approval=page.getByRole('region',{name:'Tool approval',exact:true}); await approval.waitFor(); await approval.getByText('Create a Word document from the requested outline.',{exact:true}).waitFor(); await button(label).click(); await page.waitForFunction(value=>window.events.filter(e=>e[0]==='answer').at(-1)[1].decision===value,decision); await approval.getByText(decision==='deny'?'Denied':'Answered',{exact:true}).waitFor()}
  await page.evaluate(()=>window.addDecision('clarification')); await page.screenshot({path:'.local-data/chat-flow-queue-question.png'}); assert.deepEqual(errors,[]); console.log('PASS streaming Enter/Queue with separate Stop, enqueue failure retains draft, captured skill IDs, queue menu/edit/reorder/remove/pause, navigation ownership, no queue bypass while paused, approval mode run lock, clarification options/free text/pending/error, queued prompt never answers, and all approval decisions.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
