// Memory-only interaction fixture; never touches the user's workspace.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {chromium}=require('playwright-core');
(async()=>{
 const {build}=await import('vite'),{default:react}=await import('@vitejs/plugin-react'),{default:tailwind}=await import('@tailwindcss/vite');
 const root=path.resolve('.local-data/chat-approval-disclosure');fs.mkdirSync(root,{recursive:true});
 fs.writeFileSync(root+'/index.html','<div id="root"></div><script type="module" src="./main.tsx"></script>');
 fs.writeFileSync(root+'/main.tsx',`import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{ModuleHostProvider}from'@zq/module-api';import ChatInteraction from '../../modules/chat/ChatInteraction';import '@zq/ui/styles.css';import '../../apps/desktop/src/shell.css';import '../../modules/chat/chat.css';import '../../modules/chat/chat-flow.css';
 const initial={id:'approval',kind:'approval',status:'waiting',question:'Allow Scite.AI to run search_literature?',tool:'mcp:fixture',detail:'Scite.AI · search_literature\\n{"author":"Zach Rossmiller"}',createdAt:1};
 function App(){const[item,setItem]=useState(initial);window.setInteraction=next=>setItem({...initial,...next});const host={closing:false,registerFlush:()=>()=>{},notify:()=>{},services:{clipboard:{writeText:async text=>{window.copied=text;return{ok:true}}},chat:{respondToInteraction:async({decision,answer})=>{setItem(i=>({...i,status:decision==='deny'?'denied':'answered',answer:answer||(decision==='chat'?'Allowed for this chat':decision==='once'?'Allowed once':'Denied')}));return{ok:true}}}}};return <ModuleHostProvider value={host}><main style={{padding:32,maxWidth:720,margin:'auto'}}><p>Your search is complete.</p><ChatInteraction interaction={item} conversationId="fixture" disabled={false}/><textarea aria-label="Chat message"/></main></ModuleHostProvider>};createRoot(document.getElementById('root')).render(<App/>);`);
 await build({root,configFile:false,logLevel:'error',plugins:[react(),tailwind()],resolve:{dedupe:['react','react-dom','radix-ui']}});
 const server=http.createServer((req,res)=>{const file=path.join(root,'dist',new URL(req.url,'http://localhost').pathname);const target=fs.existsSync(file)&&fs.statSync(file).isFile()?file:root+'/dist/index.html';res.setHeader('Content-Type',target.endsWith('.js')?'text/javascript':target.endsWith('.css')?'text/css':'text/html');fs.createReadStream(target).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:900,height:500},reducedMotion:'reduce'}),errors=[];page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);const region=page.getByRole('region',{name:'Tool approval',exact:true}),detail=region.locator('.chat-interaction-detail');
 for(const [decision,label] of [['Allow once','Allowed once'],['Allow for this chat','Allowed for this chat'],['Deny','Denied']]){await page.evaluate(()=>window.setInteraction({}));await detail.waitFor();await page.getByRole('button',{name:decision,exact:true}).click();const summary=region.getByRole('button',{name:label,exact:true});await summary.waitFor();assert.equal(await summary.getAttribute('aria-expanded'),'false');assert.equal(await detail.isVisible(),false);assert.ok((await region.boundingBox()).height<50);await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Chat message');await summary.focus();await page.keyboard.press('Enter');await detail.waitFor();assert.equal(await summary.getAttribute('aria-expanded'),'true');assert.equal(await page.getByRole('button',{name:'Allow once',exact:true}).count(),0);await page.keyboard.press('Space');assert.equal(await summary.getAttribute('aria-expanded'),'false');await summary.click({button:'right'});await page.getByRole('menuitem',{name:'Copy answer',exact:true}).click();assert.equal(await page.evaluate(()=>window.copied),label)}
 await page.evaluate(()=>window.setInteraction({status:'cancelled'}));await region.getByRole('button',{name:'Cancelled',exact:true}).waitFor();assert.equal(await detail.isVisible(),false);
 await page.evaluate(()=>window.setInteraction({id:'saved',status:'answered',answer:'Allowed for this chat'}));const saved=region.getByRole('button',{name:'Allowed for this chat',exact:true});await saved.waitFor();assert.equal(await saved.getAttribute('aria-expanded'),'false');await page.screenshot({path:root+'/collapsed-light.png'});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:root+'/collapsed-dark.png'});await saved.click();await detail.waitFor();await page.screenshot({path:root+'/expanded-dark.png'});
 await page.evaluate(()=>window.setInteraction({kind:'clarification',status:'answered',question:'Which audience?',answer:'Executives'}));await page.getByRole('region',{name:'Question for you'}).getByText('Executives',{exact:true}).waitFor();assert.deepEqual(errors,[]);console.log('PASS approval decisions collapse, keyboard disclosure, copy context menu, cancelled/history defaults, clarification remains visible.');
 }finally{await browser?.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
