'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ChatService}=require('../electron/chat-service.cjs'),{ArtifactService}=require('../electron/artifact-service.cjs');
async function wait(fn){for(let i=0;i<400;i++){if(fn())return;await new Promise(r=>setTimeout(r,5))}assert.fail('Timed out')}
async function fixture(t,streamChat){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-interactions-'));const artifacts=new ArtifactService({directory});const service=new ChatService({directory,artifacts,provider:{supportsLocalTools:async()=>true,streamChat}});const connection=await service.saveConnection({provider:'ollama',name:'Fixture',baseUrl:'http://localhost:11434'}),conversation=service.createConversation({connectionId:connection.id,model:'fixture'});t.after(()=>{service.shutdown();fs.rmSync(directory,{recursive:true,force:true})});return {service,artifacts,directory,id:conversation.id,last:()=>service.conversation(conversation.id).messages.at(-1),send:()=>service.sendMessage({conversationId:conversation.id,text:'Create a document'})}}
const doc={name:'create_document',arguments:{format:'docx',title:'Example',content:'A complete document.'}};
test('clarification pauses actual run, answer resumes same request, snapshot survives disk',async t=>{let answer;const f=await fixture(t,async req=>{assert(req.localTools.some(t=>t.name==='request_user_input'));answer=await req.onLocalTool({name:'request_user_input',arguments:{question:'Who is the audience?',options:['Students','Staff']}});req.onDelta({content:'For '+answer.answer})});await f.send();await wait(()=>f.last().interactions?.length);const card=f.last().interactions[0];assert.equal(f.service.runs.size,1);assert.equal(card.status,'waiting');assert.equal(new (require('../electron/chat-store.cjs').ChatStore)(f.directory).load().conversations[0].messages.at(-1).interactions[0].status,'waiting');f.service.respondToInteraction({conversationId:f.id,id:card.id,answer:'Staff'});await wait(()=>!f.service.runs.size);assert.equal(f.last().content,'For Staff');assert.equal(f.service.conversation(f.id).messages.length,2)});
test('strict mode creates no artifact until allow; ordinary mode needs no extra question',async t=>{let result;const f=await fixture(t,async req=>{result=await req.onLocalTool(doc);req.onDelta({content:result.ok?'Created.':'Declined.'})});f.service.setApprovalMode({conversationId:f.id,mode:'ask'});await f.send();await wait(()=>f.last().interactions?.length);assert.equal(f.artifacts.list().length,0);f.service.respondToInteraction({conversationId:f.id,id:f.last().interactions[0].id,decision:'once'});await wait(()=>!f.service.runs.size);assert.equal(f.artifacts.list().length,1);assert.equal(f.last().generatedFiles.length,1)});
test('denial pauses queue and prevents repeated mutation attempts in same run',async t=>{const results=[];const f=await fixture(t,async req=>{results.push(await req.onLocalTool(doc));results.push(await req.onLocalTool({...doc,arguments:{...doc.arguments,title:'Attempt 2'}}));req.onDelta({content:'Declined.'})});f.service.setApprovalMode({conversationId:f.id,mode:'ask'});await f.send();await wait(()=>f.last().interactions?.length);f.service.respondToInteraction({conversationId:f.id,id:f.last().interactions[0].id,decision:'deny'});await wait(()=>!f.service.runs.size);assert.equal(f.artifacts.list().length,0);assert.equal(f.last().status,'stopped');assert.equal(results.length,0);assert.equal(f.service.conversation(f.id).queue.paused,true)});
test('stop cancels waiting question; restart marks pending decisions cancelled',async t=>{const f=await fixture(t,async req=>{await req.onLocalTool({name:'request_user_input',arguments:{question:'Which topic?'}});req.onDelta({content:'Late result'})});await f.send();await wait(()=>f.last().interactions?.length);const id=f.last().interactions[0].id;f.service.stop(f.id);assert.equal(f.last().status,'stopped');assert.equal(f.last().interactions[0].status,'cancelled');assert.throws(()=>f.service.respondToInteraction({conversationId:f.id,id,answer:'topic'}),/no longer/);await f.send();await wait(()=>f.last().interactions?.length);const copy=fs.mkdtempSync(path.join(os.tmpdir(),'zq-interactions-restart-'));try{fs.copyFileSync(path.join(f.directory,'chat.json'),path.join(copy,'chat.json'));const restarted=new ChatService({directory:copy});assert.equal(restarted.conversation(f.id).messages.at(-1).interactions[0].status,'cancelled');restarted.shutdown()}finally{fs.rmSync(copy,{recursive:true,force:true})}});
test('queued follow-up waits for clarification and receives its answer in context',async t=>{const requests=[];const f=await fixture(t,async req=>{requests.push(req);if(requests.length===1){const answer=await req.onLocalTool({name:'request_user_input',arguments:{question:'Which audience?'}});req.onDelta({content:'Draft prepared.'});assert.equal(answer.answer,'Students')}else req.onDelta({content:'Follow-up done.'})});await f.send();await wait(()=>f.last().interactions?.length);f.service.enqueueMessage({conversationId:f.id,text:'Now summarize it'});assert.equal(f.service.conversation(f.id).queue.items.length,1);assert.equal(requests.length,1);f.service.respondToInteraction({conversationId:f.id,id:f.last().interactions[0].id,answer:'Students'});await wait(()=>requests.length===2&&!f.service.runs.size);assert(requests[1].messages.some(m=>m.role==='user'&&m.content==='Students'));assert.equal(f.service.conversation(f.id).queue.items.length,0);assert.equal(f.service.conversation(f.id).messages.length,4)});
test('an answered clarification remains context after a provider error',async t=>{let count=0,followup;const f=await fixture(t,async req=>{if(++count===1){await req.onLocalTool({name:'request_user_input',arguments:{question:'Which audience?'}});throw Error('Provider unavailable')}followup=req;req.onDelta({content:'Recovered.'})});await f.send();await wait(()=>f.last().interactions?.length);f.service.respondToInteraction({conversationId:f.id,id:f.last().interactions[0].id,answer:'Students'});await wait(()=>!f.service.runs.size);await f.send();await wait(()=>!f.service.runs.size);assert(followup.messages.some(m=>m.role==='user'&&m.content==='Students'))});
test('denial ends the provider run and discards late hosted output',async t=>{let request;const f=await fixture(t,async req=>{request=req;await req.onLocalTool(doc);await new Promise(()=>{})});f.service.setApprovalMode({conversationId:f.id,mode:'ask'});await f.send();await wait(()=>f.last().interactions?.length);const card=f.last().interactions[0];f.service.respondToInteraction({conversationId:f.id,id:card.id,decision:'deny'});assert.equal(request.signal.aborted,true);assert.equal(f.service.runs.size,0);request.onDelta({content:'Unauthorized continuation'});assert.equal(f.last().content,'');assert.equal(f.last().interactions[0].status,'denied');assert.equal(f.artifacts.list().length,0)});
