const {test} = require('node:test'), assert = require('node:assert/strict')
const fs = require('node:fs'), os = require('node:os'), path = require('node:path')
const {execFileSync} = require('node:child_process')
const {workspace,MAX_FILE} = require('../electron/code/workspace.cjs')
const fixture = t => {const root = fs.mkdtempSync(path.join(os.tmpdir(),'zq-workspace-')); t.after(() => fs.rmSync(root,{recursive:true,force:true})); return root}
test('bounded files and conflict protection reject traversal, links and binary',async t => {
 const root=fixture(t); fs.writeFileSync(path.join(root,'a'),'one'); fs.symlinkSync('/etc',path.join(root,'escape'))
 const one=await workspace(root,'readFile',{path:'a'}); assert.equal(one.text,'one')
 await assert.rejects(workspace(root,'readFile',{path:'../escape'}),{code:'INVALID_PATH'})
 await assert.rejects(workspace(root,'readFile',{path:'escape/passwd'}),{code:'SYMLINK_NOT_SUPPORTED'})
 await workspace(root,'writeFile',{path:'a',text:'two',fingerprint:one.fingerprint})
 await assert.rejects(workspace(root,'writeFile',{path:'a',text:'stale',fingerprint:one.fingerprint}),{code:'FILE_CONFLICT'})
 fs.writeFileSync(path.join(root,'big'),'x'.repeat(MAX_FILE+1)); fs.writeFileSync(path.join(root,'bin'),Buffer.from([0,1]))
 await assert.rejects(workspace(root,'readFile',{path:'big'}),{code:'FILE_TOO_LARGE'})
 await assert.rejects(workspace(root,'readFile',{path:'bin'}),{code:'BINARY_FILE'})
 assert.equal((await workspace(root,'listFiles',{})).entries.find(e=>e.name==='escape').kind,'symlink')
})
test('git paths are literal; staged, unstaged, untracked, and rename status',async t=>{
 const root=fixture(t), git=args=>execFileSync('/opt/homebrew/bin/git',['-C',root,...args]); git(['init','-q'])
 const name=':(glob)*; $(touch INJECTED)'; fs.writeFileSync(path.join(root,name),'first\n'); git(['add','--all'])
 assert.match((await workspace(root,'gitDiff',{path:name,staged:true})).diff,/first/)
 fs.writeFileSync(path.join(root,name),'second\n'); assert.match((await workspace(root,'gitDiff',{path:name})).diff,/second/)
 fs.writeFileSync(path.join(root,'new'),'untracked\n'); assert.match((await workspace(root,'gitDiff',{path:'new'})).diff,/untracked/)
 assert.equal((await workspace(root,'gitDiff',{path:':(glob)*'})).diff,'')
 assert.equal(fs.existsSync(path.join(root,'INJECTED')),false)
})
