const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const {spawn,execFileSync}=require('node:child_process')
const {RemoteHosts,runSSH,openRemote}=require('../electron/code/remote.cjs')
test('synthetic SSH transport bootstraps real persistent remote host and reconnects same terminal',async t=>{
 const home=fs.mkdtempSync('/tmp/zq-rp-'),local=path.join(home,'local');fs.mkdirSync(local,{mode:0o700})
 const env={...process.env,HOME:home,TMUX_TMPDIR:home,PATH:'/opt/homebrew/bin:'+process.env.PATH}
 const transport=(_file,args,opts)=>spawn('/bin/sh',['-c',args.at(-1)],{...opts,env})
 const manager=new RemoteHosts(local,{run:(alias,args,input)=>runSSH(alias,args,input,transport),open:(alias,bridge)=>openRemote(alias,bridge,transport)})
 t.after(async()=>{manager.close();await new Promise(r=>setTimeout(r,100));try{execFileSync('/opt/homebrew/bin/tmux',['kill-server'],{env,stdio:'ignore'})}catch{}try{execFileSync('/opt/homebrew/bin/tmux',['-S',path.join(home,'.local/share/zq/code/runtime/tmux'),'kill-server'],{stdio:'ignore'})}catch{}await new Promise(r=>setTimeout(r,100));fs.rmSync(home,{recursive:true,force:true,maxRetries:5})})
 const host=manager.create({name:'Fixture',sshAlias:'fixture'})
 await manager.connect(host.id)
 const cwd=path.join(home,'checkout with spaces');fs.mkdirSync(cwd);fs.writeFileSync(path.join(cwd,'a'),'original')
 const launch=path.join(home,'launch.zsh');fs.writeFileSync(launch,'generic() { exec /bin/cat; }\n')
 const p=await manager.request(host.id,'createProject',{name:'Remote work',cwd})
 const profile=await manager.request(host.id,'createProfile',{name:'Generic',launcherFile:launch,functionName:'generic',adapter:'terminal'})
 const s=await manager.request(host.id,'createSession',{projectId:p.id,profileId:profile.id,mode:'terminal'})
 assert.equal(s.state,'ready');assert.ok(s.pid)
 const standalone=await manager.request(host.id,'createTerminal',{hostId:'local',name:'test-ssh-shell'})
 assert.equal(standalone.projectId,'');assert.equal(standalone.ownership,'external')
 await manager.request(host.id,'linkTerminal',{id:standalone.id,projectId:p.id})
 const sessionFile=await manager.request(host.id,'readFile',{sessionId:s.id,path:'a'})
 assert.equal(sessionFile.text,'original')
 const binary=require('node:crypto').randomBytes(120003),client=manager.clients.get(host.id)
 const transfer=(action,params={})=>client.request('code:transfer',{action,sessionId:s.id,...params})
 const upload=await transfer('beginWrite',{name:'binary payload.bin',folder:'',size:binary.length})
 for(let i=0;i<binary.length;i+=32768)await transfer('writeChunk',{token:upload.id,data:binary.subarray(i,i+32768).toString('base64')})
 await transfer('finishWrite',{token:upload.id})
 const download=await transfer('beginRead',{path:'binary payload.bin'}),chunks=[]
 for(let done=false;!done;){const chunk=await transfer('readChunk',{token:download.id});chunks.push(Buffer.from(chunk.data,'base64'));done=chunk.done}
 await transfer('finishRead',{token:download.id});assert.deepEqual(Buffer.concat(chunks),binary)
 const abandoned=await transfer('beginWrite',{name:'abandoned.bin',size:100})
 assert(abandoned.id)
 const file=await manager.request(host.id,'readFile',{projectId:p.id,path:'a'})
 await manager.request(host.id,'writeFile',{projectId:p.id,path:'a',text:'edited',fingerprint:file.fingerprint})
 manager.disconnect(host.id);await manager.connect(host.id)
 assert(!fs.readdirSync(cwd).some(n=>n.startsWith('.zq-upload-')),'Disconnected bridges clean partial uploads')
 const resumed=manager.snapshots.get(host.id).sessions.find(r=>r.id===s.id)
 const terminal=(await manager.request(host.id,'discoverTerminals',{})).find(r=>r.target===standalone.tmuxTarget)
 assert.equal(terminal.name,'test-ssh-shell')
 const attached=await manager.request(host.id,'attachExternalTerminal',{target:terminal.target,identity:terminal.identity})
 assert.equal(attached.id,standalone.id);assert.equal(attached.projectId,p.id)
 assert.equal(resumed.pid,s.pid);assert.equal(resumed.hostId,host.id)
 assert.equal((await manager.request(host.id,'readFile',{projectId:p.id,path:'a'})).text,'edited')
 await manager.request(host.id,'claimSession',{id:s.id})
 assert.equal((await manager.request(host.id,'stopSession',{id:s.id,expectedRevision:0})).state,'stopped')
})
