const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path')
const {spawn,execFileSync}=require('node:child_process')
const {RemoteHosts,runSSH,openRemote}=require('../electron/code/remote.cjs')
test('synthetic SSH transport bootstraps real persistent remote host and reconnects same terminal',async t=>{
 const home=fs.mkdtempSync('/tmp/zq-rp-'),local=path.join(home,'local');fs.mkdirSync(local,{mode:0o700})
 const env={...process.env,HOME:home,PATH:'/opt/homebrew/bin:'+process.env.PATH}
 const transport=(_file,args,opts)=>spawn('/bin/sh',['-c',args.at(-1)],{...opts,env})
 const manager=new RemoteHosts(local,{run:(alias,args,input)=>runSSH(alias,args,input,transport),open:(alias,bridge)=>openRemote(alias,bridge,transport)})
 t.after(async()=>{manager.close();await new Promise(r=>setTimeout(r,100));try{execFileSync('/opt/homebrew/bin/tmux',['-S',path.join(home,'.local/share/zq/code/runtime/tmux'),'kill-server'],{stdio:'ignore'})}catch{}await new Promise(r=>setTimeout(r,100));fs.rmSync(home,{recursive:true,force:true,maxRetries:5})})
 const host=manager.create({name:'Fixture',sshAlias:'fixture'})
 await manager.connect(host.id)
 const cwd=path.join(home,'checkout with spaces');fs.mkdirSync(cwd);fs.writeFileSync(path.join(cwd,'a'),'original')
 const launch=path.join(home,'launch.zsh');fs.writeFileSync(launch,'generic() { exec /bin/cat; }\n')
 const p=await manager.request(host.id,'createProject',{name:'Remote work',cwd})
 const profile=await manager.request(host.id,'createProfile',{name:'Generic',launcherFile:launch,functionName:'generic',adapter:'terminal'})
 const s=await manager.request(host.id,'createSession',{projectId:p.id,profileId:profile.id,mode:'terminal'})
 assert.equal(s.state,'ready');assert.ok(s.pid)
 const file=await manager.request(host.id,'readFile',{projectId:p.id,path:'a'})
 await manager.request(host.id,'writeFile',{projectId:p.id,path:'a',text:'edited',fingerprint:file.fingerprint})
 manager.disconnect(host.id);await manager.connect(host.id)
 const resumed=manager.snapshots.get(host.id).sessions.find(r=>r.id===s.id)
 assert.equal(resumed.pid,s.pid);assert.equal(resumed.hostId,host.id)
 assert.equal((await manager.request(host.id,'readFile',{projectId:p.id,path:'a'})).text,'edited')
 await manager.request(host.id,'claimSession',{id:s.id})
 assert.equal((await manager.request(host.id,'stopSession',{id:s.id,expectedRevision:0})).state,'stopped')
})
