// Real packaged UI/native services; native picker results are controlled in an isolated workspace.
const {_electron:electron}=require('playwright-core'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{randomBytes}=require('node:crypto'),{spawnSync}=require('node:child_process')
;(async()=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'zq-files-app-')),cwd=path.join(root,'project'),local=path.join(root,'local');fs.mkdirSync(cwd);fs.mkdirSync(local);fs.mkdirSync(path.join(cwd,'docs'));fs.writeFileSync(path.join(cwd,'docs','note.txt'),'Before\n')
 const payload=randomBytes(100007),source=path.join(local,'payload.zip'),download=path.join(local,'saved.zip');fs.writeFileSync(source,payload)
 let app,page
 try {
  if(process.env.ZQ_TEST_CODE_MODULE){
   const asar=require('@electron/asar'),{ModuleStore}=require('../electron/module-store.cjs')
   const archive=path.resolve('apps/desktop/release/mac-arm64/zQ.app/Contents/Resources/app.asar')
   const store=new ModuleStore({directory:path.join(root,'modules'),bundles:['hq','notes','tasks','chat','code'].map(n=>JSON.parse(asar.extractFile(archive,'bundled-modules/'+n+'.zqmodule'))),trustedKeys:JSON.parse(asar.extractFile(archive,'bundled-modules/trusted-keys.json'))})
   const candidate=JSON.parse(fs.readFileSync(path.resolve(process.env.ZQ_TEST_CODE_MODULE),'utf8')),bundled=JSON.parse(asar.extractFile(archive,'bundled-modules/code.zqmodule'))
   if(candidate.manifest.version===bundled.manifest.version)assert.deepEqual(candidate,bundled,'Equal-version test module must match bundled bytes')
   else store.installFile(path.resolve(process.env.ZQ_TEST_CODE_MODULE))
  }
  app=await electron.launch({executablePath:process.env.ZQ_TEST_APP||path.resolve('apps/desktop/release/mac-arm64/zQ.app/Contents/MacOS/zQ'),env:{...process.env,ZQ_DATA_DIR:root,TMUX_TMPDIR:root},timeout:30000})
  page=await app.firstWindow();page.setDefaultTimeout(15000);await page.waitForFunction(()=>!!window.zq)
  await app.evaluate(({dialog},{source,download})=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[source]});dialog.showSaveDialog=async()=>({canceled:false,filePath:download});dialog.showMessageBox=async()=>({response:0})},{source,download})
  if(process.env.ZQ_TEST_QUICK_TERMINAL){
   await page.getByRole('button',{name:'Code module',exact:true}).click()
   await page.getByRole('button',{name:'New terminal',exact:true}).click()
   await page.waitForFunction(()=>document.querySelector('.xterm')&&!document.querySelector('.code-terminal-reconnect'))
   assert.equal(await page.getByRole('dialog').count(),0)
   let state=await page.evaluate(()=>window.zq.code.invoke('snapshot'))
   assert.equal(state.projects.length,0);assert.equal(state.sessions.length,1);assert.equal(state.sessions[0].hostId,'local');assert.equal(state.sessions[0].projectId,'')
   await page.locator('.xterm-screen').click();await page.keyboard.press('Meta+t')
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]').length===2&&!document.querySelector('.code-terminal-reconnect'))
   await page.getByRole('button',{name:'New terminal tab in pane 1',exact:true}).click()
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]').length===3&&!document.querySelector('.code-terminal-reconnect'))
   state=await page.evaluate(()=>window.zq.code.invoke('snapshot'));assert.equal(state.sessions.length,3);assert(state.sessions.every(s=>s.hostId==='local'&&s.mode==='terminal'))
   const quickPid=s=>spawnSync('/opt/homebrew/bin/tmux',['display-message','-p','-t',s.tmuxTarget,'#{pane_pid}'],{env:{...process.env,TMUX_TMPDIR:root},encoding:'utf8'}).stdout.trim()
   const quickPids=state.sessions.map(quickPid);assert(quickPids.every(Boolean))
   const quickTabs=page.getByRole('tab')
   await page.locator('.xterm-screen').click();await page.keyboard.press('Meta+Shift+[')
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]')[1]?.getAttribute('aria-selected')==='true')
   await page.keyboard.press('Meta+Shift+]')
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]')[2]?.getAttribute('aria-selected')==='true')
   await page.keyboard.press('Meta+Shift+]')
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]')[0]?.getAttribute('aria-selected')==='true')
   await page.keyboard.press('Meta+Shift+[')
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]')[2]?.getAttribute('aria-selected')==='true')
   await page.waitForFunction(()=>!document.querySelector('.code-terminal-reconnect'))
   await page.locator('.xterm-screen').click();await page.keyboard.press('Control+w')
   assert.equal(await quickTabs.count(),3,'Ctrl+W on macOS remains a shell editing shortcut')
   await page.getByRole('button',{name:'Session actions',exact:true}).click()
   await page.getByRole('menuitem',{name:'Rename',exact:true}).click()
   await page.getByRole('dialog').waitFor()
   const closeNativeTab=()=>app.evaluate(({Menu})=>{const menu=Menu.getApplicationMenu().items.find(i=>i.label==='File').submenu.items.find(i=>i.label==='Close Tab');menu.click()})
   await closeNativeTab();await page.waitForTimeout(100);assert.equal(await page.locator('.code-tabs [role=tab]').count(),3,'Native Close Tab respects dialogs')
   await page.keyboard.press('Escape')
   await page.locator('.xterm-screen').click();await page.keyboard.press('Meta+w')
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]').length===2)
   await closeNativeTab()
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]').length===1)
   await closeNativeTab()
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]').length===0)
   assert.equal(app.windows().length,1,'Closing the last tab keeps the app window open')
   assert.deepEqual(state.sessions.map(quickPid),quickPids,'Keyboard and native menu closes preserve shells')
   await page.getByRole('button',{name:'Notes module',exact:true}).click();await page.keyboard.press('Meta+t')
   assert.equal((await page.evaluate(()=>window.zq.code.invoke('snapshot'))).sessions.length,3,'Shortcut is scoped to Code')
   await page.getByRole('button',{name:'Code module',exact:true}).click()
   const tabs=page.locator('.code-tabs button[aria-label^="Close tab"]');while(await tabs.count())await tabs.last().click()
   console.log('PASS: direct local terminal with zero projects, Cmd+T from focused terminal, plus creates another shell, previous/next wrap, Cmd+W and native Close Tab detach without stopping shells, dialogs protected, Ctrl+W preserved, shortcut scoped to Code.')
  }
  const session=await page.evaluate(async cwd=>{const project=await window.zq.code.invoke('createProject',{name:'File test',cwd});const session=await window.zq.code.invoke('createTerminal',{hostId:'local',projectId:project.id,name:'files-check'});await window.zq.code.invoke('linkTerminal',{id:session.id,projectId:null});return session},cwd)
  await page.getByRole('button',{name:'Code module',exact:true}).click()
  await page.locator('.code-session-navigation').getByRole('button',{name:'files-check · This Mac',exact:true}).click()
  await page.locator('.xterm').waitFor()
  await page.locator('.code-terminal-reconnect').waitFor({state:'hidden'})
  if(process.env.ZQ_TEST_CODE_MODULE){
   assert.match(await page.locator('.code-toolbar-title').innerText(),/This Mac\s*\/\s*files-check\s*\/\s*private\/.*\/project/)
   await page.getByRole('button',{name:'Session actions',exact:true}).click()
   await page.getByRole('menuitem',{name:'Rename',exact:true}).waitFor()
   await page.keyboard.press('Escape')
  }
  const tmuxEnv={...process.env,TMUX_TMPDIR:root}
  spawnSync('/opt/homebrew/bin/tmux',['set-option','-t',session.tmuxTarget,'mouse','on'],{env:tmuxEnv})
  await page.evaluate(id=>window.zq.code.invoke('writeTerminal',{id,data:'\x15printf "scroll-test-%s\\n" {1..200}\r'}),session.id)
  await page.waitForTimeout(250)
  const screen=page.locator('.xterm-screen');await screen.hover();const started=Date.now();await page.mouse.wheel(0,-200);await page.mouse.wheel(0,-200);await page.mouse.wheel(0,-200)
  let scrolled=false
  for(let i=0;i<40;i++){const state=spawnSync('/opt/homebrew/bin/tmux',['display-message','-p','-t',session.tmuxTarget,'#{pane_in_mode}:#{scroll_position}'],{env:tmuxEnv,encoding:'utf8'}).stdout.trim();if(state.startsWith('1:')&&Number(state.split(':')[1])>0){scrolled=true;break}await page.waitForTimeout(25)}
  if(!scrolled){await page.screenshot({path:'.local-data/scroll-failure.png'});console.log('tmux',spawnSync('/opt/homebrew/bin/tmux',['show-options','-t',session.tmuxTarget,'mouse'],{env:tmuxEnv,encoding:'utf8'}).stdout);console.log('pane',spawnSync('/opt/homebrew/bin/tmux',['capture-pane','-p','-t',session.tmuxTarget],{env:tmuxEnv,encoding:'utf8'}).stdout.slice(-1600));console.log('ui',await page.locator('.code-session-host').getAttribute('aria-label'))}
  assert(scrolled,'Browser wheel events reach tmux history through the attached PTY')
  console.log('Terminal wheel → tmux history visible in '+(Date.now()-started)+' ms')
  spawnSync('/opt/homebrew/bin/tmux',['send-keys','-t',session.tmuxTarget,'-X','cancel'],{env:tmuxEnv})
  await page.getByRole('button',{name:'Workspace',exact:true}).click()
  const button=name=>page.getByRole('button',{name,exact:true}),menu=name=>page.getByRole('menuitem',{name,exact:true})
  await button('Folder docs').click();await button('File docs/note.txt').click()
  await page.getByRole('textbox',{name:'Edit docs/note.txt'}).fill('After\n');await button('Save').click()
  await page.waitForFunction(()=>!document.querySelector('.code-editor-heading').textContent.includes('•'))
  assert.equal(fs.readFileSync(path.join(cwd,'docs','note.txt'),'utf8'),'After\n')
  await button('Folder docs').click({button:'right'});await menu('Upload files…').click()
  await button('File docs/payload.zip').waitFor();assert.deepEqual(fs.readFileSync(path.join(cwd,'docs','payload.zip')),payload)
  await button('File docs/payload.zip').click({button:'right'});await menu('Download…').click()
  await page.waitForFunction(()=>document.querySelectorAll('.code-transfer.done').length===2);assert.deepEqual(fs.readFileSync(download),payload)
  // Reject overwrite through the actual native confirmation callback.
  fs.writeFileSync(source,'replacement');await button('Folder docs').click({button:'right'});await menu('Upload files…').click();await page.getByText('Skipped',{exact:true}).waitFor();assert.deepEqual(fs.readFileSync(path.join(cwd,'docs','payload.zip')),payload)
  for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await page.waitForTimeout(200);await page.screenshot({path:'.local-data/files-packaged-'+theme+'.png'})}
  await button('Close workspace panel').click();await button('Workspace').click();await page.getByText('Skipped',{exact:true}).waitFor();
  assert.equal((await page.evaluate(id=>window.zq.code.invoke('fileTransfers',{sessionId:id}),session.id)).length,3)
  if(process.env.ZQ_TEST_WORKBENCH){
   await button('Close workspace panel').click()
   const sessions=await page.evaluate(async()=>{const result=[];for(const name of ['tab-two','tab-three'])result.push(await window.zq.code.invoke('createTerminal',{hostId:'local',name}));return result})
   const nav=name=>page.locator('.code-session-navigation').getByRole('button',{name:name+' · This Mac',exact:true})
   await nav('tab-two').click();await nav('tab-three').click();await nav('files-check').click()
   assert.equal(await page.getByRole('tab').count(),3)
   await button('Terminals').click();await nav('files-check').click()
   await page.waitForFunction(()=>document.querySelectorAll('.xterm').length===1&&!document.querySelector('.code-terminal-reconnect'))

   await button('Split side by side').click()
   await page.waitForFunction(()=>document.querySelectorAll('.xterm').length===2&&!document.querySelector('.code-terminal-reconnect'))
   const panes=page.locator('.code-pane')
   assert.equal(await panes.count(),2)
   await panes.nth(0).locator('.xterm-screen').click();await page.keyboard.type('printf "LEFT-PANE-CHECK\\n"');await page.keyboard.press('Enter')
   await panes.nth(1).locator('.xterm-screen').click();await page.keyboard.type('printf "RIGHT-PANE-CHECK\\n"');await page.keyboard.press('Enter')
   await page.waitForTimeout(200)
   const capture=s=>spawnSync('/opt/homebrew/bin/tmux',['capture-pane','-p','-t',s.tmuxTarget],{env:tmuxEnv,encoding:'utf8'}).stdout
   assert.match(capture(session),/LEFT-PANE-CHECK/);assert.doesNotMatch(capture(session),/RIGHT-PANE-CHECK/)
   assert.match(capture(sessions[0]),/RIGHT-PANE-CHECK/);assert.doesNotMatch(capture(sessions[0]),/LEFT-PANE-CHECK/)
   await button('Close tab tab-three').click();assert.equal(await page.getByRole('tab').count(),2)
   await page.getByRole('separator',{name:'Resize session panes'}).focus();await page.keyboard.press('ArrowRight')
   assert.equal(await page.getByRole('separator').getAttribute('aria-valuenow'),'55')
   await button('Split top and bottom').click();assert.equal(await page.getByRole('separator').getAttribute('aria-orientation'),'horizontal')
   await button('Split side by side').click()
   await panes.nth(0).locator('.xterm-screen').click();await button('Workspace').click()
   for(const theme of ['light','dark']){await page.evaluate(theme=>document.documentElement.dataset.theme=theme,theme);await page.waitForTimeout(200);await page.screenshot({path:'.local-data/workbench-'+theme+'.png'})}
   const before=await page.evaluate(()=>JSON.parse(localStorage.getItem('zq.code.workbench')))
   const pid=s=>spawnSync('/opt/homebrew/bin/tmux',['display-message','-p','-t',s.tmuxTarget,'#{pane_pid}'],{env:tmuxEnv,encoding:'utf8'}).stdout.trim()
   const pids=[session,...sessions].map(pid);assert(pids.every(Boolean))
   await app.close();app=await electron.launch({executablePath:process.env.ZQ_TEST_APP||path.resolve('apps/desktop/release/mac-arm64/zQ.app/Contents/MacOS/zQ'),env:{...process.env,ZQ_DATA_DIR:root,TMUX_TMPDIR:root},timeout:30000})
   page=await app.firstWindow();page.setDefaultTimeout(15000);await page.waitForFunction(()=>!!window.zq)
   await page.getByRole('button',{name:'Code module',exact:true}).click()
   await page.waitForFunction(()=>document.querySelectorAll('.xterm').length===2&&!document.querySelector('.code-terminal-reconnect'))
   assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('zq.code.workbench'))),before)
   assert.equal(await page.getByRole('complementary',{name:'File workspace'}).count(),1)
   assert.deepEqual([session,...sessions].map(pid),pids,'App restart and tab close preserve all underlying shell processes')
   await page.getByRole('tab').first().click({button:'right'});await page.getByRole('menuitem',{name:'Move to other pane',exact:true}).click()
   await page.waitForFunction(()=>document.querySelectorAll('.xterm').length===1&&!document.querySelector('.code-terminal-reconnect'))
   await button('Merge panes').click();assert.equal(await page.locator('.code-pane').count(),1)
   assert.equal(await page.getByRole('tab').count(),2)
   await page.getByRole('tab').first().focus();await page.keyboard.press('ArrowRight')
   assert.equal(await page.getByRole('tab').last().getAttribute('aria-selected'),'true')
   await button('Close tab tab-two').click()
   await button('Split side by side').click();await button('New terminal in pane 2').click()
   await page.waitForFunction(()=>document.querySelectorAll('.xterm').length===2&&!document.querySelector('.code-terminal-reconnect'))
   assert.equal(await page.getByRole('tab').count(),2)
   await button('New terminal tab in pane 2').click()
   await page.waitForFunction(()=>document.querySelectorAll('[role=tab]').length===3&&!document.querySelector('.code-terminal-reconnect'))
   await button('Merge panes').click()
   const closeButtons=page.locator('.code-tabs button[aria-label^="Close tab"]');while(await closeButtons.count())await closeButtons.last().click()

   assert.deepEqual([session,...sessions].map(pid),pids,'Closing views never stops shells')
   console.log('PASS: real PTY split input isolation, tab close, keyboard resize, both split axes, right-click move/merge, keyboard tabs, full app restart restores layout and workspace panel without replacing shell PIDs.')
  }
  console.log('PASS: packaged standalone terminal explorer, nested folder editing, right-click binary upload/download, native overwrite cancellation, light/dark, and transfer status after panel reopening. Isolated workspace '+root)
 } finally {
  if(app){await app.close()}
  spawnSync('/opt/homebrew/bin/tmux',['kill-server'],{env:{...process.env,TMUX_TMPDIR:root},stdio:'ignore'})
  spawnSync('/opt/homebrew/bin/tmux',['-S',path.join(root,'code','tmux'),'kill-server'],{stdio:'ignore'})
 }
})().catch(error=>{console.error(error);process.exitCode=1})
