const test = require('node:test'), assert = require('node:assert/strict')
const fs = require('node:fs'), path = require('node:path'), {fork} = require('node:child_process'), {randomUUID} = require('node:crypto')
const {atomic, privateRead} = require('../electron/code/code-catalog.cjs')
const {requestRunner} = require('../electron/code/structured-runner.cjs')
const delay = ms => new Promise(r => setTimeout(r, ms))
test('long native history is durable before ready without a disk sync per replayed message', {timeout:30000}, async t => {
  const root=fs.mkdtempSync('/tmp/zq-kperf-'), id=randomUUID(), token='a'.repeat(64)
  fs.writeFileSync(path.join(root,'token'),token,{mode:0o600})
  const fixture=path.join(root,'agent.cjs'), probe=path.join(root,'probe.cjs')
  fs.writeFileSync(probe, `const fs=require('node:fs');let syncs=0;const original=fs.fsyncSync;fs.fsyncSync=(...args)=>{syncs++;return original(...args)};process.on('message',()=>process.send({syncs}));`)
  fs.writeFileSync(fixture, `const readline=require('node:readline');const send=m=>process.stdout.write(JSON.stringify({jsonrpc:'2.0',...m})+'\\n');readline.createInterface({input:process.stdin}).on('line',line=>{const m=JSON.parse(line);if(m.method==='initialize')send({id:m.id,result:{agentCapabilities:{loadSession:true}}});else if(m.method==='session/load'){for(let n=0;n<1600;n++)send({method:'session/update',params:{sessionId:'performance',update:{sessionUpdate:n%2?'agent_message_chunk':'user_message_chunk',content:{type:'text',text:'Turn '+n+' '+('History text. '.repeat(80))}}}});send({id:m.id,result:{}})}else if(m.method==='session/close')send({id:m.id,result:{}})});`)
  atomic(path.join(root,id+'.launch.json'),{adapter:'kimi',nativeId:'performance',nonce:'fixture',launch:{file:process.execPath,args:[fixture],cwd:root}})
  const started=performance.now()
  const runner=fork(path.resolve(__dirname,'../electron/code/structured-runner.cjs'),[root,id],{execArgv:['--require',probe],stdio:['ignore','ignore','inherit','ipc']})
  t.after(async()=>{try{await requestRunner(root,id,token,'stop')}catch{};for(let n=0;n<100&&runner.exitCode===null;n++)await delay(20);if(runner.exitCode===null)runner.kill();fs.rmSync(root,{recursive:true,force:true})})
  let status
  for(let n=0;n<500;n++){try{status=await requestRunner(root,id,token,'status')}catch{};if(status?.initialized)break;await delay(20)}
  assert.equal(status?.state,'ready')
  const elapsed=Math.round(performance.now()-started)
  const metrics=await new Promise(resolve=>{runner.once('message',resolve);runner.send('metrics')})
  const disk=privateRead(path.join(root,id+'.events.json'))
  assert.equal(disk.seq,1600)
  assert(disk.events.at(-1).text.startsWith('Turn 1599 '))
  assert(Buffer.byteLength(JSON.stringify(disk))<=240000)
  assert(disk.events.length<=256)
  console.log(JSON.stringify({historyMessages:1600,readyMs:elapsed,fsyncCalls:metrics.syncs}))
  if(!process.env.ZQ_PERF_BASELINE)assert(metrics.syncs<100,`History replay performed ${metrics.syncs} disk syncs`)
})
