const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os')
const {randomUUID,randomBytes}=require('node:crypto')
const {FileTransfers,workspaceRoot,CHUNK}=require('../electron/code/file-transfers.cjs')
const {TransferService}=require('../electron/code/transfer-service.cjs')
const {sessionWorkspace}=require('../electron/code/session-workspace.cjs')
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'zq-files-'));const f=new FileTransfers();t.after(()=>{f.close();fs.rmSync(root,{recursive:true,force:true})});return {root,f}}
test('session workspace reads and edits without creating a project; target and path confinement',async t=>{
 const {root}=fixture(t),id=randomUUID(),snapshot={projects:[],sessions:[{id,cwd:root}]};fs.writeFileSync(path.join(root,'note'),'one')
 const file=await sessionWorkspace(snapshot,'readFile',{sessionId:id,path:'note'});assert.equal(file.text,'one')
 await sessionWorkspace(snapshot,'writeFile',{sessionId:id,path:'note',text:'two',fingerprint:file.fingerprint})
 assert.equal(fs.readFileSync(path.join(root,'note'),'utf8'),'two')
 assert.throws(()=>sessionWorkspace(snapshot,'readFile',{sessionId:id,projectId:randomUUID(),path:'note'}),/INVALID_REQUEST/)
 assert.throws(()=>workspaceRoot(snapshot,{sessionId:id,hostId:'local'}),/INVALID_REQUEST/)
 await assert.rejects(async()=>sessionWorkspace(snapshot,'readFile',{sessionId:id,path:'../escape'}),/INVALID_PATH/)
})
test('binary upload/download, empty files, overwrite conflict, cleanup, symlinks and traversal',t=>{
 const {root,f}=fixture(t),data=randomBytes(CHUNK*3+101)
 const begin=f.invoke('beginWrite',{folder:'',name:'a.bin',size:data.length},root)
 for(let start=0;start<data.length;start+=CHUNK)f.invoke('writeChunk',{token:begin.id,data:data.subarray(start,start+CHUNK).toString('base64')})
 f.invoke('finishWrite',{token:begin.id});assert.deepEqual(fs.readFileSync(path.join(root,'a.bin')),data)
 const read=f.invoke('beginRead',{path:'a.bin'},root),chunks=[];let done=false
 while(!done){const r=f.invoke('readChunk',{token:read.id});chunks.push(Buffer.from(r.data,'base64'));done=r.done}
 f.invoke('finishRead',{token:read.id});assert.deepEqual(Buffer.concat(chunks),data)
 const empty=f.invoke('beginWrite',{name:'empty',size:0},root);f.invoke('finishWrite',{token:empty.id});assert.equal(fs.statSync(path.join(root,'empty')).size,0)
 const conflict=f.invoke('beginWrite',{name:'a.bin',size:0},root);assert(conflict.exists);fs.writeFileSync(path.join(root,'a.bin'),'changed')
 assert.throws(()=>f.invoke('finishWrite',{token:conflict.id}),/FILE_CONFLICT/);assert.equal(fs.readFileSync(path.join(root,'a.bin'),'utf8'),'changed')
 const incomplete=f.invoke('beginWrite',{name:'incomplete',size:10},root);assert.throws(()=>f.invoke('finishWrite',{token:incomplete.id}),/TRANSFER_INCOMPLETE/)
 fs.symlinkSync(path.join(root,'a.bin'),path.join(root,'link'))
 assert.throws(()=>f.invoke('beginRead',{path:'link'},root),/SYMLINK/)
 assert.throws(()=>f.invoke('beginWrite',{name:'link',size:0},root),/INVALID_FILE_TYPE/)
 assert.throws(()=>f.invoke('beginWrite',{folder:'../',name:'bad',size:0},root),/INVALID_PATH/)
 assert.throws(()=>f.invoke('beginWrite',{name:'../bad',size:0},root),/INVALID_PATH/)
 assert(!fs.readdirSync(root).some(n=>n.endsWith('.tmp')))
})
test('native pickers govern transfer paths, canceled overwrite preserves file, progress and failure survive panel navigation',async t=>{
 const {root}=fixture(t),remote=path.join(root,'remote'),local=path.join(root,'local');fs.mkdirSync(remote);fs.mkdirSync(local)
 const id=randomUUID(),source=path.join(local,'payload.bin'),output=path.join(local,'download.bin'),data=randomBytes(100003)
 fs.writeFileSync(source,data)
 let replace=false,pick=true;const owner={snapshot:async()=>({projects:[],sessions:[{id,cwd:remote,hostId:'local'}]})}
 const service=new TransferService(owner,{pickUpload:async()=>pick?[source]:null,pickDownload:async()=>output,confirmReplace:async()=>replace});t.after(()=>service.close())
 assert.equal((await service.run('uploadFiles',{sessionId:id,path:''})).completed,1)
 assert.deepEqual(fs.readFileSync(path.join(remote,'payload.bin')),data)
 fs.writeFileSync(source,'new')
 assert.equal((await service.run('uploadFiles',{sessionId:id,path:''})).completed,0);assert.deepEqual(fs.readFileSync(path.join(remote,'payload.bin')),data)
 replace=true;await service.run('uploadFiles',{sessionId:id,path:''});assert.equal(fs.readFileSync(path.join(remote,'payload.bin'),'utf8'),'new')
 await service.run('downloadFile',{sessionId:id,path:'payload.bin'});assert.equal(fs.readFileSync(output,'utf8'),'new')
 pick=false;assert.equal((await service.run('uploadFiles',{sessionId:id,path:''})).canceled,true)
 await assert.rejects(service.run('downloadFile',{sessionId:id,path:'missing'}),/ENOENT/)
 assert.equal(service.list({sessionId:id}).at(-1).state,'failed')
 assert(service.list({sessionId:id}).some(j=>j.state==='done'&&j.bytes===3))
 assert(!fs.readdirSync(remote).some(n=>n.endsWith('.tmp')));assert(!fs.readdirSync(local).some(n=>n.endsWith('.tmp')))
})
