const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const {prepareRoot,readCatalog,writeCatalog} = require('../electron/code/service-storage.cjs')
function root(t) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(),'zq-service-'))
  t.after(() => fs.rmSync(dir,{recursive:true,force:true}))
  return dir
}
test('private state and token persist without changing identity',t => {
  const paths = prepareRoot(root(t))
  const state = readCatalog(paths)
  assert.deepEqual(state,{version:1,seq:0,sessions:[],events:[]})
  writeCatalog(paths,state)
  assert.deepEqual(readCatalog(paths),state)
  assert.equal(prepareRoot(paths.root).token,paths.token)
  assert.equal(fs.statSync(path.join(paths.root,'catalog.json')).mode & 0o777,0o600)
})
test('rejects symlink root and permissive directory',t => {
  const dir = root(t)
  fs.symlinkSync(dir,path.join(dir,'link'))
  assert.throws(() => prepareRoot(path.join(dir,'link')),{code:'UNSAFE_SERVICE_PATH'})
  fs.chmodSync(dir,0o755)
  assert.throws(() => prepareRoot(dir),{code:'UNSAFE_SERVICE_PATH'})
})
test('rejects symbolic or permissive token rather than following or repairing it',t => {
  const dir = root(t)
  fs.writeFileSync(path.join(dir,'target'),'x'.repeat(64),{mode:0o600})
  fs.symlinkSync(path.join(dir,'target'),path.join(dir,'token'))
  assert.throws(() => prepareRoot(dir),{code:'UNSAFE_SERVICE_PATH'})
  fs.unlinkSync(path.join(dir,'token'))
  fs.writeFileSync(path.join(dir,'token'),'x'.repeat(64),{mode:0o644})
  assert.throws(() => prepareRoot(dir),{code:'UNSAFE_SERVICE_PATH'})
})
test('invalid writes cannot replace a valid catalog',t => {
  const paths = prepareRoot(root(t))
  const state = readCatalog(paths)
  writeCatalog(paths,state)
  assert.throws(() => writeCatalog(paths,{...state,version:2}),{code:'INVALID_CATALOG'})
  assert.deepEqual(readCatalog(paths),state)
  fs.writeFileSync(path.join(paths.root,'catalog.json'),'{broken')
  assert.throws(() => readCatalog(paths),{code:'INVALID_CATALOG'})
})
test('rejects oversized and symlinked catalogs',t => {
  const paths = prepareRoot(root(t))
  const file = path.join(paths.root,'catalog.json')
  fs.writeFileSync(file,'x'.repeat(1024*1024+1),{mode:0o600})
  assert.throws(() => readCatalog(paths),{code:'INVALID_CATALOG'})
  fs.unlinkSync(file)
  fs.symlinkSync(path.join(paths.root,'token'),file)
  assert.throws(() => readCatalog(paths),{code:'UNSAFE_SERVICE_PATH'})
})
