// Run after pack. All changes use a disposable app workspace; no account sign-in.
const {_electron:electron}=require('playwright-core');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const root=process.cwd(),output=path.join(root,'.local-data/catalog-verification');fs.mkdirSync(output,{recursive:true});const directory=fs.mkdtempSync(path.join(output,'profile-'));let app,page;
const unwrap=result=>{assert.equal(result.ok,true,JSON.stringify(result.error));return result.value};
(async()=>{
 app=await electron.launch({executablePath:path.join(root,'apps/desktop/release/mac-arm64/zQ.app/Contents/MacOS/zQ'),env:{...process.env,ZQ_DATA_DIR:directory},timeout:30000});page=await app.firstWindow();const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.waitForFunction(()=>!!window.zq);
 await app.evaluate(({shell})=>{shell.openExternal=async()=>{throw Error('No browser authorization permitted in catalog fixture')}});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Connectors',exact:true}).click();await page.getByRole('tab',{name:'Discover',exact:true}).click();await page.locator('[data-catalog-id="github"]').waitFor();assert.equal(await page.getByRole('article').count(),7);
 const catalog=unwrap(await page.evaluate(()=>window.zq.connectors.catalog()));assert.equal(catalog.length,7);assert.deepEqual(unwrap(await page.evaluate(()=>window.zq.connectors.list())),[]);
 await page.getByRole('button',{name:'Set up Gmail',exact:true}).click();assert.match(await page.getByRole('dialog').innerText(),/Personal Google account/);assert.match(await page.getByRole('dialog').innerText(),/127.0.0.1:43187\/oauth\/callback/);assert.equal(await page.getByRole('button',{name:'Save and connect',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Add and connect arXiv',exact:true}).click();await page.getByRole('button',{name:'Manage arXiv',exact:true}).waitFor();await page.getByRole('button',{name:'Manage arXiv',exact:true}).click();await page.getByRole('button',{name:'Choose tools',exact:true}).click();
 const search=page.getByRole('checkbox',{name:'Enable Search arXiv papers'});await search.waitFor();assert.equal(await search.isChecked(),false);await page.getByRole('button',{name:'Select all',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('[role=dialog] [role=checkbox]')].every(e=>e.getAttribute('aria-checked')==='true'));await page.getByRole('button',{name:'Clear all',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('[role=dialog] [role=checkbox]')].every(e=>e.getAttribute('aria-checked')==='false'));await search.check();await page.getByRole('button',{name:'Done',exact:true}).click();const row=unwrap(await page.evaluate(()=>window.zq.connectors.list()))[0];assert.equal(row.status,'connected');assert.equal(row.tools.filter(tool=>tool.enabled).length,1);
 await page.getByRole('tab',{name:'Discover',exact:true}).click();assert.match(await page.locator('[data-catalog-id="arxiv"]').innerText(),/Connected/);await page.screenshot({path:path.join(output,'catalog-packaged.png'),fullPage:true});
 await page.locator('[data-catalog-id="arxiv"]').click({button:'right'});await page.getByRole('menuitem',{name:'Manage connector…',exact:true}).waitFor();await page.keyboard.press('Escape');assert.deepEqual(errors,[]);
 console.log('PASS packaged catalog: seven native presets, personal Google setup, no automatic login, real bundled arXiv MCP, disabled tools, selection, installed state, context menu. Profile: '+directory);
})().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{if(page&&!page.isClosed())await page.evaluate(async()=>{const result=await window.zq.connectors.list();for(const row of result.value??[])await window.zq.connectors.remove(row.id)}).catch(()=>{});await app?.close()});
