// Browser-only fixture; all connector mutations live in this isolated page's memory.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require('playwright-core');const catalog=require('../electron/mcp/catalog.cjs').getCatalog();
(async()=>{const {build}=await import('vite'),{default:react}=await import('@vitejs/plugin-react'),{default:tailwind}=await import('@tailwindcss/vite');const root=path.resolve('.local-data/connector-tools-browser');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'index.html'),'<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>');fs.writeFileSync(path.join(root,'main.tsx'),"import '../../apps/desktop/tests/fixtures/connectors'");await build({root,configFile:false,logLevel:'error',plugins:[react(),tailwind()],resolve:{dedupe:['react','react-dom','radix-ui']}});const dist=path.join(root,'dist'),server=http.createServer((req,res)=>{const file=path.join(dist,new URL(req.url,'http://localhost').pathname),target=file===dist+'/'?path.join(dist,'index.html'):file;if(!target.startsWith(dist)||!fs.existsSync(target)){res.writeHead(404).end();return}res.setHeader('Content-Type',/\.js$/.test(target)?'text/javascript':/\.css$/.test(target)?'text/css':'text/html');fs.createReadStream(target).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1050,height:1000},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(3000);await page.addInitScript({content:`window.catalog=${JSON.stringify(catalog)}`});await page.goto(`http://127.0.0.1:${server.address().port}`);const button=name=>page.getByRole('button',{name,exact:true}),menu=name=>page.getByRole('menuitem',{name,exact:true}),card=id=>page.locator(`[data-catalog-id="${id}"]`),discover=()=>page.getByRole('tab',{name:'Discover',exact:true}).click();

await page.evaluate(()=>window.seedTools());await button('Manage tools').click();const dialog=page.getByRole('dialog',{name:'Gmail tools'}),search=page.getByRole('textbox',{name:'Search connector tools'});await dialog.waitFor();assert.equal(await dialog.locator('.connector-tool-row').count(),9);assert.equal(await dialog.getByText('1 of 9 selected',{exact:true}).isVisible(),true);assert.equal(await dialog.locator('.connector-tool-details').count(),0);
await button('Select all').click();await page.waitForFunction(()=>window.connectors[0].tools.every(t=>t.enabled));assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='setTools').length),1);assert.equal(await button('Select all').isDisabled(),true);
await search.fill('draft');await button('Clear results').click();await page.waitForFunction(()=>window.connectors[0].tools.filter(t=>t.enabled).length===7);assert.equal(await dialog.locator('.connector-tool-row').count(),2);assert.equal(await button('Clear results').isDisabled(),true);await button('Select results').click();await page.waitForFunction(()=>window.connectors[0].tools.every(t=>t.enabled));await search.fill('');await button('Clear all').click();await page.waitForFunction(()=>window.connectors[0].tools.every(t=>!t.enabled));
const detail=button('Details for Create draft');await detail.focus();await page.keyboard.press('Enter');assert.equal(await detail.getAttribute('aria-expanded'),'true');assert.equal(await page.getByRole('checkbox',{name:'Enable create_draft',exact:true}).isChecked(),false);await page.keyboard.press('Space');assert.equal(await detail.getAttribute('aria-expanded'),'false');await dialog.getByText('Create draft',{exact:true}).click({button:'right'});await menu('Copy tool name').click();assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='copy').at(-1)[1]),'create_draft');
await page.evaluate(()=>window.failTools=true);await button('Select all').click();await page.getByRole('alert').getByText('Could not save tool selection.',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.connectors[0].tools.some(t=>t.enabled)),false);
await page.evaluate(()=>{window.failTools=false;window.holdTools=true});await button('Select all').click();await page.waitForFunction(()=>!!window.finishTools);assert.equal(await button('Done').isDisabled(),true);assert.equal(await page.getByRole('checkbox',{name:'Enable create_draft',exact:true}).isDisabled(),true);await page.keyboard.press('Escape');assert.equal(await dialog.isVisible(),true);await page.evaluate(()=>{window.holdTools=false;window.finishTools()});await page.waitForFunction(()=>window.connectors[0].tools.every(t=>t.enabled));await button('Clear all').click();await page.waitForFunction(()=>window.connectors[0].tools.every(t=>!t.enabled));await page.getByRole('checkbox',{name:'Enable search_threads',exact:true}).check();
await page.screenshot({path:path.join(root,'tools-light.png')});await page.evaluate(()=>document.documentElement.dataset.theme='dark');await page.screenshot({path:path.join(root,'tools-dark.png')});await page.setViewportSize({width:420,height:600});const footer=await button('Done').boundingBox();assert.ok(footer.y>=0&&footer.y+footer.height<=600);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(root,'tools-narrow.png')});await search.fill('no matching tool');await dialog.getByText('No matching tools.',{exact:true}).waitFor();assert.equal(await button('Select results').isDisabled(),true);await search.fill('');await button('Done').click();await dialog.waitFor({state:'detached'});await page.waitForFunction(()=>document.activeElement?.textContent==='Manage tools');
assert.deepEqual(errors,[]);console.log('PASS compact tool picker: atomic bulk changes, filtered selection preserves hidden tools, keyboard details, context copy, failure preservation, pending lock, responsive footer and focus restoration.');
}finally{await browser?.close();await new Promise(r=>server.close(r))}})().catch(error=>{console.error(error);process.exitCode=1});
