const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path')
const {GitHubBoard}=require('../electron/github/board.cjs'),{GitHubClient}=require('../electron/github/client.cjs')
const row=(number=1,patch={})=>({number,title:'Fix navigation',author:{login:'me'},state:'OPEN',headRefOid:'abc123',isDraft:false,updatedAt:'2026-09-18T00:00:00Z',reviewDecision:'REVIEW_REQUIRED',reviewRequests:[{login:'me'}],statusCheckRollup:[{status:'COMPLETED',conclusion:'SUCCESS'}],...patch})
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-pr-')),state={rows:[row()],truncated:false,missing:row(1,{state:'MERGED'}),issueRows:[],issueMissing:row(2,{state:'CLOSED'}),events:[],sessions:[],calls:[],urls:[]};t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const client={login:async()=>{if(state.authError)throw Error('Sign in');return'me'},discover:async()=>({repositories:['owner/repo'],login:'me'}),pulls:async repo=>{if(state.error||repo==='owner/fails')throw Error('Offline');return{rows:state.rows,truncated:state.truncated}},issues:async()=>{if(state.issueError)throw Error('Issues offline');return{rows:state.issueRows,truncated:!!state.issuesTruncated}},issue:async()=>{if(state.issueMissingError)throw Error('Unavailable');return state.issueMissing},pull:async()=>{if(state.missingError)throw Error('Unavailable');return state.missing}}
 const code=async(method,input)=>{state.calls.push({method,input});if(method==='snapshot'&&state.contextError)throw Error('Offline');if(method==='snapshot')return{projects:[{id:'p',hostId:'local',name:'Project',cwd:directory}],profiles:[{id:'c',hostId:'local',name:'claude',adapter:'claude'},{id:'x',hostId:'local',name:'codex-gmail',adapter:'codex'}],sessions:state.sessions};if(method==='events')return{events:state.events};if(method==='openNativeSession'){if(state.openWait)await state.openWait;const s={id:'s'+state.sessions.length,state:'ready',revision:1};state.sessions.push(s);return s}if(method==='resumeSession'){const session=state.sessions.find(s=>s.id===input.id);assert.equal(input.expectedRevision,session.revision);session.state='ready';session.revision++;return session}if(method==='stopSession'){if(state.stopError)throw Error(state.stopError);const session=state.sessions.find(s=>s.id===input.id);assert.equal(input.expectedRevision,session.revision);if(!state.stopUnconfirmed){session.state='stopped';session.revision++}return session}if(method==='sendMessage'){if(state.sendError)throw Error('Disconnected after dispatch');state.events.push({seq:state.events.length+1,kind:'user',text:input.text});state.sessions.at(-1).state='busy';return{}}throw Error('unexpected '+method)}
 const make=()=>new GitHubBoard({directory,client,code,openExternal:async u=>state.urls.push(u)});return{directory,state,client,make,board:make()}}
async function ready(f,repositories=['owner/repo']){await f.board.configure({repositories});return f.board.refresh()}
const assign={id:'owner/repo#1',agent:'codex',profileId:'x',projectId:'p'}
test('GitHub discovery and sync requests are read-only, explicit-host, bounded and shell-free',async()=>{const calls=[];const client=new GitHubClient({run:async args=>{calls.push(args);if(args.at(-1)==='user')return{login:'me'};if(args.includes('api'))return[{full_name:'owner/repo'},{full_name:'owner/archive',archived:true}];return Array.from({length:201},(_,n)=>row(n+1))}});assert.deepEqual((await client.discover()).repositories,['owner/repo']);assert.equal((await client.pulls('owner/repo')).truncated,true);await client.pull('owner/repo',1);assert(calls.every(a=>a[0]==='api'?a.includes('GET'):['list','view'].includes(a[1])));assert(calls.filter(a=>a[0]==='pr').every(a=>a.includes('https://github.com/owner/repo')));await assert.rejects(client.pulls('owner/repo; touch /tmp/no'))})
test('refresh persists unique cards and local columns without GitHub mutations',async t=>{const f=fixture(t);let s=await ready(f);assert.equal(s.cards.length,1);assert.equal(s.cards[0].requested,true);assert.equal(s.cards[0].checks,'passing');await f.board.move({id:assign.id,stage:'Ready to merge'});s=await f.board.refresh();assert.equal(s.cards.length,1);assert.equal(s.cards[0].stage,'Ready to merge');s=await f.make().snapshot();assert.equal(s.cards[0].stage,'Ready to merge');assert.equal(fs.statSync(f.board.file).mode&0o777,0o600);await f.board.invoke('open',{id:assign.id});assert.deepEqual(f.state.urls,['https://github.com/owner/repo/pull/1']);assert(f.state.calls.every(c=>c.method==='snapshot'))})
test('new head invalidates ready-to-merge; verified closure preserves review history',async t=>{const f=fixture(t);await ready(f);f.board.state.cards[0].runs=[{id:'old',state:'complete',report:'Saved report',head:'abc123'}];await f.board.move({id:assign.id,stage:'Ready to merge'});f.state.rows=[row(1,{headRefOid:'newhead',statusCheckRollup:[{state:'FAILURE'}]})];let s=await f.board.refresh();assert.equal(s.cards[0].stage,'Needs review');assert.equal(s.cards[0].checks,'failing');f.state.rows=[];s=await f.board.refresh();assert.equal(s.cards[0].state,'MERGED');assert.equal(s.cards[0].stage,'Ready to merge');assert.equal(s.cards[0].runs[0].report,'Saved report');await assert.rejects(f.board.assign(assign),/Refresh/);await f.board.configure({repositories:[]});s=await f.board.configure({repositories:['owner/repo']});assert.equal(s.cards[0].runs[0].report,'Saved report')})
test('auth, partial repository failures and truncated lists preserve last known cards',async t=>{const f=fixture(t);await ready(f,['owner/repo','owner/fails']);f.state.authError=true;let s=await f.board.refresh();assert.equal(s.cards.length,1);assert.equal(s.repositories[0].error,'Sign in');await assert.rejects(f.board.assign(assign),/Refresh/);f.state.authError=false;f.state.rows=[];f.state.truncated=true;s=await f.board.refresh();assert.equal(s.cards[0].state,'OPEN');assert.equal(s.cards[0].stale,true);assert.equal(s.repositories[1].error,'Offline');f.state.truncated=false;f.state.missingError=true;s=await f.board.refresh();assert.equal(s.cards[0].stale,true);await assert.rejects(f.board.assign(assign),/Refresh/)})
test('review assignment is once-only, uses selected profile and preserves native session on restart',async t=>{const f=fixture(t);await ready(f);let release;f.state.openWait=new Promise(r=>release=r);const pending=f.board.assign(assign);await new Promise(r=>setImmediate(r));await assert.rejects(f.board.assign(assign),/already active/);release();let s=await pending;const run=s.cards[0].runs[0];assert.equal(run.state,'running');assert.equal(run.sessionId,'s0');const call=f.state.calls.find(c=>c.method==='openNativeSession');assert.equal(call.input.profileId,'x');assert.equal(call.input.agent,'codex');assert.equal(call.input.mode,'chat');assert(f.state.events[0].text.includes('do not modify files'));assert(f.state.events[0].text.includes('--repo owner/repo'));f.state.events.push({seq:2,kind:'assistant',text:'I will inspect the diff.'});f.state.sessions[0].state='ready';s=await f.board.snapshot();assert.equal(s.cards[0].runs[0].state,'running','ready alone must not make commentary a complete report');f.state.events.push({seq:3,kind:'assistant',text:'## Findings\nNo blockers.'},{seq:4,kind:'status',text:'Turn complete'});s=await f.make().snapshot();assert.equal(s.cards[0].runs[0].state,'complete');assert.equal(s.cards[0].stage,'Needs your input');assert.match(s.cards[0].runs[0].report,/No blockers/);assert.equal(f.state.calls.filter(c=>c.method==='sendMessage').length,1)})
test('uncertain dispatch is never replayed automatically; permissions, completion and partial reports survive refresh',async t=>{const f=fixture(t);await ready(f);f.state.sendError=true;let s=await f.board.assign(assign);assert.equal(s.cards[0].runs[0].state,'uncertain');s=await f.make().snapshot();assert.equal(s.cards[0].runs[0].state,'uncertain');await assert.rejects(f.board.assign(assign),/already active/);assert.equal(f.state.calls.filter(c=>c.method==='sendMessage').length,1);const r=f.board.state.cards[0].runs[0];f.state.events=[{seq:1,kind:'user',text:r.marker},{seq:2,kind:'permission',requestId:'ask',text:'Read diff?'}];f.state.sessions[0].state='approval';s=await f.board.snapshot();assert.equal(s.cards[0].runs[0].state,'needs_input');await assert.rejects(f.board.endTracking({id:assign.id}),/Stop or finish/);f.state.events.push({seq:3,kind:'status',requestId:'ask',resolved:true,text:'Permission request cancelled'},{seq:4,kind:'assistant',text:'Partial findings'});f.state.sessions[0].state='busy';s=await f.board.refresh();assert.equal(s.cards[0].runs[0].state,'running');assert.equal(s.cards[0].runs[0].error,undefined);f.state.events.push({seq:5,kind:'status',text:'Interrupted'});f.state.sessions[0].state='ready';s=await f.make().snapshot();assert.equal(s.cards[0].runs[0].state,'failed');assert.equal(s.cards[0].runs[0].report,'Partial findings')})
test('interrupted setup remains visible and can be explicitly ended without deleting history',async t=>{const f=fixture(t);await ready(f);f.board.state.cards[0].runs.push({id:'r',state:'starting',head:'abc123',report:''});f.board.save();f.board=f.make();let s=await f.board.snapshot();assert.equal(s.cards[0].runs[0].state,'uncertain');s=await f.board.endTracking({id:assign.id});assert.equal(s.cards[0].runs[0].state,'failed');assert.match(s.cards[0].runs[0].error,/preserved/)})
test('rejects untrusted methods and invalid selection, and never trusts cached external URLs',async t=>{const f=fixture(t);await ready(f);await assert.rejects(f.board.configure({repositories:['$(touch nope)/x']}));await assert.rejects(f.board.invoke('merge',{id:assign.id}));await assert.rejects(f.board.move({id:assign.id,stage:'MERGED'}));f.board.state.cards[0].url='file:///etc/passwd';await f.board.invoke('open',{id:assign.id});assert.equal(f.state.urls[0],'https://github.com/owner/repo/pull/1')})
test('Code tasks share workflow and agent runs with PRs, and persist separately from the main Tasks workspace',async t=>{
 const f=fixture(t);await ready(f);let s=await f.board.invoke('saveTask',{title:'Audit terminal performance',description:'Inspect scrolling and report findings. Do not edit files.',category:'Performance',stage:'Backlog'});const task=s.tasks[0];assert.equal(task.source,'task');assert.equal(s.cards.length,1)
 s=await f.board.move({id:task.id,stage:'Needs review'});assert.equal(s.tasks[0].stage,'Needs review');assert.equal(s.cards[0].stage,'Needs review')
 s=await f.board.assign({...assign,id:task.id});assert.equal(s.tasks[0].runs[0].state,'running');assert.match(f.state.events[0].text,/Task: Audit terminal performance/);assert.match(f.state.events[0].text,/Inspect scrolling/)
 await assert.rejects(f.board.deleteTask({id:task.id}),/Finish/);await assert.rejects(f.board.saveTask({...task,title:'Changed'}));f.state.events.push({seq:2,kind:'assistant',text:'Performance report'},{seq:3,kind:'status',text:'Turn complete'});f.state.sessions[0].state='ready';s=await f.make().snapshot();assert.equal(s.tasks[0].runs[0].report,'Performance report');assert.equal(s.tasks[0].stage,'Needs your input')
 f.board=f.make();s=await f.board.saveTask({id:task.id,title:'Review performance report',description:'Follow up',category:'General',stage:'Ready to merge'});assert.equal(s.tasks[0].runs[0].report,'Performance report');assert.equal(s.tasks[0].category,'General');await f.board.deleteTask({id:task.id});s=await f.make().snapshot();assert.equal(s.tasks.length,0);assert.equal(s.cards.length,1);assert.equal(f.state.sessions.length,1)
})
test('Code task validation reserves the Open PRs category for GitHub and retains old PR-only stores',async t=>{
 const f=fixture(t);await ready(f);await assert.rejects(f.board.saveTask({title:'x',description:'',category:'Open PRs',stage:'Backlog'}));assert.deepEqual((await f.make().snapshot()).tasks,[]);await assert.rejects(f.board.deleteTask({id:assign.id}),/cannot be deleted/)
})

test('bulk repository selection persists and refreshes with bounded concurrency',async t=>{
 const f=fixture(t),repositories=Array.from({length:130},(_,i)=>`owner/repo-${i}`);let active=0,peak=0;
 f.client.pulls=async()=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,2));active--;return {rows:[row()],truncated:false}};
 await f.board.configure({repositories:[...repositories,'OWNER/REPO-0']});
 assert.equal((await f.make().snapshot()).repositories.length,130);
 const data=await f.board.refresh();assert.equal(data.cards.length,130);assert.equal(new Set(data.cards.map(c=>c.id)).size,130);assert(peak>1&&peak<=4);assert(data.repositories.every(r=>r.checkedAt&&!r.error));
 await assert.rejects(f.board.configure({repositories:Array.from({length:1001},(_,i)=>`owner/limit-${i}`)}),/1,000/);
});

test('cached merged and closed cards recover to Done without losing reports, even offline',async t=>{
 const f=fixture(t);await ready(f);const c=f.board.state.cards[0];Object.assign(c,{state:'MERGED',stage:'Needs your input',runs:[{id:'r',state:'complete',report:'Original findings',sessionId:'saved'}]});f.board.save();f.state.authError=true;
 const s=await f.make().refresh();assert.equal(s.cards[0].stage,'Ready to merge');assert.equal(s.cards[0].runs[0].report,'Original findings');assert.equal(s.cards[0].runs[0].sessionId,'saved');
})
test('end session stops only the linked agent with a revision guard and retains the report after restart',async t=>{
 const f=fixture(t);await ready(f);await f.board.assign(assign);f.state.events.push({seq:2,kind:'assistant',text:'Saved findings'},{seq:3,kind:'status',text:'Turn complete'});f.state.sessions[0].state='ready';f.state.sessions.push({id:'other',state:'busy',revision:1});let s=await f.board.snapshot();const r=s.cards[0].runs[0];
 f.state.rows=[];s=await f.board.refresh();assert.equal(s.cards[0].stage,'Ready to merge');
 s=await f.board.invoke('endSession',{id:assign.id,runId:r.id});assert.equal(s.cards[0].runs[0].sessionState,'stopped');assert.equal(s.cards[0].runs[0].state,'complete');assert(s.cards[0].runs[0].endedAt);assert.equal(f.state.sessions[1].state,'busy');assert.deepEqual(f.state.calls.find(c=>c.method==='stopSession').input,{id:r.sessionId,expectedRevision:1});
 s=await f.make().snapshot();assert.equal(s.cards[0].runs[0].report,'Saved findings');assert.equal(s.cards[0].stage,'Ready to merge');await f.board.endSession({id:assign.id,runId:r.id});assert.equal(f.state.calls.filter(c=>c.method==='stopSession').length,1);
 f.state.sessions[0].state='ready';s=await f.make().snapshot();assert.equal(s.cards[0].runs[0].sessionState,'ready','resuming elsewhere restores the ability to end it');
})
test('end session rejects missing runs, busy agents, unavailable context and unconfirmed stops',async t=>{
 const f=fixture(t);await ready(f);const s=await f.board.assign(assign),r=s.cards[0].runs[0],input={id:assign.id,runId:r.id};await assert.rejects(f.board.endSession({...input,runId:'wrong'}),/no linked/);await assert.rejects(f.board.endSession(input),/still working/);f.state.sessions[0].state='ready';f.state.contextError=true;await assert.rejects(f.board.endSession(input),/Code is unavailable/);f.state.contextError=false;f.state.stopError='STALE_REVISION';await assert.rejects(f.board.endSession(input),/STALE_REVISION/);delete f.state.stopError;f.state.stopUnconfirmed=true;await assert.rejects(f.board.endSession(input),/confirmed stopped/);assert.equal(f.board.state.cards[0].runs[0].endedAt,undefined);
})
test('issues share the workflow, keep identities separate and require human review before a fix',async t=>{
 const f=fixture(t);f.state.issueRows=[row(1,{labels:[{name:'bug'}],assignees:[{login:'me'}]})];let s=await ready(f);assert.equal(s.issues.length,1);assert.notEqual(s.issues[0].id,s.cards[0].id);assert.equal(s.issues[0].url,'https://github.com/owner/repo/issues/1');assert.deepEqual(s.issues[0].labels,['bug']);
 const id=s.issues[0].id;s=await f.board.assign({...assign,id});assert.match(f.state.events[0].text,/Investigate GitHub issue/);assert.match(f.state.events[0].text,/reproduce/);assert.match(f.state.events[0].text,/Stop for human review before implementing/);assert.match(f.state.events[0].text,/Do not commit, push/);
 f.state.events.push({seq:2,kind:'assistant',text:'Reproduced in an isolated fixture. Suggested fix: restore focus.'},{seq:3,kind:'status',text:'Turn complete'});f.state.sessions[0].state='ready';s=await f.make().snapshot();assert.equal(s.issues[0].stage,'Needs your input');assert.equal(s.issues[0].runs[0].state,'complete');assert.equal(s.cards[0].runs.length,0);
 f.state.issueRows=[];f.state.issueMissing=row(1,{state:'CLOSED'});s=await f.board.refresh();assert.equal(s.issues[0].state,'CLOSED');assert.equal(s.issues[0].stage,'Ready to merge');assert.match(s.issues[0].runs[0].report,/Suggested fix/);await assert.rejects(f.board.assign({...assign,id}),/Refresh/);
 await f.board.invoke('open',{id});assert.equal(f.state.urls[0],'https://github.com/owner/repo/issues/1');
 f.state.issueRows=[row(1)];s=await f.board.refresh();assert.equal(s.issues[0].stage,'Needs review','reopened issue returns to To do');assert.equal(s.issues[0].runs.length,1);
})
test('issue read failures and truncation preserve cached work independently of PR sync',async t=>{
 const f=fixture(t);f.state.issueRows=[row(2)];await ready(f);f.state.issueRows=[];f.state.issuesTruncated=true;let s=await f.board.refresh();assert.equal(s.issues[0].state,'OPEN');assert(s.issues[0].stale);assert.equal(s.repositories[0].issuesTruncated,true);await assert.rejects(f.board.assign({...assign,id:s.issues[0].id}),/Refresh/);
 f.state.issuesTruncated=false;f.state.issueMissingError=true;s=await f.board.refresh();assert(s.issues[0].stale);f.state.issueError=true;s=await f.board.refresh();assert.equal(s.repositories[0].issuesError,'Issues offline');assert.equal(s.repositories[0].error,undefined);assert.equal(s.cards.length,1);assert.equal(s.issues.length,1);await f.board.configure({repositories:[]});assert.equal((await f.make().snapshot()).issues.length,1);
 await assert.rejects(f.board.saveTask({title:'x',description:'',category:'Issues',stage:'Backlog'}));
})
test('issue CLI reads use explicit repositories and bounded structured output',async()=>{
 const calls=[],client=new GitHubClient({run:async args=>{calls.push(args);return args[1]==='list'?Array.from({length:201},(_,i)=>row(i+1)):row(1)}});const result=await client.issues('owner/repo');assert.equal(result.rows.length,200);assert(result.truncated);await client.issue('owner/repo',1);assert(calls.every(a=>a[0]==='issue'&&['list','view'].includes(a[1])&&a.includes('https://github.com/owner/repo')));assert(calls[0].includes('number,title,author,state,updatedAt,assignees,labels,stateReason'));await assert.rejects(client.issues('x/y;echo bad'));await assert.rejects(client.issue('owner/repo',-1));
})

test('disabled Issues are a setting, preserve cached reports, and recover when re-enabled',async t=>{
 const f=fixture(t);f.state.issueRows=[row(2)];await ready(f);f.board.state.issues[0].runs=[{id:'r',state:'complete',report:'Saved issue report'}];f.board.state.repositories[0].issuesError='Old generic error';f.client.issues=async()=>({rows:[],truncated:false,disabled:true});let s=await f.board.refresh();assert.equal(s.repositories[0].issuesDisabled,true);assert.equal(s.repositories[0].issuesError,undefined);assert(s.repositories[0].issuesCheckedAt);assert.equal(s.issues[0].state,'OPEN');assert(s.issues[0].stale);assert.equal(s.issues[0].runs[0].report,'Saved issue report');assert.equal(s.cards.length,1);await assert.rejects(f.board.assign({...assign,id:s.issues[0].id}),/Refresh/);
 f.client.issues=async()=>({rows:[row(2)],truncated:false,disabled:false});s=await f.board.refresh();assert.equal(s.repositories[0].issuesDisabled,false);assert.equal(s.issues[0].stale,false);assert.equal(s.issues[0].runs[0].report,'Saved issue report');
})
test('CLI distinguishes disabled issues from auth, rate-limit and network failures',async()=>{
 const {classifyFailure}=require('../electron/github/client.cjs');const disabled=classifyFailure({stderr:"the 'owner/fork' repository has disabled issues"});assert.equal(disabled.code,'GITHUB_ISSUES_DISABLED');const client=new GitHubClient({run:async()=>{throw disabled}});assert.deepEqual(await client.issues('owner/fork'),{rows:[],truncated:false,disabled:true});
 for(const [stderr,pattern] of [['HTTP 401: authentication required',/login/],['API rate limit exceeded',/limiting/],['connect: network unreachable',/connection/]]){const error=classifyFailure({stderr});assert.equal(error.code,/rate limit/.test(stderr)?'GITHUB_RATE_LIMITED':'GITHUB_UNAVAILABLE');assert.match(error.message,pattern);client.run=async()=>{throw error};await assert.rejects(client.issues('owner/repo'),pattern)}
})

test('explicit issue close uses a fixed repository, validated reason and shell-free CLI arguments',async()=>{
 const calls=[],client=new GitHubClient({run:async(args,options)=>{calls.push({args,options});return ''}});
 for(const reason of ['completed','not_planned'])await client.closeIssue('owner/repo',2,reason);
 assert.deepEqual(calls.map(c=>c.args),['completed','not planned'].map(reason=>['issue','close','2','--repo','https://github.com/owner/repo','--reason',reason]));assert(calls.every(c=>c.options.json===false));
 for(const args of [['owner/repo;bad',2,'completed'],['owner/repo',-1,'completed'],['owner/repo',2,'duplicate'],['owner/repo',2,'--comment bad']])await assert.rejects(client.closeIssue(...args));assert.equal(calls.length,2);
})
async function closeFixture(t){const f=fixture(t);f.state.issueRows=[row(2)];await ready(f);f.state.currentIssue=row(2);f.state.closes=[];f.client.issue=async()=>structuredClone(f.state.currentIssue);f.client.closeIssue=async(repo,number,reason)=>{f.state.closes.push({repo,number,reason});f.state.currentIssue=row(number,{state:'CLOSED',stateReason:reason.toUpperCase()});f.state.issueRows=[]};return f}
const closeInput={id:'owner/repo#issue-2',reason:'not_planned'};
test('closing either way verifies GitHub, moves to Done and preserves report/history on restart without an agent',async t=>{
 for(const reason of ['completed','not_planned']){const f=await closeFixture(t);f.board.state.issues[0].runs=[{id:'saved',state:'complete',report:'Original report',sessionId:'native-history'}];f.board.state.issues[0].url='https://evil.invalid/issues/9';
 const s=await f.board.invoke('closeIssue',{...closeInput,reason});assert.equal(s.issues[0].state,'CLOSED');assert.equal(s.issues[0].stateReason,reason.toUpperCase());assert.equal(s.issues[0].stage,'Ready to merge');assert.equal(s.issues[0].url,'https://github.com/owner/repo/issues/2');assert.equal(s.cards[0].state,'OPEN');
 assert.deepEqual(f.state.closes,[{repo:'owner/repo',number:2,reason}]);const restored=await f.make().snapshot();assert.equal(restored.issues[0].runs[0].report,'Original report');assert.equal(restored.issues[0].runs[0].sessionId,'native-history');assert(f.state.calls.every(c=>c.method==='snapshot'));
 await f.board.closeIssue({...closeInput,reason});assert.equal(f.state.closes.length,1,'already closed is idempotent');}
})
test('close rejects non-issues and invalid reasons; local Done never closes GitHub',async t=>{
 const f=await closeFixture(t);await f.board.move({id:closeInput.id,stage:'Ready to merge'});assert.equal(f.state.closes.length,0);assert.equal(f.board.state.issues[0].state,'OPEN');
 await assert.rejects(f.board.closeIssue({...closeInput,id:assign.id}),/Only GitHub issues/);await assert.rejects(f.board.closeIssue({...closeInput,reason:'invalid'}),/Completed or Not planned/);
 const tasks=await f.board.saveTask({title:'Local',description:'',category:'General',stage:'Backlog'});await assert.rejects(f.board.closeIssue({...closeInput,id:tasks.tasks[0].id}),/Only GitHub issues/);assert.equal(f.state.closes.length,0);
})
test('close preserves local state on denied or unconfirmed writes and never automatically retries',async t=>{
 const f=await closeFixture(t);let writes=0;f.client.closeIssue=async()=>{writes++;throw Error('GitHub denied the close request.')};await assert.rejects(f.board.closeIssue(closeInput),/denied/);assert.equal(writes,1);assert.equal(f.board.state.issues[0].state,'OPEN');assert.equal(f.board.state.issues[0].stage,'Needs review');
 f.client.closeIssue=async()=>{writes++;f.client.issue=async()=>{throw Error('offline')}};await assert.rejects(f.board.closeIssue(closeInput),/could not be confirmed/);assert.equal(writes,2);assert.equal(f.board.state.issues[0].state,'OPEN');
 f.client.issue=async()=>row(99);await assert.rejects(f.board.closeIssue(closeInput),/different issue/);assert.equal(writes,2);
})
test('a timed-out close is accepted only when a fresh read confirms closure',async t=>{
 const f=await closeFixture(t);f.client.closeIssue=async()=>{f.state.currentIssue=row(2,{state:'CLOSED',stateReason:'NOT_PLANNED'});throw Error('Timed out')};const s=await f.board.closeIssue(closeInput);assert.equal(s.issues[0].state,'CLOSED');assert.equal(s.issues[0].stage,'Ready to merge');
})
test('close waits for older refreshes, rejects duplicate submission and lets later refreshes see the closure',async t=>{
 const f=await closeFixture(t);let releaseRead,releaseWrite;const waitRead=new Promise(r=>releaseRead=r),waitWrite=new Promise(r=>releaseWrite=r);let reads=0;f.client.issues=async()=>{if(reads++===0)await waitRead;return{rows:f.state.issueRows,truncated:false}};
 const originalClose=f.client.closeIssue;f.client.closeIssue=async(...args)=>{await waitWrite;return originalClose(...args)};
 const older=f.board.refresh();await new Promise(r=>setImmediate(r));const close=f.board.closeIssue(closeInput);await assert.rejects(f.board.closeIssue(closeInput),/Wait for/);const later=f.board.refresh();releaseRead();await older;assert.equal(f.state.closes.length,0);releaseWrite();await close;const s=await later;assert.equal(s.issues[0].state,'CLOSED');assert.equal(s.issues[0].stage,'Ready to merge');assert.equal(f.state.closes.length,1);
})

const limited=()=>Object.assign(Error('Rate limited'),{code:'GITHUB_RATE_LIMITED'});
test('automatic sync is cached across navigation/restart and scales its interval with selected repos',async t=>{
 const f=fixture(t);let reads=0;f.client.pulls=async()=>{reads++;return{rows:[row()],truncated:false}};await ready(f);await f.board.invoke('refresh',{automatic:true});await f.make().invoke('refresh',{automatic:true});assert.equal(reads,1);
 await f.board.invoke('refresh',undefined);assert.equal(reads,2,'manual refresh remains available outside cooldown');
 const repos=Array.from({length:130},(_,i)=>`owner/repo-${i}`);await f.board.configure({repositories:repos});await f.board.invoke('refresh',{automatic:true});assert.equal(reads,132);assert(f.board.state.nextRefreshAt>Date.now()+14*60000);
 await assert.rejects(f.board.invoke('refresh',{automatic:'yes'}));
})
test('rate limits stop the queued sweep, persist reset time and block retries after restart',async t=>{
 const f=fixture(t);await ready(f);f.board.state.cards[0].runs=[{id:'saved',state:'complete',report:'Keep me'}];let reads=0,status=0;const reset=Math.floor(Date.now()/1000)+1800;
 f.client.pulls=async()=>{reads++;throw limited()};f.client.rateLimit=async()=>{status++;return{resources:{graphql:{remaining:0,reset}}}};
 await f.board.configure({repositories:Array.from({length:130},(_,i)=>`owner/repo-${i}`)});let s=await f.board.refresh();assert(reads<=4);assert.equal(status,1);assert(s.retryAt>=reset*1000);assert.equal(s.cards[0].runs[0].report,'Keep me');assert(s.repositories.every(r=>!r.error&&!r.issuesError),'one global pause instead of 260 source errors');
 const count=reads;f.board=f.make();await f.board.refresh();await f.board.invoke('refresh',{automatic:true});await assert.rejects(f.board.invoke('discover'),/Sync is paused/);assert.equal(reads,count);
 f.board.state.retryAt=Date.now()-1;f.board.state.nextRefreshAt=0;f.client.pulls=async()=>({rows:[],truncated:false});s=await f.board.refresh();assert.equal(s.retryAt,undefined);assert.equal(s.rateLimitFailures,0);
})
test('secondary limits back off exponentially when remaining budget is nonzero or unavailable',async t=>{
 const f=fixture(t);await ready(f);f.client.login=async()=>{throw limited()};f.client.rateLimit=async()=>({resources:{graphql:{remaining:5000,reset:Math.floor(Date.now()/1000)+3600}}});let s=await f.board.refresh();assert(s.retryAt>Date.now()+59000&&s.retryAt<Date.now()+61000);
 f.board.state.retryAt=0;s=await f.board.refresh();assert(s.retryAt>Date.now()+119000);assert.equal(s.rateLimitFailures,2);
})
test('rate limit during missing-item verification preserves all cached cards and stops further lookups',async t=>{
 const f=fixture(t);f.state.rows=[row(1),row(2),row(3)];await ready(f);f.state.rows=[];let reads=0;f.client.pull=async()=>{reads++;throw limited()};const s=await f.board.refresh();assert.equal(reads,1);assert.equal(s.cards.length,3);assert(s.cards.every(c=>c.state==='OPEN'));assert(s.retryAt>Date.now());
})
test('rate-limited close stays open and never dispatches or replays a mutation',async t=>{
 const f=await closeFixture(t);f.client.issue=async()=>{throw limited()};await assert.rejects(f.board.closeIssue(closeInput),/Sync is paused/);assert.equal(f.state.closes.length,0);assert.equal(f.board.state.issues[0].state,'OPEN');await assert.rejects(f.make().closeIssue(closeInput),/Sync is paused/);assert.equal(f.state.closes.length,0);
})
test('a rate-limited write pauses before verification and is never automatically replayed',async t=>{
 const f=await closeFixture(t);let writes=0,reads=0;f.client.issue=async()=>{reads++;return row(2)};f.client.closeIssue=async()=>{writes++;throw limited()};await assert.rejects(f.board.closeIssue(closeInput),/Sync is paused/);assert.equal(writes,1);assert.equal(reads,1);await f.board.refresh();assert.equal(writes,1);assert.equal(f.board.state.issues[0].state,'OPEN');
})

async function reviewedFixture(t,issue=false){const f=fixture(t);if(issue)f.state.issueRows=[row(2)];await ready(f);const id=issue?'owner/repo#issue-2':assign.id;await f.board.assign({...assign,id});f.state.events.push({seq:2,kind:'assistant',text:'Original findings'},{seq:3,kind:'status',text:'Turn complete'});f.state.sessions[0].state='ready';f.state.sessions[0].mode='chat';await f.board.snapshot();return{...f,id,runId:f.board.find(id).runs[0].id}}
test('follow-up uses the same native session, preserves each report and returns the new turn to Human Review',async t=>{
 const f=await reviewedFixture(t,true);let s=await f.board.followUp({id:f.id,runId:f.runId,action:'implement',instructions:'Include a regression test.'});assert.equal(s.issues[0].stage,'Agent reviewing');assert.equal(s.issues[0].runs.length,2);const next=s.issues[0].runs[1];assert.equal(next.sessionId,s.issues[0].runs[0].sessionId);assert.equal(s.issues[0].runs[0].report,'Original findings');assert.equal(next.parentRunId,f.runId);assert.equal(next.action,'implement');assert.equal(next.state,'running');assert.equal(next.report,'');assert.equal(f.state.sessions.length,1);assert.match(f.state.events.at(-1).text,/Do not commit, push, publish a PR/);
 f.state.events.push({seq:5,kind:'assistant',text:'Fix implemented and verified'},{seq:6,kind:'status',text:'Turn complete'});f.state.sessions[0].state='ready';s=await f.make().snapshot();assert.equal(s.issues[0].stage,'Needs your input');assert.equal(s.issues[0].runs[1].report,'Fix implemented and verified');assert.equal(s.issues[0].runs[0].report,'Original findings');
})
test('follow-up resumes a stopped agent with a revision guard and rejects stale reports and busy turns',async t=>{
 const f=await reviewedFixture(t);await f.board.endSession({id:f.id,runId:f.runId});let s=await f.board.followUp({id:f.id,runId:f.runId,action:'changes',instructions:'Recheck the edge case.'});assert.equal(f.state.calls.filter(c=>c.method==='resumeSession').length,1);assert.equal(s.cards[0].runs.length,2);await assert.rejects(f.board.followUp({id:f.id,runId:f.runId,action:'changes',instructions:'Duplicate'}),/latest completed/);assert.equal(f.state.calls.filter(c=>c.method==='sendMessage').length,2);
 const busy=await reviewedFixture(t);busy.state.sessions[0].state='busy';await assert.rejects(busy.board.followUp({id:busy.id,runId:busy.runId,action:'changes',instructions:'More'}),/still working/);assert.equal(busy.board.find(busy.id).runs.length,1);
})
test('uncertain follow-up never replays on restart and does not overwrite the prior report',async t=>{
 const f=await reviewedFixture(t);f.state.sendError=true;let s=await f.board.followUp({id:f.id,runId:f.runId,action:'changes',instructions:'More evidence'});assert.equal(s.cards[0].runs[1].state,'uncertain');s=await f.make().snapshot();assert.equal(s.cards[0].runs[0].report,'Original findings');assert.equal(s.cards[0].runs[1].state,'uncertain');assert.equal(f.state.calls.filter(c=>c.method==='sendMessage').length,2);
})
test('PR merge sends an exact head guard and only marks Done after confirmed success',async t=>{
 const f=await reviewedFixture(t);f.client.pull=async()=>row(1,{mergeable:'MERGEABLE',mergeStateStatus:'CLEAN'});const calls=[];f.client.mergePull=async(...args)=>{calls.push(args);return{merged:true,sha:'def456'}};const preview=await f.board.prepareMerge({id:f.id,runId:f.runId});assert.equal(preview.head,'abc123');assert.equal(calls.length,0);
 const s=await f.board.mergePR({id:f.id,runId:f.runId,head:preview.head,method:'squash'});assert.deepEqual(calls,[['owner/repo',1,'abc123','squash']]);assert.equal(s.cards[0].state,'MERGED');assert.equal(s.cards[0].stage,'Ready to merge');assert.equal(s.cards[0].runs[0].report,'Original findings');assert.equal(f.state.sessions[0].state,'ready');
})
test('merge refuses changed heads, draft/blocked/check failures and missing completed reviews before writing',async t=>{
 const f=await reviewedFixture(t);let writes=0;f.client.mergePull=async()=>{writes++;return{merged:true}};
 for(const patch of [{headRefOid:'new123'},{isDraft:true},{mergeable:'CONFLICTING'},{mergeStateStatus:'BLOCKED'},{statusCheckRollup:[{state:'FAILURE'}]},{statusCheckRollup:[{state:'PENDING'}]},{reviewDecision:'CHANGES_REQUESTED'}]){f.client.pull=async()=>row(1,{mergeable:'MERGEABLE',mergeStateStatus:'CLEAN',...patch});await assert.rejects(f.board.mergePR({id:f.id,runId:f.runId,head:'abc123',method:'squash'}));}
 f.client.pull=async()=>row(1,{mergeable:'MERGEABLE',mergeStateStatus:'CLEAN'});await assert.rejects(f.board.mergePR({id:f.id,runId:f.runId,head:'older1',method:'squash'}),/changed/);await assert.rejects(f.board.mergePR({id:f.id,runId:'wrong',head:'abc123',method:'squash'}),/latest completed/);assert.equal(writes,0);
})
test('merge permissions, uncertain outcomes and rate limits preserve reports without replaying',async t=>{
 const f=await reviewedFixture(t);let writes=0;f.client.pull=async()=>row(1,{mergeable:'MERGEABLE',mergeStateStatus:'CLEAN'});f.client.mergePull=async()=>{writes++;throw Error('Permission denied')};const input={id:f.id,runId:f.runId,head:'abc123',method:'merge'};await assert.rejects(f.board.mergePR(input),/Permission denied/);assert.equal(f.board.find(f.id).state,'OPEN');assert.equal(writes,1);
 f.client.mergePull=async()=>{writes++;f.client.pull=async()=>row(1,{state:'MERGED'});throw Error('Timeout')};const s=await f.board.mergePR(input);assert.equal(s.cards[0].state,'MERGED');await f.board.mergePR(input);assert.equal(writes,2);assert.equal(s.cards[0].runs[0].report,'Original findings');
})
test('PR links are verified, bidirectionally addressable and survive refresh/restart without altering GitHub',async t=>{
 const f=await reviewedFixture(t,true);f.client.pull=async()=>row(7);let s=await f.board.linkPR({id:f.id,repo:'owner/repo',number:7});assert.deepEqual(s.issues[0].linkedPRIds,['owner/repo#7']);assert.equal(s.cards.find(c=>c.number===7).state,'OPEN');await f.board.linkPR({id:f.id,repo:'owner/repo',number:7});assert.equal(f.board.find(f.id).linkedPRIds.length,1);s=await f.board.refresh();assert.deepEqual(s.issues[0].linkedPRIds,['owner/repo#7']);assert.equal((await f.make().snapshot()).issues[0].runs[0].report,'Original findings');await assert.rejects(f.board.linkPR({id:f.id,repo:'other/repo',number:7}),/Select this repository/);s=await f.board.unlinkPR({id:f.id,prId:'owner/repo#7'});assert.deepEqual(s.issues[0].linkedPRIds,[]);assert(s.cards.some(c=>c.number===7));
})
test('merge CLI uses REST with a required reviewed SHA and no admin override or branch deletion',async()=>{
 const calls=[],client=new GitHubClient({run:async(args,options)=>{calls.push({args,options});return{merged:true}}});await client.mergePull('owner/repo',7,'abc123','squash');assert.deepEqual(calls[0],{args:['api','--hostname','github.com','--method','PUT','repos/owner/repo/pulls/7/merge','-f','sha=abc123','-f','merge_method=squash'],options:{mutation:true}});await assert.rejects(client.mergePull('owner/repo',7,'','squash'));await assert.rejects(client.mergePull('owner/repo',7,'abc123','admin'));await assert.rejects(client.mergePull('owner/repo;bad',7,'abc123','squash'));assert.equal(calls.length,1);
})
