// Packaged end-to-end Gmail test. All data and API responses are isolated fixtures.
const {_electron:electron}=require('playwright-core');const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=process.cwd(),output=path.join(root,'.local-data/gmail-verification');fs.mkdirSync(output,{recursive:true});const directory=fs.mkdtempSync(path.join(output,'profile-'));let app,page,origin,authorization,apiCalls=0,opens=0,mode='search',sends=0;
const unwrap=r=>{assert.equal(r.ok,true,JSON.stringify(r.error));return r.value};
const server=http.createServer(async(req,res)=>{try{
 let text='';for await(const chunk of req)text+=chunk;const url=new URL(req.url,origin);const json=data=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(data))};
 if(url.pathname==='/.well-known/oauth-authorization-server')return json({issuer:'https://accounts.google.com',authorization_endpoint:'https://accounts.google.com/o/oauth2/v2/auth',token_endpoint:'https://oauth2.googleapis.com/token',response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['client_secret_post'],code_challenge_methods_supported:['S256'],authorization_response_iss_parameter_supported:true});
 if(url.pathname==='/authorize'){opens++;authorization=url;const callback=new URL(url.searchParams.get('redirect_uri'));callback.searchParams.set('state',url.searchParams.get('state'));callback.searchParams.set('code','fixture-code');callback.searchParams.set('iss','https://accounts.google.com');assert.equal((await fetch(callback)).status,200);return json({ok:true})}
 if(url.pathname==='/token'){const params=new URLSearchParams(text);assert.equal(params.get('client_secret'),'fixture-google-secret');assert.equal(crypto.createHash('sha256').update(params.get('code_verifier')).digest('base64url'),authorization.searchParams.get('code_challenge'));return json({access_token:'fixture-google-token',refresh_token:'fixture-refresh',token_type:'Bearer',expires_in:3600,scope:authorization.searchParams.get('scope')})}
 if(url.pathname.startsWith('/gmail/v1/')){assert.equal(req.headers.authorization,'Bearer fixture-google-token');apiCalls++;
  if(url.pathname.endsWith('/drafts/send')){assert.equal(req.method,'POST');assert.equal(JSON.parse(text).id,'draft1');sends++;return json({id:'sent1',threadId:'abc123'})}
  assert.equal(req.method,'GET');
  if(url.pathname.endsWith('/drafts/draft1'))return json({id:'draft1',message:{id:'draftMessage1',raw:Buffer.from('To: friend@example.test\r\nSubject: Poem\r\n\r\nHello friend').toString('base64url'),payload:{mimeType:'text/plain',headers:[{name:'To',value:'friend@example.test'},{name:'Subject',value:'Poem'}],body:{data:Buffer.from('Hello friend').toString('base64url')}}}});
  if(url.pathname.endsWith('/profile'))return json({emailAddress:'fixture@example.test'});
  if(url.pathname.endsWith('/threads')){assert.equal(url.searchParams.get('q'),'concert');return json({threads:[{id:'abc123'}]})}
  if(url.pathname.endsWith('/threads/abc123'))return json({id:'abc123',messages:[{id:'def456',threadId:'abc123',snippet:'Concert ticket confirmation',payload:{headers:[{name:'Subject',value:'Concert tickets'}]}}]});
 }
 if(url.pathname.startsWith('/calendar/v3/')){assert.equal(req.method,'GET');assert.equal(req.headers.authorization,'Bearer fixture-google-token');return json(url.pathname.endsWith('/events')?{timeZone:'America/Chicago',items:[{id:'event1',summary:'Fixture meeting',start:{dateTime:'2026-09-13T10:00:00-05:00'},end:{dateTime:'2026-09-13T11:00:00-05:00'}}]}:{items:[{id:'primary',timeZone:'America/Chicago'}]})}
 if(url.pathname.startsWith('/drive/v3/')){assert.equal(req.method,'GET');assert.equal(req.headers.authorization,'Bearer fixture-google-token');return json(url.pathname.endsWith('/about')?{user:{permissionId:'fixture'}}:{files:[{id:'file1',name:'Fixture registration',mimeType:'text/plain'}]})}
 if(url.pathname==='/api/show')return json({capabilities:['tools']});
 if(url.pathname==='/api/tags')return json({models:[{name:'fixture:tools',model:'fixture:tools',details:{family:'fixture'}}]});
 if(url.pathname==='/api/chat'){const body=JSON.parse(text),tool=body.tools?.find(t=>t.function.name.startsWith('mcp_'));assert.ok(tool);const after=body.messages.at(-1)?.role==='tool';const expected={search:'Concert tickets',send:'sent1',calendar:'Fixture meeting',drive:'Fixture registration'}[mode];if(after)assert.ok(body.messages.at(-1).content.includes(expected));const args={search:{query:'concert',pageSize:5},send:{draftId:'draft1'},calendar:{timeMin:'2026-09-13T00:00:00-05:00',timeMax:'2026-09-14T00:00:00-05:00'},drive:{query:'registration'}}[mode];const message=after?{content:mode==='search'?'I found a concert ticket email.':'Verified '+mode}:{content:'',tool_calls:[{function:{index:0,name:tool.function.name,arguments:args}}]};res.writeHead(200,{'content-type':'application/x-ndjson'});return res.end(JSON.stringify({message:{role:'assistant',...message},done:false})+'\n'+JSON.stringify({done:true,done_reason:'stop'})+'\n')}
 throw Error('Unexpected fixture route '+url.pathname);
}catch(error){console.error(error);res.writeHead(500);res.end()}});
async function reply(id,predicate){const end=Date.now()+20000;while(Date.now()<end){const state=unwrap(await page.evaluate(()=>window.zq.chat.load()));const last=state.conversations.find(c=>c.id===id)?.messages.at(-1);if(last?.status==='error')throw Error(last.error);if(predicate(last))return last;await new Promise(r=>setTimeout(r,50))}throw Error('Chat response timed out')}
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;
 app=await electron.launch({executablePath:process.env.ZQ_TEST_APP??path.join(root,'apps/desktop/release/mac-arm64/zQ.app/Contents/MacOS/zQ'),env:{...process.env,ZQ_DATA_DIR:directory},timeout:30000});page=await app.firstWindow();await page.waitForFunction(()=>!!window.zq);
 // Replace the network boundary only. Real native auth, Keychain, MCP, chat, and UI execute.
 await app.evaluate(({app,shell},origin)=>{
  const load=process.getBuiltinModule('module').createRequire(app.getAppPath()+'/electron/main.cjs');const {ConnectorService}=load('./mcp/service.cjs');const connect=ConnectorService.prototype.connect;
  ConnectorService.prototype.connect=function(...args){this.fetchImpl=(url,init)=>{const target=new URL(url);if(!['accounts.google.com','oauth2.googleapis.com','gmail.googleapis.com','www.googleapis.com'].includes(target.hostname))throw Error('Unexpected Google host');return fetch(origin+target.pathname+target.search,init)};return connect.apply(this,args)};
  shell.openExternal=async raw=>{const url=new URL(raw);if(url.origin+url.pathname!=='https://accounts.google.com/o/oauth2/v2/auth')throw Error('Unexpected authorization');await fetch(origin+'/authorize'+url.search)};
 },origin);
 const net=require('node:net'),listener=net.createServer();await new Promise(r=>listener.listen(0,'127.0.0.1',r));const port=listener.address().port;await new Promise(r=>listener.close(r));
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Connectors',exact:true}).click();await page.getByRole('tab',{name:'Discover',exact:true}).click();await page.getByRole('button',{name:'Set up Gmail',exact:true}).click();
 assert.match(await page.getByRole('dialog').innerText(),/standard Gmail API/);await page.locator('#connector-client').fill('fixture-google-client');await page.locator('#connector-secret').fill('fixture-google-secret');await page.locator('#connector-port').fill(String(port));await page.getByRole('button',{name:'Save and connect',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});
 assert.equal(opens,1);assert.equal(apiCalls,1);await page.getByRole('button',{name:'Manage Gmail',exact:true}).click();await page.getByRole('button',{name:'Choose tools',exact:true}).click();await page.getByRole('checkbox',{name:'Enable Search Gmail',exact:true}).check();await page.getByRole('button',{name:'Done',exact:true}).click();
 const connector=unwrap(await page.evaluate(()=>window.zq.connectors.list()))[0];assert.equal(connector.url,'https://gmail.googleapis.com/gmail/v1');
 const connection=unwrap(await page.evaluate(baseUrl=>window.zq.chat.saveConnection({provider:'ollama',name:'Fixture model',baseUrl}),origin));const conversation=unwrap(await page.evaluate(connectionId=>window.zq.chat.createConversation({connectionId,model:'fixture:tools'}),connection.id));
 unwrap(await page.evaluate(({id,connectorId})=>window.zq.chat.setConversationConnectors({conversationId:id,connectorIds:[connectorId]}),{id:conversation.id,connectorId:connector.id}));unwrap(await page.evaluate(id=>window.zq.chat.saveChatView({selected:id,projectId:null,projectHome:false,positions:{}}),conversation.id));
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Chat module',exact:true}).click();unwrap(await page.evaluate(id=>window.zq.chat.send({conversationId:id,text:'Find my concert emails'}),conversation.id));const waiting=await reply(conversation.id,r=>r?.interactions?.some(i=>i.status==='waiting'));assert.equal(apiCalls,1);const interaction=waiting.interactions.find(i=>i.status==='waiting');
 unwrap(await page.evaluate(input=>window.zq.chat.respondToInteraction(input),{conversationId:conversation.id,id:interaction.id,decision:'chat'}));const complete=await reply(conversation.id,r=>r?.status==='complete');assert.match(complete.content,/concert ticket/);assert.equal(complete.toolActivity[0].status,'complete');assert.equal(apiCalls,3);await page.getByText('I found a concert ticket email.',{exact:true}).waitFor();await page.screenshot({path:path.join(output,'chat.png')});
 unwrap(await page.evaluate(id=>window.zq.connectors.disconnect(id),connector.id));unwrap(await page.evaluate(id=>window.zq.connectors.connect(id),connector.id));assert.equal(opens,1);assert.equal(apiCalls,4);assert.equal(unwrap(await page.evaluate(()=>window.zq.connectors.list()))[0].tools.find(t=>t.name==='search_threads').enabled,true);
 mode='send';unwrap(await page.evaluate(id=>window.zq.connectors.setTools({id,names:['send_draft']}),connector.id));
 unwrap(await page.evaluate(id=>window.zq.chat.send({conversationId:id,text:'Send the draft'}),conversation.id));const sendWaiting=await reply(conversation.id,r=>r?.interactions?.some(i=>i.status==='waiting'));assert.equal(sends,0);assert.equal(sendWaiting.interactions[0].onceOnly,true);
 await page.getByRole('button',{name:'Send email',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Allow for this chat',exact:true}).count(),0);await page.getByText('To: friend@example.test',{exact:false}).waitFor();await page.screenshot({path:path.join(output,'send-approval.png')});await page.getByRole('button',{name:'Send email',exact:true}).click();await reply(conversation.id,r=>r?.status==='complete');assert.equal(sends,1);
 for(const [catalogId,toolName,nextMode]of [['google-calendar','list_events','calendar'],['google-drive','search_files','drive']]){
  mode=nextMode;const entries=unwrap(await page.evaluate(()=>window.zq.connectors.catalog()));const entry=entries.find(e=>e.id===catalogId);const saved=unwrap(await page.evaluate(({entry,port})=>window.zq.connectors.save({name:entry.name,catalogId:entry.id,url:entry.url,authType:'oauth',clientId:'fixture-google-client',clientSecret:'fixture-google-secret',redirectPort:port,redirectHost:'127.0.0.1'}),{entry,port})).find(row=>row.catalogId===catalogId);unwrap(await page.evaluate(id=>window.zq.connectors.connect(id),saved.id));unwrap(await page.evaluate(({id,toolName})=>window.zq.connectors.setTools({id,names:[toolName]}),{id:saved.id,toolName}));
  const c=unwrap(await page.evaluate(connectionId=>window.zq.chat.createConversation({connectionId,model:'fixture:tools'}),connection.id));unwrap(await page.evaluate(({id,connectorId})=>window.zq.chat.send({conversationId:id,text:'Find '+id,connectorIds:[connectorId]}),{id:c.id,connectorId:saved.id}));const waiting=await reply(c.id,r=>r?.interactions?.some(i=>i.status==='waiting'));unwrap(await page.evaluate(input=>window.zq.chat.respondToInteraction(input),{conversationId:c.id,id:waiting.interactions[0].id,decision:'once'}));const done=await reply(c.id,r=>r?.status==='complete');assert.match(done.content,/Verified/);assert.equal(done.toolActivity[0].status,'complete');
 }
 console.log('PASS packaged Gmail: browser OAuth/PKCE, native credentials, standard API access check, tool selection, permission gate, search result, silent reconnect, reviewed draft sending, Calendar events and Drive search. Isolated profile: '+directory);
})().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{if(page&&!page.isClosed())await page.evaluate(async()=>{const result=await window.zq.connectors.list();for(const row of result.value??[])await window.zq.connectors.remove(row.id)}).catch(()=>{});if(app){await app.evaluate(({app})=>app.exit(0)).catch(()=>{});await app.close().catch(()=>{})}server.closeAllConnections();server.close()});
