// Run from the repository root after npm run pack. Uses a disposable profile and local OAuth/MCP server.
const { _electron:electron }=require('playwright-core');const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const root=process.cwd();fs.mkdirSync(path.join(root,'.local-data/mcp-verification'),{recursive:true});const dir=fs.mkdtempSync(path.join(root,'.local-data/mcp-verification/profile-'));let origin,authorization,opens=0,tokens=0,toolCalls=0,app,page;
const server=http.createServer(async(req,res)=>{try{let text='';for await(const chunk of req)text+=chunk;const url=new URL(req.url,origin),json=(value,status=200,headers={})=>{res.writeHead(status,{'content-type':'application/json',...headers});res.end(JSON.stringify(value))};
 if(url.pathname.startsWith('/.well-known/oauth-protected-resource'))return json({resource:origin+'/mcp',authorization_servers:[origin]});
 if(url.pathname==='/.well-known/oauth-authorization-server')return json({issuer:origin,authorization_endpoint:origin+'/authorize',token_endpoint:origin+'/token',registration_endpoint:origin+'/register',response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['none'],code_challenge_methods_supported:['S256'],authorization_response_iss_parameter_supported:true});
 if(url.pathname==='/register')return json({...JSON.parse(text),client_id:'fixture-native'},201);
 if(url.pathname==='/authorize'){opens++;authorization=url;const callback=new URL(url.searchParams.get('redirect_uri'));callback.searchParams.set('state',url.searchParams.get('state'));callback.searchParams.set('code','fixture-code');callback.searchParams.set('iss',origin);const response=await fetch(callback);assert.equal(response.status,200);return json({authorized:true})}
 if(url.pathname==='/token'){tokens++;const params=new URLSearchParams(text);if(params.get('grant_type')==='authorization_code'){assert.equal(params.get('code'),'fixture-code');assert.equal(crypto.createHash('sha256').update(params.get('code_verifier')).digest('base64url'),authorization.searchParams.get('code_challenge'))}return json({access_token:'fixture-access',refresh_token:'fixture-refresh',token_type:'Bearer',expires_in:3600})}
 if(url.pathname==='/mcp'){
  if(req.headers.authorization!=='Bearer fixture-access')return json({},401,{'WWW-Authenticate':`Bearer resource_metadata="${origin}/.well-known/oauth-protected-resource"`});
  if(req.method!=='POST'){res.writeHead(req.method==='DELETE'?200:405);return res.end()}
  const msg=JSON.parse(text);if(msg.id===undefined){res.writeHead(202);return res.end()}
  const reply=result=>json({jsonrpc:'2.0',id:msg.id,result});
  if(msg.method==='initialize')return reply({protocolVersion:'2025-11-25',capabilities:{tools:{}},serverInfo:{name:'OAuth fixture',version:'1'}});
  if(msg.method==='tools/list')return reply({tools:[{name:'lookup',title:'Look up a document',description:'Find one fixture document',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],unevaluatedProperties:false},annotations:{readOnlyHint:true}}]});
  if(msg.method==='tools/call'){toolCalls++;return reply({content:[{type:'text',text:'Fixture document found.'},{type:'resource_link',uri:'https://example.test/fixture',name:'Fixture document'}]})}
 }
 if(url.pathname==='/api/show')return json({capabilities:['tools']});
 if(url.pathname==='/api/tags')return json({models:[{name:'fixture:tools',model:'fixture:tools',modified_at:new Date().toISOString(),size:1,digest:'test',details:{family:'fixture',parameter_size:'1B',quantization_level:'F16'}}]});
 if(url.pathname==='/api/chat'){const body=JSON.parse(text),tool=body.tools?.find(t=>t.function.name.startsWith('mcp_'));const after=body.messages.at(-1)?.role==='tool';assert.ok(tool);const message=after?{content:'I found your document through the connector.'}:{content:'',tool_calls:[{function:{index:0,name:tool.function.name,arguments:{query:'fixture'}}}]};res.writeHead(200,{'content-type':'application/x-ndjson'});return res.end(JSON.stringify({message:{role:'assistant',...message},done:false})+'\n'+JSON.stringify({done:true,done_reason:'stop'})+'\n')}
 res.writeHead(404);res.end();
 }catch(e){console.error('Fixture server error:',e.message);res.writeHead(500);res.end()}});
async function waitReply(id,predicate){const until=Date.now()+20000;while(Date.now()<until){const state=unwrap(await page.evaluate(()=>window.zq.chat.load()));const reply=state.conversations.find(c=>c.id===id)?.messages.at(-1);if(predicate(reply))return reply;if(reply?.status==='error')throw Error('Chat failed: '+reply.error);await new Promise(r=>setTimeout(r,50))}throw Error('Timed out waiting for chat reply')}
const unwrap=r=>{assert.equal(r.ok,true,JSON.stringify(r.error));return r.value};
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${server.address().port}`;
 app=await electron.launch({executablePath:path.join(root,'apps/desktop/release/mac-arm64/zQ.app/Contents/MacOS/zQ'),env:{...process.env,ZQ_DATA_DIR:dir},timeout:30000});
 page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForFunction(()=>!!window.zq);
 await app.evaluate(({shell})=>{shell.openExternal=async url=>{const response=await fetch(url);if(!response.ok)throw Error('Fixture authorization failed')}});
 await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('button',{name:'Connectors',exact:true}).click();await page.getByRole('button',{name:'Add custom connector',exact:true}).click();await page.getByLabel('Name',{exact:true}).fill('Fixture OAuth');await page.getByLabel('Server URL').fill(origin+'/mcp');await page.getByRole('button',{name:'Save connector',exact:true}).click();await page.getByRole('button',{name:'Connect',exact:true}).click();await page.getByRole('button',{name:'Choose tools',exact:true}).waitFor({timeout:45000});assert.equal(opens,1);assert.equal(tokens,1);
 await page.getByRole('button',{name:'Choose tools',exact:true}).click();const checkbox=page.getByRole('checkbox',{name:'Enable Look up a document'});assert.equal(await checkbox.isChecked(),false);await checkbox.check();await page.getByRole('button',{name:'Done',exact:true}).click();await page.screenshot({path:root+'/.local-data/mcp-verification/settings.png'});
 const row=unwrap(await page.evaluate(()=>window.zq.connectors.list()))[0];assert.equal(row.tools[0].enabled,true);
 const connection=unwrap(await page.evaluate(baseUrl=>window.zq.chat.saveConnection({provider:'ollama',name:'Fixture model',baseUrl}),origin));
 const conversation=unwrap(await page.evaluate(connectionId=>window.zq.chat.createConversation({connectionId,model:'fixture:tools'}),connection.id));
 unwrap(await page.evaluate(({id,cid})=>window.zq.chat.setConversationConnectors({conversationId:cid,connectorIds:[id]}),{id:row.id,cid:conversation.id}));
 unwrap(await page.evaluate(id=>window.zq.chat.saveChatView({selected:id,projectId:null,projectHome:false,positions:{}}),conversation.id));
 await page.keyboard.press('Escape');await page.getByRole('button',{name:'Chat module',exact:true}).click();
 unwrap(await page.evaluate(id=>window.zq.chat.send({conversationId:id,text:'Find the fixture document'}),conversation.id));
 await waitReply(conversation.id,reply=>reply?.interactions?.some(i=>i.status==='waiting'));assert.equal(toolCalls,0);
 const state=unwrap(await page.evaluate(()=>window.zq.chat.load()));const interaction=state.conversations.find(c=>c.id===conversation.id).messages.at(-1).interactions[0];
 unwrap(await page.evaluate(input=>window.zq.chat.respondToInteraction(input),{conversationId:conversation.id,id:interaction.id,decision:'chat'}));
 await waitReply(conversation.id,reply=>reply?.status==='complete');
 assert.equal(toolCalls,1);const complete=unwrap(await page.evaluate(()=>window.zq.chat.load())).conversations.find(c=>c.id===conversation.id).messages.at(-1);assert.equal(complete.sources.length,1);assert.equal(complete.toolActivity[0].status,'complete');assert.match(complete.content,/through the connector/);await page.getByText('I found your document through the connector.',{exact:true}).waitFor();assert.doesNotMatch(await page.locator('body').innerText(),/mcp:[a-f0-9]{32}/);const approval=page.getByRole('region',{name:'Tool approval',exact:true}),summary=approval.getByRole('button',{name:'Allowed for this chat',exact:true});await summary.waitFor();assert.equal(await summary.getAttribute('aria-expanded'),'false');await approval.locator('.chat-interaction-detail').waitFor({state:'hidden'});await summary.click();await approval.locator('.chat-interaction-detail').waitFor();await summary.click();assert.equal(await summary.getAttribute('aria-expanded'),'false');await page.screenshot({path:root+'/.local-data/mcp-verification/chat.png'});
 await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].close());await page.waitForEvent('close');await app.evaluate(({app})=>app.emit('activate'));page=await app.firstWindow();await page.waitForFunction(()=>!!window.zq);const disconnected=unwrap(await page.evaluate(()=>window.zq.connectors.list()))[0];assert.equal(disconnected.status,'disconnected');unwrap(await page.evaluate(id=>window.zq.connectors.connect(id),row.id));assert.equal(opens,1);
 unwrap(await page.evaluate(id=>window.zq.chat.send({conversationId:id,text:'Find it after reopening'}),conversation.id));await waitReply(conversation.id,reply=>reply?.status==='complete');assert.equal(toolCalls,2);
 unwrap(await page.evaluate(id=>window.zq.connectors.remove(id),row.id));assert.deepEqual(unwrap(await page.evaluate(()=>window.zq.connectors.list())),[]);assert.deepEqual(errors,[]);
 console.log('PASS packaged app: real SDK OAuth/PKCE, native Keychain, tools default off, permission gate, bounded worker schema, Ollama tool execution, activity/citations, macOS close/reopen, silent reconnect and credential removal. Isolated profile: '+dir);
})().catch(async error=>{console.error(error);if(page)console.error((await page.locator('body').innerText().catch(()=>'' )).slice(0,5000));process.exitCode=1}).finally(async()=>{if(page&&!page.isClosed())await page.evaluate(async()=>{const result=await window.zq.connectors.list();for(const row of result.value??[])await window.zq.connectors.remove(row.id)}).catch(()=>{});await app?.close();server.closeAllConnections();server.close()});
