const {test}=require('node:test');const assert=require('node:assert/strict');
const {createProvider}=require('@zq/providers');
const bases={openai:'https://api.openai.com/v1',anthropic:'https://api.anthropic.com/v1',google:'https://generativelanguage.googleapis.com/v1beta',xai:'https://api.x.ai/v1',openrouter:'https://openrouter.ai/api/v1',groq:'https://api.groq.com/openai/v1',vllm:'http://127.0.0.1:8000/v1',perplexity:'https://api.perplexity.ai',ollama:'http://127.0.0.1:11434'};
const event=p=>`data: ${typeof p==='string'?p:JSON.stringify(p)}\n\n`;
function response(wire){return {status:200,body:new ReadableStream({start(c){c.enqueue(Buffer.from(wire));c.close()}})}}
async function run(provider,rounds,extra={}){const usages=[],models=[],deltas=[],bodies=[];let i=0;const adapter=createProvider(provider,{apiKey:'fixture-only',fetchImpl:async(_url,options)=>{bodies.push(JSON.parse(options.body));return response(rounds[i++])}});await adapter.streamChat({baseUrl:bases[provider],model:provider==='google'?'gemini-2.5-pro':provider==='perplexity'?'sonar':'fixture-model',messages:[{role:'user',content:'Hi'}],onDelta:d=>deltas.push(d),onUsage:u=>usages.push(u),onModel:m=>models.push(m),onTool(){},...extra});return {usages,models,deltas,bodies}}
const openDone=extra=>event({type:'response.completed',response:{status:'completed',output:[],...extra}});
const stop=event({choices:[{index:0,delta:{},finish_reason:'stop'}]});
const aStart=usage=>event({type:'message_start',message:{model:'claude-reported',usage}}),aDelta=(output,reason)=>event({type:'message_delta',usage:{output_tokens:output},delta:{stop_reason:reason}}),aStop=event({type:'message_stop'});
test('OpenAI Responses exposes reported model and final usage without counting repeated snapshots twice',async()=>{const result=await run('openai',[event({type:'response.created',response:{model:'reported-version'}})+openDone({model:'reported-version',usage:{input_tokens:20,output_tokens:7,input_tokens_details:{cached_tokens:4},output_tokens_details:{reasoning_tokens:2}}})]);assert.deepEqual(result.models,['reported-version']);assert.deepEqual(result.usages,[{inputTokens:20,outputTokens:7,cachedInputTokens:4,reasoningTokens:2}])});
test('Anthropic merges cumulative output updates and includes reported cache reads/writes in input totals',async()=>{const result=await run('anthropic',[aStart({input_tokens:10,cache_creation_input_tokens:4,cache_read_input_tokens:6,output_tokens:1})+aDelta(5)+aDelta(7,'end_turn')+aStop]);assert.deepEqual(result.usages.at(-1),{inputTokens:20,cachedInputTokens:6,outputTokens:7});assert.equal(result.models[0],'claude-reported')});
test('hosted Anthropic continuation adds separate requests but not their cumulative deltas',async()=>{const result=await run('anthropic',[aStart({input_tokens:10,output_tokens:1})+aDelta(4,'pause_turn')+aStop,aStart({input_tokens:14,output_tokens:1})+aDelta(6,'end_turn')+aStop],{tools:['web_search'],model:'claude-sonnet-4-6'});assert.deepEqual(result.usages.at(-1),{inputTokens:24,outputTokens:10});assert.equal(result.bodies.length,2)});
test('Gemini usage includes thoughts within output and preserves reported version',async()=>{const result=await run('google',[event({modelVersion:'gemini-reported',candidates:[{index:0,content:{parts:[{text:'Hi'}]}}],usageMetadata:{promptTokenCount:10,candidatesTokenCount:2,thoughtsTokenCount:3,cachedContentTokenCount:4}})+event({modelVersion:'gemini-reported',candidates:[{index:0,finishReason:'STOP'}],usageMetadata:{promptTokenCount:10,candidatesTokenCount:4,thoughtsTokenCount:3,cachedContentTokenCount:4}})]);assert.deepEqual(result.usages.at(-1),{inputTokens:10,outputTokens:7,cachedInputTokens:4,reasoningTokens:3});assert.deepEqual(result.models,['gemini-reported'])});
for(const provider of ['xai','openrouter','groq','vllm','perplexity'])test(`${provider} handles trailing usage-only chunks without inventing metadata`,async()=>{const result=await run(provider,[stop+event({model:'actual-model',choices:[],usage:{prompt_tokens:11,completion_tokens:5,prompt_tokens_details:{cached_tokens:3},completion_tokens_details:{reasoning_tokens:2}}})+event('[DONE]')]);assert.deepEqual(result.usages.at(-1),{inputTokens:11,outputTokens:5,cachedInputTokens:3,reasoningTokens:2});assert.deepEqual(result.models,['actual-model'])});
test('Ollama reports final counters and actual model',async()=>{const result=await run('ollama',[JSON.stringify({model:'llama-reported',message:{role:'assistant',content:'Hi'},done:false})+'\n'+JSON.stringify({model:'llama-reported',done:true,prompt_eval_count:8,eval_count:3})+'\n']);assert.deepEqual(result.usages,[{inputTokens:8,outputTokens:3}]);assert.deepEqual(result.models,['llama-reported'])});
test('invalid or missing telemetry never breaks a valid answer or creates guessed counts',async()=>{const result=await run('openai',[event({type:'response.created',response:{model:'bad\nmodel'}})+openDone({usage:{input_tokens:-1,output_tokens:'7',input_tokens_details:{cached_tokens:1.5}},model:'x'.repeat(600)})]);assert.deepEqual(result.usages,[]);assert.deepEqual(result.models,[])});
for(const provider of ['openai','google'])test(`${provider} hosted tools report native usage`,async()=>{const wire=provider==='openai'?openDone({model:'reported',usage:{input_tokens:3,output_tokens:4}}):event({modelVersion:'reported',candidates:[{index:0,finishReason:'STOP'}],usageMetadata:{promptTokenCount:3,candidatesTokenCount:4}});const result=await run(provider,[wire],{tools:['code_execution'],model:provider==='openai'?'gpt-4.1':'gemini-2.5-pro'});assert.deepEqual(result.usages.at(-1),{inputTokens:3,outputTokens:4});assert.deepEqual(result.models,['reported'])});
for(const provider of ['xai','openrouter'])test(`${provider} hosted routing forwards usage`,async()=>{const wire=provider==='xai'?openDone({model:'reported',usage:{input_tokens:3,output_tokens:4}}):stop+event({choices:[],model:'reported',usage:{prompt_tokens:3,completion_tokens:4}})+event('[DONE]');const result=await run(provider,[wire],{tools:['web_search'],model:provider==='xai'?'grok-4':'openai/gpt-4.1'});assert.deepEqual(result.usages.at(-1),{inputTokens:3,outputTokens:4});assert.deepEqual(result.models,['reported'])});
test('legacy OpenAI opts into final usage without sending compatibility flags to other providers',async()=>{const result=await run('openai',[stop+event({choices:[],usage:{prompt_tokens:2,completion_tokens:3}})+event('[DONE]')],{model:'gpt-3.5-turbo'});assert.deepEqual(result.usages,[{inputTokens:2,outputTokens:3}]);assert.deepEqual(result.bodies[0].stream_options,{include_usage:true});const router=await run('openrouter',[stop+event('[DONE]')]);assert.equal(router.bodies[0].stream_options,undefined)});
test('Bedrock decodes final metadata usage and does not invent the resolved inference-profile model',async()=>{const {Readable}=require('node:stream'),{EventStreamCodec}=require('@smithy/core/event-streams');const codec=new EventStreamCodec(bytes=>Buffer.from(bytes).toString('utf8'),text=>Buffer.from(text));const events=[{messageStart:{role:'assistant'}},{contentBlockDelta:{contentBlockIndex:0,delta:{text:'Hi'}}},{contentBlockStop:{contentBlockIndex:0}},{messageStop:{stopReason:'end_turn'}},{metadata:{usage:{inputTokens:20,outputTokens:6,totalTokens:26,cacheReadInputTokens:7},metrics:{latencyMs:1}}}];const wire=Buffer.concat(events.map(event=>{const [type,payload]=Object.entries(event)[0];return Buffer.from(codec.encode({headers:{':message-type':{type:'string',value:'event'},':event-type':{type:'string',value:type},':content-type':{type:'string',value:'application/json'}},body:Buffer.from(JSON.stringify(payload))}))}));const usages=[],models=[];const adapter=createProvider('bedrock',{apiKey:'fixture-only',requestHandler:{handle:async()=>({response:{statusCode:200,headers:{'content-type':'application/vnd.amazon.eventstream'},body:Readable.from([wire])}}),destroy(){}}});await adapter.streamChat({baseUrl:'https://bedrock-runtime.us-east-1.amazonaws.com',model:'us.anthropic.claude-sonnet-4-6',messages:[{role:'user',content:'Hi'}],onDelta(){},onUsage:u=>usages.push(u),onModel:m=>models.push(m)});assert.deepEqual(usages,[{inputTokens:27,outputTokens:6,cachedInputTokens:7}]);assert.deepEqual(models,[])});
test('Bedrock emits a resolved model only when the provider reports prompt-router trace metadata',()=>{const {createTelemetry}=require('../../../packages/providers/usage.cjs');const models=[],usages=[];const telemetry=createTelemetry({onModel:m=>models.push(m),onUsage:u=>usages.push(u)});telemetry.observe('bedrock',{usage:{inputTokens:9,outputTokens:3},trace:{promptRouter:{invokedModelId:'anthropic.claude-reported'}}});assert.deepEqual(models,['anthropic.claude-reported']);assert.deepEqual(usages,[{inputTokens:9,outputTokens:3}])});
test('invalid optional counts are skipped while valid zero counts and updates remain exact',async()=>{const wire=event({type:'response.created',response:{usage:{input_tokens:5,output_tokens:0,input_tokens_details:{cached_tokens:0}}}})+openDone({usage:{input_tokens:5,output_tokens:4,input_tokens_details:{cached_tokens:0},output_tokens_details:{reasoning_tokens:-1}}});const result=await run('openai',[wire]);assert.deepEqual(result.usages,[{inputTokens:5,outputTokens:0,cachedInputTokens:0},{inputTokens:5,outputTokens:4,cachedInputTokens:0}]);assert.deepEqual(result.models,[])});

test('Bedrock includes reported cache reads and writes with safe-integer guards',()=>{const {createTelemetry}=require('../../../packages/providers/usage.cjs');for(const [usage,want] of [[{inputTokens:20,cacheReadInputTokens:7,cacheWriteInputTokens:3,outputTokens:6},{inputTokens:30,outputTokens:6,cachedInputTokens:7}],[{inputTokens:20,cacheReadInputTokens:-2,cacheWriteInputTokens:"3",outputTokens:6},{inputTokens:20,outputTokens:6}],[{inputTokens:Number.MAX_SAFE_INTEGER,cacheWriteInputTokens:1,outputTokens:6},{outputTokens:6}],[{cacheReadInputTokens:7,cacheWriteInputTokens:3,outputTokens:6},{outputTokens:6,cachedInputTokens:7}]]){const seen=[];createTelemetry({onUsage:u=>seen.push(u)}).observe('bedrock',{usage});assert.deepEqual(seen,[want])}});
