const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{execFileSync}=require('node:child_process'),{_electron}=require('playwright-core');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'zq-sidebar-'));
let app;
async function launch(){app=await _electron.launch({executablePath:path.resolve('apps/desktop/release/mac-arm64/zQ.app/Contents/MacOS/zQ'),env:{...process.env,ZQ_DATA_DIR:root,TMUX_TMPDIR:root},timeout:30000});const p=await app.firstWindow();p.setDefaultTimeout(10000);return p}
async function navigate(p,module){if(module==='HQ')await p.locator('.header-brand').click();else await p.getByRole('button',{name:module+' module',exact:true}).click()}
;(async()=>{try{
 let p=await launch();const errors=[];p.on('pageerror',e=>errors.push(e.message));
 const groups=[['HQ',['Projects','Pinned notes']],['Notes',['Your scratchpads']],['Tasks',['Projects']],['Chat',['Projects','Recents']],['Code',['Projects']]];
 for(const [module,titles] of groups){await navigate(p,module);for(const title of titles){const section=p.locator('.context-sidebar .zq-sidebar-section').filter({has:p.getByRole('button',{name:'Collapse '+title,exact:true})});const trigger=section.getByRole('button',{name:'Collapse '+title,exact:true});await trigger.waitFor();await p.mouse.move(1000,80);assert.equal(await trigger.locator('svg').evaluate(e=>getComputedStyle(e).opacity),'0');await trigger.hover();assert.equal(await trigger.locator('svg').evaluate(e=>getComputedStyle(e).opacity),'1');await trigger.focus();await p.keyboard.press('Enter');const closed=p.getByRole('button',{name:'Expand '+title,exact:true});assert.equal(await closed.getAttribute('aria-expanded'),'false');await p.mouse.move(1000,80);await closed.evaluate(e=>e.blur());assert.equal(await closed.locator('svg').evaluate(e=>getComputedStyle(e).opacity),'1');await closed.focus();await p.keyboard.press('Space');await p.getByRole('button',{name:'Collapse '+title,exact:true}).click({button:'right'});await p.getByRole('menuitem',{name:'Collapse '+title,exact:true}).click();await closed.waitFor();}}
 await navigate(p,'Chat');await p.getByRole('button',{name:'New project',exact:true}).click();await p.getByRole('dialog').waitFor();await p.keyboard.press('Escape');assert.equal(await p.getByRole('button',{name:'Expand Projects',exact:true}).getAttribute('aria-expanded'),'false');
 for(const theme of ['light','dark']){await p.evaluate(t=>document.documentElement.dataset.theme=t,theme);await p.evaluate(()=>Promise.all(document.getAnimations().map(a=>a.finished.catch(()=>{}))));await p.screenshot({path:'.local-data/sidebar-sections-'+theme+'.png'})}
 await app.close();app=null;p=await launch();for(const [module,titles] of groups){await navigate(p,module);for(const title of titles)await p.getByRole('button',{name:'Expand '+title,exact:true}).waitFor()}
 await p.getByRole('button',{name:'Expand Projects',exact:true}).click();await navigate(p,'Tasks');await p.getByRole('button',{name:'Expand Projects',exact:true}).waitFor();assert.deepEqual(errors,[]);
 console.log('PASS: all five module sidebars, hover/closed carets, keyboard, context menus, collapsed actions, independent state and restart persistence');
}finally{if(app)await app.close().catch(()=>{});try{execFileSync('/opt/homebrew/bin/tmux',['-S',path.join(root,'code/tmux'),'kill-server'],{stdio:'ignore'})}catch{}fs.rmSync(root,{recursive:true,force:true,maxRetries:5,retryDelay:100})}})().catch(e=>{console.error(e);process.exitCode=1});
