// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skill-updates-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button=name=>page.getByRole('button',{name,exact:true}), menu=name=>page.getByRole('menuitem',{name,exact:true}), docx=page.locator('.skill-catalog-row').filter({has:page.getByRole('button',{name:'Preview skill docx',exact:true})})
  await button('Browse skills').click(); await button('Preview skill docx').waitFor(); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='checkUpdates').length),0); assert.equal(await docx.locator('.skill-installed-badge').count(),0)
  await button('Preview skill docx').click(); const importReview=page.getByRole('dialog',{name:'Import skill',exact:true}); await importReview.waitFor(); await importReview.getByRole('button',{name:'Import skill',exact:true}).click(); await page.getByRole('status').filter({hasText:'docx imported.'}).waitFor(); assert.equal(await docx.locator('.skill-installed-badge').innerText(),'Up to date'); assert.equal(await page.evaluate(()=>window.selection),null)
  await button('Check for updates').click(); await docx.getByText('Up to date',{exact:true}).waitFor(); await button('Preview skill docx').click(); const updateReview=page.getByRole('dialog',{name:'Review skill update',exact:true}); await updateReview.waitFor(); assert.equal(await updateReview.getByRole('button',{name:'Update skill',exact:true}).isDisabled(),true); assert.equal(await page.getByRole('button',{name:'Import skill',exact:true}).count(),0); await updateReview.getByRole('button',{name:'Cancel',exact:true}).click()
  await page.evaluate(()=>{window.catalogRevision='r2';window.modifyInstalled()}); await button('Check for updates').click(); await docx.getByText('Update available',{exact:true}).waitFor(); await button('Actions for catalog skill docx').click(); assert.deepEqual(await page.getByRole('menuitem').allTextContents(),['Preview update','View on skills.sh','View source']); await menu('Preview update').click(); await updateReview.waitFor(); assert.equal(await updateReview.getByRole('textbox',{name:'Skill update name',exact:true}).inputValue(),'My document workflow'); await updateReview.getByText('You have local changes.',{exact:false}).waitFor(); await updateReview.getByRole('button',{name:'Cancel',exact:true}).click(); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='updateSkill').length),0); assert.equal(await page.evaluate(()=>window.skills.find(s=>s.source).source.revision),'r1')
  await button('Preview skill docx').click({button:'right'}); await menu('Preview update').click(); await updateReview.waitFor(); await page.evaluate(()=>window.failUpdate=true); await updateReview.getByRole('button',{name:'Update skill',exact:true}).click(); await updateReview.getByRole('alert').filter({hasText:'changed after the preview'}).waitFor(); assert.equal(await updateReview.getByRole('textbox',{name:'Skill update name',exact:true}).inputValue(),'My document workflow'); await updateReview.getByRole('button',{name:'Cancel',exact:true}).click(); await page.evaluate(()=>{window.failUpdate=false;window.fillAroundInstalled()}); await button('Preview skill docx').click(); await updateReview.waitFor(); assert.equal(await updateReview.getByRole('button',{name:'Update skill',exact:true}).isEnabled(),true)
  await page.evaluate(()=>window.holdUpdate=true); await updateReview.getByRole('button',{name:'Update skill',exact:true}).click(); await page.waitForFunction(()=>!!window.finishUpdate); await page.keyboard.press('Escape'); assert.equal(await updateReview.count(),1); assert.equal(await updateReview.getByRole('button',{name:'Cancel',exact:true}).isDisabled(),true); await page.evaluate(()=>{window.holdUpdate=false;window.finishUpdate()}); await docx.getByText('Up to date',{exact:true}).waitFor(); assert.equal(await page.evaluate(()=>window.skills.length),100); assert.equal(await page.evaluate(()=>window.skills.find(s=>s.source).source.revision),'r2'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='import').length),1); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='updateSkill').at(-1)[1].expectedHash),'expected-current-hash')
  await page.evaluate(()=>window.failEntry=true); await button('Check for updates').click(); await docx.getByText('Could not check this skill.',{exact:true}).waitFor(); assert.equal(await docx.locator('.skill-installed-badge').innerText(),'Installed'); await page.evaluate(()=>{window.failEntry=false;window.failCheck=true}); await button('Check for updates').click(); await page.getByRole('alert').filter({hasText:'Update checks failed'}).waitFor(); assert.equal(await docx.locator('.skill-installed-badge').innerText(),'Installed'); await page.evaluate(()=>window.failCheck=false); await button('Check for updates').click(); await docx.getByText('Up to date',{exact:true}).waitFor(); await page.screenshot({path:'.local-data/skill-updates.png'}); await page.evaluate(()=>window.removeInstalled()); await docx.locator('.skill-installed-badge').waitFor({state:'detached'}); assert.deepEqual(errors,[]); console.log('PASS source-based installed status, manual latest checks, update badges, no duplicate import, current read-only preview, modified warning/cancel, concurrent-change error, expectedHash commit, pending guard, full-library update, failed-check stale status suppression, live removal.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
