// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skill-packages-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button = name => page.getByRole('button', { name, exact: true }), menu = name => page.getByRole('menuitem', { name, exact: true })
  await button('Import skill').waitFor(); await page.evaluate(()=>{const text='Reference body',script='#!/bin/sh\necho preserved';window.packageImport={name:'Portable writing',description:'Portable skill',instructions:'Read references/guide.md.',warnings:['This skill declares external tool requirements. They are not enabled by importing.'],files:[{name:'Guide',resourcePath:'references/guide.md',kind:'text',mime:'text/plain',size:text.length,text}],package:{frontmatter:'name: portable-writing\ndescription: Portable skill\nlicense: MIT\ncompatibility: Requires example-tool\nmetadata:\n  author: Example',resources:[{path:'references/guide.md',data:btoa(text),size:text.length},{path:'scripts/helper.sh',data:btoa(script),size:script.length},{path:'assets/logo.png',data:btoa(String.fromCharCode(137,80,78,71,0,255)),size:6}]}}})
  await button('Skill import options').click(); await menu('Import folder…').click(); const preview=page.getByRole('dialog',{name:'Import skill',exact:true}); await preview.waitFor(); assert.equal(await page.evaluate(()=>window.events.find(e=>e[0]==='pickImport')[1].directory),true)
  const packageRows=preview.locator('.skill-package-file'); assert.equal(await packageRows.count(),3); assert.match(await packageRows.filter({hasText:'references/guide.md'}).innerText(),/Active context/); assert.match(await packageRows.filter({hasText:'scripts/helper.sh'}).innerText(),/Preserved for export/)
  await preview.getByText('Package metadata',{exact:true}).click(); await preview.getByText('license: MIT',{exact:false}).waitFor(); await button('Preview package file scripts/helper.sh').click({button:'right'}); assert.deepEqual(await page.getByRole('menuitem').allTextContents(),['Preview']); await menu('Preview').click(); const scriptDialog=page.getByRole('dialog',{name:'scripts/helper.sh',exact:true}); await scriptDialog.waitFor(); assert.equal(await scriptDialog.locator('pre').innerText(),'#!/bin/sh\necho preserved'); await page.keyboard.press('Escape'); await scriptDialog.waitFor({state:'detached'}); await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Preview package file scripts/helper.sh'); assert.equal(await preview.count(),1)
  await button('Actions for package file assets/logo.png').click(); await menu('Preview').click(); const binary=page.getByRole('dialog',{name:'assets/logo.png',exact:true}); await binary.waitFor(); assert.match(await binary.innerText(),/cannot be previewed as text/); await page.keyboard.press('Escape'); await binary.waitFor({state:'detached'})
  await preview.getByRole('button',{name:'Import skill',exact:true}).click(); await button('Edit skill Portable writing').waitFor(); assert.equal(await page.evaluate(()=>window.events.find(e=>e[0]==='import')[1].package.resources.length),3)
  await button('Edit skill Portable writing').click(); const editor=page.getByRole('dialog',{name:'Edit skill',exact:true}); await editor.waitFor(); assert.equal(await page.getByRole('textbox',{name:'Skill instructions',exact:true}).getAttribute('maxlength'),'1048576'); assert.equal(await page.getByRole('textbox',{name:'Skill description',exact:true}).getAttribute('maxlength'),'1024')
  await button('Preview package file scripts/helper.sh').click({button:'right'}); assert.deepEqual(await page.getByRole('menuitem').allTextContents(),['Preview','Save file']); await menu('Preview').click(); await scriptDialog.waitFor(); assert.equal(await scriptDialog.locator('pre').innerText(),'#!/bin/sh\necho preserved'); await page.keyboard.press('Escape'); await scriptDialog.waitFor({state:'detached'}); await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Preview package file scripts/helper.sh'); assert.equal(await editor.count(),1)
  await button('Actions for package file assets/logo.png').click(); await page.evaluate(()=>window.holdResource=true); await menu('Save file').click(); await page.waitForFunction(()=>!!window.finishResource); assert.equal(await button('Save skill').isDisabled(),true); await page.keyboard.press('Escape'); assert.equal(await editor.count(),1); const flushError=await page.evaluate(async()=>{try{for(const f of window.flushers.values())await f();return ''}catch(e){return e.message}}); assert.match(flushError,/Wait for/); await page.evaluate(()=>{window.holdResource=false;window.finishResource()}); await page.getByRole('status').filter({hasText:'assets/logo.png saved.'}).waitFor()
  await button('Actions for reference Guide').click(); await menu('Remove').click(); assert.match(await editor.locator('.skill-package-file').filter({hasText:'references/guide.md'}).innerText(),/Preserved for export/); assert.equal(await editor.locator('.skill-package-file').count(),3); await button('Save skill').click(); assert.equal(await page.evaluate(()=>window.skills.find(s=>s.name==='Portable writing').package.resources.length),3)
  await button('Edit skill Portable writing').click(); await page.screenshot({path:'.local-data/skill-packages-editor.png'}); await button('Cancel').click(); await button('Import skill').click(); await preview.waitFor(); await preview.getByRole('button',{name:'Preview Guide',exact:true}).click({button:'right'}); await menu('Remove').click(); assert.match(await preview.locator('.skill-package-file').filter({hasText:'references/guide.md'}).innerText(),/Preserved for export/); assert.equal(await preview.locator('.skill-package-file').count(),3); await preview.getByRole('button',{name:'Cancel',exact:true}).click(); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='import').length),1); assert.deepEqual(errors,[]); console.log('PASS package import folder action, retained paths/YAML, script and binary preview, right-click/menu parity, nested preview focus, native save/pending guard, active-reference removal preserves original resources.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
