const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ChatService}=require('../electron/chat-service.cjs');
const source={catalogId:'anthropics/skills/docx',revision:'a'.repeat(40),contentHash:'b'.repeat(64)};
const draft=()=>({name:'Word',description:'Write documents',instructions:'Original instructions',files:[],warnings:[],source:{...source},package:{frontmatter:'name: docx\ndescription: Write documents',resources:[{path:'assets/example.bin',data:'AQID',size:3}]}});
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-skill-updates-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return new ChatService({directory})}
test('catalog provenance survives import, rename, public snapshots and restart; personal duplicates detach',t=>{const s=fixture(t),skill=s.importSkill(draft());assert.deepEqual(skill.source,source);s.saveSkill({id:skill.id,name:'My Word helper'});assert.deepEqual(s.snapshot().skills[0].source,source);assert.deepEqual(new ChatService({directory:s.store.directory}).state.skills[0].source,source);assert.equal(s.duplicateSkill(skill.id).source,undefined);assert.throws(()=>s.importSkill({...draft(),source:{...source,revision:'../bad'}}));});
test('reviewed updates replace package atomically while retaining skill identity, selection and sent history',t=>{const s=fixture(t),skill=s.importSkill(draft()),p=s.saveProject({name:'Example'});s.updateProject({id:p.id,skillIds:[skill.id]});const review=s.prepareSkillUpdate(skill.id);assert.match(review.expectedHash,/^[a-f0-9]{64}$/);const candidate={...draft(),instructions:'New instructions',source:{...source,revision:'c'.repeat(40)},package:{frontmatter:'name: docx',resources:[{path:'assets/new.bin',data:'BAUG',size:3}]}};const updated=s.updateCatalogSkill({id:skill.id,expectedHash:review.expectedHash,candidate});assert.equal(updated.id,skill.id);assert.equal(updated.createdAt,skill.createdAt);assert.equal(s.state.skills.length,1);assert.equal(updated.instructions,'New instructions');assert.deepEqual(s.state.projects[0].skillIds,[skill.id]);assert.equal(s.state.skills[0].source.revision,'c'.repeat(40));assert.deepEqual(s.skillResource({id:skill.id,path:'assets/new.bin'}).bytes,Buffer.from([4,5,6]));});
test('stale review, mismatched source and failed storage never overwrite an installed skill',t=>{const s=fixture(t),skill=s.importSkill(draft()),review=s.prepareSkillUpdate(skill.id);s.saveSkill({id:skill.id,instructions:'Local edit'});assert.throws(()=>s.updateCatalogSkill({id:skill.id,expectedHash:review.expectedHash,candidate:draft()}),/changed/i);assert.equal(s.state.skills[0].instructions,'Local edit');const current=s.prepareSkillUpdate(skill.id);assert.equal(current.modified,true);assert.throws(()=>s.updateCatalogSkill({id:skill.id,expectedHash:current.expectedHash,candidate:{...draft(),source:{...source,catalogId:'other/repo/skill'}}}),/source/i);const before=structuredClone(s.state),blobs=fs.readdirSync(s.skillResources.directory);s.store.save=()=>{throw Error('Disk full')};assert.throws(()=>s.updateCatalogSkill({id:skill.id,expectedHash:current.expectedHash,candidate:{...draft(),package:{frontmatter:'',resources:[{path:'new.txt',data:'bmV3',size:3}]}}}),/Disk full/);assert.deepEqual(s.state,before);assert.deepEqual(fs.readdirSync(s.skillResources.directory),blobs);});
test('untracked ZIP/manual skills cannot claim update support',t=>{const s=fixture(t),input=draft();delete input.source;const skill=s.importSkill(input);assert.equal(skill.source,undefined);assert.throws(()=>s.prepareSkillUpdate(skill.id),/source/i);});
test('unchanged imported packages are current despite native resource IDs; edits are detected',t=>{const {skillContentHash}=require('../electron/skill-source.cjs'),s=fixture(t),input=draft();input.source.contentHash=skillContentHash(input);const created=s.importSkill(input);assert.equal(s.prepareSkillUpdate(created.id).modified,false);s.saveSkill({id:created.id,instructions:'Customized locally'});assert.equal(s.prepareSkillUpdate(created.id).modified,true);});
test('updating keeps previously sent skill snapshots and their immutable resource bytes',t=>{const s=fixture(t),created=s.importSkill(draft()),old=structuredClone(s.state.skills[0]),chat=s.createConversation({});s.change(state=>{state.conversations[0].messages.push({id:'sent',role:'user',content:'Hello',thinking:'',status:'complete',createdAt:1,error:'',context:[],skillContext:[old]});return null});const review=s.prepareSkillUpdate(created.id);s.updateCatalogSkill({id:created.id,expectedHash:review.expectedHash,candidate:{...draft(),instructions:'Updated instructions',source:{...source,revision:'c'.repeat(40)}}});const restored=new ChatService({directory:s.store.directory}),snapshot=restored.state.conversations.find(c=>c.id===chat.id).messages[0].skillContext[0];assert.equal(snapshot.instructions,'Original instructions');assert.equal(snapshot.source.revision,'a'.repeat(40));assert.deepEqual(restored.skillResources.read(snapshot.package.resources[0]),Buffer.from([1,2,3]));});
test('tracked catalog imports cannot accidentally install duplicates',t=>{const s=fixture(t),original=s.importSkill(draft());assert.throws(()=>s.importSkill(draft()),/already installed/i);assert.equal(s.state.skills.length,1);const copy=s.duplicateSkill(original.id);assert.equal(copy.source,undefined);assert.equal(s.state.skills.length,2);});
