// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skill-legacy-installed-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button=name=>page.getByRole('button',{name,exact:true})
  await button('Browse skills').waitFor(); await page.evaluate(()=>{window.loadLegacyImports();window.holdReconciliation=true}); await button('Edit skill My Word workflow').waitFor(); const before=await page.evaluate(()=>structuredClone(window.skills)); assert.equal(before.length,4); assert.ok(before.every(skill=>skill.source===null))
  await button('Browse skills').click(); await page.waitForFunction(()=>!!window.finishReconciliation); await page.getByRole('status').filter({hasText:'Loading curated skills'}).waitFor(); assert.equal(await page.locator('.skill-installed-badge').count(),0); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='reconcileLegacySources').length),0)
  await page.evaluate(()=>{window.holdReconciliation=false;window.finishReconciliation()}); for(const name of ['docx','pdf','xlsx','pptx']){const row=page.locator('.skill-catalog-row').filter({has:page.getByRole('button',{name:'Preview skill '+name,exact:true})}); await row.getByText('Installed',{exact:true}).waitFor()}; assert.equal(await page.locator('.skill-installed-badge').count(),4); await page.getByRole('status').filter({hasText:'Updates have not been checked.'}).waitFor(); assert.equal(await page.getByText('Up to date',{exact:true}).count(),0)
  const after=await page.evaluate(()=>structuredClone(window.skills)); assert.deepEqual(after.map(({source,...rest})=>rest),before.map(({source,...rest})=>rest)); assert.deepEqual(after.map(skill=>skill.source.catalogId),['docx','pdf','xlsx','pptx']); assert.deepEqual(await page.evaluate(()=>window.events.map(event=>event[0])),['browse','reconcileLegacySources']); await page.screenshot({path:'.local-data/skill-legacy-four-installed.png'})
  await button('Preview skill docx').click({button:'right'}); await page.getByRole('menuitem',{name:'Preview',exact:true}).click(); const review=page.getByRole('dialog',{name:'Review skill update',exact:true}); await review.waitFor(); assert.equal(await review.getByRole('textbox',{name:'Skill update name',exact:true}).inputValue(),'My Word workflow'); assert.equal(await review.getByRole('button',{name:'Update skill',exact:true}).isDisabled(),true); assert.equal(await page.getByRole('button',{name:'Import skill',exact:true}).count(),0); assert.equal(await page.evaluate(()=>window.events.find(event=>event[0]==='updatePreview')[1]),'legacy-docx'); await review.getByRole('button',{name:'Cancel',exact:true}).click(); assert.equal(await page.evaluate(()=>window.events.filter(event=>event[0]==='import'||event[0]==='checkUpdates'||event[0]==='updateSkill').length),0); assert.equal(await page.evaluate(()=>window.skills.length),4); assert.deepEqual(errors,[]); console.log('PASS four source-less legacy imports become Installed from metadata published before Browse resolves; IDs/content/labels preserved, no check/download/reinstall on Browse, and recognized Preview uses installed update review.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
