// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skills-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button = name => page.getByRole('button', { name, exact: true }), menu = name => page.getByRole('menuitem', { name, exact: true })
  await button('New skill').click(); await page.getByRole('textbox', { name: 'Skill name', exact: true }).fill('Review checklist'); await page.getByRole('textbox', { name: 'Skill instructions', exact: true }).fill('Check correctness and clarity.')
  await page.evaluate(() => { window.failSave = true }); await button('Save skill').click(); await page.getByRole('alert').filter({ hasText: 'Could not save' }).waitFor(); assert.equal(await page.getByRole('textbox', { name: 'Skill instructions', exact: true }).inputValue(), 'Check correctness and clarity.')
  await page.evaluate(() => { window.failSave = false; window.holdSave = true }); await button('Save skill').click(); await page.waitForFunction(() => !!window.finishSave)
  assert.equal(await page.getByRole('textbox', { name: 'Skill name', exact: true }).isDisabled(), true); await page.keyboard.press('Escape'); assert.equal(await page.getByRole('dialog').count(), 1)
  const guard = await page.evaluate(async () => { try { for (const flush of window.flushers.values()) await flush(); return '' } catch (error) { return error.message } }); assert.match(guard, /Wait for/)
  await page.evaluate(() => { window.holdSave = false; window.finishSave() }); await button('Edit skill Review checklist').waitFor()
  await page.getByRole('textbox', { name: 'Search skills', exact: true }).fill('Review'); assert.equal(await button('Edit skill Writing style').count(), 0); await page.getByRole('textbox', { name: 'Search skills', exact: true }).fill('')
  await button('Edit skill Writing style').click(); await page.getByRole('textbox', { name: 'Skill instructions', exact: true }).fill('Keep my pending input.'); await page.evaluate(() => window.refreshSkill()); assert.equal(await page.getByRole('textbox', { name: 'Skill instructions', exact: true }).inputValue(), 'Keep my pending input.')
  await button('Cancel').click(); await page.getByRole('dialog', { name: 'Discard skill changes?' }).waitFor(); await button('Keep editing').click(); await button('Save skill').click(); await button('Edit skill Writing style').waitFor()
  await button('Edit skill Writing style').click({ button: 'right' }); assert.deepEqual(await page.getByRole('menuitem').allTextContents(), ['Edit', 'Rename', 'Duplicate', 'Export', 'Delete']); await menu('Rename').click(); await page.getByRole('textbox', { name: 'Skill name', exact: true }).fill('House style'); await button('Rename').click(); await button('Edit skill House style').waitFor()
  await button('Actions for skill House style').click(); await menu('Export').click(); await page.waitForFunction(() => window.events.some(e => e[0] === 'export' && e[1] === 'writing'))
  await button('Actions for skill House style').click(); await menu('Duplicate').click(); await page.getByRole('textbox', { name: 'Skill name', exact: true }).waitFor(); assert.equal(await page.getByRole('textbox', { name: 'Skill name', exact: true }).inputValue(), 'House style copy'); await button('Save skill').click()
  await button('Edit skill House style').click(); await button('Add files').click(); await button('Style guide.txt').waitFor(); await button('Style guide.txt').click(); await page.getByRole('dialog', { name: 'Style guide.txt', exact: true }).waitFor(); assert.equal(await page.getByRole('dialog', { name: 'Style guide.txt', exact: true }).locator('pre').innerText(), 'Prefer concrete words.'); await page.keyboard.press('Escape')
  await button('Style guide.txt').click({ button: 'right' }); await menu('Remove').click(); await button('Style guide.txt').waitFor({ state: 'detached' }); await button('Save skill').click()
  await button('Actions for skill House style copy').click(); await menu('Delete').click(); await page.getByRole('dialog', { name: 'Delete skill?' }).waitFor(); assert.match(await page.getByRole('dialog').innerText(), /Previously sent chats retain their skill snapshots/); await button('Delete skill').click(); await button('Edit skill House style copy').waitFor({ state: 'detached' })
  await button('New skill').click(); await page.getByRole('textbox', { name: 'Skill name', exact: true }).fill('References draft'); await button('Add files').click(); await button('Style guide.txt').waitFor(); await page.evaluate(() => { window.failFiles = true }); await button('Save skill').click(); await page.getByRole('alert').filter({ hasText: 'Reference text exceeds' }).waitFor(); await page.getByRole('textbox', { name: 'Skill instructions', exact: true }).fill('Pending after partial save.');
  const partialId = await page.evaluate(() => window.skills.find(s => s.name === 'References draft').id); await page.evaluate(() => { window.failFiles = false }); await button('Save skill').click(); await button('Edit skill References draft').waitFor(); assert.equal(await page.evaluate(() => window.skills.filter(s => s.name === 'References draft').length), 1); assert.equal(await page.evaluate(() => window.skills.find(s => s.name === 'References draft').id), partialId)
  await button('Edit skill References draft').click(); await page.screenshot({ path: '.local-data/skills-editor.png' }); await page.evaluate(() => document.documentElement.dataset.theme = 'dark'); await page.screenshot({ path: '.local-data/skills-editor-dark.png' }); await page.evaluate(() => delete document.documentElement.dataset.theme); await button('Cancel').click(); await button('Actions for skill References draft').click(); await menu('Delete').click(); await button('Delete skill').click(); await button('Edit skill References draft').waitFor({ state: 'detached' })
  await page.screenshot({ path: '.local-data/skills-library.png' }); await page.evaluate(() => document.documentElement.dataset.theme = 'dark'); await page.screenshot({ path: '.local-data/skills-library-dark.png' }); await page.evaluate(() => delete document.documentElement.dataset.theme)
  await button('Browse skills').click(); await page.getByRole('heading',{name:'Browse skills',exact:true}).waitFor();
  await button('Picker fixture').click(); await page.getByRole('button', { name: 'Skills, 1 enabled', exact: true }).click(); assert.equal(await page.getByRole('checkbox', { name: 'Use project skills', exact: true }).isChecked(), true); assert.equal(await page.getByRole('checkbox', { name: 'Enable skill House style', exact: true }).isChecked(), true)
  await button('No skills').click(); assert.equal(await page.locator('output').innerText(), '[]'); await page.getByRole('checkbox', { name: 'Enable skill Review checklist', exact: true }).check(); assert.equal((await page.evaluate(() => window.selection)).length, 1)
  await page.getByRole('checkbox', { name: 'Use project skills', exact: true }).check(); assert.equal(await page.locator('output').innerText(), 'null'); await page.getByRole('checkbox', { name: 'Enable skill House style', exact: true }).click({ button: 'right' }); assert.deepEqual(await page.getByRole('menuitem').allTextContents(), ['Edit', 'Rename', 'Duplicate', 'Export', 'Delete']); await page.keyboard.press('Escape')
  await page.screenshot({ path: '.local-data/skills-picker.png' }); await button('Manage skills').click(); await button('New skill').waitFor({timeout:2000})
  await button('Actions for skill House style').focus(); await page.keyboard.press('Enter'); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter'); await page.getByRole('dialog').waitFor(); await button('Cancel').click()
  assert.deepEqual(errors, []); console.log('PASS Skills library CRUD, both action menus, keyboard access, save failure and pending guards, async edit retention, reference preview/removal, picker inheritance and explicit disable. Screenshots in .local-data/skills-*.png')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
