// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skill-browser-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button=name=>page.getByRole('button',{name,exact:true}), menu=name=>page.getByRole('menuitem',{name,exact:true})
  await button('Browse skills').waitFor(); await page.evaluate(()=>window.failBrowse=true); await button('Browse skills').click(); await page.getByRole('alert').filter({hasText:'Curated list unavailable'}).waitFor(); await page.evaluate(()=>window.failBrowse=false); await button('Try again').click(); await button('Preview skill docx').waitFor(); assert.equal(await page.locator('.skill-catalog-row').count(),6); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='catalogPreview').length),0)
  await page.getByRole('textbox',{name:'Search curated skills'}).fill('pdf'); assert.equal(await page.locator('.skill-catalog-row').count(),1); await page.getByRole('textbox',{name:'Search curated skills'}).fill('does not exist'); await page.getByText('No curated skills match',{exact:false}).waitFor(); await page.getByRole('textbox',{name:'Search curated skills'}).fill('')
  await button('Preview skill docx').click({button:'right'}); assert.deepEqual(await page.getByRole('menuitem').allTextContents(),['Preview','View on skills.sh','View source']); await menu('View source').click(); await page.waitForFunction(()=>window.events.some(e=>e[0]==='openLink'&&e[1]==='https://github.com/anthropics/skills/tree/main/skills/docx')); await button('Actions for catalog skill docx').click(); await menu('View on skills.sh').click(); await page.waitForFunction(()=>window.events.some(e=>e[0]==='openLink'&&e[1]==='https://skills.sh/anthropics/skills/docx')); await button('Explore skills.sh').click(); await page.waitForFunction(()=>window.events.some(e=>e[0]==='openLink'&&e[1]==='https://skills.sh'))
  await page.evaluate(()=>window.failCatalog=true); await button('Preview skill docx').click(); await page.getByRole('alert').filter({hasText:'Could not download'}).waitFor(); assert.equal(await page.getByRole('dialog').count(),0); await page.evaluate(()=>{window.failCatalog=false;window.holdCatalog=true}); await button('Preview skill docx').click(); await page.waitForFunction(()=>!!window.finishCatalog); assert.equal(await button('Back to library').isDisabled(),true); const guard=await page.evaluate(async()=>{try{for(const f of window.flushers.values())await f();return ''}catch(e){return e.message}}); assert.match(guard,/Wait for/); await page.evaluate(()=>{window.holdCatalog=false;window.finishCatalog()}); const review=page.getByRole('dialog',{name:'Import skill',exact:true}); await review.waitFor(); await review.getByText('Requires external scripts and tools; these do not run in zQ.',{exact:true}).waitFor(); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='import').length),0); await review.getByRole('button',{name:'Cancel',exact:true}).click(); await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Preview skill docx')
  await button('Preview skill docx').click({button:'right'}); await menu('Preview').click(); await review.waitFor(); await review.getByRole('button',{name:'Import skill',exact:true}).click(); await review.waitFor({state:'detached'}); await page.getByRole('status').filter({hasText:'docx imported.'}).waitFor(); assert.equal(await page.evaluate(()=>window.selection),null); await page.screenshot({path:'.local-data/skill-browser.png'}); await button('Back to library').click(); await button('Edit skill docx').waitFor(); await page.waitForFunction(()=>document.activeElement?.textContent==='Browse skills')
  await page.evaluate(()=>window.fillLibrary()); await button('Browse skills').click(); await button('Preview skill docx').click(); await review.waitFor(); assert.equal(await review.getByRole('button',{name:'Import skill',exact:true}).isDisabled(),true); assert.equal(await review.getByRole('button',{name:'Cancel',exact:true}).isEnabled(),true); await review.getByRole('button',{name:'Cancel',exact:true}).click(); await button('Back to library').click(); await button('Browse skills').waitFor(); assert.deepEqual(errors,[]); console.log('PASS curated list/retry/search, honest catalog scope, source/catalog menus, package preview failure/pending guard, shared import review, requirements, focus, no auto-enable and full-library browse.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
