// Run from the repository root: node apps/desktop/tests/skills-shell.browser.cjs
// Uses isolated fixtures and a temporary local server; no workspace or provider writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require('playwright-core');
(async()=>{const {build}=await import('vite'),{default:react}=await import('@vitejs/plugin-react'),{default:tailwind}=await import('@tailwindcss/vite');const root=path.resolve('.local-data/skill-import-browser');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'index.html'),'<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>');fs.writeFileSync(path.join(root,'main.tsx'),"import '../../apps/desktop/tests/fixtures/skills'");await build({root,configFile:false,logLevel:'error',plugins:[react(),tailwind()],resolve:{dedupe:['react','react-dom','radix-ui']}});const dist=path.join(root,'dist');const server=http.createServer((req,res)=>{const file=path.join(dist,new URL(req.url,'http://localhost').pathname);const target=file===dist+'/'?path.join(dist,'index.html'):file;if(!target.startsWith(dist)||!fs.existsSync(target)){res.writeHead(404).end();return}res.setHeader('Content-Type',/\.js$/.test(target)?'text/javascript':/\.css$/.test(target)?'text/css':'text/html');fs.createReadStream(target).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1200,height:850}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(2000);await page.goto(`http://127.0.0.1:${server.address().port}`);
const upload=page.getByRole('button',{name:'Import skill',exact:true});await upload.click();const preview=page.getByRole('dialog',{name:'Import skill'});await preview.waitFor();assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='import').length),0);
await preview.getByText('Preserve exact instructions.',{exact:true}).waitFor();await preview.getByText('Extra metadata was not imported.',{exact:true}).waitFor();await preview.getByRole('button',{name:'Preview guide.md'}).click();await page.getByRole('dialog',{name:'guide.md'}).getByText('Reference body').waitFor();await page.keyboard.press('Escape');await page.getByRole('dialog',{name:'guide.md'}).waitFor({state:'detached'});await page.waitForFunction(()=>document.activeElement?.getAttribute('aria-label')==='Preview guide.md');
await preview.getByLabel('Imported skill name').fill('Imported house style');await page.screenshot({path:'.local-data/skill-import-preview.png'});await page.evaluate(()=>window.failImport=true);await preview.getByRole('button',{name:'Import skill',exact:true}).click();await preview.getByRole('alert').filter({hasText:'Could not import'}).waitFor();assert.equal(await preview.getByLabel('Imported skill name').inputValue(),'Imported house style');
await page.evaluate(()=>{window.failImport=false;window.holdImport=true});await preview.getByRole('button',{name:'Import skill',exact:true}).click();await page.waitForFunction(()=>!!window.finishImport);await page.keyboard.press('Escape');assert.equal(await preview.count(),1);assert.equal(await preview.getByRole('button',{name:'Cancel',exact:true}).isDisabled(),true);await page.evaluate(()=>window.finishImport());await preview.waitFor({state:'detached'});await page.getByRole('button',{name:'Edit skill Imported house style',exact:true}).waitFor();
await page.evaluate(()=>window.cancelImport=true);await upload.click();assert.equal(await page.getByRole('dialog').count(),0);await page.evaluate(()=>{window.cancelImport=false;window.importError=true});await upload.click();await page.getByRole('alert').filter({hasText:'Invalid skill file'}).waitFor();
assert.deepEqual(errors,[]);console.log('PASS import preview, reference preview, metadata notice, editable name, no early writes, failed import retention/retry, pending guard, native cancel/error.');}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
