const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ChatService}=require('../electron/chat-service.cjs'),{parseSkillEntries,parseSkillPackage}=require('../electron/skill-package.cjs');
function fixture(t){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-standard-skills-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return new ChatService({directory})}
const raw=Buffer.from([0,255,12,1]);
const source=()=>parseSkillEntries([{path:'SKILL.md',bytes:Buffer.from('---\nname: writing\ndescription: Clear writing\nlicense: MIT\nmetadata:\n  author: example\nallowed-tools: Read\n---\nUse [guide](references/guide.md).\n')},{path:'references/guide.md',bytes:Buffer.from('Preserve exact guide.\n')},{path:'assets/template.bin',bytes:raw},{path:'scripts/run.py',bytes:Buffer.from('print("example")\n')}]);
test('standard packages persist binary resources once, duplicate, edit and export interoperably',async t=>{const s=fixture(t),draft=await source(),created=s.importSkill(draft);assert.equal(created.package.resources.length,3);assert(created.package.resources.every(f=>!('data' in f)));const copy=s.duplicateSkill(created.id);assert.deepEqual(copy.package,created.package);assert.equal(fs.readdirSync(s.skillResources.directory).length,3);s.saveSkill({id:created.id,name:'Writing style',instructions:'Changed body\n'});const loaded=new ChatService({directory:s.store.directory}),out=await loaded.exportSkillPackage(created.id),parsed=await parseSkillPackage({name:out.name,bytes:out.bytes});assert.match(out.name,/\.zip$/);assert.equal(parsed.name,'writing-style');assert.equal(parsed.instructions,'Changed body\n');assert.match(parsed.package.frontmatter,/license: MIT/);assert.match(parsed.package.frontmatter,/author: example/);assert.deepEqual(Buffer.from(parsed.package.resources.find(f=>f.path==='assets/template.bin').data,'base64'),raw);assert.equal(loaded.previewSkillResource({id:created.id,path:'scripts/run.py'}).text,'print("example")\n');assert.equal(loaded.previewSkillResource({id:created.id,path:'assets/template.bin'}).text,undefined);assert.throws(()=>loaded.skillResource({id:created.id,path:'../secret'}));loaded.removeSkillFile({id:created.id,attachmentId:loaded.state.skills.find(x=>x.id===created.id).files[0].id});assert.equal(loaded.state.skills.find(x=>x.id===created.id).package.resources.length,3)});
test('failed import rolls back new resource blobs and leaves existing shared bytes intact',async t=>{const s=fixture(t),first=await source();s.importSkill(first);const files=fs.readdirSync(s.skillResources.directory),before=structuredClone(s.state),other=await parseSkillEntries([{path:'SKILL.md',bytes:Buffer.from('---\nname: another\ndescription: Example\n---\nTest')},{path:'assets/new.bin',bytes:Buffer.from('unique bytes')}]);s.store.save=()=>{throw Error('Disk full')};assert.throws(()=>s.importSkill(other),/Disk full/);assert.deepEqual(s.state,before);assert.deepEqual(fs.readdirSync(s.skillResources.directory),files);assert.throws(()=>s.importSkill(first),/Disk full/);assert.deepEqual(fs.readdirSync(s.skillResources.directory),files)});
test('large standard instructions import intact but cannot exceed chat context budget',async t=>{const s=fixture(t),p=await parseSkillEntries([{path:'SKILL.md',bytes:Buffer.from('---\nname: long-skill\ndescription: Large reference\n---\n'+'a'.repeat(120000))}]),created=s.importSkill(p);assert.equal(s.state.skills[0].instructions.length,120000);const inspected=s.inspectContext({text:'Hello',skillIds:[created.id]});assert.match(inspected.error,/100 KB/)});
test('an import committed before a metadata flush failure remains usable and reports success with a warning',async t=>{
 const s=fixture(t),draft=await source(),rename=fs.renameSync,sync=fs.fsyncSync;let renamed=false,created;
 try{
  fs.renameSync=(from,to)=>{const result=rename(from,to);if(to===s.store.path)renamed=true;return result};
  fs.fsyncSync=fd=>{if(renamed&&fs.fstatSync(fd).isDirectory())throw Error('Injected metadata directory flush failure');return sync(fd)};
  created=s.importSkill(draft);
 }finally{fs.renameSync=rename;fs.fsyncSync=sync}
 assert.equal(s.state.skills.length,1);assert.equal(created.id,s.state.skills[0].id);assert.match(s.snapshot().error,/saved.*flush/i);
 const restored=new ChatService({directory:s.store.directory});assert.equal(restored.state.skills.length,1);assert.deepEqual(restored.skillResource({id:created.id,path:'assets/template.bin'}).bytes,raw);
 s.saveSkill({id:created.id,description:'After recovery'});assert.equal(s.snapshot().error,'');assert.equal(new ChatService({directory:s.store.directory}).state.skills.length,1);
});
test('notification failure after a skill import does not roll back committed resources',async t=>{
 const s=fixture(t),draft=await source();s.onChange=()=>{throw Error('Window closed')};const created=s.importSkill(draft);
 assert.deepEqual(new ChatService({directory:s.store.directory}).skillResource({id:created.id,path:'assets/template.bin'}).bytes,raw);
});
