// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skills-composer-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills-chat'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.setDefaultTimeout(5000); page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button=name=>page.getByRole('button',{name,exact:true}),menu=name=>page.getByRole('menuitem',{name,exact:true}),message=page.getByRole('textbox',{name:'Chat message',exact:true})
  const openSkills=async()=>{await button('Add attachments').click();await page.getByRole('menuitem',{name:/^Skills/}).click();await page.getByRole('menuitemcheckbox',{name:/^(Use project skills|Automatic)/}).waitFor()},closeSkills=async()=>{await page.keyboard.press('Escape');await page.keyboard.press('Escape')}
  await message.waitFor(); await page.evaluate(()=>window.installSlashSkills()); assert.equal(await page.locator('.composer-actions .skill-picker-trigger').count(),0); await openSkills(); assert.equal(await page.getByRole('menuitemcheckbox',{name:'Writing style',exact:true}).getAttribute('aria-checked'),'true'); await page.getByRole('menuitemcheckbox',{name:'Code review',exact:true}).click(); assert.deepEqual(await page.evaluate(()=>window.chatState.skillChoices['new:general']),['writing','skill-1']); await menu('No skills').click(); assert.deepEqual(await page.evaluate(()=>window.chatState.skillChoices['new:general']),[]); await closeSkills()
  await button('Add attachments').focus(); await page.keyboard.press('Enter'); await page.getByRole('menuitem',{name:/^Skills/}).focus(); await page.keyboard.press('ArrowRight'); await page.getByRole('menuitemcheckbox',{name:'Code review',exact:true}).focus(); await page.keyboard.press('Enter'); assert.deepEqual(await page.evaluate(()=>window.chatState.skillChoices['new:general']),['skill-1']); await closeSkills()
  await openSkills(); await page.getByRole('menuitemcheckbox',{name:'Code review',exact:true}).click({button:'right'}); const actions=page.getByRole('menu',{name:'Skill actions for Code review',exact:true}); await actions.waitFor(); assert.deepEqual(await actions.getByRole('menuitem').allTextContents(),['Edit','Rename','Duplicate','Export','Delete']); await actions.getByRole('menuitem',{name:'Edit',exact:true}).click(); await page.getByRole('dialog',{name:'Edit skill',exact:true}).waitFor(); assert.equal(await page.getByRole('textbox',{name:'Skill name',exact:true}).inputValue(),'Code review'); await button('Cancel').click()
  await openSkills(); await menu('Manage skills').click(); await button('New skill').waitFor(); assert.equal(await page.getByRole('heading',{name:'Browse skills',exact:true}).count(),0); await button('Return to composer').click(); await openSkills(); await menu('Browse skills').click(); await page.getByRole('heading',{name:'Browse skills',exact:true}).waitFor(); await button('Return to composer').click()
  await message.fill('/'); const list=page.getByRole('listbox',{name:'Installed skills',exact:true}); await list.waitFor(); assert.equal(await list.getByRole('option').count(),3); await page.keyboard.press('ArrowDown'); await page.keyboard.press('Enter'); await list.waitFor({state:'detached'}); assert.equal(await message.inputValue(),'/code-review '); assert.equal(await page.locator('.skill-command-highlight').textContent(),'/code-review'); assert.deepEqual(await page.evaluate(()=>window.chatState.skillChoices['new:general']),['skill-1']); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='send').length),0)
  await message.fill('Before /Research notes after'); for(let i=0;i<6;i++)await page.keyboard.press('ArrowLeft'); await list.waitFor(); await list.getByRole('option',{name:'Research notes Installed skill 2',exact:true}).click(); assert.equal(await message.inputValue(),'Before /research-notes after'); await page.waitForFunction(()=>document.querySelector('[aria-label="Chat message"]').selectionStart===23); assert.deepEqual(await page.evaluate(()=>window.chatState.skillChoices['new:general']),['skill-2']); await page.keyboard.type('please '); assert.equal(await list.count(),0); assert.equal(await message.inputValue(),'Before /research-notes please after'); await page.screenshot({path:'.local-data/skill-command-inline.png'}); await message.fill('/research-notes '+('A line of the draft.\n'.repeat(35))); await message.evaluate(el=>{el.scrollTop=el.scrollHeight;el.dispatchEvent(new Event('scroll'))}); assert.equal(await page.locator('.skill-draft-highlights').evaluate(el=>el.scrollTop),await message.evaluate(el=>el.scrollTop)); assert.equal(await page.locator('.skill-command-highlight').count(),1)
  await message.fill('/Writ'); await list.waitFor(); await page.keyboard.press('Escape'); await list.waitFor({state:'detached'}); assert.equal(await message.inputValue(),'/Writ'); await message.fill('1 / 2'); assert.equal(await list.count(),0)
  await message.fill('/Research'); await list.waitFor(); await list.getByRole('option').focus(); await page.keyboard.press('Escape'); await list.waitFor({state:'detached',timeout:1500}); assert.equal(await message.inputValue(),'/Research'); assert.equal(await message.evaluate(el=>document.activeElement===el),true)
  await message.fill('/unknown'); await page.getByText('No matching installed skills.',{exact:true}).waitFor(); await page.keyboard.press('Enter'); assert.equal(await message.inputValue(),'/unknown'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='send').length),0)
  await message.fill('/Writing'); await list.waitFor(); await message.evaluate(el=>el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,isComposing:true}))); assert.equal(await message.inputValue(),'/Writing'); assert.equal(await page.evaluate(()=>window.events.filter(e=>e[0]==='send').length),0); await page.keyboard.press('Escape')
  await message.fill('/Code'); await list.waitFor(); await list.getByRole('option').click({button:'right'}); await page.getByRole('menu',{name:'Skill actions for Code review',exact:true}).getByRole('menuitem',{name:'Rename',exact:true}).click(); await page.getByRole('dialog',{name:'Rename skill',exact:true}).waitFor(); await button('Cancel').click()
  await page.evaluate(()=>{window.installSlashSkills(11);window.chatState.setSkillChoices('new:general',Array.from({length:10},(_,i)=>i===0?'writing':'skill-'+i))}); await message.fill('/Skill 10'); await list.waitFor(); assert.equal(await list.getByRole('option').isDisabled(),true); await page.keyboard.press('Enter'); assert.equal(await message.inputValue(),'/Skill 10'); assert.equal(await page.evaluate(()=>window.chatState.skillChoices['new:general'].length),10); await page.keyboard.press('Escape')
  await page.evaluate(()=>{window.installSlashSkills(30);window.chatState.setSkillChoices('new:general',[])}); await message.fill('/'); await list.waitFor(); for(let i=0;i<20;i++)await page.keyboard.press('ArrowDown'); const activeId=await message.getAttribute('aria-activedescendant'); assert.match(activeId,/skill-20$/); assert.equal(await page.locator('.skill-slash-list').evaluate(el=>el.scrollTop>0),true); await page.screenshot({path:'.local-data/skills-slash-menu.png'}); await page.keyboard.press('Escape'); assert.equal(await button('Send message').isDisabled(),true)
  await message.fill('1 / 2'); await page.keyboard.press('Meta+Enter'); await page.waitForFunction(()=>window.events.filter(e=>e[0]==='send').length===1); assert.equal(await page.evaluate(()=>window.events.find(e=>e[0]==='send')[1].text),'1 / 2'); await openSkills(); await page.screenshot({path:'.local-data/skills-composer-submenu.png'}); await closeSkills(); await message.fill('/Writing'); await list.waitFor(); await list.getByRole('option',{name:'Writing style Clear prose',exact:true}).click(); await page.keyboard.type('Make this concise.'); await page.keyboard.press('Enter'); await page.waitForFunction(()=>window.events.filter(e=>e[0]==='send').length===2); const invoked=await page.evaluate(()=>window.events.filter(e=>e[0]==='send')[1][1]); assert.equal(invoked.text,'/writing-style Make this concise.'); assert.deepEqual(invoked.skillIds,['writing']); await page.evaluate(()=>window.installCollidingSkills()); await message.fill('/Code'); await list.waitFor(); await list.getByRole('option',{name:'Code review Clear prose',exact:true}).click(); const firstCommand=(await message.inputValue()).trim(); await page.keyboard.type('/Code'); await list.waitFor(); await list.getByRole('option',{name:'Code-review Clear prose',exact:true}).click(); const both=await message.inputValue(),secondCommand=both.trim().split(' ').at(-1); assert.notEqual(firstCommand,secondCommand); await message.fill(secondCommand+' remains'); assert.deepEqual(await page.evaluate(()=>window.chatState.skillChoices[window.chatState.draftId]),['second-two']); assert.equal(await page.locator('.skill-command-highlight').textContent(),secondCommand); assert.deepEqual(errors,[]); console.log('PASS + Skills submenu selection/inheritance actions, keyboard/rightclick parity, direct Manage/Browse, slash filtering/full names, explicit invoke preserving text/caret, Escape/IME/no-match/cap guards, long-list scroll and ordinary arithmetic/CmdEnter send.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
