// Isolated React fixtures; no reads or writes to the user's workspace.
const assert = require('node:assert/strict'), fs = require('node:fs'), path = require('node:path'), http = require('node:http')
const { chromium } = require('playwright-core')
;(async () => {
 const { build } = await import('vite'), { default: react } = await import('@vitejs/plugin-react'), { default: tailwind } = await import('@tailwindcss/vite')
 const root = path.resolve('.local-data/skills-chat-browser'); fs.mkdirSync(root, { recursive: true })
 fs.writeFileSync(path.join(root, 'index.html'), '<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>')
 fs.writeFileSync(path.join(root, 'main.tsx'), "import '../../apps/desktop/tests/fixtures/skills-chat'")
 await build({ root, configFile: false, logLevel: 'error', plugins: [react(), tailwind()], resolve: { dedupe: ['react', 'react-dom', 'radix-ui'] } })
 const dist = path.join(root, 'dist'), server = http.createServer((req, res) => { const p = new URL(req.url, 'http://localhost').pathname, file = path.join(dist, p === '/' ? 'index.html' : p); if (!file.startsWith(dist) || !fs.existsSync(file)) { res.writeHead(404).end(); return }; res.setHeader('Content-Type', /\.js$/.test(file) ? 'text/javascript' : /\.css$/.test(file) ? 'text/css' : 'text/html'); fs.createReadStream(file).pipe(res) })
 await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); let browser
 try {
  browser = await chromium.launch({ channel: 'chrome', headless: true }); const page = await browser.newPage({ viewport: { width: 1200, height: 900 }, reducedMotion: 'reduce' }), errors = []
  page.on('pageerror', error => errors.push(error.message)); await page.goto(`http://127.0.0.1:${server.address().port}`)
  const button = name => page.getByRole('button', { name, exact: true })
  await page.getByRole('textbox', { name: 'Chat message', exact: true }).waitFor(); assert.equal(await page.getByRole('textbox', { name: 'Chat message', exact: true }).inputValue(), 'Hydrated message')
  const openSkills=async()=>{await button('Add attachments').click();await page.getByRole('menuitem',{name:/^Skills/}).click();await page.getByRole('menuitemcheckbox',{name:/^(Use project skills|Automatic)/}).waitFor()},closeSkills=async()=>{await page.keyboard.press('Escape');await page.keyboard.press('Escape')}; await openSkills(); assert.equal(await page.getByRole('menuitemcheckbox',{name:'Writing style',exact:true}).getAttribute('aria-checked'),'true'); assert.equal(await page.getByRole('menuitemcheckbox',{name:/^(Use project skills|Automatic)/}).getAttribute('aria-checked'),'false')
  await page.getByRole('menuitem',{name:'No skills',exact:true}).click(); await closeSkills(); await button('Send message').click(); await page.waitForFunction(() => window.events.some(event => event[0] === 'send')); assert.deepEqual(await page.evaluate(() => window.events.find(event => event[0] === 'send')[1].skillIds), [])
  assert.deepEqual(await page.evaluate(() => window.chatState.skillChoices['chat-1']), []); assert.equal(await page.evaluate(() => 'new:general' in window.chatState.skillChoices), false); assert.equal(await page.evaluate(() => window.events.find(event => event[0] === 'create')[1].draftFrom), 'new:general')
  await openSkills(); await page.getByRole('menuitemcheckbox',{name:'Writing style',exact:true}).click(); await closeSkills(); await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('Use the selected writing skill'); await button('Send message').click(); await page.waitForFunction(() => window.events.filter(event => event[0] === 'send').length === 2); assert.deepEqual(await page.evaluate(() => window.events.filter(event => event[0] === 'send')[1][1].skillIds), ['writing'])
  await button('Add attachments').click(); await page.getByRole('menuitem',{name:'View context',exact:true}).click(); const context = page.getByRole('dialog', {name:'Message context',exact:true}); await context.waitFor(); assert.equal(await context.locator('pre').first().innerText(), 'Use short sentences.'); await context.getByRole('heading', {name:'Writing style',exact:true}).click({button:'right'}); assert.deepEqual(await page.getByRole('menuitem').allTextContents(), ['Edit','Rename','Duplicate','Export','Delete']); await page.getByRole('menuitem', {name:'Edit',exact:true}).click(); await page.getByRole('dialog', {name:'Edit skill',exact:true}).waitFor(); assert.equal(await page.getByRole('textbox', {name:'Skill name',exact:true}).evaluate(el=>el===document.activeElement), true); await button('Cancel').click()
  await button('Open project draft').click(); await button('New chat').click(); await openSkills(); assert.equal(await page.getByRole('menuitemcheckbox',{name:/^(Use project skills|Automatic)/}).getAttribute('aria-checked'),'true'); await closeSkills(); await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('Inherit the project skill'); await button('Send message').click(); await page.waitForFunction(() => window.events.filter(event => event[0] === 'send').length === 3); assert.equal(await page.evaluate(() => window.events.filter(event => event[0] === 'send')[2][1].skillIds), null)
  await button('Open first chat').click(); await button('Add attachments').waitFor(); await page.evaluate(() => window.deleteLibrarySkill()); await button('Add attachments').waitFor(); await page.waitForFunction(() => JSON.stringify(window.chatState.skillChoices['chat-1']) === '[]'); await page.getByRole('textbox', { name: 'Chat message', exact: true }).fill('After deleting the skill'); await button('Send message').click(); await page.waitForFunction(() => window.events.filter(event => event[0] === 'send').length === 4); assert.deepEqual(await page.evaluate(() => window.events.filter(event => event[0] === 'send')[3][1].skillIds), [])
  await page.screenshot({ path: '.local-data/skills-chat-composer.png' }); assert.deepEqual(errors, []); console.log('PASS actual useChat + ChatView hydrated skill selection, no-skills override, first-send draft transfer, explicit and inherited send.skillIds, deleted skill reconciliation.')
 } finally { await browser?.close(); server.close() }
})().catch(error => { console.error(error); process.exitCode = 1 })
