// Run from the repository root: node apps/desktop/tests/skills-shell.browser.cjs
// Uses isolated fixtures and a temporary local server; no workspace or provider writes.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');const {chromium}=require('playwright-core');
(async()=>{const {build}=await import('vite'),{default:react}=await import('@vitejs/plugin-react'),{default:tailwind}=await import('@tailwindcss/vite');const root=path.resolve('.local-data/skills-shell-browser');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'index.html'),'<html><body><div id="root"></div><script type="module" src="./main.tsx"></script></body></html>');fs.writeFileSync(path.join(root,'main.tsx'),"import '../../apps/desktop/tests/fixtures/skills-shell'");await build({root,configFile:false,logLevel:'error',plugins:[react(),tailwind()],resolve:{dedupe:['react','react-dom','radix-ui']}});const dist=path.join(root,'dist');const server=http.createServer((req,res)=>{const file=path.join(dist,new URL(req.url,'http://localhost').pathname);const target=file===dist+'/'?path.join(dist,'index.html'):file;if(!target.startsWith(dist)||!fs.existsSync(target)){res.writeHead(404).end();return}res.setHeader('Content-Type',/\.js$/.test(target)?'text/javascript':/\.css$/.test(target)?'text/css':'text/html');fs.createReadStream(target).pipe(res)});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1200,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(`http://127.0.0.1:${server.address().port}`);
await page.getByRole('button',{name:'Manage skills from chat'}).click();await page.getByRole('button',{name:'New skill',exact:true}).waitFor();
assert.equal(await page.getByRole('heading',{name:'Connections fixture'}).isVisible(),false);
await page.getByRole('button',{name:'Appearance',exact:true}).last().click();await page.getByRole('heading',{name:'Your space, your way.'}).waitFor();assert.equal(await page.getByRole('button',{name:'New skill',exact:true}).isVisible(),false);
await page.getByRole('button',{name:'Skills',exact:true}).click();await page.getByRole('button',{name:'New skill',exact:true}).click();await page.getByRole('textbox',{name:'Skill name'}).fill('Unsaved skill');
await page.keyboard.press('Meta+k');assert.equal(await page.getByRole('textbox',{name:'Search workspace'}).count(),0);await page.evaluate(()=>window.nativeCommand('settings'));await page.getByRole('textbox',{name:'Skill name'}).waitFor();
await page.keyboard.press('Escape');await page.getByRole('heading',{name:'Discard skill changes?'}).waitFor();await page.getByRole('button',{name:'Keep editing'}).click();assert.equal(await page.getByRole('textbox',{name:'Skill name'}).inputValue(),'Unsaved skill');
await page.getByRole('button',{name:'Cancel',exact:true}).click();await page.getByRole('button',{name:'Discard changes',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Manage skills from chat'}).waitFor();
assert.deepEqual(errors,[]);console.log('PASS real shell Skills portal, Appearance preserved, modal keyboard/native command guards, dirty dismiss, and Escape returns to Chat.');}finally{await browser?.close();server.close()}})().catch(e=>{console.error(e);process.exitCode=1});
