const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {VoiceService}=require('../electron/voice-service.cjs');
const {transcribeOpenAI}=require('../electron/voice-service.cjs');
function wav(){const b=Buffer.alloc(3244);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(1,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(32000,28);b.writeUInt16LE(2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(3200,40);b.writeInt16LE(1000,44);return b}
function setup(t,options={}){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'zq-voice-test-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));return new VoiceService({directory,localAvailability:async()=>({available:true,engine:'Apple Speech',languages:['en-US'],message:'Ready'}),localTranscribe:async()=> 'Local words',...options})}
const connection={id:'openai',name:'OpenAI',provider:'openai',baseUrl:'https://api.openai.com/v1',credentialRef:'fixture-ref'};
test('saved settings survive restart and a recording keeps its original mode',async t=>{let uploads=0;const s=setup(t,{listConnections:()=>[connection],providerTranscribe:async()=>{uploads++;return 'Cloud words'}});const recording=await s.begin({originId:'chat-a'});s.save({...s.load(),mode:'provider',connectionId:'openai'});assert.equal(new VoiceService({directory:s.directory}).load().mode,'provider');assert.deepEqual(await s.transcribe({id:recording.id,audio:wav()}),{id:recording.id,originId:'chat-a',text:'Local words'});assert.equal(uploads,0)});
test('local failures never call a provider and temporary audio is removed',async t=>{let uploads=0,temporary;const s=setup(t,{localTranscribe:async({file})=>{temporary=file;assert.ok(fs.existsSync(file));throw Error('Local model missing')},providerTranscribe:async()=>{uploads++;return 'bad'}});const r=await s.begin({originId:'chat'});await assert.rejects(s.transcribe({id:r.id,audio:wav()}),/Local model missing/);assert.equal(uploads,0);assert.equal(fs.existsSync(temporary),false)});
test('cancel prevents upload, rejects stale work, and releases the global recorder',async t=>{const s=setup(t);const r=await s.begin({originId:'a'});await assert.rejects(s.begin({originId:'b'}),/already/);s.cancel(r.id);await assert.rejects(s.transcribe({id:r.id,audio:wav()}),/no longer/);assert.equal((await s.begin({originId:'b'})).originId,'b')});
test('cancel during transcription aborts work and suppresses its result',async t=>{let finish,signal;const s=setup(t,{localTranscribe:({signal:s})=>{signal=s;return new Promise(resolve=>{finish=resolve})}});const r=await s.begin({originId:'a'});const pending=s.transcribe({id:r.id,audio:wav()});await new Promise(resolve=>setImmediate(resolve));s.cancel(r.id);assert.equal(signal.aborted,true);finish('Stale words');await assert.rejects(pending,/canceled/);assert.equal(fs.readdirSync(path.join(s.directory,'voice-audio')).length,0)});
test('duplicate stop is rejected while native transcription is pending',async t=>{let finish;const s=setup(t,{localTranscribe:()=>new Promise(resolve=>{finish=resolve})});const r=await s.begin({originId:'a'});const pending=s.transcribe({id:r.id,audio:wav()});await new Promise(resolve=>setImmediate(resolve));await assert.rejects(s.transcribe({id:r.id,audio:wav()}),/already/);finish('One');assert.equal((await pending).text,'One')});
test('provider selection rejects incompatible endpoints and removed connections',async t=>{let connections=[{...connection,baseUrl:'https://example.com/v1'}];const s=setup(t,{listConnections:()=>connections});assert.throws(()=>s.save({...s.load(),mode:'provider',connectionId:'openai'}),/compatible/);connections=[connection];s.save({...s.load(),mode:'provider',connectionId:'openai'});connections=[];await assert.rejects(s.begin({originId:'a'}),/compatible/)});
test('local unavailable is rejected before recording and malformed audio is never processed',async t=>{const s=setup(t,{localAvailability:async()=>({available:false,message:'Language unavailable',languages:[],engine:'Apple Speech'})});await assert.rejects(s.begin({originId:'a'}),/Language unavailable/);const ready=setup(t);const r=await ready.begin({originId:'a'});await assert.rejects(ready.transcribe({id:r.id,audio:Buffer.from('bad')}),/audio/);assert.equal(ready.active,null)});
test('settings reads reject symlinks and oversize documents; explicit save preserves corruption',t=>{const s=setup(t);fs.writeFileSync(s.file,'broken');const reloaded=new VoiceService({directory:s.directory});assert.match(reloaded.loadWarning,/could not/);reloaded.save(reloaded.load());assert.ok(fs.readdirSync(s.directory).some(name=>name.startsWith('voice.json.corrupt-')));fs.rmSync(s.file);const outside=path.join(s.directory,'outside');fs.writeFileSync(outside,'private');fs.symlinkSync(outside,s.file);const linked=new VoiceService({directory:s.directory});assert.throws(()=>linked.save(linked.load()),/symbolic|regular/);assert.equal(fs.readFileSync(outside,'utf8'),'private');fs.rmSync(s.file);fs.writeFileSync(s.file,'x'.repeat(20000));assert.match(new VoiceService({directory:s.directory}).loadWarning,/could not/)});
test('audio directory cannot follow a symlink outside the Voice store',t=>{const s=setup(t);fs.rmdirSync(s.audioDirectory);const outside=fs.mkdtempSync(path.join(os.tmpdir(),'zq-voice-outside-'));t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));fs.symlinkSync(outside,s.audioDirectory);assert.throws(()=>new VoiceService({directory:s.directory}),/symbolic|directory/)});
test('provider payload uses bounded WAV upload and rejects oversize response',async()=>{let request;const config={model:'gpt-4o-mini-transcribe',language:'fr-FR'};const options={audio:wav(),config,connection,resolveCredential:async()=> 'fixture-only',signal:new AbortController().signal,fetchImpl:async(url,input)=>{request={url,input};return new Response(JSON.stringify({text:'Bonjour'}))}};assert.equal(await transcribeOpenAI(options),'Bonjour');assert.equal(request.url,'https://api.openai.com/v1/audio/transcriptions');assert.equal(request.input.body.get('language'),'fr');assert.equal(request.input.body.get('file').type,'audio/wav');assert.equal(request.input.redirect,'error');await assert.rejects(transcribeOpenAI({...options,fetchImpl:async()=>new Response('x'.repeat(300000))}),/too large/)});
test('transcript rejects NUL and overlong multibyte output before delivery',async t=>{for(const text of ['bad\0text','界'.repeat(24000)]){const s=setup(t,{localTranscribe:async()=>text}),r=await s.begin({originId:'chat'});await assert.rejects(s.transcribe({id:r.id,audio:wav()}),/transcript|speech|shorter/);assert.equal(s.active,null)}});
