const test=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {auth}=require('@modelcontextprotocol/client');const {NativeOAuthProvider}=require('../electron/mcp/oauth.cjs');const {SecretStore,createSafeFetch}=require('../electron/mcp/security.cjs');
const RESOURCE='https://workiq.svc.cloud.microsoft/mcp',AUTHORITY='https://login.microsoftonline.com/organizations/v2.0',PRM='https://workiq.svc.cloud.microsoft/.well-known/oauth-protected-resource/mcp',OIDC=AUTHORITY+'/.well-known/openid-configuration',TOKEN='https://login.microsoftonline.com/organizations/oauth2/v2.0/token';
const resource={resource:RESOURCE,authorization_servers:[AUTHORITY],scopes_supported:['fdcc1f02-fc51-4226-8753-f668596af7f7/WorkIQAgent.Ask'],bearer_methods_supported:['header']};
const metadata={issuer:'https://login.microsoftonline.com/{tenantid}/v2.0',authorization_endpoint:'https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize',token_endpoint:TOKEN,response_types_supported:['code'],token_endpoint_auth_methods_supported:['client_secret_post','private_key_jwt','client_secret_basic'],scopes_supported:['openid','profile','email','offline_access']};
function setup(t,extra={}){const map=new Map(),secrets=new SecretStore({get:async k=>map.get(k),set:async(k,v)=>map.set(k,v),delete:async k=>map.delete(k)},crypto.randomUUID());let opened;const provider=new NativeOAuthProvider({row:{url:RESOURCE,catalogId:'microsoft365',authType:'oauth',clientId:'ba081686-5d24-4bc6-a0d6-d034ecffed87',redirectPort:12798,redirectHost:'127.0.0.1',...extra},secrets,signal:new AbortController().signal,openExternal:async url=>{opened=new URL(url)},onAuthenticating:()=>{}});t.after(()=>provider.close());return {provider,secrets,opened:()=>opened}}
function fetcher(provider,overrides={},onToken=()=>{}){return createSafeFetch({credentialOrigin:new URL(RESOURCE).origin,tokenEndpoint:()=>provider.discovery?.authorizationServerMetadata?.token_endpoint,fetchImpl:async(input,init)=>{const url=String(input);if(url===PRM)return Response.json(overrides.resource??resource);if(url===OIDC)return Response.json(overrides.metadata??metadata);if(url===TOKEN){onToken(init);return Response.json({access_token:'fixture-only-access',refresh_token:'fixture-only-refresh',token_type:'Bearer',expires_in:3600})}throw Error('Unexpected request: '+url)}})}
test('published WorkIQ config prepares verified Entra discovery and completes public PKCE with its root callback',async t=>{
 const f=setup(t),p=f.provider;await p.start();assert.equal(p.redirectUrl,'http://127.0.0.1:12798/');let exchanges=0;
 const fetchFn=fetcher(p,{},init=>{exchanges++;assert.equal(init.body.get('resource'),null);assert.equal(new Headers(init.headers).get('authorization'),null);assert.equal(init.body.get('client_secret'),null);assert.equal(init.body.get('client_id'),'ba081686-5d24-4bc6-a0d6-d034ecffed87');assert.equal(crypto.createHash('sha256').update(init.body.get('code_verifier')).digest('base64url'),f.opened().searchParams.get('code_challenge'))});
 await p.prepare(fetchFn);assert.equal(f.opened(),undefined);assert.equal(exchanges,0);assert.equal(await auth(p,{serverUrl:RESOURCE,fetchFn}),'REDIRECT');assert.equal(f.opened().searchParams.get('resource'),null);const callback=new URL(p.redirectUrl);callback.searchParams.set('state',f.opened().searchParams.get('state'));callback.searchParams.set('code','fixture-code');assert.equal((await fetch(callback)).status,200);await p.finish(await p.callback,fetchFn);assert.equal(exchanges,1);assert.equal(p.tokens().access_token,'fixture-only-access');assert.match(f.opened().searchParams.get('scope'),/WorkIQAgent.Ask/);
});
test('WorkIQ discovery rejects changed issuers, endpoints and resource authorities before any browser or credentials',async t=>{
 const f=setup(t);await f.provider.start();for(const overrides of [{metadata:{...metadata,issuer:'https://evil.example/{tenantid}/v2.0'}},{metadata:{...metadata,token_endpoint:'https://evil.example/token'}},{metadata:{...metadata,authorization_endpoint:'https://evil.example/authorize'}},{resource:{...resource,authorization_servers:['https://evil.example']}},{resource:{...resource,resource:'https://evil.example/mcp'}}])await assert.rejects(f.provider.prepare(fetcher(f.provider,overrides)),/Work IQ.*metadata|Work IQ.*configuration/i);assert.equal(f.opened(),undefined);
});
test('ordinary connectors cannot use the WorkIQ issuer or public-client exception',async t=>{
 const f=setup(t,{catalogId:'custom'});await f.provider.start();assert.match(f.provider.redirectUrl,/\/oauth\/callback$/);let reads=0;await f.provider.prepare(async()=>{reads++;throw Error()});assert.equal(reads,0);await assert.rejects(f.provider.saveDiscoveryState({authorizationServerUrl:AUTHORITY,authorizationServerMetadata:metadata}),/client secret/);
});
