import { TooltipButton } from '@zq/ui'
import {useEffect,useRef,useState} from 'react'
import {useHost,unwrap,type Artifact,type ArtifactVersion,type ArtifactTarget} from '@zq/module-api'
import {SquaresFour,MagnifyingGlass,Plus,File,DotsThree,ArrowLeft,DownloadSimple} from '@phosphor-icons/react'
import {Button,Input,SelectField,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@zq/ui'
import ArtifactEditor from './ArtifactEditor'
import {ResearchReportEditor,researchReportActions} from './ResearchReport'
import ArtifactAttachDialog from './ArtifactAttachDialog'
import type {ChatController} from './useChat'
import './artifacts.css'
export default function ArtifactLibrary({chat}:{chat:ChatController}){
 const [reportEdit,setReportEdit]=useState<{artifact:Artifact;target:ArtifactTarget}|null>(null)
 const focusTarget=useRef<HTMLElement|null>(null)
 function restoreFocus(e:Event){e.preventDefault();requestAnimationFrame(()=>{if(!document.querySelector('[data-slot=dialog-content][data-state=open]')&&focusTarget.current?.isConnected)focusTarget.current.focus()})}
 const {services,closing,commands}=useHost(),[items,setItems]=useState<Artifact[]>([]),[query,setQuery]=useState(''),[format,setFormat]=useState('all'),[scope,setScope]=useState('active'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[edit,setEdit]=useState<{existing?:Artifact;content:string}|null>(null),[rename,setRename]=useState<Artifact|null>(null),[title,setTitle]=useState(''),[remove,setRemove]=useState<Artifact|null>(null),[attach,setAttach]=useState<{artifact:Artifact;version:ArtifactVersion;kind:'note'|'task'}|null>(null),[busy,setBusy]=useState(false),lock=useRef(false)
 useEffect(()=>{let live=true;const apply=(a:Artifact[])=>{if(live)setItems(a)};const stop=services.artifacts.subscribe(apply);unwrap(services.artifacts.list()).then(async items=>{apply(items);const status=await unwrap(services.artifacts.status());if(live&&status.warning)setError(status.warning)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false;stop()}},[])
 async function run(action:()=>Promise<void>){if(lock.current||closing)return;lock.current=true;setBusy(true);setError('');try{await action()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 function open(a:Artifact,v=a.versions.at(-1)!){chat.openArtifact({artifactId:a.id,versionId:v.id})}
 function actions(a:Artifact,v=a.versions.at(-1)!){const target={artifactId:a.id,versionId:v.id};return[
 {label:'Open artifact',action:()=>open(a,v)},
 {label:'Rename…',action:()=>{setTitle(a.name);setRename(a)}},
 ...researchReportActions(a,target,chat,run,()=>setReportEdit({artifact:a,target}),services),
 {label:'Download…',action:()=>void run(async()=>{await unwrap(services.artifacts.save(target))})},
 {label:'Version history',action:()=>open(a,v)},
 {label:'Revise in chat…',disabled:!!a.deletedAt||!['pdf','docx','xlsx','pptx'].includes(a.format),action:()=>void run(()=>chat.reviseArtifact(target))},
 {label:'Create new version…',disabled:!!a.deletedAt||!['pdf','docx','xlsx','pptx'].includes(a.format),action:()=>void run(async()=>{const saved=await unwrap(services.artifacts.version(target));const shown=await unwrap(services.artifacts.preview(target));setEdit({existing:a,content:saved.content??shown.text??''})})},
 {label:'Attach to Notes…',action:()=>setAttach({artifact:a,version:v,kind:'note'})},
 {label:'Attach to Tasks…',action:()=>setAttach({artifact:a,version:v,kind:'task'})},
 {label:a.deletedAt?'Restore artifact':'Delete…',action:()=>a.deletedAt?void run(async()=>{await unwrap(services.artifacts.update({id:a.id,deleted:false}))}):setRemove(a)},
 ]}
 const rows=items.filter(a=>(scope==='deleted'?!!a.deletedAt:!a.deletedAt)&&(format==='all'||a.format===format)&&[a.name,...a.versions.map(v=>v.source?.conversationTitle??'')].join(' ').toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt-a.updatedAt)
 return <div className="artifact-library" onFocusCapture={e=>{if(e.target instanceof HTMLButtonElement&&e.currentTarget.contains(e.target))focusTarget.current=e.target}}><header className="artifact-library-heading"><div><h1>Artifacts</h1><p>Documents and files from your chats.</p></div><Button tooltip="Create a downloadable document from text or Markdown" variant="ghost" onClick={()=>setEdit({content:''})} disabled={closing}><Plus size={16}/>Create artifact</Button></header><div className="artifact-library-toolbar"><div className="artifact-search"><MagnifyingGlass size={16}/><input aria-label="Search artifacts" placeholder="Search artifacts" value={query} onChange={e=>setQuery(e.target.value)}/></div><SelectField label="Artifact format" tooltip="Filter the library by document or file format" value={format} onValueChange={setFormat} options={[{value:'all',label:'All formats'},...['pdf','docx','xlsx','pptx'].map(f=>({value:f,label:f.toUpperCase()})),...Array.from(new Set(items.map(a=>a.format))).filter(f=>!['pdf','docx','xlsx','pptx'].includes(f)).map(f=>({value:f,label:f.toUpperCase()}))]}/><SelectField label="Artifact collection" tooltip="Choose active artifacts or deleted artifacts you can restore" value={scope} onValueChange={setScope} options={[{value:'active',label:'All artifacts'},{value:'deleted',label:'Deleted'}]}/></div>{error&&<p className="chat-error" role="alert">{error}</p>}
 <div className="artifact-list">{rows.map(a=><ContextMenu key={a.id}><ContextMenuTrigger asChild><div className="artifact-row" data-artifact-id={a.id} onContextMenu={e=>{focusTarget.current=e.currentTarget.querySelector('button')}}><TooltipButton tooltip={`Preview ${a.name}. Right-click for artifact actions.`} type="button" className="artifact-row-open" disabled={closing} onClick={()=>open(a)} onKeyDown={e=>{if(e.key==='F2'){e.preventDefault();setTitle(a.name);setRename(a)}}}><File size={22}/><span><strong>{a.name}</strong><small>{a.format.toUpperCase()} · {a.versions.length===1?'1 version':`${a.versions.length} versions`}{a.versions.at(-1)?.source?.projectName?` · ${a.versions.at(-1)!.source!.projectName}`:''}</small></span><time>{new Date(a.updatedAt).toLocaleDateString()}</time></TooltipButton><DropdownMenu><DropdownMenuTrigger asChild><TooltipButton type="button" className="artifact-more" aria-label={`Actions for ${a.name}`} disabled={busy||closing}><DotsThree size={20}/></TooltipButton></DropdownMenuTrigger><DropdownMenuContent onCloseAutoFocus={restoreFocus}>{actions(a).map(action=><DropdownMenuItem key={action.label} disabled={busy||closing||action.disabled} onSelect={action.action}>{action.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></ContextMenuTrigger><ContextMenuContent onCloseAutoFocus={restoreFocus}>{actions(a).map(action=><ContextMenuItem key={action.label} disabled={busy||closing||action.disabled} onSelect={action.action}>{action.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>)}</div>{!rows.length&&<div className="artifact-empty"><SquaresFour size={28}/><p>{loading?'Loading artifacts…':query?'No matching artifacts.':scope==='deleted'?'No deleted artifacts.':'Your artifacts will appear here.'}</p>{!loading&&!query&&scope==='active'&&<span>Create one from a response’s action menu, or start a document here.</span>}</div>}
 {reportEdit&&<ResearchReportEditor {...reportEdit} onClose={()=>setReportEdit(null)} onSaved={a=>{setReportEdit(null);open(a)}}/>}
 {edit&&<ArtifactEditor {...edit} library={items} onClose={()=>setEdit(null)} onCreated={a=>{setEdit(null);setScope('active');open(a)}}/>}
 <Dialog open={!!rename} onOpenChange={value=>{if(!value)setRename(null)}}><DialogContent onCloseAutoFocus={restoreFocus}><DialogTitle>Rename artifact</DialogTitle><DialogDescription>Changes the library name. Saved version files retain their original names.</DialogDescription><form onSubmit={e=>{e.preventDefault();if(rename)void run(async()=>{await unwrap(services.artifacts.update({id:rename.id,name:title}));setRename(null)})}}><Input aria-label="Artifact name" value={title} onChange={e=>setTitle(e.target.value)}/>{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button type="button" variant="ghost" onClick={()=>setRename(null)}>Cancel</Button><Button type="submit" disabled={busy||!title.trim()}>Rename</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!remove} onOpenChange={value=>{if(!value)setRemove(null)}}><DialogContent onCloseAutoFocus={restoreFocus}><DialogTitle>Delete {remove?.name}?</DialogTitle><DialogDescription>The artifact moves to Deleted. Its saved versions remain available in Notes and Tasks, and you can restore it.</DialogDescription>{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button variant="ghost" onClick={()=>setRemove(null)}>Cancel</Button><Button tooltip="Move this artifact to Deleted; existing attachments keep their saved versions" disabled={busy} onClick={()=>remove&&void run(async()=>{await unwrap(services.artifacts.update({id:remove.id,deleted:true}));setRemove(null)})}>Delete artifact</Button></div></DialogContent></Dialog>
 {attach&&<ArtifactAttachDialog {...attach} onClose={()=>setAttach(null)}/>}
 </div>
}
