import {useRef,useState} from 'react'
import {useHost,unwrap,type Artifact,type ArtifactCreate,type ArtifactFormat,type ArtifactSource} from '@zq/module-api'
import {Dialog,DialogContent,DialogTitle,DialogDescription,Input,Textarea,SelectField,Button} from '@zq/ui'
export default function ArtifactEditor({content='',source,existing,library=[],onClose,onCreated}:{content?:string;source?:ArtifactSource;existing?:Artifact;library?:Artifact[];onClose:()=>void;onCreated:(artifact:Artifact)=>void}){
 const {services,closing}=useHost(),[title,setTitle]=useState(existing?.name??(content.split('\n').find(l=>l.trim())??'Untitled artifact').replace(/^#+\s*/,'').slice(0,100)),[body,setBody]=useState(content),[format,setFormat]=useState<ArtifactFormat>((existing?.format as ArtifactFormat)??'docx'),[target,setTarget]=useState(existing?.id??''),[expected,setExpected]=useState(existing?.versions.at(-1)?.id),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false)
 async function save(){if(lock.current||closing)return;lock.current=true;setBusy(true);setError('');try{const artifact=await unwrap(services.artifacts.create({format,title,content:body,source,...(target?{artifactId:target,expectedLatestVersionId:expected}:{})}));onCreated(artifact)}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 const targets=existing?[existing]:library.filter(a=>!a.deletedAt&&a.format===format)
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="artifact-editor"><DialogTitle>{target?'Create artifact version':'Create artifact'}</DialogTitle><DialogDescription>{target?'Saves a new version. Existing attachments keep the version they already reference.':'Create a downloadable document from this content.'}</DialogDescription><form onSubmit={e=>{e.preventDefault();void save()}}><label>Title<Input aria-label="Artifact title" value={title} onChange={e=>setTitle(e.target.value)} disabled={busy||closing} maxLength={200}/></label><div className="artifact-editor-options"><SelectField label="Artifact format" value={format} disabled={busy||!!existing} onValueChange={v=>{setFormat(v as ArtifactFormat);setTarget('');setExpected(undefined)}} options={[{value:'pdf',label:'PDF document'},{value:'docx',label:'Word document (.docx)'},{value:'xlsx',label:'Excel workbook (.xlsx)'},{value:'pptx',label:'PowerPoint (.pptx)'}]}/><SelectField label="Save as" value={target} disabled={busy||!!existing} onValueChange={v=>{setTarget(v);setExpected(targets.find(a=>a.id===v)?.versions.at(-1)?.id)}} options={[{value:'',label:'New artifact'},...targets.map(a=>({value:a.id,label:`New version of ${a.name}`}))]}/></div><label>Content<Textarea aria-label="Artifact content" value={body} onChange={e=>setBody(e.target.value)} disabled={busy||closing} placeholder="Write or paste content. Use headings and Markdown tables to structure it."/></label><p className="artifact-help">{format==='xlsx'?'Markdown tables become worksheet cells; other text is kept as rows.':format==='pptx'?'Headings organize the slides. Longer sections continue on additional slides.':'Headings, paragraphs, lists and tables are formatted in the document.'}</p>{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button type="button" variant="ghost" onClick={onClose} disabled={busy}>Cancel</Button><Button type="submit" disabled={busy||closing||!title.trim()||!body.trim()}>{busy?'Creating…':target?'Save new version':'Create artifact'}</Button></div></form></DialogContent></Dialog>
}
