import {useEffect,useId,useRef,useState} from 'react'
import {useHost,unwrap,type ChatInteraction as Interaction} from '@zq/module-api'
import {Button,Textarea,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@zq/ui'
import {DotsThree} from '@phosphor-icons/react'
export default function ChatInteraction({interaction,conversationId,disabled}:{interaction:Interaction;conversationId:string;disabled:boolean}){
 const host=useHost(),id=useId(),input=useRef<HTMLTextAreaElement>(null),lock=useRef(false),mounted=useRef(true)
 const [answer,setAnswer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const waiting=interaction.status==='waiting',blocked=disabled||host.closing||busy||!waiting
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>host.registerFlush(`chat-interaction-${id}`,async()=>{if(lock.current)throw Error('Wait for your response to finish before closing zQ.')}),[host.registerFlush,id])
 async function respond(input:{answer?:string;decision?:'once'|'chat'|'deny'}){if(blocked||lock.current)return;lock.current=true;setBusy(true);setError('');try{await unwrap(host.services.chat.respondToInteraction({conversationId,id:interaction.id,...input}));if(mounted.current)requestAnimationFrame(()=>{if(mounted.current)document.querySelector<HTMLTextAreaElement>('[aria-label="Chat message"]')?.focus({preventScroll:true})})}catch(e){if(mounted.current)setError((e as Error).message)}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 async function copy(text:string,label:string){try{await unwrap(host.services.clipboard.writeText(text));host.notify(`${label} copied`)}catch{host.notify(`Couldn’t copy the ${label.toLowerCase()}. Try selecting the text.`)}}
 const actions=[{label:'Copy question',text:interaction.question},...(interaction.answer?[{label:'Copy answer',text:interaction.answer}]:[])]
 return <ContextMenu><ContextMenuTrigger asChild><section className={`chat-interaction chat-interaction-${interaction.kind}`} aria-label={interaction.kind==='clarification'?'Question for you':'Tool approval'} aria-busy={busy}>
  <header><strong>{interaction.kind==='clarification'?'Question for you':'Tool approval'}</strong><span>{waiting?'Waiting for you':interaction.status==='answered'?'Answered':interaction.status==='denied'?'Denied':'Cancelled'}</span><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="ghost" size="icon-sm" aria-label={interaction.kind==='clarification'?'Question actions':'Approval actions'} disabled={host.closing}><DotsThree size={17}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end">{actions.map(action=><DropdownMenuItem key={action.label} disabled={host.closing} onSelect={()=>void copy(action.text,action.label.slice(5))}>{action.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></header>
  <p className="chat-interaction-question">{interaction.question}</p>{interaction.tool&&<p className="chat-interaction-tool">{interaction.tool.replaceAll('_',' ')}</p>}{interaction.detail&&<p className="chat-interaction-detail">{interaction.detail}</p>}
  {!waiting?<p className="chat-interaction-result">{interaction.answer|| (interaction.status==='denied'?'This tool action was denied.':interaction.status==='cancelled'?'This request was cancelled.':'Response recorded.')}</p>:interaction.kind==='approval'?<div className="chat-interaction-actions"><Button type="button" disabled={blocked} tooltip="Allow this tool action once" onClick={()=>void respond({decision:'once'})}>Allow once</Button><Button type="button" variant="outline" disabled={blocked} tooltip="Allow this tool for the rest of this conversation" onClick={()=>void respond({decision:'chat'})}>Allow for this chat</Button><Button type="button" variant="ghost" disabled={blocked} tooltip="Decline this tool action" onClick={()=>void respond({decision:'deny'})}>Deny</Button></div>:<form onSubmit={event=>{event.preventDefault();if(answer.trim())void respond({answer:answer.trim()})}}>
   {!!interaction.options?.length&&<div className="chat-interaction-options">{interaction.options.map((option,index)=><Button tooltip={`Use this answer: ${option}. You can edit it before sending.`} key={`${index}-${option}`} type="button" variant="outline" disabled={blocked} onClick={()=>{setAnswer(option);input.current?.focus()}}>{option}</Button>)}</div>}
   <label className="sr-only" htmlFor={id}>Your answer</label><Textarea ref={input} id={id} aria-label="Your answer" placeholder="Your answer…" value={answer} disabled={blocked} onChange={event=>setAnswer(event.target.value)} onKeyDown={event=>{if(event.key==='Enter'&&!event.shiftKey&&!event.nativeEvent.isComposing){event.preventDefault();if(answer.trim())void respond({answer:answer.trim()})}}}/><div className="chat-interaction-actions"><Button tooltip="Send your answer so the conversation can continue" type="submit" disabled={blocked||!answer.trim()}>{busy?'Sending…':'Send answer'}</Button></div>
  </form>}{error&&<p className="chat-action-error" role="alert">{error}</p>}
 </section></ContextMenuTrigger><ContextMenuContent>{actions.map(action=><ContextMenuItem key={action.label} disabled={host.closing} onSelect={()=>void copy(action.text,action.label.slice(5))}>{action.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>
}
