import { TooltipButton } from '@zq/ui'
import {useEffect,useId,useRef,useState} from 'react'
import {useHost,unwrap,type Conversation,type QueuedMessage} from '@zq/module-api'
import {ArrowUp,ArrowDown,DotsThree,PencilSimple,Trash,Pause,Play} from '@phosphor-icons/react'
import {Button,Textarea,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@zq/ui'

function contextSummary(item:QueuedMessage){return [item.model,item.attachments.length?`Files: ${item.attachments.map(file=>file.name).join(', ')}`:'',item.context.length?`Notes: ${item.context.map(note=>note.title).join(', ')}`:'',item.skillContext?.length?`Skills: ${item.skillContext.map(skill=>skill.name).join(', ')}`:'',item.tools.length?`Tools: ${item.tools.join(', ')}`:''].filter(Boolean).join(' · ')}
export default function ChatQueue({conversation,disabled,waiting}:{conversation:Conversation;disabled:boolean;waiting:boolean}){
 const host=useHost(),id=useId(),queue=conversation.queue
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[editor,setEditor]=useState<{item:QueuedMessage;text:string}|null>(null),[discard,setDiscard]=useState(false)
 const lock=useRef(false),mounted=useRef(true),opening=useRef(false),input=useRef<HTMLTextAreaElement>(null),origin=useRef<HTMLButtonElement|null>(null),rows=useRef(new Map<string,HTMLButtonElement>())
 const dirty=!!editor&&editor.text!==editor.item.text,dirtyRef=useRef(dirty);dirtyRef.current=dirty
 const blocked=disabled||host.closing||busy
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>host.registerFlush(`chat-queue-${id}`,async()=>{if(lock.current)throw Error('Wait for the queue change to finish before closing zQ.');if(dirtyRef.current)throw Error('Save or discard your queued message edits before closing zQ.')}),[host.registerFlush,id])
 async function run(action:()=>Promise<unknown>,done?:()=>void){if(blocked||lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();if(mounted.current)done?.()}catch(e){if(mounted.current)setError((e as Error).message)}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 function edit(item:QueuedMessage){origin.current=rows.current.get(item.id)??null;opening.current=true;void run(async()=>{if(!queue?.paused)await unwrap(host.services.chat.setQueuePaused({conversationId:conversation.id,paused:true}))},()=>setEditor({item,text:item.text}))}
 function change(item:QueuedMessage,patch:{move?:'up'|'down';remove?:boolean}){void run(()=>unwrap(host.services.chat.updateQueuedMessage({conversationId:conversation.id,id:item.id,...patch})),()=>{if(patch.remove)requestAnimationFrame(()=>{if(mounted.current)(rows.current.values().next().value??document.querySelector<HTMLTextAreaElement>('[aria-label="Chat message"]'))?.focus()})})}
 function close(){if(blocked||lock.current)return;if(dirty)setDiscard(true);else{setEditor(null);setError('')}}
 function closeMenu(event:Event){if(opening.current){event.preventDefault();opening.current=false}}
 if(!queue||!queue.items.length&&!queue.error)return null
 return <section className="chat-queue" aria-label="Message queue">
  <header><strong>Queue <span>{queue.items.length}</span></strong><span className="chat-queue-status">{waiting?'Waiting for your answer':queue.paused?'Paused':'Sends in order'}</span><Button tooltip={waiting ? 'Answer the pending question before resuming the queue' : queue.paused ? 'Resume sending queued messages in order' : 'Pause queued messages; the current response continues'} type="button" variant="ghost" disabled={blocked||waiting} onClick={()=>void run(()=>unwrap(host.services.chat.setQueuePaused({conversationId:conversation.id,paused:!queue.paused})))}>{queue.paused?<Play size={13}/>:<Pause size={13}/>} {queue.paused?'Resume queue':'Pause queue'}</Button></header>
  <div className="chat-queue-items">{queue.items.map((item,index)=>{const actions=[{label:'Edit',icon:PencilSimple,disabled:false,run:()=>edit(item)},{label:'Move up',icon:ArrowUp,disabled:index===0,run:()=>change(item,{move:'up'})},{label:'Move down',icon:ArrowDown,disabled:index===queue.items.length-1,run:()=>change(item,{move:'down'})},{label:'Remove',icon:Trash,disabled:false,run:()=>change(item,{remove:true})}];return <ContextMenu key={item.id}><ContextMenuTrigger asChild disabled={blocked}><div className="chat-queue-item"><span className="chat-queue-index">{index+1}</span><TooltipButton ref={node=>{if(node)rows.current.set(item.id,node);else rows.current.delete(item.id)}} type="button" disabled={blocked} aria-label={`Edit queued message ${index+1}`} tooltip={`Edit queued message ${index+1}. Saved context: ${contextSummary(item)}`} onClick={()=>edit(item)} className="chat-queue-copy"><strong>{item.text||'Attached context'}</strong><small>{contextSummary(item)}</small></TooltipButton><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="ghost" size="icon" disabled={blocked} aria-label={`Actions for queued message ${index+1}`}><DotsThree size={17}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" onCloseAutoFocus={closeMenu}>{actions.map(action=><DropdownMenuItem key={action.label} disabled={blocked||action.disabled} onSelect={action.run}><action.icon size={14}/>{action.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></ContextMenuTrigger><ContextMenuContent aria-label={`Queued message actions ${index+1}`} onCloseAutoFocus={closeMenu}>{actions.map(action=><ContextMenuItem key={action.label} disabled={blocked||action.disabled} onSelect={action.run}><action.icon size={14}/>{action.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>})}</div>
  {queue.error&&<p className="chat-action-error" role="alert">{queue.error}</p>}{error&&!editor&&<p className="chat-action-error" role="alert">{error}</p>}
  <Dialog open={!!editor} onOpenChange={open=>{if(!open)close()}}><DialogContent className="chat-queue-editor" showCloseButton={!blocked} onOpenAutoFocus={event=>{event.preventDefault();input.current?.focus()}} onCloseAutoFocus={event=>{event.preventDefault();if(origin.current?.isConnected)origin.current.focus();else document.querySelector<HTMLTextAreaElement>('[aria-label="Chat message"]')?.focus()}}><DialogTitle>Edit queued message</DialogTitle><DialogDescription>The queue is paused while you edit. Saved attachments, notes, skills and model choices stay with this message. Resume the queue when ready.</DialogDescription>{editor&&<form onSubmit={event=>{event.preventDefault();void run(()=>unwrap(host.services.chat.updateQueuedMessage({conversationId:conversation.id,id:editor.item.id,text:editor.text})),()=>setEditor(null))}}><Textarea ref={input} aria-label="Queued message text" disabled={blocked} value={editor.text} onChange={event=>setEditor({...editor,text:event.target.value})}/><p className="chat-queue-context">{contextSummary(editor.item)}</p>{error&&<p className="chat-action-error" role="alert">{error}</p>}<div className="dialog-actions"><Button type="button" variant="ghost" disabled={blocked} onClick={close}>Cancel</Button><Button tooltip="Save these message edits; resume the queue when you are ready" type="submit" disabled={blocked||!editor.text.trim()&&!editor.item.attachments.length&&!editor.item.context.length}>{busy?'Saving…':'Save queued message'}</Button></div></form>}</DialogContent></Dialog>
  <Dialog open={discard} onOpenChange={setDiscard}><DialogContent><DialogTitle>Discard queued message edits?</DialogTitle><DialogDescription>The saved queued message will stay unchanged.</DialogDescription><div className="dialog-actions"><Button variant="ghost" onClick={()=>setDiscard(false)}>Keep editing</Button><Button variant="destructive" onClick={()=>{setDiscard(false);setEditor(null);setError('')}}>Discard edits</Button></div></DialogContent></Dialog>
 </section>
}
