import {ConnectorIcon} from '@zq/ui'
import {useState} from 'react'
import type {Connector} from '@zq/module-api'
import {Button,Checkbox,Popover,PopoverContent,PopoverTrigger,DropdownMenuSub,DropdownMenuSubTrigger,DropdownMenuSubContent,DropdownMenuItem,DropdownMenuSeparator} from '@zq/ui'
import {CaretRight,Check,GearSix} from '@phosphor-icons/react'
import {ConnectorMenus,connectorStatus} from './ConnectorSettings'
export type ConnectorPickerProps={connectors:Connector[];selected:string[]|null;inherited?:string[];allowInherit?:boolean;disabled:boolean;onChange:(ids:string[]|null)=>void;onManage:()=>void}
export function ConnectorSubmenu({connectors,selected,inherited=[],disabled,onChange,onManage}:ConnectorPickerProps){
 const active=selected??inherited
 return <DropdownMenuSub><DropdownMenuSubTrigger disabled={disabled} className="composer-skills-subtrigger"><ConnectorIcon size={17}/><span>Connectors</span>{active.length>0&&<small>{active.length} enabled</small>}<CaretRight size={13}/></DropdownMenuSubTrigger><DropdownMenuSubContent className="composer-skills-submenu" aria-label="Choose connectors"><DropdownMenuItem role="menuitemcheckbox" aria-checked={selected===null} disabled={disabled} onSelect={event=>{event.preventDefault();onChange(null)}}><span className="composer-skill-check">{selected===null&&<Check size={14}/>}</span><span>Use project connectors<small>{inherited.length?`${inherited.length} selected by project`:'No connectors selected by project'}</small></span></DropdownMenuItem><DropdownMenuSeparator/><div className="composer-skills-list">{connectors.map(connector=><ConnectorMenus key={connector.id} connector={connector} disabled={disabled}><DropdownMenuItem role="menuitemcheckbox" aria-checked={active.includes(connector.id)} disabled={disabled||(connector.status!=='connected'||active.length>=10)&&!active.includes(connector.id)} onSelect={event=>{event.preventDefault();onChange(active.includes(connector.id)?active.filter(id=>id!==connector.id):[...active,connector.id])}}><span className="composer-skill-check">{active.includes(connector.id)&&<Check size={14}/>}</span><span>{connector.name}<small>{connectorStatus(connector)}</small></span></DropdownMenuItem></ConnectorMenus>)}</div>{!connectors.length&&<p className="skill-help composer-skills-empty">No connectors yet.</p>}<DropdownMenuSeparator/><DropdownMenuItem disabled={disabled} onSelect={event=>{event.preventDefault();onChange([])}}>No connectors</DropdownMenuItem><DropdownMenuItem onSelect={onManage}><GearSix size={15}/>Manage connectors</DropdownMenuItem></DropdownMenuSubContent></DropdownMenuSub>
}
export default function ConnectorPicker({connectors,selected,inherited=[],allowInherit=false,disabled,onChange,onManage}:ConnectorPickerProps){
 const [open,setOpen]=useState(false),active=selected??inherited
 return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button type="button" variant="ghost" disabled={disabled}><ConnectorIcon size={15}/>Connectors{active.length>0&&<span className="skill-count">{active.length}</span>}</Button></PopoverTrigger><PopoverContent className="connector-picker" align="start"><strong>Connectors</strong>{allowInherit&&<label className="connector-choice"><Checkbox checked={selected===null} disabled={disabled} onCheckedChange={()=>onChange(null)} aria-label="Use project connectors"/><span>Use project connectors</span></label>}<div className="connector-picker-list">{connectors.map(connector=><ConnectorMenus key={connector.id} connector={connector} disabled={disabled}><label className="connector-choice"><Checkbox aria-label={`Use ${connector.name}`} checked={active.includes(connector.id)} disabled={disabled||(connector.status!=='connected'||active.length>=10)&&!active.includes(connector.id)} onCheckedChange={checked=>onChange(checked===true?[...active,connector.id]:active.filter(id=>id!==connector.id))}/><span>{connector.name}<small>{connectorStatus(connector)}</small></span></label></ConnectorMenus>)}</div>{!connectors.length&&<p className="connector-help">Add a remote MCP server in Connectors settings.</p>}<div className="skill-picker-footer"><Button variant="ghost" disabled={disabled} onClick={()=>onChange([])}>No connectors</Button><Button variant="ghost" onClick={()=>{setOpen(false);onManage()}}>Manage connectors</Button></div></PopoverContent></Popover>
}
