import {ConnectorIcon} from '@zq/ui'
import {useRef,useState,type ReactElement} from 'react'
import {useHost,unwrap,type Connector,type ConnectorInput,type ConnectorCatalogEntry} from '@zq/module-api'
import {DotsThree,Plus} from '@phosphor-icons/react'
import {Button,Input,Checkbox,SelectField,Tabs,TabsList,TabsTrigger,TabsContent,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@zq/ui'
import type {ChatController} from './useChat'
import './connectors.css'
import ConnectorDiscover from './ConnectorDiscover'
import {ConnectorLogo} from './ConnectorLogo'
import {matchesCatalog,connectorNeedsSetup,normalizeConnectorUrl,canonicalConnectorUrl,catalogCallbackPath} from './connector-catalog'

export function connectorStatus(connector:Connector){return connector.status==='authenticating'?'Waiting for browser sign-in':connector.status==='connecting'?'Connecting…':connector.status==='connected'?(connector.tools.some(tool=>tool.enabled)?`Connected · ${connector.tools.filter(tool=>tool.enabled).length} ${connector.tools.filter(tool=>tool.enabled).length===1?'tool':'tools'} enabled`:'Connected · Choose tools to use in chat'):connector.status==='error'?'Connection failed':'Disconnected'}

export function ConnectorEditor({connector,entry,disabled,onClose,onCloseAutoFocus}:{connector?:Connector;entry?:ConnectorCatalogEntry;disabled:boolean;onClose:()=>void;onCloseAutoFocus?:(event:Event)=>void}){
 const googleOAuth=['gmail','google-calendar','google-drive'].includes(entry?.id??'')
 const {services}=useHost(),[name,setName]=useState(connector?.name??entry?.name??''),[url,setUrl]=useState(connector?.url??entry?.url??''),[clientId,setClientId]=useState(connector?.clientId??entry?.clientId??''),[metadata,setMetadata]=useState(connector?.clientMetadataUrl??'')
 const [authType,setAuthType]=useState<'oauth'|'bearer'>(googleOAuth?'oauth':connector?.authType??entry?.authType??'oauth'),[token,setToken]=useState<string|undefined>(),[clientSecret,setClientSecret]=useState<string|undefined>(),[port,setPort]=useState(String(connector?.redirectPort??entry?.redirectPort??'')),[redirectHost,setRedirectHost]=useState(connector?.redirectHost??entry?.redirectHost??'127.0.0.1')
 const [busy,setBusy]=useState(false),[connecting,setConnecting]=useState(false),[cancelling,setCancelling]=useState(false),[error,setError]=useState(''),lock=useRef(false),savedId=useRef(connector?.id),cancelled=useRef(false),cancelLock=useRef(false)
 const sameCredentialEndpoint=!!connector&&canonicalConnectorUrl(url)===connector.url&&authType===(connector.authType??'oauth'),savedToken=sameCredentialEndpoint&&connector?.hasToken,savedSecret=sameCredentialEndpoint&&clientId.trim()===connector?.clientId&&connector?.hasClientSecret
 const needsSetup=connectorNeedsSetup({authType,clientId,redirectPort:port?Number(port):undefined,hasToken:token===undefined?savedToken:!!token,hasClientSecret:clientSecret===undefined?savedSecret:!!clientSecret},entry)
 async function save(connect=false){if(disabled||lock.current)return;lock.current=true;cancelled.current=false;setBusy(true);setError('');try{
  const input:ConnectorInput={id:savedId.current,name:name.trim(),url:url.trim(),clientId:clientId.trim(),clientMetadataUrl:metadata.trim(),catalogId:entry?.id??connector?.catalogId,authType,token,clientSecret,redirectPort:port?Number(port):undefined,redirectHost:port||connector?.redirectHost||entry?.redirectHost||redirectHost==='localhost'?redirectHost:undefined}
  const rows=await unwrap(services.connectors.save(input));const saved=rows.find(row=>row.id===savedId.current)??[...rows].reverse().find(row=>normalizeConnectorUrl(row.url)===normalizeConnectorUrl(input.url)&&row.name===input.name);if(saved)savedId.current=saved.id;if(connect){if(!saved)throw Error('Connector was saved. Open Your connectors to connect.');setConnecting(true);await unwrap(services.connectors.connect(saved.id))}if(!cancelled.current)onClose()
 }catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false);setConnecting(false)}}
 async function cancelConnection(){if(disabled||!connecting||!savedId.current||cancelLock.current)return;cancelLock.current=true;cancelled.current=true;setCancelling(true);try{await unwrap(services.connectors.disconnect(savedId.current))}catch(e){setError((e as Error).message)}finally{cancelLock.current=false;setCancelling(false)}}
 const blocked=disabled||busy
 const callbackPath=catalogCallbackPath(entry,{name,url,authType,clientId,clientMetadataUrl:metadata,catalogId:entry?.id??connector?.catalogId,redirectPort:port?Number(port):undefined,redirectHost})
 return <Dialog open onOpenChange={open=>{if(!open&&!blocked)onClose()}}><DialogContent className="connector-dialog" showCloseButton={!blocked} onCloseAutoFocus={onCloseAutoFocus}><DialogTitle>{connector?'Edit connector':entry?`Set up ${entry.name}`:'Add connector'}</DialogTitle><DialogDescription>{entry?.setupNote??'Save an MCP server address, then connect to discover tools and sign in if required.'}</DialogDescription>
 {entry&&<div className="connector-setup-meta"><span>{entry.accountLabel}</span><Button variant="link" onClick={()=>void unwrap(services.chat.openLink(entry.documentationUrl)).catch(e=>setError(e.message))}>Publisher setup guide</Button></div>}
 <form onSubmit={e=>{e.preventDefault();void save()}}>
 <label htmlFor="connector-name">Name</label><Input id="connector-name" value={name} maxLength={100} disabled={blocked} onChange={e=>setName(e.target.value)} required autoFocus placeholder="My connector"/>
 <label htmlFor="connector-url">Server URL</label><Input id="connector-url" type={entry?.bundled?'text':'url'} value={url} disabled={blocked||entry?.bundled} onChange={e=>setUrl(e.target.value)} required placeholder="https://example.com/mcp"/>
 {!entry?.bundled&&<><label>Authentication</label>{googleOAuth?<span className="connector-help">Browser sign-in (OAuth)</span>:<SelectField label="Authentication" value={authType} onValueChange={value=>{setAuthType(value as 'oauth'|'bearer');setToken(undefined);setClientSecret(undefined)}} options={[{value:'oauth',label:'Browser sign-in (OAuth)'},{value:'bearer',label:'Access token'}]} disabled={blocked}/>}
 {authType==='bearer'?<><label htmlFor="connector-token">Access token</label><Input id="connector-token" type="password" autoComplete="new-password" value={token??''} disabled={blocked} onChange={e=>setToken(e.target.value)} placeholder={savedToken?'Saved token · leave blank to keep':'Paste a provider access token'}/>{connector?.hasToken&&<Button variant="ghost" type="button" disabled={blocked} onClick={()=>setToken('')}>Clear saved token</Button>}<p className="connector-help">Tokens are stored securely and never displayed here.{token===''&&connector?.hasToken?' The saved token will be removed when you save.':''}</p></>:<details className="connector-advanced" open={entry?.requiresSetup||!!clientId||!!metadata||undefined}>
 <summary>OAuth app settings</summary><p>Use these settings when the publisher requires your own registered OAuth app. Leave secret fields untouched to keep saved credentials.</p>
 <label htmlFor="connector-client">Client ID</label><Input id="connector-client" value={clientId} disabled={blocked} onChange={e=>setClientId(e.target.value)}/>
 <label htmlFor="connector-secret">Client secret</label><Input id="connector-secret" type="password" autoComplete="new-password" value={clientSecret??''} disabled={blocked} onChange={e=>setClientSecret(e.target.value)} placeholder={savedSecret?'Saved secret · leave blank to keep':'Only if required by the provider'}/>{connector?.hasClientSecret&&<Button type="button" variant="ghost" disabled={blocked} onClick={()=>setClientSecret('')}>Clear saved client secret</Button>}{clientSecret===''&&connector?.hasClientSecret&&<p>The saved client secret will be removed when you save.</p>}
 <label htmlFor="connector-metadata">Client metadata URL</label><Input id="connector-metadata" type="url" value={metadata} disabled={blocked} onChange={e=>setMetadata(e.target.value)} placeholder="https://example.com/client.json"/>
 <label htmlFor="connector-port">Callback port</label><Input id="connector-port" type="number" min={1} max={65535} step={1} value={port} disabled={blocked} onChange={e=>setPort(e.target.value)} placeholder="Automatic"/>
 <label>Callback host</label><SelectField label="Callback host" value={redirectHost} onValueChange={value=>setRedirectHost(value as 'localhost'|'127.0.0.1')} options={['127.0.0.1','localhost']} disabled={blocked}/>
 {port&&<p>Register this exact redirect URI: <code>http://{redirectHost}:{port}{callbackPath}</code></p>}
 </details>}</>}
 {needsSetup&&<p className="connector-help" role="status">Complete the app credentials and callback settings before connecting. You can save this connector and finish setup later.</p>}
 {error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button type="button" variant="ghost" disabled={disabled||cancelling||(busy&&!connecting)} onClick={()=>connecting?void cancelConnection():onClose()}>{cancelling?'Cancelling…':connecting?'Cancel connection':'Cancel'}</Button><Button type="submit" variant={entry?'outline':'default'} disabled={blocked||!name.trim()||!url.trim()}>{connecting?'Connecting…':busy?'Saving…':'Save connector'}</Button>{entry&&<Button type="button" disabled={blocked||needsSetup||!name.trim()||!url.trim()} onClick={()=>void save(true)}>Save and connect</Button>}</div></form></DialogContent></Dialog>
}

function ConnectorTools({connector,disabled,onClose,onCloseAutoFocus}:{connector:Connector;disabled:boolean;onClose:()=>void;onCloseAutoFocus:(event:Event)=>void}){
 const {services}=useHost(),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false)
 async function toggle(name:string,enabled:boolean){if(disabled||lock.current)return;lock.current=true;setBusy(true);setError('');try{await unwrap(services.connectors.setTools({id:connector.id,names:enabled?[...connector.tools.filter(t=>t.enabled).map(t=>t.name),name]:connector.tools.filter(t=>t.enabled&&t.name!==name).map(t=>t.name)}))}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 const tools=connector.tools.filter(tool=>`${tool.name} ${tool.title??''} ${tool.description}`.toLowerCase().includes(query.toLowerCase()))
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="connector-tools-dialog" onCloseAutoFocus={onCloseAutoFocus}><DialogTitle>{connector.name} tools</DialogTitle><DialogDescription>Enable only tools you want available to selected chats. Newly discovered tools start off. Tool actions request permission when needed.</DialogDescription><p className="connector-help">{connectorStatus(connector)}. Read-only labels are supplied by the server.</p>{connector.tools.length>5&&<Input aria-label="Search connector tools" placeholder="Find a tool…" value={query} onChange={e=>setQuery(e.target.value)}/>}<div className="connector-tool-list">{tools.map(tool=><ContextMenu key={tool.name}><ContextMenuTrigger asChild><label className="connector-tool"><Checkbox aria-label={`Enable ${tool.title||tool.name}`} checked={tool.enabled} disabled={disabled||busy} onCheckedChange={checked=>void toggle(tool.name,checked===true)}/><span><strong>{tool.title||tool.name}</strong><code>{tool.name}</code>{tool.description&&<small>{tool.description}</small>}{tool.readOnly&&<small>Server marks this tool read-only</small>}</span></label></ContextMenuTrigger><ContextMenuContent><ContextMenuItem disabled={disabled||busy} onSelect={()=>void toggle(tool.name,!tool.enabled)}>{tool.enabled?'Disable tool':'Enable tool'}</ContextMenuItem><ContextMenuItem onSelect={()=>void unwrap(services.clipboard.writeText(tool.name)).catch(e=>setError(e.message))}>Copy tool name</ContextMenuItem></ContextMenuContent></ContextMenu>)}</div>{!tools.length&&<p className="connector-help">{connector.tools.length?'No matching tools.':connector.status==='connected'?'This server has no tools.':'Connect to discover available tools.'}</p>}{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={busy} onClick={onClose}>Done</Button></div></DialogContent></Dialog>
}

export function ConnectorMenus({connector,entry,disabled,children,showMore=false}:{connector:Connector;entry?:ConnectorCatalogEntry;disabled:boolean;children:ReactElement;showMore?:boolean}){
 const {services,notify}=useHost(),[action,setAction]=useState<'edit'|'tools'|'remove'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),origin=useRef<HTMLElement|null>(null),opening=useRef(false),lock=useRef(false),cancel=useRef<HTMLButtonElement>(null)
 const authenticating=connector.status==='authenticating'||connector.status==='connecting'
 function choose(next:typeof action){origin.current=document.activeElement as HTMLElement;opening.current=true;setError('');setAction(next)}
 function focus(event:Event){event.preventDefault();if(origin.current?.isConnected)origin.current.focus()}
 function menuFocus(event:Event){if(opening.current){event.preventDefault();opening.current=false}}
 async function run(kind:'connect'|'disconnect'|'remove'|'copy'){
  if(disabled||(lock.current&&kind!=='disconnect'))return
  if(kind!=='disconnect')lock.current=true;setBusy(true);setError('')
  try{if(kind==='connect'&&connectorNeedsSetup(connector,entry)){choose('edit');return}if(kind==='copy')await unwrap(services.clipboard.writeText(connector.url));else {if(kind==='connect'&&connector.status==='connected')await unwrap(services.connectors.disconnect(connector.id));await unwrap(services.connectors[kind](connector.id));}if(kind==='remove')setAction(null)}catch(e){if(kind==='remove')setError((e as Error).message);else notify((e as Error).message)}finally{lock.current=false;setBusy(false)}
 }
 const actions=[...(entry?[{label:'Publisher documentation',run:()=>void unwrap(services.chat.openLink(entry.documentationUrl)).catch(e=>notify(e.message)),disabled:false}]:[]),{label:'Manage tools…',run:()=>choose('tools'),disabled:disabled||busy},{label:'Edit connector…',run:()=>choose('edit'),disabled:disabled||busy||authenticating},{label:connector.status==='connected'?'Reconnect':'Connect',run:()=>void run('connect'),disabled:disabled||busy||authenticating},{label:authenticating?'Cancel sign-in / connection':'Disconnect',run:()=>void run('disconnect'),disabled:disabled||(!authenticating&&(busy||connector.status==='disconnected'))},{label:'Copy server URL',run:()=>void run('copy'),disabled:disabled||busy},{label:'Remove connector…',run:()=>choose('remove'),disabled:disabled||busy||authenticating}]
 return <><ContextMenu><ContextMenuTrigger asChild>{showMore?<div className="connector-row settings-resource-row" data-connector-id={connector.id}>{children}<Button variant="ghost" disabled={disabled||busy&&!authenticating} onClick={()=>authenticating?void run('disconnect'):connector.status==='connected'?choose('tools'):void run('connect')}>{authenticating?'Cancel':connector.status==='connected'?(connector.tools.some(tool=>tool.enabled)?'Manage tools':'Choose tools'):'Connect'}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="settings-more-button" disabled={disabled} tooltip={`Actions for ${connector.name}`} aria-label={`Actions for connector ${connector.name}`}><DotsThree size={20}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" onCloseAutoFocus={menuFocus}>{actions.map(item=><DropdownMenuItem key={item.label} disabled={item.disabled} onSelect={item.run}>{item.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div>:children}</ContextMenuTrigger><ContextMenuContent aria-label={`Connector actions for ${connector.name}`} onCloseAutoFocus={menuFocus}>{actions.map(item=><ContextMenuItem key={item.label} disabled={item.disabled} onSelect={item.run}>{item.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>
 {action==='edit'&&<ConnectorEditor connector={connector} entry={entry} disabled={disabled} onClose={()=>setAction(null)} onCloseAutoFocus={focus}/>}
 {action==='tools'&&<ConnectorTools connector={connector} disabled={disabled} onClose={()=>setAction(null)} onCloseAutoFocus={focus}/>}
 <Dialog open={action==='remove'} onOpenChange={open=>{if(!open&&!busy)setAction(null)}}><DialogContent className="connector-dialog" onCloseAutoFocus={focus} onOpenAutoFocus={event=>{event.preventDefault();cancel.current?.focus()}} showCloseButton={!busy}><DialogTitle>Remove connector?</DialogTitle><DialogDescription>Remove “{connector.name}” ({connector.url}) and its saved sign-in credentials. Its tools will no longer be available to chats or projects. Existing messages are kept.</DialogDescription>{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button ref={cancel} variant="ghost" disabled={busy||disabled} onClick={()=>setAction(null)}>Cancel</Button><Button variant="destructive" disabled={busy||disabled} onClick={()=>void run('remove')}>{busy?'Removing…':'Remove connector'}</Button></div></DialogContent></Dialog></>
}

export default function ConnectorSettings({chat,closing}:{chat:ChatController;closing:boolean}){
 const [adding,setAdding]=useState(false),[tab,setTab]=useState('yours'),add=useRef<HTMLButtonElement>(null),disabled=closing||chat.connectorsLoading
 function manage(connector:Connector){setTab('yours');requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[data-connector-id="${CSS.escape(connector.id)}"] button`)?.focus())}
 return <section className="connectors-settings"><div className="settings-panel-header"><div><h2>Connectors</h2><p>Bring your research, files, and work into chats with MCP tools.</p></div><Button ref={add} variant="outline" disabled={disabled} onClick={()=>setAdding(true)}><Plus size={15}/>Add custom connector</Button></div>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="connector-tabs" aria-label="Connectors"><TabsTrigger value="yours" disabled={closing}>Your connectors{chat.connectors.length>0&&<span>{chat.connectors.length}</span>}</TabsTrigger><TabsTrigger value="discover" disabled={closing}>Discover</TabsTrigger></TabsList>
 <TabsContent value="yours" className="connector-tab-panel">{chat.connectorsError&&<p role="alert" className="chat-error">{chat.connectorsError}</p>}{chat.connectorsLoading?<p role="status">Loading connectors…</p>:!chat.connectors.length&&<div className="connection-empty"><p>No connectors yet. Discover a service or add a custom MCP server.</p><Button variant="ghost" onClick={()=>setTab('discover')}>Discover connectors</Button></div>}<div className="connection-list">{chat.connectors.map(connector=>{const entry=chat.connectorCatalog?.find(item=>matchesCatalog(connector,item));return <ConnectorMenus key={connector.id} connector={connector} entry={entry} disabled={disabled} showMore><div className="connector-summary">{entry?<ConnectorLogo id={entry.id}/>:<ConnectorIcon size={22}/>}<div><strong>{connector.name}</strong><span className="connector-url">{connector.url}</span><small role="status">{connectorNeedsSetup(connector,entry)?'Saved · Setup required':connectorStatus(connector)}</small>{connector.error&&<p role="alert" className="chat-error">{connector.error}</p>}{connector.status==='authenticating'&&<small>Finish sign-in in your browser. Use the actions menu to cancel.</small>}</div></div></ConnectorMenus>})}</div></TabsContent>
 <TabsContent value="discover" className="connector-tab-panel"><ConnectorDiscover chat={chat} disabled={disabled} onManage={manage}/></TabsContent></Tabs>
 {adding&&<ConnectorEditor disabled={closing} onClose={()=>setAdding(false)} onCloseAutoFocus={event=>{event.preventDefault();add.current?.focus()}}/>}</section>
}
