import {useRef,useState,type ReactElement} from 'react'
import {useHost,unwrap,type Connector,type ConnectorInput} from '@zq/module-api'
import {DotsThree,Plus,PlugsConnected} from '@phosphor-icons/react'
import {Button,Input,Checkbox,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@zq/ui'
import type {ChatController} from './useChat'
import './connectors.css'

export function connectorStatus(connector:Connector){return connector.status==='authenticating'?'Waiting for browser sign-in':connector.status==='connecting'?'Connecting…':connector.status==='connected'?`Connected · ${connector.tools.filter(tool=>tool.enabled).length} ${connector.tools.filter(tool=>tool.enabled).length===1?'tool':'tools'} enabled`:connector.status==='error'?'Connection failed':'Disconnected'}

export function ConnectorEditor({connector,disabled,onClose,onCloseAutoFocus}:{connector?:Connector;disabled:boolean;onClose:()=>void;onCloseAutoFocus?:(event:Event)=>void}){
 const {services}=useHost(),[name,setName]=useState(connector?.name??''),[url,setUrl]=useState(connector?.url??''),[clientId,setClientId]=useState(connector?.clientId??''),[metadata,setMetadata]=useState(connector?.clientMetadataUrl??'')
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false)
 async function save(){if(disabled||lock.current)return;lock.current=true;setBusy(true);setError('');try{const input:ConnectorInput={id:connector?.id,name:name.trim(),url:url.trim(),clientId:clientId.trim(),clientMetadataUrl:metadata.trim()};await unwrap(services.connectors.save(input));onClose()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy&&!disabled)onClose()}}><DialogContent className="connector-dialog" showCloseButton={!busy&&!disabled} onCloseAutoFocus={onCloseAutoFocus}><DialogTitle>{connector?'Edit connector':'Add connector'}</DialogTitle><DialogDescription>Connect a remote MCP server using Streamable HTTP. Save its address, then connect to discover tools and sign in if required.</DialogDescription><form onSubmit={e=>{e.preventDefault();void save()}}><label htmlFor="connector-name">Name</label><Input id="connector-name" value={name} maxLength={100} disabled={disabled||busy} onChange={e=>setName(e.target.value)} required autoFocus placeholder="My connector"/><label htmlFor="connector-url">Server URL</label><Input id="connector-url" type="url" value={url} disabled={disabled||busy} onChange={e=>setUrl(e.target.value)} required placeholder="https://example.com/mcp"/><details className="connector-advanced" open={clientId||metadata?true:undefined}><summary>Advanced OAuth settings</summary><p>Only fill these in if the server requires a registered public client or client metadata URL. No client secret is needed.</p><label htmlFor="connector-client">Public client ID</label><Input id="connector-client" value={clientId} disabled={disabled||busy} onChange={e=>setClientId(e.target.value)}/><label htmlFor="connector-metadata">Client metadata URL</label><Input id="connector-metadata" type="url" value={metadata} disabled={disabled||busy} onChange={e=>setMetadata(e.target.value)} placeholder="https://example.com/client.json"/></details>{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button type="button" variant="ghost" disabled={disabled||busy} onClick={onClose}>Cancel</Button><Button type="submit" disabled={disabled||busy||!name.trim()||!url.trim()}>{busy?'Saving…':'Save connector'}</Button></div></form></DialogContent></Dialog>
}

function ConnectorTools({connector,disabled,onClose,onCloseAutoFocus}:{connector:Connector;disabled:boolean;onClose:()=>void;onCloseAutoFocus:(event:Event)=>void}){
 const {services}=useHost(),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),lock=useRef(false)
 async function toggle(name:string,enabled:boolean){if(disabled||lock.current)return;lock.current=true;setBusy(true);setError('');try{await unwrap(services.connectors.setTools({id:connector.id,names:enabled?[...connector.tools.filter(t=>t.enabled).map(t=>t.name),name]:connector.tools.filter(t=>t.enabled&&t.name!==name).map(t=>t.name)}))}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 const tools=connector.tools.filter(tool=>`${tool.name} ${tool.title??''} ${tool.description}`.toLowerCase().includes(query.toLowerCase()))
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="connector-tools-dialog" onCloseAutoFocus={onCloseAutoFocus}><DialogTitle>{connector.name} tools</DialogTitle><DialogDescription>Enable only tools you want available to selected chats. Newly discovered tools start off. Tool actions request permission when needed.</DialogDescription><p className="connector-help">{connectorStatus(connector)}. Read-only labels are supplied by the server.</p>{connector.tools.length>5&&<Input aria-label="Search connector tools" placeholder="Find a tool…" value={query} onChange={e=>setQuery(e.target.value)}/>}<div className="connector-tool-list">{tools.map(tool=><ContextMenu key={tool.name}><ContextMenuTrigger asChild><label className="connector-tool"><Checkbox aria-label={`Enable ${tool.title||tool.name}`} checked={tool.enabled} disabled={disabled||busy} onCheckedChange={checked=>void toggle(tool.name,checked===true)}/><span><strong>{tool.title||tool.name}</strong><code>{tool.name}</code>{tool.description&&<small>{tool.description}</small>}{tool.readOnly&&<small>Server marks this tool read-only</small>}</span></label></ContextMenuTrigger><ContextMenuContent><ContextMenuItem disabled={disabled||busy} onSelect={()=>void toggle(tool.name,!tool.enabled)}>{tool.enabled?'Disable tool':'Enable tool'}</ContextMenuItem><ContextMenuItem onSelect={()=>void unwrap(services.clipboard.writeText(tool.name)).catch(e=>setError(e.message))}>Copy tool name</ContextMenuItem></ContextMenuContent></ContextMenu>)}</div>{!tools.length&&<p className="connector-help">{connector.tools.length?'No matching tools.':connector.status==='connected'?'This server has no tools.':'Connect to discover available tools.'}</p>}{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={busy} onClick={onClose}>Done</Button></div></DialogContent></Dialog>
}

export function ConnectorMenus({connector,disabled,children,showMore=false}:{connector:Connector;disabled:boolean;children:ReactElement;showMore?:boolean}){
 const {services,notify}=useHost(),[action,setAction]=useState<'edit'|'tools'|'remove'|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),origin=useRef<HTMLElement|null>(null),opening=useRef(false),lock=useRef(false),cancel=useRef<HTMLButtonElement>(null)
 const authenticating=connector.status==='authenticating'||connector.status==='connecting'
 function choose(next:typeof action){origin.current=document.activeElement as HTMLElement;opening.current=true;setError('');setAction(next)}
 function focus(event:Event){event.preventDefault();if(origin.current?.isConnected)origin.current.focus()}
 function menuFocus(event:Event){if(opening.current){event.preventDefault();opening.current=false}}
 async function run(kind:'connect'|'disconnect'|'remove'|'copy'){
  if(disabled||(lock.current&&kind!=='disconnect'))return
  if(kind!=='disconnect')lock.current=true;setBusy(true);setError('')
  try{if(kind==='copy')await unwrap(services.clipboard.writeText(connector.url));else {if(kind==='connect'&&connector.status==='connected')await unwrap(services.connectors.disconnect(connector.id));await unwrap(services.connectors[kind](connector.id));}if(kind==='remove')setAction(null)}catch(e){if(kind==='remove')setError((e as Error).message);else notify((e as Error).message)}finally{lock.current=false;setBusy(false)}
 }
 const actions=[{label:'Manage tools…',run:()=>choose('tools'),disabled:disabled||busy},{label:'Edit connector…',run:()=>choose('edit'),disabled:disabled||busy||authenticating},{label:connector.status==='connected'?'Reconnect':'Connect',run:()=>void run('connect'),disabled:disabled||busy||authenticating},{label:authenticating?'Cancel sign-in / connection':'Disconnect',run:()=>void run('disconnect'),disabled:disabled||(!authenticating&&(busy||connector.status==='disconnected'))},{label:'Copy server URL',run:()=>void run('copy'),disabled:disabled||busy},{label:'Remove connector…',run:()=>choose('remove'),disabled:disabled||busy||authenticating}]
 return <><ContextMenu><ContextMenuTrigger asChild>{showMore?<div className="connector-row settings-resource-row">{children}<Button variant="ghost" disabled={disabled||busy&&!authenticating} onClick={()=>authenticating?void run('disconnect'):connector.status==='connected'?choose('tools'):void run('connect')}>{authenticating?'Cancel':connector.status==='connected'?'Manage tools':'Connect'}</Button><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" className="settings-more-button" disabled={disabled} aria-label={`Actions for connector ${connector.name}`}><DotsThree size={20}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" onCloseAutoFocus={menuFocus}>{actions.map(item=><DropdownMenuItem key={item.label} disabled={item.disabled} onSelect={item.run}>{item.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div>:children}</ContextMenuTrigger><ContextMenuContent aria-label={`Connector actions for ${connector.name}`} onCloseAutoFocus={menuFocus}>{actions.map(item=><ContextMenuItem key={item.label} disabled={item.disabled} onSelect={item.run}>{item.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>
 {action==='edit'&&<ConnectorEditor connector={connector} disabled={disabled} onClose={()=>setAction(null)} onCloseAutoFocus={focus}/>}
 {action==='tools'&&<ConnectorTools connector={connector} disabled={disabled} onClose={()=>setAction(null)} onCloseAutoFocus={focus}/>}
 <Dialog open={action==='remove'} onOpenChange={open=>{if(!open&&!busy)setAction(null)}}><DialogContent className="connector-dialog" onCloseAutoFocus={focus} onOpenAutoFocus={event=>{event.preventDefault();cancel.current?.focus()}} showCloseButton={!busy}><DialogTitle>Remove connector?</DialogTitle><DialogDescription>Remove “{connector.name}” ({connector.url}) and its saved sign-in credentials. Its tools will no longer be available to chats or projects. Existing messages are kept.</DialogDescription>{error&&<p role="alert" className="chat-error">{error}</p>}<div className="dialog-actions"><Button ref={cancel} variant="ghost" disabled={busy||disabled} onClick={()=>setAction(null)}>Cancel</Button><Button variant="destructive" disabled={busy||disabled} onClick={()=>void run('remove')}>{busy?'Removing…':'Remove connector'}</Button></div></DialogContent></Dialog></>
}

export default function ConnectorSettings({chat,closing}:{chat:ChatController;closing:boolean}){
 const [adding,setAdding]=useState(false),add=useRef<HTMLButtonElement>(null),disabled=closing||chat.connectorsLoading
 return <section className="connectors-settings"><div className="settings-panel-header"><div><h2>Connectors</h2><p>Connect remote MCP servers, choose their tools, and enable them in chats or projects.</p></div><Button ref={add} variant="outline" disabled={disabled} onClick={()=>setAdding(true)}><Plus size={15}/>Add connector</Button></div>{chat.connectorsError&&<p role="alert" className="chat-error">{chat.connectorsError}</p>}{chat.connectorsLoading?<p role="status">Loading connectors…</p>:!chat.connectors.length&&<p className="connection-empty">No connectors yet. Add a remote MCP server to get started.</p>}<div className="connection-list">{chat.connectors.map(connector=><ConnectorMenus key={connector.id} connector={connector} disabled={disabled} showMore><div className="connector-summary"><PlugsConnected size={22}/><div><strong>{connector.name}</strong><span className="connector-url">{connector.url}</span><small role="status">{connectorStatus(connector)}</small>{connector.error&&<p role="alert" className="chat-error">{connector.error}</p>}{connector.status==='authenticating'&&<small>Finish sign-in in your browser. Use the actions menu to cancel.</small>}</div></div></ConnectorMenus>)}</div>{adding&&<ConnectorEditor disabled={closing} onClose={()=>setAdding(false)} onCloseAutoFocus={event=>{event.preventDefault();add.current?.focus()}}/>}</section>
}
