import { TooltipButton } from '@zq/ui'
import {useRef,useState} from 'react'
import {useHost,unwrap,type ChatMessage,type GeneratedFile} from '@zq/module-api'
import {ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,Dialog,DialogContent,DialogTitle,DialogDescription,Button,SelectField} from '@zq/ui'
import {File,DotsThree,DownloadSimple} from '@phosphor-icons/react'
import type {ChatController} from './useChat'
import './generated-files.css'
import ArtifactAttachDialog from './ArtifactAttachDialog'
export default function GeneratedFiles({message,conversationId,chat,closing}:{message:ChatMessage;conversationId:string;chat:ChatController;closing:boolean}){
 const {services,notify,commands}=useHost(),[artifactAttach,setArtifactAttach]=useState<{artifact:import('@zq/module-api').Artifact;version:import('@zq/module-api').ArtifactVersion;kind:'note'|'task'}|null>(null),[busy,setBusy]=useState(false),[projectFile,setProjectFile]=useState<GeneratedFile|null>(null),[projectId,setProjectId]=useState(''),[error,setError]=useState(''),lock=useRef(false),openingDialog=useRef(false),focusTarget=useRef<HTMLElement|null>(null)
 const target=(fileId:string)=>({conversationId,messageId:message.id,fileId})
 function dialogOpen(){openingDialog.current=true;if(document.activeElement?.getAttribute('role')!=='menuitem')focusTarget.current=document.activeElement as HTMLElement}
 function menuClose(event:Event){if(openingDialog.current){event.preventDefault();openingDialog.current=false}}
 function restoreFocus(event:Event){event.preventDefault();if(focusTarget.current?.isConnected)focusTarget.current.focus()}
 async function run(action:()=>Promise<unknown>){if(lock.current||closing)return;lock.current=true;setBusy(true);setError('');try{await action()}catch(e){setError((e as Error).message);notify((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 function actions(file:GeneratedFile){return[
  {label:'Open artifact',action:()=>run(()=>chat.openGeneratedArtifact(target(file.id),{origin:focusTarget.current})),disabled:false},
  {label:'View in library',action:()=>run(()=>chat.openGeneratedArtifact(target(file.id),{library:true,origin:focusTarget.current})),disabled:false},
  {label:'Save file…',action:()=>run(()=>unwrap(services.chat.saveGeneratedFile(target(file.id)))),disabled:false},
  {label:'Revise in chat…',action:()=>run(()=>chat.reviseGeneratedArtifact(target(file.id))),disabled:!['pdf','docx','xlsx','pptx'].includes(file.name.split('.').at(-1)?.toLowerCase()??'')},
  {label:'Attach to follow-up',action:()=>run(()=>chat.addGeneratedFile(target(file.id))),disabled:!!chat.conversation?.deletedAt||!!chat.conversation?.archivedAt},
  ...(['note','task'] as const).map(kind=>({label:kind==='note'?'Attach to Notes…':'Attach to Tasks…',disabled:false,action:()=>{dialogOpen();const current=chat.captureArtifactRequest();return run(async()=>{try{const a=await unwrap(services.artifacts.importGenerated(target(file.id)));if(!current())return;const version=a.versions.find(v=>v.source?.generatedFileId===file.id);if(!version)throw Error('The original generated file version is unavailable.');setArtifactAttach({artifact:a,version,kind})}catch(e){if(current())throw e}})}})),
  {label:'Add to project…',action:()=>{dialogOpen();setProjectId(chat.project?.id??chat.state.projects[0]?.id??'');setProjectFile(file)},disabled:!chat.state.projects.length},
 ]}
 return <>{!!message.generatedFiles?.length&&<div className="chat-generated-files">{message.generatedFiles.map(file=><ContextMenu key={file.id}><ContextMenuTrigger asChild><div className="generated-file-row" onFocusCapture={e=>{if(e.target instanceof HTMLButtonElement)focusTarget.current=e.target}} onContextMenu={e=>{focusTarget.current=e.currentTarget.querySelector('button')}}><TooltipButton type="button" className="chat-generated-file" disabled={busy||closing} onClick={()=>void actions(file)[0].action()} aria-label={`Open ${file.name}`}><File size={18}/><span>{file.name}<small>{file.size<1024?`${file.size} B`:`${Math.ceil(file.size/1024)} KB`}</small></span></TooltipButton><TooltipButton type="button" className="generated-file-icon" disabled={busy||closing} tooltip={`Save ${file.name} to your computer`} aria-label={`Save ${file.name}`} onClick={()=>void actions(file)[2].action()}><DownloadSimple size={16}/></TooltipButton><DropdownMenu><DropdownMenuTrigger asChild><TooltipButton type="button" className="generated-file-icon" aria-label={`Actions for ${file.name}`} disabled={busy||closing}><DotsThree size={18}/></TooltipButton></DropdownMenuTrigger><DropdownMenuContent onCloseAutoFocus={menuClose}>{actions(file).map(a=><DropdownMenuItem key={a.label} disabled={busy||closing||a.disabled} onSelect={()=>void a.action()}>{a.label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu></div></ContextMenuTrigger><ContextMenuContent onCloseAutoFocus={menuClose}>{actions(file).map(a=><ContextMenuItem key={a.label} disabled={busy||closing||a.disabled} onSelect={()=>void a.action()}>{a.label}</ContextMenuItem>)}</ContextMenuContent></ContextMenu>)}</div>}
 <Dialog open={!!projectFile} onOpenChange={open=>{if(!open&&!busy)setProjectFile(null)}}><DialogContent onCloseAutoFocus={restoreFocus}><DialogTitle>Add file to project</DialogTitle><DialogDescription>This file will be included as reference material in future project messages.</DialogDescription><SelectField label="Project" tooltip="Choose the project that will use this file as shared reference material" value={projectId} onValueChange={setProjectId} options={chat.state.projects.map(p=>({value:p.id,label:p.name}))} disabled={busy}/>{error&&<p role="alert">{error}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={busy} onClick={()=>setProjectFile(null)}>Cancel</Button><Button tooltip="Add this file as reference material for future project messages" disabled={busy||!projectId} onClick={()=>projectFile&&void run(async()=>{await unwrap(services.chat.generatedFileToProject({...target(projectFile.id),projectId}));setProjectFile(null);notify('Added to project')})}>Add file</Button></div></DialogContent></Dialog>
 {artifactAttach&&<ArtifactAttachDialog {...artifactAttach} onClose={()=>setArtifactAttach(null)}/>}
 </>
}
