import {useEffect,useRef,useState} from 'react'
import Markdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import {useHost,unwrap,type Artifact,type ArtifactTarget,type ResearchDataset,type ResearchEvidence,type ResearchExport,type ResearchReportView} from '@zq/module-api'
import {Button,Input,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem} from '@zq/ui'
import type {ChatController} from './useChat'
import './research-report.css'
export function researchReportActions(artifact:Artifact|undefined,target:ArtifactTarget,chat:ChatController,run:(fn:()=>Promise<void>)=>Promise<void>,edit:()=>void,services:ReturnType<typeof useHost>['services']):{label:string;disabled?:boolean;action:()=>void}[]{
 if(artifact?.format!=='research')return []
 return [
  {label:'Export Markdown and assets…',action:()=>void run(async()=>{await unwrap(services.artifacts.exportResearch({...target,format:'markdown'}))})},
  {label:'Export PDF…',action:()=>void run(async()=>{await unwrap(services.artifacts.exportResearch({...target,format:'pdf'}))})},
  {label:'Edit report…',disabled:!!artifact.deletedAt,action:edit},
  {label:'Follow up with research…',disabled:!!artifact.deletedAt,action:()=>void run(()=>chat.followupResearch(target))},
 ]
}
export function ResearchReportEditor({artifact,target,onClose,onSaved}:{artifact:Artifact;target:ArtifactTarget;onClose:()=>void;onSaved:(artifact:Artifact)=>void}){
 const {services,closing}=useHost(),[title,setTitle]=useState(''),[markdown,setMarkdown]=useState(''),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),lock=useRef(false)
 useEffect(()=>{let live=true;unwrap(services.artifacts.researchView(target)).then(v=>{if(live){setTitle(v.document.title);setMarkdown(v.document.markdown);setLoaded(true)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[target.artifactId,target.versionId])
 async function save(){if(lock.current||closing)return;lock.current=true;setBusy(true);setError('');try{onSaved(await unwrap(services.artifacts.reviseResearch({...target,expectedLatestVersionId:artifact.versions.at(-1)!.id,title,markdown})))}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose()}}><DialogContent className="research-dialog" onEscapeKeyDown={e=>{if(busy)e.preventDefault()}} onPointerDownOutside={e=>{if(busy)e.preventDefault()}}><DialogTitle>Edit research report</DialogTitle><DialogDescription>Saves a new version. Keep citation numbers intact. Saved evidence, tables and chart data remain attached to this version.</DialogDescription><label>Title<Input aria-label="Report title" maxLength={200} value={title} disabled={!loaded||busy||closing} onChange={e=>setTitle(e.target.value)}/></label><textarea className="research-report-editor" aria-label="Report Markdown" value={markdown} disabled={!loaded||busy||closing} onChange={e=>setMarkdown(e.target.value)}/>{error&&<p role="alert">{error}</p>}<div className="research-dialog-footer"><Button variant="ghost" disabled={busy} onClick={onClose}>Cancel</Button><Button disabled={!loaded||busy||closing||!title.trim()||!markdown.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save new version'}</Button></div></DialogContent></Dialog>
}
function DataTable({dataset,cite}:{dataset:ResearchDataset;cite:(ids:string[])=>React.ReactNode}){return <div className="research-report-table" role="region" aria-label={dataset.title} tabIndex={0}><table><thead><tr>{dataset.columns.map(c=><th key={c.key}>{c.label}{c.unit?` (${c.unit})`:''}</th>)}<th>Sources</th></tr></thead><tbody>{dataset.rows.map((r,i)=><tr key={i}>{r.values.map((v,n)=><td key={n}>{v??'—'}</td>)}<td>{cite(r.evidenceIds)}</td></tr>)}</tbody></table></div>}
export default function ResearchReport({target}:{target:ArtifactTarget}){
 const {services,notify,closing}=useHost(),[view,setView]=useState<ResearchReportView|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[data,setData]=useState<ResearchDataset|null>(null),[source,setSource]=useState<ResearchEvidence|null>(null),[busy,setBusy]=useState(false),lock=useRef(false)
 const dataFocus=useRef<HTMLElement|null>(null),sourceFocus=useRef<HTMLElement|null>(null)
 function showData(value:ResearchDataset){dataFocus.current=document.activeElement as HTMLElement;setData(value)}
 function showSource(value:ResearchEvidence|null){sourceFocus.current=document.activeElement as HTMLElement;setSource(value)}
 function restoreFocus(event:Event,element:HTMLElement|null){event.preventDefault();requestAnimationFrame(()=>{const fallback=document.querySelector<HTMLElement>('[role=dialog] button,.research-report-source,[data-pane-close]');(element?.isConnected?element:fallback)?.focus()})}
 const key=JSON.stringify(target),owner=useRef(key);owner.current=key
 useEffect(()=>{let live=true;setView(null);setError('');setData(null);setSource(null);unwrap(services.artifacts.researchView(target)).then(v=>{if(live)setView(v)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[key,refresh])
 async function run(fn:()=>Promise<unknown>){if(closing||lock.current)return;lock.current=true;setBusy(true);try{await fn()}catch(e){if(owner.current===key)setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 const save=(format:ResearchExport['format'],itemId?:string)=>void run(()=>unwrap(services.artifacts.exportResearch({...target,format,itemId})))
 const copy=(dataset:ResearchDataset)=>void run(async()=>{await unwrap(services.clipboard.writeText(view!.datasets.find(d=>d.id===dataset.id)!.csv));notify('Table copied')})
 const report=view?.document
 function cite(ids:string[]){return ids.map(id=><button type="button" className="research-report-citation" key={id} onClick={()=>showSource(report!.evidence.find(e=>e.id===id)!)} aria-label={`View source ${report!.citationIds.indexOf(id)+1}`}>[{report!.citationIds.indexOf(id)+1}]</button>)}
 if(!view||!report)return <div className="artifact-pane-status" role={error?'alert':'status'}>{error||'Loading saved research…'}{error&&<Button variant="outline" onClick={()=>setRefresh(v=>v+1)}>Retry report</Button>}</div>
 const markdown=report.markdown.replace(/\[(\d+)\](?!\()/g,(_,n)=>`[${n}](#research-source-${n})`)
 return <article className="research-report"><h1>{report.title}</h1><p className="research-report-meta">{new Date(report.createdAt).toLocaleString()} · {report.choice.model}</p>{error&&<p role="alert">{error}</p>}
 <div className="chat-prose"><Markdown remarkPlugins={[remarkGfm]} skipHtml urlTransform={url=>/^(https?:\/\/|#research-source-)/i.test(url)?url:''} components={{img:({alt})=><span>{alt}</span>,a:({href,children})=>href?.startsWith('#research-source-')?<button type="button" className="research-report-citation" onClick={()=>showSource(report.evidence.find(e=>e.id===report.citationIds[Number(href.slice(17))-1])??null)}>{children}</button>:<a href={href} onClick={e=>{e.preventDefault();if(href)void run(()=>unwrap(services.chat.openLink(href)))}}>{children}</a>}}>{markdown}</Markdown></div>
 {report.charts.map(chart=>{const dataset=report.datasets.find(d=>d.id===chart.datasetId)!;return <ContextMenu key={chart.id}><ContextMenuTrigger asChild><figure className="research-report-chart"><img src={view.charts.find(c=>c.id===chart.id)!.image} alt={chart.title}/><figcaption>{chart.title} · {dataset.method}</figcaption><div className="research-report-actions"><Button variant="ghost" size="sm" onClick={()=>showData(dataset)}>View data</Button><Button variant="ghost" size="sm" disabled={busy||closing} onClick={()=>save('svg',chart.id)}>Save chart…</Button></div></figure></ContextMenuTrigger><ContextMenuContent><ContextMenuItem onSelect={()=>showData(dataset)}>View data</ContextMenuItem><ContextMenuItem disabled={busy||closing} onSelect={()=>copy(dataset)}>Copy table</ContextMenuItem><ContextMenuItem disabled={busy||closing} onSelect={()=>save('csv',dataset.id)}>Download CSV…</ContextMenuItem><ContextMenuItem disabled={busy||closing} onSelect={()=>save('svg',chart.id)}>Save chart…</ContextMenuItem></ContextMenuContent></ContextMenu>})}
 {report.datasets.map(dataset=><ContextMenu key={dataset.id}><ContextMenuTrigger asChild><section className="research-report-dataset"><h2>{dataset.title}</h2><DataTable dataset={dataset} cite={cite}/><p>{dataset.method}</p></section></ContextMenuTrigger><ContextMenuContent><ContextMenuItem onSelect={()=>showData(dataset)}>View data</ContextMenuItem><ContextMenuItem disabled={busy||closing} onSelect={()=>copy(dataset)}>Copy table</ContextMenuItem><ContextMenuItem disabled={busy||closing} onSelect={()=>save('csv',dataset.id)}>Download CSV…</ContextMenuItem></ContextMenuContent></ContextMenu>)}
 <section><h2>Source evidence</h2>{report.citationIds.map((id,i)=>{const evidence=report.evidence.find(e=>e.id===id)!;return <ContextMenu key={id}><ContextMenuTrigger asChild><button type="button" className="research-report-source" onClick={()=>showSource(evidence)}><strong>[{i+1}] {evidence.title}</strong><span>{evidence.level} · Retrieved {new Date(evidence.retrievedAt).toLocaleString()}</span></button></ContextMenuTrigger><ContextMenuContent><ContextMenuItem onSelect={()=>showSource(evidence)}>View evidence</ContextMenuItem><ContextMenuItem disabled={closing} onSelect={()=>void run(()=>unwrap(services.clipboard.writeText(`${evidence.title} — ${evidence.url??evidence.locator}`)))}>Copy citation</ContextMenuItem>{evidence.url&&<ContextMenuItem disabled={closing} onSelect={()=>void run(()=>unwrap(services.chat.openLink(evidence.url!)))}>Open original</ContextMenuItem>}</ContextMenuContent></ContextMenu>})}</section>
 <Dialog open={!!data} onOpenChange={open=>{if(!open)setData(null)}}><DialogContent className="research-dialog" onCloseAutoFocus={e=>restoreFocus(e,dataFocus.current)}><DialogTitle>{data?.title??'Chart data'}</DialogTitle><DialogDescription>{data?.method}</DialogDescription>{data&&<DataTable dataset={data} cite={cite}/>}<div className="research-dialog-footer"><Button variant="outline" disabled={busy||closing} onClick={()=>data&&copy(data)}>Copy table</Button><Button disabled={busy||closing} onClick={()=>data&&save('csv',data.id)}>Download CSV…</Button></div></DialogContent></Dialog>
 <Dialog open={!!source} onOpenChange={open=>{if(!open)setSource(null)}}><DialogContent className="research-dialog" onCloseAutoFocus={e=>restoreFocus(e,sourceFocus.current)}><DialogTitle>{source?.title??'Source evidence'}</DialogTitle><DialogDescription>{source?.level} · {source?.locator}</DialogDescription><pre className="research-report-excerpt">{source?.excerpt}</pre><p className="research-hint">Retrieved {source&&new Date(source.retrievedAt).toLocaleString()} · {source?.provenance.tool}. This is the evidence saved with this report version.</p>{source?.url&&<Button variant="outline" disabled={closing} onClick={()=>void run(()=>unwrap(services.chat.openLink(source.url!)))}>Open original</Button>}</DialogContent></Dialog>
 </article>
}
