import {useEffect,useId,useRef,useState} from 'react'
import {useHost,unwrap,type SkillImport,type SkillUpdatePreview} from '@zq/module-api'
import {UploadSimple,FileText,DotsThree,CaretDown} from '@phosphor-icons/react'
import {SkillPackageFiles,type SkillPackageFilesHandle} from './SkillPackageFiles'
import {Button,Input,Dialog,DialogContent,DialogTitle,DialogDescription,ContextMenu,ContextMenuTrigger,ContextMenuContent,ContextMenuItem,DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@zq/ui'

export default function SkillImportControl({disabled,externalCandidate,hideTrigger=false,importDisabled=false,importDisabledReason,updatePreview,updateAllowed=false,onReviewClose,onReviewCloseAutoFocus}:{disabled:boolean;externalCandidate?:SkillImport|null;hideTrigger?:boolean;importDisabled?:boolean;importDisabledReason?:string;updatePreview?:SkillUpdatePreview|null;updateAllowed?:boolean;onReviewClose?:()=>void;onReviewCloseAutoFocus?:()=>void}){
 const host=useHost(),id=useId(),lock=useRef(false),mounted=useRef(true),trigger=useRef<HTMLButtonElement>(null)
 const referenceOrigin=useRef<HTMLButtonElement|null>(null),referenceButtons=useRef(new Map<number,HTMLButtonElement>()),nameInput=useRef<HTMLInputElement>(null)
 const [candidate,setCandidate]=useState<SkillImport|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('')
 const [reference,setReference]=useState<SkillImport['files'][number]|null>(null)
 const [packageBusy,setPackageBusy]=useState(false),[packagePreview,setPackagePreview]=useState(false),packageFiles=useRef<SkillPackageFilesHandle>(null)
 const blocked=disabled||host.closing||busy||packageBusy
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[])
 useEffect(()=>{if(externalCandidate){setCandidate(externalCandidate);setError('');setStatus('')}},[externalCandidate])
 useEffect(()=>host.registerFlush(`skill-import-${id}`,async()=>{if(lock.current)throw Error('Wait for the skill import to finish before closing zQ.')}),[host.registerFlush,id])
 async function choose(directory=false){if(blocked||lock.current)return;lock.current=true;setBusy(true);setError('');setStatus('');try{const draft=await unwrap(host.services.chat.pickSkillImport(directory?{directory:true}:undefined));if(mounted.current)setCandidate(draft)}catch(e){if(mounted.current)setError((e as Error).message)}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 async function save(){if(!candidate||blocked||(updatePreview?!updateAllowed:importDisabled)||lock.current)return;lock.current=true;setBusy(true);setError('');try{const skill=await unwrap(updatePreview?host.services.chat.updateCatalogSkill({id:updatePreview.id,expectedHash:updatePreview.expectedHash,candidate}):host.services.chat.importSkill(candidate));if(mounted.current){setCandidate(null);setStatus(`${skill.name} ${updatePreview?'updated':'imported'}.`);onReviewClose?.()}}catch(e){if(mounted.current)setError((e as Error).message)}finally{lock.current=false;if(mounted.current)setBusy(false)}}
 function previewFile(file:SkillImport['files'][number],index:number){referenceOrigin.current=referenceButtons.current.get(index)??null;setReference(file)}
 function close(){if(blocked||lock.current)return;if(packagePreview){packageFiles.current?.closePreview();return;}if(reference){setReference(null);return;}setCandidate(null);setReference(null);setError('');onReviewClose?.()}
 return <>{!hideTrigger&&<div className="skill-import-buttons"><Button ref={trigger} title="Import SKILL.md, .zip, or .skill" variant="outline" disabled={blocked} onClick={()=>void choose()}><UploadSimple size={15}/>Import skill</Button><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="outline" size="icon" aria-label="Skill import options" disabled={blocked}><CaretDown size={13}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem disabled={blocked} onSelect={()=>void choose()}>Import file…</DropdownMenuItem><DropdownMenuItem disabled={blocked} onSelect={()=>void choose(true)}>Import folder…</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>}
 {!candidate&&error&&<p className="chat-error skill-import-result" role="alert">{error}</p>}{status&&<p className="skill-import-result" role="status">{status}</p>}
 <Dialog open={!!candidate} onOpenChange={open=>{if(!open)close()}}><DialogContent className="skill-editor skill-import-dialog" onEscapeKeyDown={e=>{if(packagePreview){e.preventDefault();packageFiles.current?.closePreview()}else if(reference){e.preventDefault();setReference(null)}}} showCloseButton={!blocked} onCloseAutoFocus={e=>{e.preventDefault();if(onReviewCloseAutoFocus)onReviewCloseAutoFocus();else trigger.current?.focus()}} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopPropagation()}}}>
  <DialogTitle>{updatePreview?'Review skill update':'Import skill'}</DialogTitle><DialogDescription>{updatePreview?'Review the new instructions and files. Updating replaces this installed skill’s instructions, references and package files. Previously sent chats keep their snapshots.':'Review this skill before adding it to your library. SKILL.md, ZIP packages and skill folders are supported. It will be saved as a new skill.'}</DialogDescription>
  {candidate&&<form onSubmit={e=>{e.preventDefault();void save()}}><label htmlFor={`${id}-name`}>Name</label><Input ref={nameInput} id={`${id}-name`} aria-label={updatePreview?"Skill update name":"Imported skill name"} value={candidate.name} maxLength={256} disabled={blocked||!!updatePreview&&!updateAllowed} onChange={e=>setCandidate({...candidate,name:e.target.value})}/>
   {updatePreview?.modified&&<p className="skill-update-notice" role="note">You have local changes. Updating replaces your local instructions and references. To keep a separate copy, cancel and duplicate this skill in your library first.</p>}
   {updatePreview&&!updateAllowed&&<p className="skill-help">This skill already uses this source revision.</p>}
   {candidate.description&&<p className="skill-import-description">{candidate.description}</p>}
   <label>Instructions</label><pre className="skill-import-text">{candidate.instructions||'No instructions.'}</pre>
   {candidate.warnings.map((warning,index)=><p className="skill-help" key={index}>{warning}</p>)}
   {candidate.files.length>0&&<><label>Reference files <span className="skill-optional">{candidate.files.length}</span></label><div className="skill-files">{candidate.files.map((file,index)=>{
    const remove=()=>setCandidate({...candidate,files:candidate.files.filter((_,i)=>i!==index)})
    return <ContextMenu key={`${index}-${file.name}`}><ContextMenuTrigger asChild disabled={blocked}><div className="skill-file"><button ref={node=>{if(node)referenceButtons.current.set(index,node);else referenceButtons.current.delete(index)}} type="button" className="skill-file-name" aria-label={`Preview ${file.name}`} disabled={blocked} onClick={()=>previewFile(file,index)}><FileText size={16}/><span>{file.name}</span></button><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="ghost" size="icon" disabled={blocked} aria-label={`Actions for reference ${file.name}`}><DotsThree size={17}/></Button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onSelect={()=>previewFile(file,index)}>Preview</DropdownMenuItem><DropdownMenuItem disabled={!!updatePreview&&!updateAllowed} onSelect={remove}>Remove</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></ContextMenuTrigger><ContextMenuContent><ContextMenuItem disabled={blocked} onSelect={()=>previewFile(file,index)}>Preview</ContextMenuItem><ContextMenuItem disabled={blocked||!!updatePreview&&!updateAllowed} onSelect={remove}>Remove</ContextMenuItem></ContextMenuContent></ContextMenu>
   })}</div></>}
   {candidate.package&&<SkillPackageFiles ref={packageFiles} resources={candidate.package.resources} frontmatter={candidate.package.frontmatter} activePaths={candidate.files.map(file=>file.resourcePath??file.name)} disabled={disabled||host.closing||busy} onBusyChange={setPackageBusy} onPreviewChange={setPackagePreview}/>}
   {importDisabled&&!updatePreview&&<p className="skill-help">{importDisabledReason||'Your library has 100 skills. Delete a library skill before importing another.'}</p>}
   {error&&<p className="chat-action-error" role="alert">{error}</p>}
   <div className="dialog-actions"><Button type="button" variant="ghost" disabled={blocked} onClick={close}>Cancel</Button><Button type="submit" disabled={blocked||(updatePreview?!updateAllowed:importDisabled)||!candidate.name.trim()}>{busy?(updatePreview?'Updating…':'Importing…'):(updatePreview?'Update skill':'Import skill')}</Button></div>
  </form>}
 </DialogContent></Dialog>
 {reference&&<Dialog open onOpenChange={open=>{if(!open)setReference(null)}}><DialogContent className="skill-editor" onCloseAutoFocus={e=>{e.preventDefault();(referenceOrigin.current?.isConnected?referenceOrigin.current:nameInput.current)?.focus({preventScroll:true})}}><DialogTitle>{reference?.name}</DialogTitle><DialogDescription>Reference text included with this skill.</DialogDescription><pre className="skill-import-text">{reference?.text||'No extracted text.'}</pre></DialogContent></Dialog>}
 </>
}
